#!/usr/bin/env python3
"""Nothing published disappears unseen.

The site's rule: a claim that can no longer be justified is retired to the archive
(docs/ARCHIVE.md), in the words it was published in, with the reason. It is never
quietly deleted. This checks that rule mechanically.

For every page, take each sentence of a published version that carries a number.
It is accounted for if
  (a) it lies in a passage some retired claim archives (retired.from is the page,
      located at retired.commit by its begin and end phrases), or
  (b) every number in it is still said somewhere on the site now - moved to
      another page, or reworded.
Anything else was published and is no longer said, with no archive entry: listed.

Which published version: by default the last commit (HEAD), so running this before
a commit shows what the working tree drops. With --swept, each page is compared
with the commit its own retirements point at - how the claims sweep of 2026-09-11
was audited.

False positives are expected - a reworded sentence whose number changed with the
data - so this lists for review; it does not refuse.

    python3 scripts/archive_audit.py            # against HEAD
    python3 scripts/archive_audit.py --swept    # against each page's retirement commit
"""
import collections
import glob
import io
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT
import claims

NUM = re.compile(r"\d+(?:[.,]\d+)*")
YEARISH = re.compile(r"^(1[89]\d\d|20\d\d)$")
REGISTERS = {"CLAIMS.md", "ARCHIVE.md", "SOURCES.md"}


def flat(t):
    t = re.sub(r"<[^>]+>", " ", t)
    t = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", t)
    t = t.replace("**", "").replace("`", "")
    return re.sub(r"\s+", " ", t).strip()


def git_show(commit, rel):
    r = subprocess.run(["git", "show", f"{commit}:{rel}"], cwd=ROOT, capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else ""


def main(argv):
    swept = "--swept" in argv
    d, nodes, cl = claims.load()
    retired = [c for c in cl.values() if c.get("retired")]
    site = set()
    for g in glob.glob(os.path.join(ROOT, "docs", "**", "*.md"), recursive=True):
        site |= set(NUM.findall(flat(io.open(g, encoding="utf-8").read())))
    pages = sorted(os.path.relpath(p, os.path.join(ROOT, "docs"))
                   for p in glob.glob(os.path.join(ROOT, "docs", "**", "*.md"), recursive=True))
    report = {}
    for page in pages:
        if page in REGISTERS:
            continue
        mine = [c["retired"] for c in retired if c["retired"]["from"] == page]
        base = "HEAD"
        if swept:
            commits = collections.Counter(r["commit"][:7] for r in mine)
            if not commits:
                continue
            base = commits.most_common(1)[0][0]
        old = git_show(base, "docs/" + page)
        if not old:
            continue
        flex = lambda p: r"\s+".join(re.escape(w) for w in p.split())
        spans = []
        for r in mine:
            if r["commit"][:7] != base[:7] and base != "HEAD":
                continue
            text = old if r["commit"][:7] == base[:7] or base == "HEAD" else git_show(r["commit"], r["file"])
            m = re.search(flex(r["begin"]), text)
            e = re.compile(flex(r["end"])).search(text, m.start()) if m else None
            if m and e and text is old:
                spans.append((m.start(), e.end()))
        flagged, pos = [], 0
        for line in old.split("\n"):
            start = pos
            pos += len(line) + 1
            fl = flat(line)
            if not fl or fl.startswith("*Generated by"):
                continue
            if any(start < e and s < start + len(line) for s, e in spans):
                continue
            for sm in re.finditer(r".+?(?:[.!?](?=\s+[A-ZÆØÅ*\"(])|$)", fl):
                sent = sm.group(0).strip()
                nums = [n for n in NUM.findall(sent) if not YEARISH.match(n)]
                if len(sent) < 25 or not nums or all(n in site for n in nums):
                    continue
                flagged.append(sent[:180])
        if flagged:
            report[page] = (base, flagged)
    for page, (base, items) in report.items():
        print(f"== {page} (published at {base}): {len(items)} sentence(s) with numbers, "
              "not archived and not said now")
        for s in items[:10]:
            print("   -", s)
        if len(items) > 10:
            print(f"   ... and {len(items) - 10} more")
    print(f"pages with unaccounted sentences: {len(report)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
