#!/usr/bin/env python3
"""Generate docs/CAUSATION.md - what survives between "agriculture 69.6% of nitrogen"
and "agriculture causes 70% of fedtemøg".

NITROGEN.md audits the number where it is produced: the denominator, the estimator, the
currency. This document does something different. It takes the number at face value and
follows it forward through the causal chain it is quoted as describing, asking at each
link what coefficient exists. The answer is that four of them do not exist, and the
product of four unknown fractions is reported as one measured fraction.

Then it puts the intervention and the outcome side by side, which nobody does, because
that juxtaposition is the only empirical test of the nitrogen-dominant model that
thirty-five years of Danish policy has actually run.

Usage:  python3 scripts/causation.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, log, read_json

MANUAL = os.path.join(ROOT, "data", "manual")
AGRI_PCT = 69.6          # the published share, taken at face value throughout
C_PER_COD = 0.375        # g organic C per g COD (CH2O + O2 -> CO2 + H2O)
C_PER_N = (106 * 12.011) / (16 * 14.007)   # Redfield, by mass: 5.68 g C per g N
C_FRAC_FAT = 0.759      # tripalmitin C51H98O6: 612.6 g C in 807 g - fat is mostly carbon
COD_PER_FAT = 2.9       # g O2 per g fat, vs ~1.07 for carbohydrate and ~1.5 for protein
N_FRAC_FAT = 0.0        # triglycerides are C, H and O. There is no nitrogen in fat.

# The chain the phrase "agriculture causes 70% of fedtemøg" asserts, one link per row.
# "coefficient" is what would have to exist for the multiplication to be legitimate.
CHAIN = [
    ("Agriculture → the land-based waterborne nitrogen term",
     "69.6%",
     "PUBLISHED",
     "A residual: measured-plus-modelled total minus modelled point sources minus "
     "modelled natural background. Retention modelled at ±16 percentage points. "
     "Returns negative values in dry years."),
    ("That term → all reactive nitrogen reaching the sea",
     "no coefficient",
     "OPEN SET",
     "10 of 20 enumerated pathways carry no number, including atmospheric deposition's "
     "organic fraction, submarine groundwater discharge, and sediment regeneration — "
     "probably the largest single supply to the productive layer."),
    ("Nitrogen → oxygen depletion",
     "no coefficient",
     "NOT COMPUTED",
     "Nitrogen is one of at least six oxygen sinks. There is no potency term: a kilogram "
     "in February into a mixed column counts the same as a kilogram in July under a "
     "pycnocline. No ventilation term, no state variable."),
    ("Oxygen depletion → loss of higher life",
     "no coefficient",
     "NOT COMPUTED",
     "Hypoxia is one route among several — toxicants, trawling, turbidity, sulphide "
     "exposure, physical loss of habitat. The soft-bottom survey runs 1 March–31 May, "
     "so the autumn kill is never observed, only its aftermath."),
    ("Loss of higher life → fedtemøg on a shore",
     "no coefficient",
     "NOT MEASURED AT ALL",
     "Fedtemøg has no national monitoring — not extent, not biomass, not duration. "
     "And it needs retention, stranding wind and a shore, which are properties of the "
     "receiving bay, not of the source."),
]


def fmt(x):
    return f"{x:,.0f}" if abs(x) >= 10 else f"{x:,.1f}"


def main():
    paths = read_json(os.path.join(MANUAL, "nitrogen_pathways.json"))["pathways"]
    mon = read_json(os.path.join(MANUAL, "monitoring.json"))
    tr = mon["load_trend_vs_outcome"]

    # the two rows that make up the land-based waterborne term the 69.6% is a share of
    land = [p for p in paths if p["pathway"].startswith("Danish land via")]
    land_lo = sum(p["lo"] for p in land)
    land_hi = sum(p["hi"] for p in land)
    agri_lo = land_lo * AGRI_PCT / 100
    agri_hi = land_hi * AGRI_PCT / 100

    quant = [p for p in paths if p["lo"] is not None]
    unquant = [p for p in paths if p["lo"] is None]
    tot_lo = sum(p["lo"] for p in quant)
    tot_hi = sum(p["hi"] for p in quant)

    # a CEILING, not a share: the denominator can only grow, so this can only fall
    ceil_hi = agri_hi / tot_lo * 100
    ceil_lo = agri_lo / tot_hi * 100

    o = []
    a = o.append

    a("# The chain from nitrogen to fedtemøg\n")
    a("Generated by `scripts/causation.py` from `data/manual/`. "
      "Companion to [NITROGEN.md](NITROGEN.md), which audits the number where it is "
      "made. This document does the opposite: it grants the number and follows it "
      "*forward*, through the causal chain it is routinely quoted as describing.\n")

    a("> **agriculture causes 70% of fedtemøg**\n")
    a("That sentence, or a close variant, is how the figure enters public argument. "
      "It is a claim about an outcome on a shore. The number behind it is a share of "
      "one term in one account. Between the two lie four links, and this document asks "
      "what coefficient each one has.\n")

    # ------------------------------------------------------------------ 1
    a("## 1. What the number is a share of\n")
    a(f"The published {AGRI_PCT}% is agriculture's share of the **land-based waterborne "
      "term** — nitrogen arriving at the coast through Danish streams and unmonitored "
      "catchments. Those are two rows of the twenty enumerated in NITROGEN.md:\n")
    a("| Row | kt N/yr | Status |")
    a("|---|---:|---|")
    for p in land:
        a(f"| {p['pathway']} | {fmt(p['lo'])} – {fmt(p['hi'])} | {p['status'].title()} |")
    a(f"| **The term the percentage divides** | **{fmt(land_lo)} – {fmt(land_hi)}** | |")
    a(f"| **{AGRI_PCT}% of it — the agricultural load** | **{fmt(agri_lo)} – {fmt(agri_hi)}** | |")
    a("")
    a(f"So the quantity in question is roughly **{fmt(agri_lo)}–{fmt(agri_hi)} kt N/yr**. "
      "That is a real number and it is not small. The question is what it is a share "
      "*of*.\n")
    a(f"The enumerated pathways that carry any number at all sum to "
      f"**{fmt(tot_lo)} – {fmt(tot_hi)} kt N/yr**, with **{len(unquant)} of {len(paths)} "
      "rows empty**. An empty row can only add. So the denominator has a floor and no "
      "ceiling, and any share computed against it is a **ceiling, not an estimate**:\n")
    a(f"> Agriculture accounts for **no more than {ceil_hi:.0f}%** of enumerated "
      "reactive nitrogen reaching Danish marine waters — and at the wide end of the "
      f"denominator bounds, as little as {ceil_lo:.0f}%. Fill any of the empty rows and "
      "that ceiling falls. It cannot rise.\n")
    a(f"The published {AGRI_PCT}% and this ceiling are not competing estimates of the "
      "same thing. They answer different questions, and only the second one is the "
      "question the public sentence is asking.\n")
    a("Two omissions set the scale of the gap. **Atmospheric deposition to Danish marine "
      "waters is 45–65 kt N/yr** — comparable to the entire land-based term, falling on "
      "the water directly, and absent from every published apportionment. **Sediment "
      "regeneration** is not a source at all in the accounting frame, yet one study puts "
      "net advection at around a tenth of what annual primary production requires, which "
      "implies internal recycling supplies most of it.\n")

    # ------------------------------------------------------------------ 2
    a("## 2. Four missing coefficients, reported as one number\n")
    a("Granting the 69.6% entirely, here is what it has to survive to become a claim "
      "about fedtemøg:\n")
    a("| Link | Coefficient | Status | Why |")
    a("|---|---|---|---|")
    for link, coef, status, why in CHAIN:
        a(f"| {link} | {coef} | **{status}** | {why} |")
    a("")
    a("Every one of those links is a real causal connection. None of them has a number. "
      "The sentence multiplies them anyway, and the product inherits the appearance of "
      "the one factor that was measured.\n")
    a("This is not a claim that the links are weak. It is a claim about what kind of "
      "object the result is. **A product of four unknown fractions is an unknown "
      "fraction** — not a small one. Agriculture may still be the largest single "
      "contributor at every link. Nobody has computed it either way, and that is the "
      "finding.\n")
    a("And section 3 argues the more serious objection: the chain is not a chain.\n")

    # ------------------------------------------------------------------ 3
    a("## 3. Nitrogen is necessary for one pathway, not for the outcome\n")
    a("Section 2 treats the argument as a chain and asks for each link's coefficient. "
      "That concedes too much, because it accepts the shape. The published framing is\n")
    a("> nitrogen → primary production → biomass → the mush on the shore\n")
    a("and that is one branch of a tree, not the trunk. There are at least three routes "
      "to the same endpoint, and **nitrogen is a necessary condition for exactly one of "
      "them**:\n")
    a("| Route | What arrives | Does it need nitrogen? |")
    a("|---|---|---|")
    a("| **A. Growth** | dissolved nutrients | **Yes** — this is the modelled pathway |")
    a("| **B. Direct organic matter** | organic carbon that is already biomass or was "
      "never alive at all — sewage solids, faecal matter, resuspended basin sludge, "
      "and fat | **No.** The material does not have to be grown. It has already been "
      "grown, somewhere else, out of somebody else's nitrogen — or, in the case of "
      "fat, contains no nitrogen at any point in its existence. |")
    a("| **C. Killing what is already there** | nothing — toxicants, hypoxia, sulphide, "
      "physical disturbance | **No.** The standing stock of living tissue in a bay is "
      "converted to detritus in place. No new carbon enters the system at all. |")
    a("")
    a("Routes B and C are not exotic. B is what a combined sewer overflow physically is. "
      "C is what every hypoxic event and every toxicant pulse does by definition. Neither "
      "appears in any nutrient accounting, because neither is a nutrient.\n")

    a("### Their own typetal, read as carbon\n")
    a("The comparison can be made from Miljøstyrelsen's own numbers. Every discharge "
      "type in the typetal table carries both an organic load (COD) and a nitrogen load. "
      "Route A's carbon is what that nitrogen could produce at Redfield stoichiometry — "
      f"{C_PER_N:.2f} g C per g N. Route B's carbon is what the water is already "
      f"carrying — {C_PER_COD} g C per g COD.\n")
    a("| Discharge type | COD mg/l | Tot-N mg/l | **B: carbon delivered** | "
      "**A: carbon its N could grow** | B ÷ A |")
    a("|---|---:|---:|---:|---:|---:|")
    tt = mon["typetal_nutrients_mg_per_l"]
    labels = [("combined_overflow", "Combined sewer overflow"),
              ("separate_stormwater", "Separate stormwater"),
              ("reference_stormwater_runoff", "Stormwater runoff (reference)"),
              ("reference_raw_sewage", "Raw sewage (reference)")]
    for key, lbl in labels:
        r = tt[key]
        cb = r["COD"] * C_PER_COD
        ca = r["Tot-N"] * C_PER_N
        a(f"| {lbl} | {r['COD']:,.0f} | {r['Tot-N']:,.1f} | {cb:.0f} mg C/l | "
          f"{ca:.0f} mg C/l | **{cb/ca:.2f}** |")
    a("")
    r = tt["combined_overflow"]
    cb = r["COD"] * C_PER_COD
    ca = r["Tot-N"] * C_PER_N
    a(f"A combined sewer overflow delivers **{cb:.0f} mg of organic carbon per litre "
      f"directly**, and carries enough nitrogen to grow **{ca:.0f} mg C/l** — a ratio of "
      f"**{cb/ca:.2f}**. The two pathways are the same size. Only one of them is "
      "counted, and that one is counted at 0.6% of a national nitrogen total.\n")
    a("For separate stormwater and for the stormwater-runoff reference the direct term is "
      "the *larger* of the two. Only raw sewage — the one stream that actually goes to "
      "treatment — is nitrogen-dominated.\n")
    a("*Both columns are ceilings.* Not all COD is degradable on a relevant timescale, "
      "and not all nitrogen is assimilated. The two overstatements run in the same "
      "direction, so the **ratio** is the robust part; the absolute milligrams are not. "
      "The point does not need them to be.\n")

    a("### Why the direct route is worth more per gram\n")
    a("The ratio above understates route B, because the two carbons are not "
      "interchangeable:\n")
    for i, t in enumerate([
        "**Route A carbon is conditional.** It requires a phototroph that is present, "
        "in a growing season, with light reaching it, and with phosphorus and silicon in "
        "supportive ratio. Nitrogen delivered in November grows nothing.",
        "**Route B carbon is unconditional.** It is already organic matter. It settles, "
        "it decays, and it consumes oxygen in the dark in December exactly as well as in "
        "July.",
        "**Route B arrives where it is discharged.** Route A carbon is produced wherever "
        "the light and the season allowed, which may be nowhere near the shore that "
        "receives the consequence.",
        "**Route B arrives in pulses, on the flow threshold** — the same events that "
        "scour a basin and resuspend its accumulated sludge. Route A is a slow "
        "background.",
    ], 1):
        a(f"{i}. {t}")
    a("")
    a("Which inverts the seasonal argument. Nitrogen's effectiveness at producing shore "
      "biomass is highest in spring and summer and close to zero in late autumn. Direct "
      "organic matter's effectiveness is **flat across the year**, and its delivery peaks "
      "in autumn and winter with the rain. The two pathways have opposite seasonality, "
      "and only the one that switches off in autumn is measured.\n")

    a("### The word names a material\n")
    a("*Fedtemøg* is not a metaphor. It means fat filth, and the fat is literal. Sewage "
      "carries fats, oils and grease continuously, and the sewer accumulates them into "
      "the deposits Danish utilities call fedtpropper — the same thing an English-"
      "speaking utility calls a fatberg.\n")
    a("As a fedtemøg precursor, fat has an uncomfortable set of properties:\n")
    a("| Property | Value | Consequence |")
    a("|---|---|---|")
    a(f"| Nitrogen content | **{N_FRAC_FAT:.0f}%** | Triglycerides are carbon, hydrogen and "
      "oxygen. A nitrogen accounting cannot see this material at all — not "
      "under-count it, *not see it*. |")
    a(f"| Carbon content | **~{C_FRAC_FAT*100:.0f}%** by mass | Roughly twice the carbon "
      "density of algal dry matter. |")
    a(f"| Oxygen demand | **~{COD_PER_FAT:.1f} g O₂ per g** | Against ~1.1 for "
      "carbohydrate and ~1.5 for protein. Fat is the most oxygen-expensive common "
      "organic material there is. |")
    a("| Density | below water | It floats. It does not settle out of the way; it goes "
      "to the surface and then to a shore. |")
    a("| Solubility | none | It does not dilute. It coalesces. |")
    a("| Degradation | slow, and slower without oxygen | It persists long enough to "
      "travel, and longest exactly where the water is already anoxic. |")
    a("")
    a("**And its release is threshold-triggered.** A fedtprop is a deposit on a pipe "
      "wall. It leaves when the flow is high enough to scour it — which is the same "
      "condition, in the same hours, as a combined sewer overflow. The material is "
      "retained through every dry day of the year and exported during precisely the "
      "hours when the flow bypasses the treatment works.\n")
    a("So the annual accounting is doubly wrong for this material. It is invisible to "
      "the nitrogen unit, and its export is concentrated in the event tail that a "
      "modelled-annual-volume × fixed-concentration method averages away.\n")
    a("**Scale, as far as it can be established.** One Danish utility reported receiving "
      "25 tonnes of fat at its treatment plant in a single year, alongside 193 tonnes of "
      "screenings. That is one utility, one year, and — the important part — it counts "
      "only what *reached the works*. Every hour the system is in overflow is an hour "
      "that stream is going somewhere else. There is no national figure, no monitoring, "
      "and no unit in which it would be reported.\n")

    a("### Route C needs no carbon at all\n")
    a("The third route has no input term to argue about. A bay holds a standing stock of "
      "living tissue — macroalgae, eelgrass, fauna, biofilm. Kill it and that tissue "
      "becomes detritus without a single additional gram entering the system. Toxicants, "
      "a hypoxic event, a sulphide pulse and a trawl all do this.\n")
    a("This route is the one the nutrient frame cannot even represent as a question. It "
      "has no source, no load, no unit. And it is the only route that explains why the "
      "same bay can produce more decaying material in a year when *less* was delivered "
      "to it.\n")
    a("**The consequence for the 70%.** A necessary condition for one branch is not a "
      "cause of the outcome. Removing nitrogen entirely would close route A and leave "
      "routes B and C running.\n")

    # ------------------------------------------------------------------ 4
    a("## 4. The bloom is mostly not made of what was delivered\n")
    a("There is a second structural problem, and it is the one that does the most damage "
      "to an apportionment. The system feeds itself.\n")
    a("The loop, stated plainly:\n")
    for i, t in enumerate([
        "simple, fast-replicating life grows on whatever is available",
        "its respiration and decay draw the oxygen down",
        "things that need oxygen die — fauna, and then everything else",
        "the dead tissue remineralises, releasing the nutrients it was built from",
        "those nutrients feed step 1 again, and there is now less competition for them",
    ], 1):
        a(f"{i}. {t}")
    a("")
    a("Every turn of that loop makes the next turn easier, and the material driving it "
      "from turn two onward was **already in the bay**. It is not a delivery. Nothing "
      "crossed a boundary that an accounting could meter.\n")
    a("This is not a speculative mechanism. It is the standard distinction in marine "
      "biogeochemistry between **new production** — running on nutrients newly supplied "
      "from outside the productive layer — and **regenerated production**, running on "
      "nutrients recycled in place. Their ratio has a name, the f-ratio, and in "
      "productive coastal water in summer it is low: most of the production is "
      "regenerated, not new.\n")
    a("Which means the sentence \"this bloom was caused by X% agriculture\" is making a "
      "claim about the minority term. The majority of the nitrogen in a late-summer "
      "bloom was not delivered that summer by anyone. It was released by the previous "
      "round of dying.\n")
    a("### What the loop does to the arithmetic\n")
    a("An apportionment is a linear instrument. It assumes the outcome is a weighted sum "
      "of the inputs, so that halving one input removes its share of the outcome. A "
      "self-amplifying loop is not a weighted sum. In one:\n")
    for t in [
        "**the trigger and the fuel are different quantities.** External input can be "
        "small and still start something that runs on internal stock;",
        "**the same input produces wildly different outcomes** depending on how far round "
        "the loop the system already is — which is the state-dependence of section 7, "
        "arriving here by a second route;",
        "**there are thresholds.** Below one, the loop damps; above it, the loop runs. "
        "Attribution either side of that line means different things;",
        "**history matters.** What is in the sediment is last decade's deliveries, and it "
        "is released on the sediment's schedule, not this year's.",
    ]:
        a(f"- {t}")
    a("")
    a("None of that is exotic or contested. It is the ordinary behaviour of a system with "
      "positive feedback, and it is why the same load can produce record damage in one "
      "year and a third of it in the next.\n")
    a("### And in Køge Bugt, the trigger is probably not nutrients\n")
    a("The loop above still starts with growth. A bay receiving a large, pulsed delivery "
      "of sewage solids and fat can enter it further along — the organic material and the "
      "oxygen demand arrive together, already made, and the die-off that releases the "
      "internal store can be the *first* step rather than the third.\n")
    a("That is a different causal shape from the one the accounting models, it produces "
      "the same shore, and it would be attributed to nitrogen by any method that only "
      "counts nitrogen.\n")

    # ------------------------------------------------------------------ 5
    a("## 5. The test that has already been run\n")
    a("There is one empirical check on the nitrogen-dominant model, and Denmark has "
      "spent thirty-five years and a great deal of money running it.\n")

    ld = tr["nitrogen_load"]
    a(f"**The intervention.** {ld['series']} has fallen from about "
      f"{ld['approx_1990_kt']:,} kt N/yr in 1990 to about {ld['approx_recent_kt']:,} kt — "
      f"a reduction of roughly {ld['reduction_pct_since_1990']}%. Airborne nitrogen to "
      "Danish sea areas is down by about the same. This is the largest environmental "
      "intervention in modern Danish policy and it is not in dispute.\n")

    ie = tr["iltsvind_extent"]
    a(f"**The outcome.** {ie['series']}, as reported by {ie['reported_by'].split(',')[0]}:\n")
    a("| Year | September extent | |")
    a("|---|---:|---|")
    for r in ie["observations"]:
        km = r.get("km2_september") or r.get("km2_late_september")
        cell = f"~{km:,} km²" if km else "—"
        a(f"| {r['year']} | {cell} | {r['note']} |")
    a("")
    a("**Put side by side:** " + tr["the_juxtaposition"] + "\n")
    a("If nitrogen load were the dominant control on oxygen depletion, halving it should "
      "have moved the extremes. It did not.\n")

    a("### The caveat that matters more than the headline\n")
    a(ie["caveat"] + "\n")
    a("2025 is the reason to be careful with this argument, and also the reason it "
      "points where it does. A system whose worst outcome swings threefold between "
      "consecutive years, under a load that barely moves between them, is a system "
      "governed by **the physics and the state of the individual year** — wind, "
      "stratification, temperature, what the bed is made of — with load as a slow "
      "background term. Note also that the load series is *flow-normalised*: the "
      "weather signal is deliberately removed from the input and is the dominant "
      "signal in the output.\n")

    # ------------------------------------------------------------------ 6
    a("## 6. Three ways to explain the gap\n")
    a("| Explanation | Standing | Detail |")
    a("|---|---|---|")
    for c in tr["competing_explanations"]:
        a(f"| {c['name']} | **{c['status']}** | {c['detail']} |")
    a("")
    a("Only the first leaves the policy frame intact — it says the intervention is "
      "working and the answer is patience. It is also the one that fails on its own "
      "terms, because the elapsed time exceeds the longest lag anyone has measured.\n")
    a("The three share a property worth stating plainly: **none of them is a source.** "
      "A source apportionment cannot represent a lag, cannot represent temperature, and "
      "cannot represent the difference between a bay that can absorb a kilogram of "
      "nitrogen and a bay that cannot. They are not omitted because they were judged "
      "small. They are omitted because the instrument has no slot of that shape.\n")
    a("So when the intervention underperforms, the instrument has exactly one thing it "
      "can recommend: more of the same intervention. Not because that is the best "
      "reading of the evidence, but because it is the only reading the instrument can "
      "express.\n")

    # ------------------------------------------------------------------ 7
    a("## 7. State-dependence, stated as the mechanism\n")
    a("The third explanation deserves its own statement, because it is the one this "
      "project's own computations support.\n")
    a("Nitrogen is not a toxicant. It is a growth subsidy — the opposite of dead water. "
      "What determines whether a subsidy produces eelgrass meadows or a bacterial mat "
      "is **which life is present and able to take it up**, and that is a property of "
      "the receiving system, not of the nitrogen.\n")
    a("So the damage function is not *f(load)*. It is *f(load, state)*, and the state "
      "term has been driven down by things that are not nutrients at all:\n")
    for i, s in enumerate([
        "toxicants and metals, which remove grazers and filter feeders — the very "
        "organisms that would otherwise convert the subsidy into structure",
        "physical disturbance of the bed, which removes the binding fauna and drops the "
        "erosion threshold roughly fivefold (SEABED.md)",
        "each hypoxic event, which kills the benthos and makes the next event cheaper",
        "the loss of eelgrass, which removed both the uptake capacity and the sediment "
        "stabilisation at once",
        "turbidity from a bed that now resuspends several times more often, which keeps "
        "the light from whatever might recolonise",
    ], 1):
        a(f"{i}. {s}")
    a("")
    a("Every item on that list is a reason the *same* kilogram of nitrogen does more "
      "damage in 2025 than it did in 1990. None of them appears in a source "
      "apportionment, because none of them is a source. **Nitrogen sensitivity is a "
      "derived property of a damaged system**, and the accounting treats it as a "
      "constant.\n")

    # ------------------------------------------------------------------ 8
    a("## 8. What this does and does not establish\n")
    a("**It does not establish that agriculture is off the hook.** Multiplying unknown "
      "fractions yields an unknown, not a small one. Agriculture is plausibly still the "
      "largest single nitrogen contributor, the load is real, and reductions have "
      "documented local benefits.\n")
    a("**It does not establish that nitrogen policy failed.** Necessary and insufficient "
      "are different findings, and the record is consistent with the second.\n")
    a("**It does establish that the number is not what it is presented as.** "
      f"\"{AGRI_PCT}% of nitrogen\" is a residual of models over one term of an open "
      "account. \"70% of fedtemøg\" is that residual multiplied by four coefficients "
      "that have never been computed. The first is a defensible piece of bookkeeping. "
      "The second is not a measurement of anything.\n")
    a("**And it establishes an asymmetry in what gets counted.** Every term that would "
      "shift blame away from a countable source — deposition, regeneration, groundwater, "
      "legacy, temperature, state — is precisely a term with no row. That may be "
      "coincidence of what is easy to measure. It is worth noticing that the easy "
      "measurements and the politically actionable ones are the same set.\n")

    a("### The practical consequence\n")
    a("If nitrogen were the whole binding constraint, this would be a solved problem in "
      "principle: catch crops, wetlands, treatment upgrades, and extractive aquaculture "
      "are all available, and we have already deployed enough of them to halve the load. "
      "Either the remaining reduction needed is far larger than anything currently "
      "proposed, or nitrogen is not the whole binding constraint.\n")
    a("Both readings sit in the same record. **That thirty-five years of data cannot "
      "distinguish them is the strongest single argument that the accounting is "
      "measuring the wrong thing.**\n")

    # ------------------------------------------------------------------ 9
    a("## 9. What would separate the readings\n")
    a("| To test | Do this |")
    a("|---|---|")
    for t, d in [
        ("Whether the extremes track load at all",
         "Regress annual iltsvind extent on flow-normalised load, wind-work over the "
         "stratified season, and bottom-water temperature anomaly. All three series "
         "exist and are published. Nobody has published the regression."),
        ("Whether state-dependence is real",
         "The same regression with an interaction term, or simply: does a given load "
         "produce more hypoxia now than in 1990, holding weather constant? Answerable "
         "from existing DCE series."),
        ("Whether the denominator can be closed",
         "Two of the ten empty rows are tractable with standard methods — submarine "
         "groundwater discharge via radon/radium tracers, internal regeneration via "
         "benthic flux chambers. Both are routine elsewhere."),
        ("Whether the potency term matters",
         "Weight existing load figures by season and receiving-water stratification. "
         "Even a crude weighting beats the current implicit weight of 1.0 everywhere."),
        ("Whether fedtemøg has the season everyone assumes",
         "Fixed coastal cameras, monthly index, year-round. The cheapest item on this "
         "list by an order of magnitude, and the only claim here that is currently "
         "unfalsifiable in either direction."),
    ]:
        a(f"| {t} | {d} |")
    a("")
    a("None of these needs new instruments. Four of the five need no new data at all — "
      "only that two published series be plotted against each other.\n")

    a("---\n")
    a("*Sources for the load and outcome series, with URLs, are in "
      "`data/manual/monitoring.json` under `load_trend_vs_outcome`. The pathway "
      "enumeration is in `data/manual/nitrogen_pathways.json`. Bounds marked as ours "
      "are constructed here and labelled as such.*")

    path = os.path.join(ROOT, "docs", "CAUSATION.md")
    text = "\n".join(o)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    log(f"wrote docs/CAUSATION.md ({len(text):,} chars)")
    log(f"  land term {land_lo}-{land_hi} kt, agriculture {agri_lo:.0f}-{agri_hi:.0f} kt")
    log(f"  quantified denominator floor {tot_lo:.0f}-{tot_hi:.0f} kt, "
        f"{len(unquant)}/{len(paths)} rows empty")
    log(f"  ceiling on agriculture's share: {ceil_lo:.0f}-{ceil_hi:.0f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
