#!/usr/bin/env python3
"""Generate docs/CAUSATION.md - what survives between "agriculture 69.6% of nitrogen"
and "agriculture causes 70% of fedtemøg".

NITROGEN.md audits the number where it is produced: the denominator, the estimator, the
currency. This document does something different. It takes the number at face value and
follows it forward through the causal chain it is quoted as describing, asking at each
link what coefficient exists. The answer is that four of them do not exist, and the
product of four unknown fractions is reported as one measured fraction.

Then it puts the intervention and the outcome side by side, which nobody does, because
that juxtaposition is the only empirical test of the nitrogen-dominant model that
thirty-five years of Danish policy has actually run.

Usage:  python3 scripts/causation.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, log, read_json

MANUAL = os.path.join(ROOT, "data", "manual")
AGRI_PCT = 69.6          # the published share, taken at face value throughout

# The chain the phrase "agriculture causes 70% of fedtemøg" asserts, one link per row.
# "coefficient" is what would have to exist for the multiplication to be legitimate.
CHAIN = [
    ("Agriculture → the land-based waterborne nitrogen term",
     "69.6%",
     "PUBLISHED",
     "A residual: measured-plus-modelled total minus modelled point sources minus "
     "modelled natural background. Retention modelled at ±16 percentage points. "
     "Returns negative values in dry years."),
    ("That term → all reactive nitrogen reaching the sea",
     "no coefficient",
     "OPEN SET",
     "10 of 20 enumerated pathways carry no number, including atmospheric deposition's "
     "organic fraction, submarine groundwater discharge, and sediment regeneration — "
     "probably the largest single supply to the productive layer."),
    ("Nitrogen → oxygen depletion",
     "no coefficient",
     "NOT COMPUTED",
     "Nitrogen is one of at least six oxygen sinks. There is no potency term: a kilogram "
     "in February into a mixed column counts the same as a kilogram in July under a "
     "pycnocline. No ventilation term, no state variable."),
    ("Oxygen depletion → loss of higher life",
     "no coefficient",
     "NOT COMPUTED",
     "Hypoxia is one route among several — toxicants, trawling, turbidity, sulphide "
     "exposure, physical loss of habitat. The soft-bottom survey runs 1 March–31 May, "
     "so the autumn kill is never observed, only its aftermath."),
    ("Loss of higher life → fedtemøg on a shore",
     "no coefficient",
     "NOT MEASURED AT ALL",
     "Fedtemøg has no national monitoring — not extent, not biomass, not duration. "
     "And it needs retention, stranding wind and a shore, which are properties of the "
     "receiving bay, not of the source."),
]


def fmt(x):
    return f"{x:,.0f}" if abs(x) >= 10 else f"{x:,.1f}"


def main():
    paths = read_json(os.path.join(MANUAL, "nitrogen_pathways.json"))["pathways"]
    mon = read_json(os.path.join(MANUAL, "monitoring.json"))
    tr = mon["load_trend_vs_outcome"]

    # the two rows that make up the land-based waterborne term the 69.6% is a share of
    land = [p for p in paths if p["pathway"].startswith("Danish land via")]
    land_lo = sum(p["lo"] for p in land)
    land_hi = sum(p["hi"] for p in land)
    agri_lo = land_lo * AGRI_PCT / 100
    agri_hi = land_hi * AGRI_PCT / 100

    quant = [p for p in paths if p["lo"] is not None]
    unquant = [p for p in paths if p["lo"] is None]
    tot_lo = sum(p["lo"] for p in quant)
    tot_hi = sum(p["hi"] for p in quant)

    # a CEILING, not a share: the denominator can only grow, so this can only fall
    ceil_hi = agri_hi / tot_lo * 100
    ceil_lo = agri_lo / tot_hi * 100

    o = []
    a = o.append

    a("# The chain from nitrogen to fedtemøg\n")
    a("Generated by `scripts/causation.py` from `data/manual/`. "
      "Companion to [NITROGEN.md](#NITROGEN.md), which audits the number where it is "
      "made. This document does the opposite: it grants the number and follows it "
      "*forward*, through the causal chain it is routinely quoted as describing.\n")

    a("> **agriculture causes 70% of fedtemøg**\n")
    a("That sentence, or a close variant, is how the figure enters public argument. "
      "It is a claim about an outcome on a shore. The number behind it is a share of "
      "one term in one account. Between the two lie four links, and this document asks "
      "what coefficient each one has.\n")

    # ------------------------------------------------------------------ 1
    a("## 1. What the number is a share of\n")
    a(f"The published {AGRI_PCT}% is agriculture's share of the **land-based waterborne "
      "term** — nitrogen arriving at the coast through Danish streams and unmonitored "
      "catchments. Those are two rows of the twenty enumerated in NITROGEN.md:\n")
    a("| Row | kt N/yr | Status |")
    a("|---|---:|---|")
    for p in land:
        a(f"| {p['pathway']} | {fmt(p['lo'])} – {fmt(p['hi'])} | {p['status'].title()} |")
    a(f"| **The term the percentage divides** | **{fmt(land_lo)} – {fmt(land_hi)}** | |")
    a(f"| **{AGRI_PCT}% of it — the agricultural load** | **{fmt(agri_lo)} – {fmt(agri_hi)}** | |")
    a("")
    a(f"So the quantity in question is roughly **{fmt(agri_lo)}–{fmt(agri_hi)} kt N/yr**. "
      "That is a real number and it is not small. The question is what it is a share "
      "*of*.\n")
    a(f"The enumerated pathways that carry any number at all sum to "
      f"**{fmt(tot_lo)} – {fmt(tot_hi)} kt N/yr**, with **{len(unquant)} of {len(paths)} "
      "rows empty**. An empty row can only add. So the denominator has a floor and no "
      "ceiling, and any share computed against it is a **ceiling, not an estimate**:\n")
    a(f"> Agriculture accounts for **no more than {ceil_hi:.0f}%** of enumerated "
      "reactive nitrogen reaching Danish marine waters — and at the wide end of the "
      f"denominator bounds, as little as {ceil_lo:.0f}%. Fill any of the empty rows and "
      "that ceiling falls. It cannot rise.\n")
    a(f"The published {AGRI_PCT}% and this ceiling are not competing estimates of the "
      "same thing. They answer different questions, and only the second one is the "
      "question the public sentence is asking.\n")
    a("Two omissions set the scale of the gap. **Atmospheric deposition to Danish marine "
      "waters is 45–65 kt N/yr** — comparable to the entire land-based term, falling on "
      "the water directly, and absent from every published apportionment. **Sediment "
      "regeneration** is not a source at all in the accounting frame, yet one study puts "
      "net advection at around a tenth of what annual primary production requires, which "
      "implies internal recycling supplies most of it.\n")

    # ------------------------------------------------------------------ 2
    a("## 2. Four missing coefficients, reported as one number\n")
    a("Granting the 69.6% entirely, here is what it has to survive to become a claim "
      "about fedtemøg:\n")
    a("| Link | Coefficient | Status | Why |")
    a("|---|---|---|---|")
    for link, coef, status, why in CHAIN:
        a(f"| {link} | {coef} | **{status}** | {why} |")
    a("")
    a("Every one of those links is a real causal connection. None of them has a number. "
      "The sentence multiplies them anyway, and the product inherits the appearance of "
      "the one factor that was measured.\n")
    a("This is not a claim that the links are weak. It is a claim about what kind of "
      "object the result is. **A product of four unknown fractions is an unknown "
      "fraction** — not a small one. Agriculture may still be the largest single "
      "contributor at every link. Nobody has computed it either way, and that is the "
      "finding.\n")

    # ------------------------------------------------------------------ 3
    a("## 3. The test that has already been run\n")
    a("There is one empirical check on the nitrogen-dominant model, and Denmark has "
      "spent thirty-five years and a great deal of money running it.\n")

    ld = tr["nitrogen_load"]
    a(f"**The intervention.** {ld['series']} has fallen from about "
      f"{ld['approx_1990_kt']:,} kt N/yr in 1990 to about {ld['approx_recent_kt']:,} kt — "
      f"a reduction of roughly {ld['reduction_pct_since_1990']}%. Airborne nitrogen to "
      "Danish sea areas is down by about the same. This is the largest environmental "
      "intervention in modern Danish policy and it is not in dispute.\n")

    ie = tr["iltsvind_extent"]
    a(f"**The outcome.** {ie['series']}, as reported by {ie['reported_by'].split(',')[0]}:\n")
    a("| Year | September extent | |")
    a("|---|---:|---|")
    for r in ie["observations"]:
        km = r.get("km2_september") or r.get("km2_late_september")
        cell = f"~{km:,} km²" if km else "—"
        a(f"| {r['year']} | {cell} | {r['note']} |")
    a("")
    a("**Put side by side:** " + tr["the_juxtaposition"] + "\n")
    a("If nitrogen load were the dominant control on oxygen depletion, halving it should "
      "have moved the extremes. It did not.\n")

    a("### The caveat that matters more than the headline\n")
    a(ie["caveat"] + "\n")
    a("2025 is the reason to be careful with this argument, and also the reason it "
      "points where it does. A system whose worst outcome swings threefold between "
      "consecutive years, under a load that barely moves between them, is a system "
      "governed by **the physics and the state of the individual year** — wind, "
      "stratification, temperature, what the bed is made of — with load as a slow "
      "background term. Note also that the load series is *flow-normalised*: the "
      "weather signal is deliberately removed from the input and is the dominant "
      "signal in the output.\n")

    # ------------------------------------------------------------------ 4
    a("## 4. Three ways to explain the gap\n")
    a("| Explanation | Standing | Detail |")
    a("|---|---|---|")
    for c in tr["competing_explanations"]:
        a(f"| {c['name']} | **{c['status']}** | {c['detail']} |")
    a("")
    a("Only the first leaves the policy frame intact — it says the intervention is "
      "working and the answer is patience. It is also the one that fails on its own "
      "terms, because the elapsed time exceeds the longest lag anyone has measured.\n")
    a("The three share a property worth stating plainly: **none of them is a source.** "
      "A source apportionment cannot represent a lag, cannot represent temperature, and "
      "cannot represent the difference between a bay that can absorb a kilogram of "
      "nitrogen and a bay that cannot. They are not omitted because they were judged "
      "small. They are omitted because the instrument has no slot of that shape.\n")
    a("So when the intervention underperforms, the instrument has exactly one thing it "
      "can recommend: more of the same intervention. Not because that is the best "
      "reading of the evidence, but because it is the only reading the instrument can "
      "express.\n")

    # ------------------------------------------------------------------ 5
    a("## 5. State-dependence, stated as the mechanism\n")
    a("The third explanation deserves its own statement, because it is the one this "
      "project's own computations support.\n")
    a("Nitrogen is not a toxicant. It is a growth subsidy — the opposite of dead water. "
      "What determines whether a subsidy produces eelgrass meadows or a bacterial mat "
      "is **which life is present and able to take it up**, and that is a property of "
      "the receiving system, not of the nitrogen.\n")
    a("So the damage function is not *f(load)*. It is *f(load, state)*, and the state "
      "term has been driven down by things that are not nutrients at all:\n")
    for i, s in enumerate([
        "toxicants and metals, which remove grazers and filter feeders — the very "
        "organisms that would otherwise convert the subsidy into structure",
        "physical disturbance of the bed, which removes the binding fauna and drops the "
        "erosion threshold roughly fivefold (SEABED.md)",
        "each hypoxic event, which kills the benthos and makes the next event cheaper",
        "the loss of eelgrass, which removed both the uptake capacity and the sediment "
        "stabilisation at once",
        "turbidity from a bed that now resuspends several times more often, which keeps "
        "the light from whatever might recolonise",
    ], 1):
        a(f"{i}. {s}")
    a("")
    a("Every item on that list is a reason the *same* kilogram of nitrogen does more "
      "damage in 2025 than it did in 1990. None of them appears in a source "
      "apportionment, because none of them is a source. **Nitrogen sensitivity is a "
      "derived property of a damaged system**, and the accounting treats it as a "
      "constant.\n")

    # ------------------------------------------------------------------ 6
    a("## 6. What this does and does not establish\n")
    a("**It does not establish that agriculture is off the hook.** Multiplying unknown "
      "fractions yields an unknown, not a small one. Agriculture is plausibly still the "
      "largest single nitrogen contributor, the load is real, and reductions have "
      "documented local benefits.\n")
    a("**It does not establish that nitrogen policy failed.** Necessary and insufficient "
      "are different findings, and the record is consistent with the second.\n")
    a("**It does establish that the number is not what it is presented as.** "
      f"\"{AGRI_PCT}% of nitrogen\" is a residual of models over one term of an open "
      "account. \"70% of fedtemøg\" is that residual multiplied by four coefficients "
      "that have never been computed. The first is a defensible piece of bookkeeping. "
      "The second is not a measurement of anything.\n")
    a("**And it establishes an asymmetry in what gets counted.** Every term that would "
      "shift blame away from a countable source — deposition, regeneration, groundwater, "
      "legacy, temperature, state — is precisely a term with no row. That may be "
      "coincidence of what is easy to measure. It is worth noticing that the easy "
      "measurements and the politically actionable ones are the same set.\n")

    a("### The practical consequence\n")
    a("If nitrogen were the whole binding constraint, this would be a solved problem in "
      "principle: catch crops, wetlands, treatment upgrades, and extractive aquaculture "
      "are all available, and we have already deployed enough of them to halve the load. "
      "Either the remaining reduction needed is far larger than anything currently "
      "proposed, or nitrogen is not the whole binding constraint.\n")
    a("Both readings sit in the same record. **That thirty-five years of data cannot "
      "distinguish them is the strongest single argument that the accounting is "
      "measuring the wrong thing.**\n")

    # ------------------------------------------------------------------ 7
    a("## 7. What would separate the readings\n")
    a("| To test | Do this |")
    a("|---|---|")
    for t, d in [
        ("Whether the extremes track load at all",
         "Regress annual iltsvind extent on flow-normalised load, wind-work over the "
         "stratified season, and bottom-water temperature anomaly. All three series "
         "exist and are published. Nobody has published the regression."),
        ("Whether state-dependence is real",
         "The same regression with an interaction term, or simply: does a given load "
         "produce more hypoxia now than in 1990, holding weather constant? Answerable "
         "from existing DCE series."),
        ("Whether the denominator can be closed",
         "Two of the ten empty rows are tractable with standard methods — submarine "
         "groundwater discharge via radon/radium tracers, internal regeneration via "
         "benthic flux chambers. Both are routine elsewhere."),
        ("Whether the potency term matters",
         "Weight existing load figures by season and receiving-water stratification. "
         "Even a crude weighting beats the current implicit weight of 1.0 everywhere."),
        ("Whether fedtemøg has the season everyone assumes",
         "Fixed coastal cameras, monthly index, year-round. The cheapest item on this "
         "list by an order of magnitude, and the only claim here that is currently "
         "unfalsifiable in either direction."),
    ]:
        a(f"| {t} | {d} |")
    a("")
    a("None of these needs new instruments. Four of the five need no new data at all — "
      "only that two published series be plotted against each other.\n")

    a("---\n")
    a("*Sources for the load and outcome series, with URLs, are in "
      "`data/manual/monitoring.json` under `load_trend_vs_outcome`. The pathway "
      "enumeration is in `data/manual/nitrogen_pathways.json`. Bounds marked as ours "
      "are constructed here and labelled as such.*")

    path = os.path.join(ROOT, "docs", "CAUSATION.md")
    text = "\n".join(o)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    log(f"wrote docs/CAUSATION.md ({len(text):,} chars)")
    log(f"  land term {land_lo}-{land_hi} kt, agriculture {agri_lo:.0f}-{agri_hi:.0f} kt")
    log(f"  quantified denominator floor {tot_lo:.0f}-{tot_hi:.0f} kt, "
        f"{len(unquant)}/{len(paths)} rows empty")
    log(f"  ceiling on agriculture's share: {ceil_lo:.0f}-{ceil_hi:.0f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
