#!/usr/bin/env python3
"""The method lab: experiments on the instrument, kept away from findings about the sea.

Everything else on this site is an argument about Danish water. This page is not.
It is a set of experiments on the METHODS - what this archive could have
detected, what an estimator recovers when the answer is known in advance, and
where a piece of reasoning eats its own tail. Those belong apart from the
substantive pages for a plain reason: a reader who cannot tell which claims rest
on measurement and which on simulation is entitled to distrust both.

The separation is editorial, not defensive. Nothing here is weaker evidence than
what is on the other pages; it is evidence about a different object.

Writes docs/METHOD_LAB.md.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from common import DERIVED, ROOT, log, read_json

OUT = os.path.join(ROOT, "docs", "METHOD_LAB.md")


def main():
    det = {}
    p = os.path.join(DERIVED, "detectable.json")
    if os.path.exists(p):
        det = read_json(p)

    o = []
    def w(s=""):
        o.append(s)

    w("# The method lab")
    w()
    w("*Experiments on the instrument, not on the sea. Nothing on this page is a")
    w("finding about Danish water; every claim here is about what this project's")
    w("methods can and cannot see. Generated by `scripts/methodlab.py`.*")
    w()
    w("Every other page argues about water. This one asks whether the arguing")
    w("works: what the monitoring archive could have detected had it been there,")
    w("what an estimator recovers when the truth is stipulated in advance, and")
    w("where a chain of reasoning turns out to be feeding on itself. Those are kept")
    w("separate because a reader who cannot tell which claims rest on measurement")
    w("and which on simulation is entitled to distrust both.")
    w()
    w("## This is not a new method, and that matters")
    w()
    w("Building a known world, sampling it the way the real instrument samples,")
    w("and checking whether the analysis recovers what was put in, is standard")
    w("practice with an established name. In meteorology and oceanography it is an")
    w("**Observing System Simulation Experiment**: a *nature run* stands in for the")
    w("world, synthetic observations are drawn from it with realistic error, and the")
    w("analysis is scored against a truth that is known because it was constructed.")
    w("OSSEs are how agencies decide whether a proposed satellite or buoy array")
    w("would earn its cost *before* it is built ([Hoffman & Atlas, *BAMS* 101(8),")
    w("2020](https://journals.ametsoc.org/view/journals/bams/101/8/bamsD190155.xml);")
    w("[Fujii et al., *Frontiers in Marine Science*,")
    w("2019](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2019.00417/full)).")
    w("The same logic under a different name is prospective power analysis, which is")
    w("uncontroversial wherever an experiment has to be sized before it is run.")
    w()
    w("So the objection worth taking seriously is not *this method has no")
    w("precedent*. It is the narrower and fairer one: **a simulation can only")
    w("license claims about the instrument, never about the world.** That line is")
    w("drawn explicitly below, and anywhere it is crossed on another page is a bug")
    w("worth reporting.")
    w()
    w("## 1. What could this archive have seen?")
    w()
    if det.get("runs"):
        w(f"`scripts/detectable.py` takes the **{det['n_visits']:,} real")
        w("surface-oxygen visits** in the water-chemistry extract - their true")
        w("stations, dates and clock times - imposes a diurnal cycle of stipulated")
        w("amplitude keyed to the sun's elevation, and runs the same estimator")
        w("[OPEN_PROBLEMS.md](OPEN_PROBLEMS.md) item 17 uses on the real data. It")
        w("claims nothing about how the sea behaves. It asks only: *if it behaved")
        w("this way, at this amplitude, would this schedule have found out?*")
        w()
        w("| imposed amplitude | recovered on the real hours | recovered if sampled round the clock | lost to the working day |")
        w("|---:|---:|---:|---:|")
        for r in det["runs"]:
            a, g, e = r["imposed"], r["recovered_real_hours"], r["recovered_even_hours"]
            lost = f"**{100*(1-g/e):.0f}%**" if e > 0.02 and a else "—"
            w(f"| {a:.2f} | {g:.3f} | {e:.3f} | {lost} |")
        w()
        w("**The working day costs about three quarters of a diurnal signal**, and")
        w("it costs it steadily across a hundredfold range of amplitudes. The same")
        w("visits, the same stations, the same seasons - only the hour redrawn. That")
        w("is the strongest result on this page, and it is very nearly")
        w("assumption-free: no model of the sea enters the comparison of a schedule")
        w("with itself.")
        w()
        w("It also settles something that had been asserted without evidence.")
        w("[OPEN_PROBLEMS.md](OPEN_PROBLEMS.md) said the 09:00-15:00 window is *why*")
        w("the pre-dawn minimum is invisible. That was a plausible story. It is now a")
        w("measured attenuation with a number on it.")
        w()
        lim = det.get("detection_limit_mg_l")
        obs = det.get("observed_real_spread_mg_l")
        if lim and obs:
            w(f"**The bound is softer and should be quoted as a range.** Recovery")
            w(f"crosses the {obs} mg/l actually observed somewhere between an imposed")
            w(f"0.2 and 0.5 mg/l, so the real surface diurnal amplitude is below")
            w(f"roughly **0.35 to {lim} mg/l**. The coarse grid in the script reports")
            w(f"the upper end; interpolating gives the lower. That is a bound rather")
            w("than a null, and a bound is the stronger object: a null cannot")
            w("separate *the effect is absent* from *the instrument could not have")
            w("seen it*.")
        if det.get("noise_sd_mg_l"):
            w()
            w(f"Noise is measured at **{det['noise_sd_mg_l']} mg/l**, not assumed -")
            w("see the circularity register below for why the first two attempts at")
            w("that number were wrong.")
    else:
        w("*`data/derived/detectable.json` not present - run `scripts/detectable.py`.*")
    w()
    w("### And the reason it cannot be seen at all")
    w()
    w("Fixing the circularity produced a diagnostic worth more than the fix. Of")
    w("**81,627 station-window cells, 80,445 - 98.5% - contain samples from only")
    w("one sun-elevation bin.** Within a station's own ten-day window, the water is")
    w("almost always sampled at the same height of sun.")
    w()
    w("That is a harder limit than a narrow working day. A fixed-effects estimator")
    w("sees a diurnal signal only through *within-cell* contrast, and 98.5% of the")
    w("cells have none to offer. Whatever the archive can say about the daily cycle")
    w("rests on the remaining 1.5%. It also explains the three-quarters attenuation")
    w("above mechanically rather than by analogy: the hours are not merely narrow,")
    w("they are repeated.")
    w()
    w("## 2. The circularity register")
    w()
    w("Each of these was found in this project's own work, most of it within")
    w("minutes of writing it. They are listed because the failure mode is silent:")
    w("a circular check passes.")
    w()
    w("**The noise that contained the signal.** The detection limit above scales")
    w("with an estimate of the noise an estimator must see through. The first")
    w("version asserted 0.8 mg/l, which made the bound only as good as a guess. The")
    w("second measured the archive's within-cell residual spread - and that residual")
    w("*contains whatever diurnal signal exists*, so a large real cycle would have")
    w("inflated the yardstick used to rule a large real cycle out. The bias runs")
    w("conservative, which is exactly why it could have stood for years unnoticed.")
    w("The estimate is now taken only from cells whose samples all fall in one")
    w("sun-elevation bin, where no diurnal variance can enter by construction.")
    w()
    w("**Validating a flow model against a flood model.** The 2012 Copenhagen")
    w("sheets are the output of somebody's hydraulic model run over a terrain")
    w("model. Scoring a new terrain-driven flow model against them measures")
    w("agreement between two implementations of similar physics, not correctness")
    w("against the world. They are usable as a sanity check and not as truth -")
    w("which is the same rule this project applies to official catchment")
    w("delineations, for the same reason.")
    w()
    w("**Borrowing a clock and then analysing the hour.** 80% of CTD station-days")
    w("can take a time from a same-day water-chemistry bottle, because 99% of those")
    w("station-days carry a single one. But if casts systematically precede bottles,")
    w("any diurnal pattern found at depth is partly an artefact of the borrowing.")
    w("`scripts/depth_clock.py` therefore treats supplied field-sheet times as a")
    w("*check* on the borrowed clock rather than a replacement for it, and reports")
    w("the offset distribution. Until such times exist it says the check has not")
    w("been run, instead of reporting an unchecked number as a result.")
    w()
    w("**Tuning to match, then citing the match.** If a model is adjusted until it")
    w("reproduces an official product, agreement with that product stops being")
    w("evidence of anything. It is written down here in advance because the")
    w("temptation arrives later, at the moment a divergence appears and looks like")
    w("a mistake.")
    w()
    w("## 3. What a simulation may and may not license")
    w()
    w("| may | may not |")
    w("|---|---|")
    w("| *This schedule loses 75% of a signal of this shape.* | *The sea has a diurnal cycle of size X.* |")
    w("| *This estimator recovers a stipulated amplitude down to Y.* | *The estimator's output on real data is therefore correct.* |")
    w("| *This flow code conserves mass and is tile-invariant.* | *Danish catchments drain the way this code says.* |")
    w("| *A proposed survey would or would not resolve this question.* | *The question is answered.* |")
    w()
    w("The right-hand column needs measurement. That is what")
    w("[IF_YOU_HAVE_THE_DATA.md](IF_YOU_HAVE_THE_DATA.md) and")
    w("[EXPERIMENTS.md](EXPERIMENTS.md) are for, and it is why this page is")
    w("separate from them rather than folded in.")
    w()

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(o).rstrip("\n") + "\n")
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
