#!/usr/bin/env python3
"""The method lab: experiments on the instrument, kept away from findings about the sea.

Everything else on this site is an argument about Danish water. This page is not.
It is a set of experiments on the METHODS - what this archive could have
detected, what an estimator recovers when the answer is known in advance, and
where a piece of reasoning eats its own tail. Those belong apart from the
substantive pages for a plain reason: a reader who cannot tell which claims rest
on measurement and which on simulation is entitled to distrust both.

The separation is editorial, not defensive. Nothing here is weaker evidence than
what is on the other pages; it is evidence about a different object.

Writes docs/METHOD_LAB.md.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from common import DERIVED, ROOT, log, write_doc
import live

OUT = os.path.join(ROOT, "docs", "METHOD_LAB.md")


def main():
    # Loaded live: every number below that comes from these files carries its
    # file and field, and write_doc() links it to its entry in SOURCES.md.
    p = os.path.join(DERIVED, "detectable.json")
    det = live.live_json(p) if os.path.exists(p) else {}
    q = os.path.join(DERIVED, "depth_clock.json")
    dc = live.live_json(q) if os.path.exists(q) else {}

    o = []
    def w(s=""):
        o.append(s)

    w("# The method lab")
    w()
    w("*Generated by `scripts/methodlab.py`.*")
    w()
    w(live.claim_begin('C-ML-SCOPE') + "This page holds experiments on this project's methods: what the")
    w("monitoring archive could have detected, what an estimator recovers when the truth is")
    w("stipulated in advance, and where a chain of reasoning feeds on itself. Its one statement")
    w("about the water is a bound, read from the real archive through a simulation and holding")
    w("only under that simulation's assumptions. It is kept apart from the pages that argue")
    w("about water because a reader who cannot tell which claims rest on measurement and which")
    w("on simulation is entitled to distrust both." + live.CLAIM_END)
    w()
    w("## This is not a new method, and that matters")
    w()
    w(live.claim_begin('C-ML-OSSE') + "Building a known world, sampling it the way the real instrument")
    w("samples, and checking whether the analysis recovers what was put in, is an established")
    w("method. In meteorology and oceanography it is an **Observing System Simulation")
    w("Experiment**: a *nature run* stands in for the world, synthetic observations are drawn")
    w("from it with realistic error, and the analysis is scored against a truth that is known")
    w("because it was constructed. The experiment below is one in miniature." + live.CLAIM_END)
    w(live.claim_begin('C-ML-OSSE-THEIRS') + "OSSEs are widely used to evaluate future observing systems")
    w("and network designs ([Fujii et al., *Frontiers in Marine Science*,")
    w("2019](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2019.00417/full))." + live.CLAIM_END)
    w(live.claim_begin('C-ML-POWER') + "The same logic under another name is prospective power analysis -")
    w("sizing an experiment by what it could detect, before it is run - which clinical-trial")
    w("guidelines require ([the ICH guideline on statistical principles for clinical")
    w("trials](https://www.ema.europa.eu/en/documents/scientific-guideline/ich-e-9-statistical-principles-clinical-trials-step-5_en.pdf))." + live.CLAIM_END)
    w()
    w(live.claim_begin('C-ML-LICENSE') + "So the objection worth taking seriously is not *this method has")
    w("no precedent*. It is the narrower one: **a simulation on its own licenses claims about the")
    w("instrument, not about the world.** A claim about the world needs a measurement: the bound")
    w("below is the real archive's spread read through the simulation, and it holds only under")
    w("the simulation's assumptions. The table at the end lists instances. The build refuses a")
    w("number built on simulation on any page but a method page; prose is not checked." + live.CLAIM_END)
    w()
    w("## 1. What could this archive have seen?")
    w()
    hi_loss = None
    if det.get("runs"):
        runs = list(det["runs"])
        ex = det.get("clock_excluded") or {}
        w(f"{live.claim_begin('C-ML-METHOD')}`scripts/detectable.py` takes the **{det['n_samples']:,} surface-oxygen")
        w("samples** the real estimate uses - read through `cycles.read_samples()`, so with the same")
        w("filters and the same clock - imposes a cycle proportional to the sine of the sun's")
        w("elevation at each sample's instant and place, adds noise measured from the archive, and")
        w("runs the estimator itself: `cycles.deviations()`, with its window and sun bins, and one")
        w(f"rule, applied to both sides, for which bins count. Each size is run on {det['draws']} noise")
        w("draws, the round-the-clock comparison on fewer. It claims nothing about how the sea")
        w("behaves. It asks only: *if it behaved this way, at this size, would this schedule have")
        w("found out?*" + live.CLAIM_END)
        w()
        if ex.get("default") and ex.get("ambiguous"):
            w(live.claim_begin('C-ML-LEFT-OUT') + f"Left out: {ex['default']:,} samples whose clock is a filled-in default")
            w(f"and {ex['ambiguous']:,} from suppliers whose clock convention is mixed. Neither can be placed")
            w("against the sun." + live.CLAIM_END + " See *The clock itself* below.")
            w()
        ceiling = runs[0]["recovered_real_p95"]
        w("| imposed size | recovered on the real hours | middle of the draws | recovered if sampled round the clock | lost to the working day | draws reaching the observed spread |")
        w("|---:|---:|---:|---:|---:|---:|")
        losses, amps = [], []
        for r in runs:
            a, g, e = r["imposed"], r["recovered_real_hours"], r["recovered_even_hours"]
            # a loss means something only where the signal stands clear of what no
            # cycle at all produces
            if a and g > ceiling:
                loss = live.step("K-SCHEDULE-LOSS", (1 - g / e) * 100)
                losses.append(loss)
                amps.append(a)
                lost = f"**{loss:.0f}%**"
            else:
                lost = "—"
            w(f"| {a:.2f} | {g:.3f} | {r['recovered_real_p05']:.3f} to "
              f"{r['recovered_real_p95']:.3f} | {e:.3f} | {lost} | "
              f"{r['share_at_or_above_observed'] * 100:.0f}% |")
        w()
        w(live.claim_begin('C-ML-TABLE-READ') + "The medians are shown; *middle of the draws* runs from about")
        w("the fifth to the ninety-fifth percentile. A loss is given only where the median recovery")
        w("clears the ninety-fifth percentile of what no cycle produces." + live.CLAIM_END)
        w()
        if len(losses) > 1:
            lo_loss, hi_loss = min(losses), max(losses)
            span = max(amps) / min(amps)
            w(f"{live.claim_begin('C-WORKDAY')}**The working day costs between {lo_loss:.0f}% and {hi_loss:.0f}% of a")
            w(f"sun-shaped daily cycle**, steadily across a {span:.0f}-fold range of sizes - every size")
            w("large enough to recover above the noise." + live.CLAIM_END)
            w(live.claim_begin('C-ML-ASSUMPTION-FREE') + "The same samples, stations and seasons are compared")
            w("with themselves, only the hour redrawn, so no model of the sea's mean state or seasons")
            w("enters. What does enter is the stipulated sun-shaped cycle and Gaussian noise of the")
            w("measured size, against a round-the-clock schedule with the hour drawn uniformly; a cycle")
            w("peaking at another hour would lose a different share." + live.CLAIM_END)
            w()
        lim = det.get("detection_limit_mg_l")
        obs = det.get("observed_real_spread_mg_l")
        null = det.get("null_share_at_or_above_observed")
        if obs is not None and null is not None and null >= 1 - det["level"]:
            w(f"**The observed spread is not evidence of a cycle.** {live.claim_begin('C-ML-SPREAD-NOT-EVIDENCE')}The real")
            w(f"archive shows a spread of {obs:g} mg/l across the sun bins. With no cycle imposed at all,")
            w(f"{null * 100:.0f}% of draws produce one at least as large, which is too often for the")
            w("observed spread to count as a sign of one." + live.CLAIM_END)
            w()
        if lim:
            at = next(r for r in runs if r["imposed"] == lim)
            w(f"**The bound.** {live.claim_begin('C-DIURNAL-BOUND')}A cycle of size {lim:g} mg/l produces a spread")
            w(f"at least as large as the observed one in {at['share_at_or_above_observed'] * 100:.0f}% of draws, and")
            w(f"every smaller size on the grid does so in fewer than {det['level'] * 100:.0f}% of them. So if")
            w("the real surface cycle follows the sine of the sun's elevation, its size is below")
            w(f"{lim:g} mg/l. The size is the coefficient on that sine: the swing from night to noon it")
            w("would give where the sun stands overhead, and more than the swing on any Danish day." + live.CLAIM_END)
            w(live.claim('C-ML-BOUND-STRONGER', "A bound is a stronger object than a null: a null cannot "
              "separate *the effect is absent* from *the instrument could not have seen it*, and a bound can."))
        if det.get("noise_sd_mg_l"):
            w()
            w(live.claim_begin('C-ML-NOISE-MEASURED') + f"Noise is measured from the archive, at **{det['noise_sd_mg_l']:g} mg/l**,")
            w(f"from {det['noise_n']:,} samples whose window neighbours all share their sun bin, so the")
            w("contrast between bins cannot enter it; its Gaussian form is stipulated." + live.CLAIM_END)
    else:
        w("*`data/derived/detectable.json` not present - run `scripts/detectable.py`.*")
    w()
    n, nw, ns = det.get("n_samples"), det.get("samples_with_neighbours"), det.get("samples_single_bin")
    if n and nw and ns:
        alone = live.step("K-SUBSET-SHARE", (n - nw) / n * 100)
        share = live.step("K-SUBSET-SHARE", ns / nw * 100)
        w("### What the estimator has to work with")
        w()
        w(live.claim_begin('C-ML-NEIGHBOURS') + "The estimator sees a diurnal signal only through contrast")
        w(f"*within* a station's own ±{det['window_days']}-day window. Of the {n:,} samples,")
        w(f"**{alone:.0f}% have no other sample from their station inside that window** and")
        w(f"contribute nothing. Of the {nw:,} that do, **{ns:,} - {share:.0f}% - have neighbours only")
        w("in their own sun-elevation bin**, and so add no contrast between bins. Whatever this")
        w("estimator can say about the daily cycle rests on the rest." + live.CLAIM_END)
        w()
    w("### The clock itself")
    w()
    w(live.claim('C-ML-TECH-INSTRUCTION', "The technical instruction for Danish marine monitoring asks for "
      "sampling times in UTC."))
    w(live.claim_begin('C-ML-CLOCK-KINDS') + "`Startklok` is not UTC wherever that can be tested, and it is")
    w("not one kind of thing. `scripts/clockzone.py` compares every station with itself in the")
    w("weeks either side of each summer-time change: a wall clock does not move, a UTC clock")
    w("jumps an hour one way, a clock with the offset added jumps the other. Until the late")
    w("nineties the archive's times are Danish wall-clock times with the offset *added*, mixed")
    w("with filled-in defaults that read noon and three in the morning local once the offset is")
    w("taken off; from the early two-thousands they are wall-clock times; and some suppliers'")
    w("conventions are mixed." + live.CLAIM_END)
    w(live.claim('C-ML-CLOCKPY', "Every analysis that places a water-chemistry sample in time takes the instant from "
      "`scripts/clock.py`, which returns one UTC instant or says why there is none; the raw column is "
      "read elsewhere only for fixed readings kept as controls and a clock-hour count no page uses."))
    w()
    w("## 2. The circularity register")
    w()
    w(live.claim_begin('C-ML-CIRC-INTRO') + "Each item below is a way a check on this project's methods can")
    w("pass without testing what it seems to test. The failure is silent: a circular")
    w("check passes." + live.CLAIM_END)
    w()
    w("**The noise that contains the signal.** " + live.claim_begin('C-ML-NOISE-CIRC')
      + "The bound above depends on an estimate of")
    w("the noise the estimator must see through. Taken as the archive's within-cell")
    w("residual spread, that estimate would contain whatever diurnal signal exists, so")
    w("a large real cycle would inflate the yardstick used to rule a large real cycle")
    w("out - and a noisier null reaches the observed spread more often, so the bias")
    w("would favour this page's conclusion that the spread is not a cycle."
      + live.CLAIM_END + " " + live.claim_begin('C-ML-NOISE-NOW') + "The noise is")
    w("therefore taken only from samples whose window neighbours all fall in their own")
    w("sun-elevation bin, so only the diurnal variation inside one bin can enter it."
      + live.CLAIM_END)
    w()
    if det.get("draws"):
        w("**Comparing a simulation with an observation.** " + live.claim_begin('C-ML-ONE-ESTIMATOR')
          + "The two are compared")
        w("through one estimator called on both sides: the observed spread and every")
        w("synthetic recovery come from `cycles.deviations()`, with the same window, the")
        w(f"same sun bins and the same rule for which bins count, over {det['draws']} noise")
        w("draws per amplitude." + live.CLAIM_END)
        w()
    w("**Validating a flow model against a flood model.** " + live.claim_begin('C-ML-FLOOD-MODEL')
      + "The 2012 Copenhagen")
    w("sheets are calculated flood scenarios for a hundred-year event, published by")
    w("Københavns Kommune: the output of a model, not a record of flooding. Which model,")
    w("over what terrain, and whether it included the sewers, is not stated in anything")
    w("this project holds." + live.CLAIM_END + " " + live.claim_begin('C-ML-FLOW-VS-FLOOD')
      + "Scoring a terrain-driven flow model")
    w("against them measures agreement with another model, not correctness against the")
    w("world, so they can serve as a sanity check and not as truth." + live.CLAIM_END + " "
      + live.claim_begin('C-ML-CATCHMENT-RULE') + "The same will hold for")
    w("official catchment delineations when this project's own flow model is scored")
    w("against them: agreement will be a sanity check, not a validation." + live.CLAIM_END)
    w()
    w("**Borrowing a clock and then analysing the hour.**")
    cs = dc.get("clock_source") if dc else None
    if cs:
        w(f"{live.claim_begin('C-DEPTH-BORROW')}{cs['borrowed']:,} oxygen measurements at depth were placed in time")
        w("with a clock borrowed from a same-day water-chemistry bottle, and")
        w(f"{cs['none']:,} had no bottle with a usable time to borrow from - none that day,")
        w("or one whose clock is a filled-in default or of a mixed convention. The two")
        w("counts are not shares of one population: the first is counted after")
        w("`scripts/depth_clock.py`'s quality filters and the second before them."
          + live.CLAIM_END)
    w(live.claim_begin('C-ML-BORROW-ARTEFACT') + "If casts systematically precede bottles, any diurnal pattern found at")
    w("depth is partly an artefact of the borrowing." + live.CLAIM_END + " "
      + live.claim_begin('C-ML-DEPTHCLOCK-CHECK') + "`scripts/depth_clock.py` therefore")
    w("uses supplied field-sheet times where they exist and, where a cast has both a")
    w("supplied and a borrowed time, reports the distribution of the offset between")
    w("them - so supplied times check the borrowed clock as well as replacing it. Until")
    w("such times exist it reports the check as not run, instead of reporting an")
    w("unchecked number as a result." + live.CLAIM_END)
    w()
    w("**Tuning to match, then citing the match.** " + live.claim_begin('C-ML-TUNING')
      + "If a model is adjusted until it")
    w("reproduces an official product, agreement with that product stops being evidence")
    w("that the model is right. It is written down here in advance because the")
    w("temptation arrives later, at the moment a divergence appears and looks like a")
    w("mistake." + live.CLAIM_END)
    w()
    obs_path = os.path.join(DERIVED, "observing.json")
    nf = live.live_json(obs_path).get("noise_floor") if os.path.exists(obs_path) else None
    if nf:
        import claims
        from observing import _case
        cd, _, _ = claims.load()
        cache = {}

        def read(ph):
            return claims.resolve(cd, ph, cache)[0]
        n_st = read("{read:DCE-STATMOD-2015:29|statistiske modeller for 29 kystnære overvågningsstationer}")
        n_wb = read("{read:DCE-STATMOD-2015:22|som repræsenterer 22 vandområder}")
        windows = read("{read:DCE-STATMOD-2015:43|op til 43 månedsintervaller}")
        dce_r2 = read("{read:DCE-STATMOD-2015:0.4|kriteriet for dette statistiske mål er tentativt sat til mindst 0,4}")
        mean56 = read("{read:DCE-STATMOD-2015:0.56|har et gennemsnit på 0,56}")
        w("## 3. The noise floor of an acceptance criterion")
        w()
        w(live.claim_begin('C-ML-DCE-SCOPE') + "[OBSERVING.md](OBSERVING.md) examines the statistical models DCE built")
        w("to calculate how far nutrient inputs must fall for Danish fjords and coastal")
        w(f"waters to reach good ecological status, at {n_st} coastal monitoring stations")
        w(f"representing {n_wb} water bodies." + live.CLAIM_END + " "
          + live.claim_begin('C-ML-DCE-METHOD') + "DCE choose each model's variables by")
        w("stepwise, cross-validated regression on a calibration part of the data,")
        w("offering each candidate - nutrient and freshwater inputs, wind, light, salinity,")
        w(f"stratification, temperature - over up to {windows} period windows. They set the")
        w("number of variables by weighing calibration against validation performance,")
        w("evaluate the model on held-out data, refit it on all the data, and accept it on")
        w(f"several criteria, of which an $R^2$ of at least {dce_r2} is one." + live.CLAIM_END)
        w()
        w(live.claim_begin('C-ML-REPLICATION') + "The simulation below does not run that procedure. It runs a simpler")
        w(f"one: an exhaustive search over every set of up to {nf['max_terms']} of "
          f"{nf['candidates']} candidates,")
        w(f"{nf['subsets_searched']} sets in all, scored by in-sample $R^2$, with no period windows,")
        w("no cross-validation and no held-out data. The two simplifications pull in opposite")
        w("directions: period windows would give noise more chances than this search does,")
        w("while cross-validated selection and a held-out check would reject much of what an")
        w("in-sample search accepts. The computation is `noise_floor()` in")
        w(f"`scripts/observing.py`, run {nf['trials']} times per condition on pure noise:"
          + live.CLAIM_END)
        w()
        w(f"| condition | median $R^2$ | 75th | 90th | share clearing $R^2$ ≥ {nf['acceptance_r2']} |")
        w("|---|---:|---:|---:|---:|")
        for c in nf["cases"]:
            w(f"| {_case(c)} | {c['median']:.2f} | {c['p75']:.2f} | {c['p90']:.2f} "
              f"| {c['share_passing'] * 100:.0f}% |")
        w()
        real = [c for c in nf["cases"] if c["trend_sd"]]
        if real:
            w(live.claim_begin('C-ML-SERIES-DECLINE') + "The rows with a shared decline stipulate candidate series that are")
            w("autocorrelated and fall together over the fitting period. That is a chosen")
            w("condition, not a measured one: no candidate series has been tested for either")
            w("here, and the candidates include wind, light, salinity, stratification and")
            w("temperature as well as the nutrient inputs." + live.CLAIM_END + " "
              + live.claim_begin('C-ML-NOISE-FLOOR') + "Under that condition the median")
            w(f"best $R^2$ from pure noise is {min(c['median'] for c in real):.2f}–"
              f"{max(c['median'] for c in real):.2f}, and "
              f"{min(c['share_passing'] for c in real) * 100:.0f}–"
              f"{max(c['share_passing'] for c in real) * 100:.0f}% of noise models")
            w(f"clear an $R^2$ of {nf['acceptance_r2']}." + live.CLAIM_END + " "
              + live.claim('C-ML-DCE-MEAN', f"DCE report a mean $R^2$ of {mean56} across their models."))
            w()
        w(live.claim('C-ML-NOT-FALSE', "None of this shows that DCE's relations are false.") + " "
          + live.claim_begin('C-ML-R2-NO-EVIDENCE') + f"An $R^2$ of {nf['acceptance_r2']} is no hurdle")
        w("for the simplified search on autocorrelated noise, which clears it more often")
        w("than not. Whether DCE's reported $R^2$ carries evidence depends on whether it was")
        w("measured on held-out data, which the report does not say; until that is known,")
        w("this is a statement about a selection procedure, not about the water."
          + live.CLAIM_END)
        w()
    w("## 4. What a simulation may and may not license")
    w()
    w("| may | may not |")
    w("|---|---|")
    example = (f"*This schedule loses {hi_loss:.0f}% of a signal of this shape.*"
               if hi_loss is not None else "*This schedule loses this much of a signal of this shape.*")
    w(f"| {example} | *The sea has a diurnal cycle of size X.* |")
    w("| *This estimator recovers a stipulated amplitude down to Y.* | *The estimator's output on real data is therefore correct.* |")
    w("| *This flow code conserves mass and is tile-invariant.* | *Danish catchments drain the way this code says.* |")
    w("| *A proposed survey would or would not resolve this question.* | *The question is answered.* |")
    w()
    w("The right-hand column needs measurement. That is what")
    w("[IF_YOU_HAVE_THE_DATA.md](IF_YOU_HAVE_THE_DATA.md) and")
    w("[EXPERIMENTS.md](EXPERIMENTS.md) are for, and it is why this page is")
    w("separate from them rather than folded in.")
    w()
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
