#!/usr/bin/env python3
"""Generate docs/NITROGEN.md - what reaches the sea, and how the numbers are made.

The published figure everyone quotes is "agriculture 69.6% of nitrogen". This document
takes that apart, not by disputing the measurements but by asking three questions the
percentage cannot survive:

  * 69.6% of WHAT - what is the denominator, and is the set of sources even closed?
  * what is each number an estimator OF, as opposed to what it is labelled?
  * is nitrogen mass the right currency for oxygen depletion at all?

Everything computed here is reproducible from data/raw and data/manual. Where a bound is
our construction rather than a published figure it is marked as such.

Usage:  python3 scripts/nitrogen.py
"""
import json
import math
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import MANUAL, RAW, ROOT, log, read_json

MM = {"O2": 31.998, "N": 14.007, "S": 32.06, "CH4": 16.04, "Fe": 55.85}
O2_PER_N = (138 / 16) * MM["O2"] / MM["N"]      # Redfield remineralisation
O2_PER_P = (138 / 1) * MM["O2"] / 30.974
O2_NITRIF = 2 * MM["O2"] / MM["N"]              # NH4+ + 2O2 -> NO3-
O2_PER_S = 2 * MM["O2"] / MM["S"]               # H2S + 2O2 -> SO4(2-)
BOD5_ULT = 1.46

# The published apportionment, relabelled by what each number is an estimator of.
APPORTIONMENT = [
    ("Agriculture", 69.6,
     "**Residual.** (grab-sampled load over 49% of the area + model output over 51%) "
     "minus modelled point sources minus modelled natural background, with retention "
     "modelled at ±6-27 percentage points."),
    ("Natural background", 22.1,
     "Model output — and the subtrahend that determines the residual above."),
    ("Treatment plants", 4.8,
     "**Reported effluent monitoring.** Flow-metered, routinely sampled. The best-measured "
     "line in the table."),
    ("Aquaculture and marine farms", 1.5, "Reported, feed-balance based."),
    ("Separate stormwater", 0.7,
     "Modelled volume × a concentration from a **1990** measurement programme."),
    ("Rain-dependent overflow", 0.6,
     "Modelled volume (30-135% stated uncertainty) × an assumed concentration, "
     "quality-controlled **against that same assumed concentration**."),
    ("Industry", 0.5, "Reported."),
    ("Scattered dwellings", 0.2,
     "Modelled from dwelling counts × assumed per-capita loads."),
]

KOEGE = ["København", "Hvidovre", "Tårnby", "Brøndby", "Vallensbæk",
         "Ishøj", "Greve", "Solrød", "Køge", "Stevns"]
KOEGE_NORTH = {"København", "Hvidovre", "Tårnby", "Brøndby"}
KOEGE_BOX = (12.10, 55.28, 12.80, 55.66)


def fmt(n, dp=0):
    return f"{n:,.{dp}f}" if isinstance(n, (int, float)) else str(n)


def koege_tables():
    """Who can actually discharge into Køge Bugt, from the national register."""
    codes = read_json(os.path.join(MANUAL, "codelists.json"))["bygvaerkstype"]
    path = os.path.join(RAW, "national", "punkt_rbu_udl.geojson")
    if not os.path.exists(path):
        return None
    st = defaultdict(lambda: {"sep": 0, "comb": 0, "basin": 0, "vol": 0.0})
    for f in read_json(path)["features"]:
        p, c = f["properties"], f["geometry"]["coordinates"]
        k, t = p.get("komm_navn"), p.get("bgv_type")
        if k not in KOEGE:
            continue
        if not (KOEGE_BOX[0] <= c[0] <= KOEGE_BOX[2] and KOEGE_BOX[1] <= c[1] <= KOEGE_BOX[3]):
            continue
        if codes.get(t, {}).get("combined_sewer"):
            st[k]["comb"] += 1
            st[k]["vol"] += p.get("vol_sb") or 0
            if t != "OV":
                st[k]["basin"] += 1
        elif t in ("SE", "SF"):
            st[k]["sep"] += 1

    plants = []
    rp = os.path.join(RAW, "national", "punkt_rens_udl.geojson")
    if os.path.exists(rp):
        for f in read_json(rp)["features"]:
            p, c = f["properties"], f["geometry"]["coordinates"]
            if (p.get("komm_navn") in KOEGE and (p.get("godk_pe") or 0) >= 10000
                    and KOEGE_BOX[0] <= c[0] <= KOEGE_BOX[2]
                    and KOEGE_BOX[1] <= c[1] <= KOEGE_BOX[3]):
                plants.append((p.get("pkt_navn"), p.get("godk_pe"), p.get("komm_navn")))
    plants.sort(key=lambda x: -x[1])
    return st, plants


def main():
    paths = read_json(os.path.join(MANUAL, "nitrogen_pathways.json"))["pathways"]
    mon = read_json(os.path.join(MANUAL, "monitoring.json"))
    o = []
    w = o.append

    w("# What the sea actually receives\n")
    w("Generated by `scripts/nitrogen.py`. Reproducible from `data/raw` and `data/manual`.\n")
    w("The figure in circulation is that agriculture accounts for **69.6% of nitrogen**. "
      "This document does not dispute the measurements behind it. It asks three questions "
      "the percentage does not survive.\n")

    # ---------------------------------------------------------------- 1. denominator
    w("## 1. There is no denominator\n")
    w("A percentage requires a closed set. Here is every pathway of reactive nitrogen to "
      "Danish marine waters we could enumerate.\n")
    w("| Pathway | kt N/yr | Basis |")
    w("|---|---:|---|")
    lo = hi = 0.0
    unq = 0
    for p in paths:
        if p["lo"] is None:
            unq += 1
            val = "**—**"
        else:
            lo += p["lo"]
            hi += p["hi"]
            val = f"{p['lo']:g} – {p['hi']:g}"
        note = (p.get("note") or "").replace("\n", " ").strip()
        name = f"**{p['pathway']}**" if p["lo"] is None else p["pathway"]
        w(f"| {name} | {val} | {p['status'].lower()} — {note} |")
    w("")
    w(f"**{unq} of {len(paths)} pathways carry no number at all**, including what is "
      "probably the largest supply to the productive layer — internal regeneration from "
      "sediment, which is not a \"source\" and so has no row in any apportionment.\n")
    w(f"The quantified subset sums to **{lo:.0f} – {hi:.0f} kt N/yr**. That is not a range "
      "for the total. With ten pathways empty the honest statement is:\n")
    w(f"> Total reactive nitrogen supply **≥ {lo:.0f} kt N/yr**, with no established upper bound.\n")
    w("A lower bound, not a range. And therefore no denominator, and no percentages — "
      "until the empty rows are filled.\n")
    w("Note the scale of what the apportionment omits. Atmospheric deposition to Danish "
      "marine waters is 45–90 kt N/yr, comparable to the entire land-based waterborne "
      "term, and appears in none of the published shares.\n")

    # ---------------------------------------------------- 2. estimator vs estimand
    w("## 2. The numbers are not estimators of what they are named\n")
    w("Each line of the published apportionment, relabelled by what actually produced it:\n")
    w("| Called | Actually is |")
    w("|---|---|")
    for name, pct, what in APPORTIONMENT:
        w(f"| **{name}, {pct}%** | {what} |")
    w("")
    w("Two of these are measurements. The rest are models, and the largest is a residual "
      "of models.\n")
    ql = mon["quality_control"]
    w("### The validation is circular\n")
    w(f"Reported nitrogen divided by reported volume must fall within "
      f"**{ql['acceptance_interval_combined_mg_per_l'][0]}–"
      f"{ql['acceptance_interval_combined_mg_per_l'][1]} mg/l** for combined sewers and "
      f"**{ql['acceptance_interval_separate_mg_per_l'][0]}–"
      f"{ql['acceptance_interval_separate_mg_per_l'][1]} mg/l** for separate ones. Outside "
      "that, *\"kontaktes den dataansvarlige med henblik på at få rettet eventuelle fejl\"* "
      "— the data owner is contacted to correct the error.\n")
    w(f"{ql['consequence']} **The assumed concentration cannot be falsified by data "
      "collected under it.**\n")
    w("### And the estimator can return impossible values\n")
    dl = mon["diffuse_load"]
    w(f"{dl['estimator_pathology']} A residual whose error can exceed its own signal is "
      "published to one decimal place with no error bar.\n")
    w(f"Underneath it: **{dl['stream_stations']} stream stations** covering "
      f"**{dl['area_measured_pct']}%** of the country, the other "
      f"**{dl['area_modelled_pct']}%** modelled. Load is grab samples plus linear "
      "interpolation, and in all three streams of the 2018 validation study that method "
      f"**always underestimated** — annual deviations {dl['deviation_annual_pct'][0]}% to "
      f"{dl['deviation_annual_pct'][1]}%, monthly deviations reaching "
      f"{dl['deviation_monthly_pct'][1]:+.0f}%. Retention, the largest single term, carries "
      f"**±{dl['retention_uncertainty_pct_points'][0]}–"
      f"{dl['retention_uncertainty_pct_points'][1]} percentage points**.\n")
    ov = mon["overflow_reporting"]
    w("### Overflow is modelled, and the deciding variable is not collected\n")
    w("| Knowledge level | Method | Stated uncertainty |")
    w("|---|---|---:|")
    for lv in ov["knowledge_levels"]:
        u = f"{lv['uncertainty_pct']}%" if lv["uncertainty_pct"] else "—"
        w(f"| {lv['level']} | {lv['method']} | {u} |")
    w("")
    w(f"{ov['note_on_flow']}\n")
    w("That matters because sediment resuspension is a **threshold** in flow, not a "
      "frequency of events. Below the critical shear stress the deposit stays in the basin; "
      "above it, the accumulated sludge leaves — and the hazardous-substances programme "
      "reports the highest median metal concentrations precisely in basin sludge. Multiplying "
      "an annual volume by an average concentration cannot represent that, and the resulting "
      "error is one-directional and largest in the wettest years.\n")

    # --------------------------------------------------------- 3. wrong currency
    w("## 3. Nitrogen mass is the wrong currency\n")
    w("Oxygen depletion is the damage. Nitrogen is one route to it. Converting everything "
      "to oxygen demand — Redfield stoichiometry, which is chemistry rather than judgement:\n")
    w("| Pathway | Oxygen demand |")
    w("|---|---:|")
    w(f"| Remineralisation of algal biomass | **{O2_PER_N:.2f} g O₂ per g N** |")
    w(f"| Remineralisation, via phosphorus | {O2_PER_P:.1f} g O₂ per g P |")
    w(f"| **Nitrification of delivered ammonium** | **{O2_NITRIF:.2f} g O₂ per g N** |")
    w(f"| **Sulphide oxidation** | **{O2_PER_S:.2f} g O₂ per g S** |")
    w(f"| Methane oxidation | {2*MM['O2']/MM['CH4']:.2f} g O₂ per g CH₄ |")
    w(f"| Direct BOD | {BOD5_ULT:.2f} g O₂ per g BOD₅ |")
    w("")
    w("Only the first line is modelled by the accounts. Three consequences:\n")
    w("**Ammonium carries its own demand.** An ammonium-rich discharge — which is what a "
      f"basin that has gone anaerobic produces — consumes {O2_NITRIF:.2f} g O₂ per g N on "
      "arrival, with no algae, no light and no delay. That pathway is absent from a "
      "nitrogen→algae→decay model entirely.\n")
    so4, o2sat = 2700.0, 8.0
    s_mgl = so4 * MM["S"] / (MM["S"] + 4 * 15.999)
    demand = s_mgl * O2_PER_S
    w(f"**Sulphate makes the debt effectively unbounded.** Seawater holds ~{so4:.0f} mg/l "
      f"sulphate = {s_mgl:.0f} mg/l as sulphur, against ~{o2sat:.0f} mg/l dissolved oxygen. "
      f"Fully reduced and later re-oxidised that is {demand:.0f} mg/l of demand — "
      f"**{demand/o2sat:.0f}× the oxygen in the water**. Reducing just "
      f"{o2sat/demand*100:.2f}% of the sulphate pool stores a debt equal to all of it. Once "
      "a basin goes anoxic the electron acceptor is effectively infinite, and every storm "
      "that mixes oxygen in spends it re-oxidising sulphide instead of restoring the water.\n")
    w("**And the ratio matters, not just the total.** Diatoms need silicon roughly 1:1 with "
      "nitrogen. Fertiliser and sewage add N and P; neither adds silicon, which comes from "
      "rock weathering. Enrichment therefore raises N:Si, and when silicon runs out the "
      "community shifts from diatoms to flagellates and dinoflagellates. A composition "
      "change driven by a ratio, invisible to any nitrogen total.\n")
    w("There is no potency term anywhere in the accounting. A kilogram delivered in "
      "February into a mixed column counts identically to a kilogram delivered in July into "
      "a stratified fjord — though vertical mixing across a summer pycnocline is roughly "
      "four orders of magnitude weaker, which is what decides whether the nitrogen is used "
      "or flushed.\n")

    # ------------------------------------------------------------- 4. blind spots
    w("## 4. What is not measured\n")
    w("| What | Window | Consequence |")
    w("|---|---|---|")
    for k, v in mon["monitoring_windows"].items():
        flag = " **(circular)**" if v.get("seasonal_claim_circular") else ""
        w(f"| {k.replace('_', ' ')} | {v['period']} | set by {v['window_set_by']}{flag} |")
    w("")
    w("The most consequential row is the second. **Soft-bottom fauna is sampled 1 March to "
      "31 May** — after the winter, before the summer. The annual die-off is observed only "
      "in its aftermath, months later, once recolonisation has begun. So the event that "
      "decides which organisms are present to receive the next year's nitrogen is the one "
      "thing nobody watches.\n")
    w("And any seasonal claim drawn from a seasonally-sampled record is circular unless the "
      "window was set by mechanism. Iltsvind's July–November window was; bathing water's "
      "June–September window was not.\n")
    mfs = mon["hazardous_substances"]
    w("### Toxicants: eleven stations\n")
    w(f"The national typetal for hazardous substances in rain-dependent discharges — applied "
      f"to all **{mfs['applied_to_discharge_points_nationally']:,}** discharge points — rest "
      f"on **{mfs['stations_combined_overflow']} combined-sewer overflows and "
      f"{mfs['stations_separate_stormwater']} separate stormwater outlets**, monitored "
      "2000–2020.\n")
    w(f"The catchments were {mfs['catchments_selected']}. The typetal cover only discharges "
      f"*{mfs['excludes_basins']}*, and the report states they are limiting for "
      f"*{mfs['excludes_heavy_catchments']}*.\n")
    w(f"Meanwhile {mfs['counterpoint']}. **The design excludes the worst cases, and says so.**\n")
    w("| µg/l | Combined overflow | Separate stormwater | Max observed |")
    w("|---|---:|---:|---:|")
    for m, v in mfs["typetal_ug_per_l"].items():
        if m.startswith("_"):
            continue
        w(f"| {m} | {v[0]} | {v[1]} | {v[2]} |")
    w("")
    w("Note that chromium, nickel and arsenic are **higher in separated stormwater than in "
      "sewage overflow** — and nationally there is "
      f"{mon['national_volumes_m3_per_year']['separate_stormwater_discharged']/1e6:.0f} "
      "million m³/yr of the former against "
      f"{mon['national_volumes_m3_per_year']['combined_overflow_water']/1e6:.0f} million m³/yr "
      "of the latter. Separating a sewer system solves the sewage overflow and delivers "
      "untreated road runoff instead.\n")

    # ---------------------------------------------------------------- 5. Køge Bugt
    kt = koege_tables()
    if kt:
        st, plants = kt
        w("## 5. A worked case: Køge Bugt\n")
        kb = mon["koege_bugt"]
        w(f"DCE's oxygen reports state, in both 2023 and 2025: *\"{kb['iltsvind_2025']}\"* — "
          "**no oxygen depletion registered**, including in 2023, the worst iltsvind year in "
          "two decades.\n")
        w(f"{kb['interpretation']}\n")
        w("### Who can discharge sewage into the bay\n")
        w("| Municipality | Separate outfalls | Combined overflows | % separated | Basin m³ |")
        w("|---|---:|---:|---:|---:|")
        tc = tv = 0
        for k in KOEGE:
            v = st.get(k)
            if not v or not (v["sep"] + v["comb"]):
                continue
            n = v["sep"] + v["comb"]
            tc += v["comb"]
            tv += v["vol"]
            bold = "**" if k in KOEGE_NORTH else ""
            w(f"| {bold}{k}{bold} | {v['sep']} | {v['comb']} | {v['sep']/n*100:.0f}% "
              f"| {v['vol']:,.0f} |")
        w("")
        nc = sum(st[k]["comb"] for k in KOEGE_NORTH if k in st)
        nv = sum(st[k]["vol"] for k in KOEGE_NORTH if k in st)
        w(f"Vallensbæk, Ishøj and Solrød have **zero** combined-sewer overflows; Greve has "
          "two. The shoreline communities separated their systems and physically cannot "
          "discharge sewage into the bay in a storm.\n")
        w(f"**{nv/tv*100:.0f}% of the bay's basin storage** ({nv:,.0f} of {tv:,.0f} m³) sits "
          f"in København, Hvidovre and Tårnby, along with {nc} of {tc} combined overflows. "
          "The bay opens southeast, so the discharge enters at the northern end and the "
          "whole shoreline is downstream of it. **The municipality that built the storage is "
          "not the one that smells it.**\n")
        if plants:
            w("### Treatment capacity discharging to the bay\n")
            w("| Plant | PE | Municipality |")
            w("|---|---:|---|")
            for n, pe, k in plants:
                w(f"| {n} | {pe:,} | {k} |")
            w("")

    # ------------------------------------------------------------------- caveats
    w("## What this does and does not establish\n")
    w("**It does not establish that urban discharge is the dominant national source.** Under "
      "every reconstruction attempted, including ones stacked generously in that direction, "
      "agriculture remained the largest nitrogen term. Stacking every identified bias in the "
      "overflow figures reaches roughly 10% of the land-based term — material, far above the "
      "published 0.6%, and still not the driver.\n")
    w("**It does establish that the published percentage answers a different question than "
      "the one it is used for.** It answers: *of the nitrogen we observe arriving by stream "
      "from Danish land, how much do we attribute to farming after subtracting our models of "
      "everything else?* It is read as: *how much of Denmark's marine nitrogen problem is "
      "agriculture?*\n")
    w("Those differ by a closed set, a potency term, and a state variable. The accounts "
      "contain none of the three.\n")
    w("**Bounds marked as ours are ours.** Several ranges in section 1 are constructed here "
      "from the biases identified, not published figures. They are stated so they can be "
      "argued with.\n")

    path = os.path.join(ROOT, "docs", "NITROGEN.md")
    text = "\n".join(o)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    log(f"wrote docs/NITROGEN.md ({len(text):,} chars)")
    log(f"  {len(paths)} pathways, {unq} unquantified, quantified subset {lo:.0f}-{hi:.0f} kt N/yr")
    return 0


if __name__ == "__main__":
    sys.exit(main())
