#!/usr/bin/env python3
"""Generate docs/REGISTER.md - the register as readable text, no browser needed.

Every number on the page is a checked entity (see LIVE_NUMBERS.md): read live from
data/derived/registry.json and constructions.geojson (scripts/build_registry.py),
from the raw national and municipal layers, or from the hand-curated structures in
data/manual/constructions.json. Counts and sums made here are carried as live
values of the file they are counted from, and every file's fields are declared in
data/manual/number_constructions.d/nitrogen.json.

Plan-page titles, structure names and category labels are quoted as `code`: they
are names that happen to contain digits, not quantities.

Usage:  python3 scripts/report.py
"""
import os
import re
import sys
from collections import Counter, defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import DERIVED, MANUAL, RAW, ROOT, log, read_json, write_doc
import live


def code(t):
    """A name quoted as text, so its digits are read as part of the name."""
    return "`" + str(t).replace("`", "'") + "`"


def name(t):
    """A name as plain text, or as code if it carries digits."""
    return code(t) if re.search(r"\d", str(t)) else str(t)


def idents(t):
    """Identifiers inside hand-written notes - plan numbers (K1.57), house numbers
    (Kalvebod Brygge 45-47) - set as code, so they read as names, not quantities."""
    t = re.sub(r"\b[A-Z]{1,3}\d+(?:\.\d+)+\b", lambda m: code(m.group(0)), str(t))
    return re.sub(r"\b([A-ZÆØÅ][a-zæøå]+) (\d+-\d+)\b", lambda m: f"{m.group(1)} {code(m.group(2))}", t)


# Every assertion on the page is a checked claim (LIVE_NUMBERS.md section 11), registered
# in data/manual/claims.d/w3-fr.json. A hand-curated structure is rendered only under
# claims registered for it, and each note in the curated file only as a registered claim:
# a new structure or note is refused until somebody has read it against its source.
HC_KEYS = {"kalvebod-brygge-skybrudstunnel": "KB"}
HC_NOTES = {("kalvebod-brygge-skybrudstunnel", "completion", "disputed"): "C-FR-RG-KB-DONE"}
# curated notes whose wording could not be justified as written: the page says the
# replacement, and the old wording is in docs/ARCHIVE.md
HC_REPLACED = {
    ("kalvebod-brygge-skybrudstunnel", "shafts", "note"): (
        "C-FR-RG-KB-SHAFTS",
        "*shafts:* HOFOR's page lists the temporary work shafts for the boring at "
        "Vodroffsvej/Gammel Kongevej, Halmtorvet/Gasværksvej and Kalvebod Brygge `45-47`. The "
        "plan's reservation page `K1.57` provided for fewer deep shafts; its supplement says the "
        "one at Skt. Jørgens Sø was left out of `K1.57` by mistake, and the later supplement for "
        "`VEL45` gives as many deep shafts as HOFOR gives work shafts."),
}
HC_EXTRA = {
    "kalvebod-brygge-skybrudstunnel": [(
        "C-FR-RG-KB-PUMP",
        "*pump capacity:* HOFOR's page gives that figure as the water that can flow through the "
        "pipes on the Sønder Boulevard - Kalvebod Brygge stretch, where the tunnel's capacity is "
        "largest, and names a permanent pumping station at Kalvebod Brygge without a capacity: "
        "the row's label is the curated file's, not HOFOR's.")],
}


def id_parts(v):
    """The ids one `klima_id` value joins ('BIR12.1&12.3' -> BIR12.1, BIR12.3): split at
    ';', '&' or ','; a part without a letter prefix takes the first part's."""
    bits = [b.strip() for b in re.split(r"[;&,]", v) if b.strip()]
    m = re.match(r"^[A-ZÆØÅ]+", bits[0]) if bits else None
    pre = m.group(0) if m else ""
    return [b if re.match(r"^[A-ZÆØÅ]", b) else pre + b for b in bits]


def main():
    C = live.claim
    rp = os.path.join(DERIVED, "registry.json")
    reg = live.live_json(rp)
    cons = live.live_json(os.path.join(DERIVED, "constructions.geojson"))
    codes = read_json(os.path.join(MANUAL, "codelists.json"))
    c = reg["counts"]
    out = []
    w = out.append

    w("# Register of claimed water constructions, Copenhagen\n")
    w(C("C-FR-RG-WHAT", "Generated by `scripts/report.py`. Each figure is counted from a named "
        "map layer or register, or read from the text of the city's wastewater plan or a named "
        "source; the plan's volumes are the city's own statements, not measurements made "
        "here.") + "\n")

    w("## Coverage\n")
    w("| | |")
    w("|---|---:|")
    w(f"| Spildevandsplan 2018 project pages | {c['plan_projects']:,} |")
    w(f"| ... linked to map geometry | {c['plan_projects_with_geometry']:,} |")
    w(f"| Distinct mapped structures (`klima_id`) | {c['unique_klima_id_with_geometry']:,} |")
    w(f"| ... cited by at least one plan page | {c['klima_id_cited_by_a_plan_page']:,} |")
    w(f"| ... found in no plan page scanned | {c['klima_id_with_geometry_but_no_plan_page']:,} |")
    if c.get("klima_id_mentioned_only_elsewhere_in_the_plan") is not None:
        w(f"| ... mentioned only outside the project register "
          f"| {c['klima_id_mentioned_only_elsewhere_in_the_plan']:,} |")
    w(f"| Construction features written | {c['construction_features']:,} |")
    w("")

    und = [str(i) for i in reg["klima_id_without_documentation"]]
    cited = ({str(i) for e in reg["projects"] for i in (e.get("klima_ids") or [])}
             | {str(i) for i in reg.get("klima_id_only_mentioned_outside_the_project_register")
                or []})
    comp = [v for v in und if len(id_parts(v)) > 1]
    comp_cited = [v for v in comp if any(x in cited for x in id_parts(v))]
    nodigit = [v for v in und if not re.search(r"\d", v)]
    n_und = live.live(len(und), rp, "klima_id_without_documentation.count")
    w(C("C-FR-RG-UNDOC", f"Of the {c['unique_klima_id_with_geometry']:,} distinct `klima_id` "
        f"values in the city's map layers, {n_und} are found in no page of the wastewater plan "
        f"scanned - the {c['plan_projects']:,} project pages and "
        f"{c['plan_other_pages_scanned']:,} appendix, status, target and 'aktuelle projekter' "
        "pages. That counts values, not structures: "
        f"{live.live(len(comp), rp, 'klima_id_without_documentation.n_composite')} of them join "
        "several ids in one value, "
        f"{live.live(len(comp_cited), rp, 'klima_id_without_documentation.n_composite_part_cited')} "
        "of those name an id some plan page does cite, and "
        f"{live.live(len(nodigit), rp, 'klima_id_without_documentation.n_no_digit')} carry no "
        "structure number at all.") + "\n")

    w("## Claimed volumes\n")
    w(C("C-FR-RG-VOLKIND", "A cubic-metre figure in planning prose can mean a tank that *holds* "
        "that much, or an outfall that *releases* that much per year. They are separated here by "
        "cue words in the figure's own sentence.") + "\n")
    w("| | m3 |")
    w("|---|---:|")
    w(f"| Storage, attributable to a single structure | {c['storage_m3_attributable']:,.0f} |")
    w(f"| Storage, stated on pages naming several structures | {c['storage_m3_shared_attribution']:,.0f} |")
    w(f"| Annual discharge / pumped volume (m3 **per year**) | {c['annual_flow_m3_per_year_distinct']:,.0f} |")
    w(f"| Figures needing a human read | {c['volume_figures_needing_human_read']:,} |")
    w("")
    w(C("C-FR-RG-FLOWSUM", "The per-year row adds the volume per year each page states, "
        "whatever its kind - overflow or rain discharged, or water pumped - so it is a sum of the "
        "plan's statements, not a flow of one kind.") + "\n")

    best = {}
    for f in cons["features"]:
        p = f["properties"]
        v = p.get("claimed_volume_m3") or p.get("claimed_volume_m3_shared")
        if not v:
            continue
        cur = best.get(str(p["klima_id"]))
        if not cur or v > cur["v"]:
            best[str(p["klima_id"])] = {
                "v": v,
                "t": (p.get("plan_titles") or [""])[0] or "",
                "u": (p.get("plan_urls") or [""])[0] or "",
                "cat": p.get("catchment"),
                "sure": bool(p.get("claimed_volume_m3")),
            }
    w("### Largest structures with a claimed storage volume\n")
    w(C("C-FR-RG-STORAGE", "Each structure's largest storage figure in the plan: *single* where a "
        "page citing that structure alone states it, *shared* where the page names several, in "
        "which case the same figure stands against each structure the page names. The page "
        "linked is the first plan page citing the structure, which need not be the page the "
        "figure came from.") + "\n")
    w("| klima_id | m3 | Attribution | Catchment | Plan page |")
    w("|---|---:|---|---|---|")
    for k, d in sorted(best.items(), key=lambda x: -x[1]["v"])[:25]:
        att = "single" if d["sure"] else "shared"
        link = f"[{code(str(d['t'])[:58])}]({d['u']})" if d["u"] else "-"
        w(f"| `{k}` | {d['v']:,.0f} | {att} | {name(d['cat'])} | {link} |")
    w("")

    flows = [e for e in reg["projects"] if e.get("annual_flow_m3_per_year")
             and e.get("annual_flow_counted", True)]
    if flows:
        w("### Stated annual discharge volumes\n")
        w(C("C-FR-RG-RATES", "Rates, not capacity: each is a volume per year stated in a sentence "
            "of a plan page - overflow or rain discharged, or water pumped - as the city states "
            "it.") + "\n")
        dups = reg.get("annual_flow_duplicates") or []
        if dups:
            w(C("C-FR-RG-ONCE", f"A figure is counted once: the {c['annual_flow_pages']:,} plan "
                f"pages that state an annual volume give {c['annual_flow_figures_distinct']:,} "
                "distinct figures, because the same volume stated for the same named structures "
                "on two pages - a project page and the requirement it answers - is one outfall, "
                "not two. Left out of the total and the table: " + "; ".join(
                    f"[{code(str(d['title'])[:60])}]({d['url']}), the same figure as "
                    f"[{code(str(d['same_figure_as'])[:60])}]({d['same_figure_as_url']})"
                    for d in dups) + ".") + "\n")
        w("| m3/year | Project |")
        w("|---:|---|")
        for e in sorted(flows, key=lambda x: -x["annual_flow_m3_per_year"])[:15]:
            w(f"| {e['annual_flow_m3_per_year']:,.0f} | [{code(str(e['title'])[:70])}]({e['url']}) |")
        w("")

    rbu = os.path.join(RAW, "vp3_basis_2019_punkt_rbu_udl.geojson")
    if os.path.exists(rbu):
        feats = list(live.live_json(rbu)["features"])
        kbh = [f for f in feats if f["properties"].get("komm_navn") == "København"]
        by_type = Counter(str(f["properties"].get("bgv_type")) for f in feats)
        munis = sorted({str(f["properties"].get("komm_navn")) for f in feats})
        w("## Discharge and overflow points\n")
        w(C("C-FR-RG-RBU", f"{live.live(len(feats), rbu, 'n_features')} rain-dependent discharge "
            "points in the layer as fetched for "
            f"{live.live(len(munis), rbu, 'municipalities.count')} municipalities "
            f"({', '.join(munis)}), {live.live(len(kbh), rbu, 'n_in_kobenhavn')} of them in "
            "Københavns Kommune (Miljøstyrelsen VP3 basisanalyse, derived from PULS).") + "\n")
        w(C("C-FR-RG-CODES", "The codes are the structure types of Miljøstyrelsen's data "
            "instruction for rain-dependent outlets (`DP02`); the English is this project's, in "
            "`data/manual/codelists.json`.") + "\n")
        w("| Code | Meaning | Points |")
        w("|---|---|---:|")
        for t, n in by_type.most_common():
            meta = codes["bygvaerkstype"].get(t, {})
            label = meta.get("en", "unknown")
            if meta.get("inferred"):
                label += " **(inferred, not in the official code list)**"
            w(f"| `{t}` | {label} | {live.live(n, rbu, 'n_by_bgv_type.' + t)} |")
        w("")
        vols = [(f["properties"]["vol_sb"], f["properties"].get("pkt_navn"),
                 f["properties"].get("bgv_type"), f["properties"].get("komm_navn"),
                 f["geometry"]["coordinates"]) for f in feats if f["properties"].get("vol_sb")]
        # the sentence calls vol_sb a detention-basin volume, which DP02 asks for on
        # overflow structures with a detention basin (sparebassin); refuse it for others
        if {str(v[2]) for v in vols} - {"OS", "OK"}:
            raise live.Unjustified("report: vol_sb is now carried by structure types without a "
                                   "detention basin - reword the basin-volume sentence")
        w(C("C-FR-RG-VOLSB", f"{live.live(len(vols), rbu, 'n_with_vol_sb')} of these carry a "
            f"detention-basin volume (`vol_sb`), totalling **{sum(v[0] for v in vols):,.0f} "
            "m3**; the largest are listed.") + "\n")
        w("| Structure | Type | m3 | Municipality | lon, lat |")
        w("|---|---|---:|---|---|")
        for v, nm, t, km, xy in sorted(vols, key=lambda x: -x[0])[:20]:
            w(f"| {code(nm)} | {t} | {v:,.0f} | {km} | {xy[0]:.4f}, {xy[1]:.4f} |")
        w("")

    rens = os.path.join(RAW, "vp3_basis_2019_punkt_rens_udl.geojson")
    if os.path.exists(rens):
        w("## Treatment plants\n")
        w(C("C-FR-RG-RENS", "The layer is of treatment-plant discharge points (`punkt_rens_udl`, "
            "titled 'Renseanlæg - udledningspunkter'), so a position is where the layer places a "
            "plant's discharge, not the plant; capacity is the approved capacity in person "
            "equivalents (`godk_pe`), and the stage is the layer's `rens_sta` code.") + "\n")
        w("| Plant | Capacity (PE) | Stage | discharge point lon, lat |")
        w("|---|---:|---|---|")
        for f in sorted(live.live_json(rens)["features"],
                        key=lambda x: -(x["properties"].get("godk_pe") or 0)):
            p, xy = f["properties"], f["geometry"]["coordinates"]
            pe = f"{p['godk_pe']:,}" if p.get("godk_pe") else "—"
            w(f"| {name(p.get('pkt_navn'))} | {pe} | {p.get('rens_sta')} "
              f"| {xy[0]:.4f}, {xy[1]:.4f} |")
        w("")

    kl = os.path.join(RAW, "sp_kloakoplande.geojson")
    if os.path.exists(kl):
        st = Counter(str(f["properties"].get("kloaksystem_status") or "unspecified")
                     for f in read_json(kl)["features"])
        w("## Sewer catchments by system type\n")
        w(C("C-FR-RG-COMBINED", "Combined (`Fælleskloakeret`) catchments are served by a combined "
            "sewer, which carries sewage and urban runoff together to a treatment plant; in large "
            "storms part of the mixture can be discharged untreated to nearby water.") + "\n")
        w("| System | Catchments |")
        w("|---|---:|")
        for k, n in st.most_common():
            w(f"| {name(k)} | {live.live(n, kl, 'n_by_kloaksystem_status.' + k.replace('.', ','))} |")
        w("")

    man = os.path.join(MANUAL, "constructions.json")
    if os.path.exists(man):
        w("## Hand-curated structures\n")
        w(C("C-FR-RG-HAND", "Facts recorded by hand from a named source - depth, diameter, "
            "capacity, completion - each with its link and the date it was read, in "
            "`data/manual/constructions.json`; where the source's page is pinned here, the claims "
            "below say so.") + "\n")
        for s in live.live_json(man)["constructions"]:
            key = HC_KEYS.get(str(s["id"]))
            if not key:
                raise live.Unjustified(f"report: the curated structure '{s['id']}' has no claims "
                                       "registered for it - read it against its sources, register "
                                       "them, and add it to HC_KEYS")
            cid = f"C-FR-RG-{key}"
            w(f"### {name(s['name'])}\n")
            w(C(cid + "-HEAD", f"*{s['type']}* - owner **{s['owner']}** - confidence: "
                f"{s['confidence']}  \nklima_id "
                f"`{', '.join(str(x) for x in (s.get('klima_id') or [])) or '-'}`, plan "
                f"`{', '.join(str(x) for x in (s.get('plan_ids') or [])) or '-'}`") + "\n")
            if s.get("route"):
                w(C(cid + "-ROUTE", f"Route: {idents(s['route'])}") + "\n")
            w(C(cid + "-TABLE", "Each value is as the source linked beside it states it, read on "
                "the date shown; HOFOR's project page is pinned here and gives each of them.")
              + "\n")
            w("| Claim | Value | Source |")
            w("|---|---|---|")
            for cl in s["claims"]:
                val = cl["value"]
                if isinstance(val, list):
                    val = f"{val[0]:g}-{val[1]:g}"
                elif cl["unit"] == "year":
                    val = f"{val}"
                else:
                    val = f"{val:,g}"
                q = f" ({idents(cl['qualifier'])})" if cl.get("qualifier") else ""
                w(f"| {cl['what'].replace('_', ' ')} | {val} {cl['unit']}{q} | "
                  f"[link]({cl['source']}) read {cl['read_on']} |")
            w("")
            for cl in s["claims"]:
                for kind in ("disputed", "note"):
                    if not cl.get(kind):
                        continue
                    k = (str(s["id"]), str(cl["what"]), kind)
                    if k in HC_REPLACED:
                        nid, text = HC_REPLACED[k]
                        w("> " + C(nid, text) + "\n")
                    elif k in HC_NOTES and kind == "disputed":
                        w("> " + C(HC_NOTES[k], f"**Disputed - {cl['what']}:** "
                                   f"{idents(cl['disputed'])}") + "\n")
                    else:
                        raise live.Unjustified(f"report: the curated {kind} on {k[0]} / {k[1]} "
                                               "has no registered claim - read it against its "
                                               "source and register it")
            for nid, text in HC_EXTRA.get(str(s["id"]), []):
                w("> " + C(nid, text) + "\n")

    ids = [str(i) for i in reg["klima_id_without_documentation"]]
    w("## Map values no plan page mentions\n")
    w(C("C-FR-RG-UNDOC-LIST", f"The {live.live(len(ids), rp, 'klima_id_without_documentation.count')} "
        "values, by prefix; a value joining several ids is listed as the layers hold it:") + "\n")
    by_pre = defaultdict(list)
    for i in ids:
        m = re.match(r"^[A-ZÆØÅ]+", i)
        by_pre[m.group(0) if m else "?"].append(i)
    for pre, group in sorted(by_pre.items()):
        n = live.live(len(group), rp, f"klima_id_without_documentation.count_by_prefix.{pre}")
        w(f"- **{pre}** ({n}): `" + "`, `".join(sorted(group)) + "`")
    w("")

    w("---\n")
    w("### Caveats\n")
    w("- " + C("C-FR-RG-CAV-LINKS", "The links between `klima_id` values and plan pages are "
               "reconstructed by scanning each page's text for ids that exist in the map layers, "
               "not taken from an official mapping."))
    w("- " + C("C-FR-RG-CAV-CLASS", "Cubic-metre figures are classified as storage, annual flow "
               "or unclear from their own sentence; a storage figure is attributed to a structure "
               "only from a page citing that one structure."))
    w("- " + C("C-FR-RG-CAV-SURVEY", "The depth and diameter above are the owner's project "
               "figures, not a survey; no source in this project's source register gives surveyed "
               "invert levels for Copenhagen's sewers."))
    w("")

    text = "\n".join(out)
    path = os.path.join(ROOT, "docs", "REGISTER.md")
    try:
        write_doc(path, text)
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote docs/REGISTER.md ({len(text):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
