#!/usr/bin/env python3
"""Generate docs/REGISTER.md - the register as readable text, no browser needed.

Usage:  python3 scripts/report.py
"""
import os
import re
import sys
from collections import Counter, defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import DERIVED, MANUAL, RAW, ROOT, log, read_json


def fmt(n):
    return f"{n:,.0f}" if isinstance(n, (int, float)) else str(n)


def main():
    reg = read_json(os.path.join(DERIVED, "registry.json"))
    cons = read_json(os.path.join(DERIVED, "constructions.geojson"))
    codes = read_json(os.path.join(MANUAL, "codelists.json"))
    c = reg["counts"]
    out = []
    w = out.append

    w("# Register of claimed water constructions, Copenhagen\n")
    w("Generated by `scripts/report.py`. Every figure traces to a source; nothing is estimated.\n")

    w("## Coverage\n")
    w("| | |")
    w("|---|---:|")
    w(f"| Spildevandsplan 2018 project pages | {fmt(c['plan_projects'])} |")
    w(f"| ... linked to map geometry | {fmt(c['plan_projects_with_geometry'])} |")
    w(f"| Distinct mapped structures (`klima_id`) | {fmt(c['unique_klima_id_with_geometry'])} |")
    w(f"| ... cited by at least one plan page | {fmt(c['klima_id_cited_by_a_plan_page'])} |")
    w(f"| ... **drawn but never described** | {fmt(c['klima_id_with_geometry_but_no_plan_page'])} |")
    w(f"| Construction features written | {fmt(c['construction_features'])} |")
    w("")
    w("The last row is the finding worth keeping: the city draws "
      f"{fmt(c['klima_id_with_geometry_but_no_plan_page'])} numbered structures that no project "
      "page in the statutory plan describes.\n")

    w("## Claimed volumes\n")
    w("A cubic-metre figure in planning prose can mean a tank that *holds* that much, or an "
      "outfall that *releases* that much per year. They are separated here.\n")
    w("| | m3 |")
    w("|---|---:|")
    w(f"| Storage, attributable to a single structure | {fmt(c['storage_m3_attributable'])} |")
    w(f"| Storage, stated on pages naming several structures | {fmt(c['storage_m3_shared_attribution'])} |")
    w(f"| Annual discharge / pumped volume (m3 **per year**) | {fmt(c['annual_flow_m3_per_year'])} |")
    w(f"| Figures needing a human read | {fmt(c['volume_figures_needing_human_read'])} |")
    w("")

    best = {}
    for f in cons["features"]:
        p = f["properties"]
        v = p.get("claimed_volume_m3") or p.get("claimed_volume_m3_shared")
        if not v:
            continue
        cur = best.get(p["klima_id"])
        if not cur or v > cur["v"]:
            best[p["klima_id"]] = {
                "v": v,
                "t": (p.get("plan_titles") or [""])[0] or "",
                "u": (p.get("plan_urls") or [""])[0] or "",
                "cat": p.get("catchment"),
                "sure": bool(p.get("claimed_volume_m3")),
            }
    w("### Largest structures with a claimed storage volume\n")
    w("| klima_id | m3 | Attribution | Catchment | Plan page |")
    w("|---|---:|---|---|---|")
    for k, d in sorted(best.items(), key=lambda x: -x[1]["v"])[:25]:
        att = "single" if d["sure"] else "shared"
        link = f"[{d['t'][:58]}]({d['u']})" if d["u"] else "-"
        w(f"| `{k}` | {fmt(d['v'])} | {att} | {d['cat']} | {link} |")
    w("")

    flows = [e for e in reg["projects"] if e.get("annual_flow_m3_per_year")]
    if flows:
        w("### Stated annual discharge volumes\n")
        w("Rates, not capacity. These say how much water leaves the system each year.\n")
        w("| m3/year | Project |")
        w("|---:|---|")
        for e in sorted(flows, key=lambda x: -x["annual_flow_m3_per_year"])[:15]:
            w(f"| {fmt(e['annual_flow_m3_per_year'])} | [{e['title'][:70]}]({e['url']}) |")
        w("")

    rbu = os.path.join(RAW, "vp3_basis_2019_punkt_rbu_udl.geojson")
    if os.path.exists(rbu):
        feats = read_json(rbu)["features"]
        kbh = [f for f in feats if f["properties"].get("komm_navn") == "København"]
        by_type = Counter(f["properties"].get("bgv_type") for f in feats)
        w("## Discharge and overflow points\n")
        w(f"{len(feats)} rain-dependent discharge points in metropolitan Copenhagen, "
          f"{len(kbh)} of them in Københavns Kommune "
          "(Miljøstyrelsen VP3 basisanalyse, derived from PULS).\n")
        w("| Code | Meaning | Points |")
        w("|---|---|---:|")
        for t, n in by_type.most_common():
            meta = codes["bygvaerkstype"].get(t, {})
            label = meta.get("en", "unknown")
            if meta.get("inferred"):
                label += " **(inferred, not in the official code list)**"
            w(f"| `{t}` | {label} | {n} |")
        w("")
        vols = [(f["properties"].get("vol_sb"), f["properties"].get("pkt_navn"),
                 f["properties"].get("bgv_type"), f["properties"].get("komm_navn"),
                 f["geometry"]["coordinates"]) for f in feats if f["properties"].get("vol_sb")]
        w(f"{len(vols)} of these carry a detention-basin volume, totalling "
          f"**{fmt(sum(v[0] for v in vols))} m3**.\n")
        w("| Structure | Type | m3 | Municipality | lon, lat |")
        w("|---|---|---:|---|---|")
        for v, name, t, km, xy in sorted(vols, reverse=True)[:20]:
            w(f"| `{name}` | {t} | {fmt(v)} | {km} | {xy[0]:.4f}, {xy[1]:.4f} |")
        w("")

    rens = os.path.join(RAW, "vp3_basis_2019_punkt_rens_udl.geojson")
    if os.path.exists(rens):
        w("## Treatment plants\n")
        w("| Plant | Capacity (PE) | Stage | lon, lat |")
        w("|---|---:|---|---|")
        for f in sorted(read_json(rens)["features"],
                        key=lambda x: -(x["properties"].get("godk_pe") or 0)):
            p, xy = f["properties"], f["geometry"]["coordinates"]
            w(f"| {p.get('pkt_navn')} | {fmt(p.get('godk_pe') or 0)} | {p.get('rens_sta')} "
              f"| {xy[0]:.4f}, {xy[1]:.4f} |")
        w("")

    kl = os.path.join(RAW, "sp_kloakoplande.geojson")
    if os.path.exists(kl):
        st = Counter((f["properties"].get("kloaksystem_status") or "unspecified")
                     for f in read_json(kl)["features"])
        w("## Sewer catchments by system type\n")
        w("Combined (*faelleskloakeret*) catchments carry sewage and rain in one pipe, which is "
          "why heavy rain is what pushes sewage into the harbour.\n")
        w("| System | Catchments |")
        w("|---|---:|")
        for k, n in st.most_common():
            w(f"| {k} | {n} |")
        w("")

    man = os.path.join(MANUAL, "constructions.json")
    if os.path.exists(man):
        w("## Hand-curated structures\n")
        w("Facts that exist only in prose - depth, diameter, pump capacity - each with a source.\n")
        for s in read_json(man)["constructions"]:
            w(f"### {s['name']}\n")
            w(f"*{s['type']}* - owner **{s['owner']}** - confidence: {s['confidence']}  ")
            w(f"klima_id `{', '.join(s.get('klima_id') or []) or '-'}`, "
              f"plan `{', '.join(s.get('plan_ids') or []) or '-'}`\n")
            if s.get("route"):
                w(f"Route: {s['route']}\n")
            w("| Claim | Value | Source |")
            w("|---|---|---|")
            for cl in s["claims"]:
                val = cl["value"]
                val = f"{val[0]}-{val[1]}" if isinstance(val, list) else fmt(val)
                q = f" ({cl['qualifier']})" if cl.get("qualifier") else ""
                w(f"| {cl['what'].replace('_', ' ')} | {val} {cl['unit']}{q} | "
                  f"[link]({cl['source']}) read {cl['read_on']} |")
            w("")
            for cl in s["claims"]:
                if cl.get("disputed"):
                    w(f"> **Disputed - {cl['what']}:** {cl['disputed']}\n")
                if cl.get("note"):
                    w(f"> *{cl['what']}:* {cl['note']}\n")

    ids = reg["klima_id_without_documentation"]
    w("## Undocumented structures\n")
    w(f"{len(ids)} `klima_id` values appear in the city's own map layers with no matching "
      "project page:\n")
    by_pre = defaultdict(list)
    for i in ids:
        m = re.match(r"^[A-ZÆØÅ]+", i)
        by_pre[m.group(0) if m else "?"].append(i)
    for pre, group in sorted(by_pre.items()):
        w(f"- **{pre}** ({len(group)}): `" + "`, `".join(sorted(group)) + "`")
    w("")

    w("---\n")
    w("### Caveats\n")
    for cv in reg.get("caveats", []):
        w(f"- {cv}")
    w("")

    text = "\n".join(out)
    path = os.path.join(ROOT, "docs", "REGISTER.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    log(f"wrote docs/REGISTER.md ({len(text):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
