#!/usr/bin/env python3
"""Generate docs/SEABED.md - wind, waves, and whether the bed stays where it is.

Iltsvind and fedtemøg are different endpoints with different geography. Oxygen depletion
needs depth and a sealed bottom layer. Fedtemøg needs shallow water, light, retention and
a shore to strand on. Køge Bugt is shallow, so it fails the first test and passes the
second - and the national instrument measures the first.

This document covers what can be computed from wind alone: wave-driven bed shear stress,
how much more often a dead bed resuspends than a live one, and how often the wind drives
surface material onto the shore.

Usage:  python3 scripts/seabed.py   (after waves.py)
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import DERIVED, ROOT, log, read_json

MM_O2 = 31.998
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def main():
    wp = os.path.join(DERIVED, "waves.json")
    op = os.path.join(DERIVED, "onshore.json")
    if not os.path.exists(wp):
        log("run scripts/waves.py first")
        return 1
    w = read_json(wp)
    on = read_json(op) if os.path.exists(op) else None
    o = []
    a = o.append

    a("# The seabed, the wind, and what stays put\n")
    a("Generated by `scripts/seabed.py`. Wind from the Open-Meteo ERA5 archive "
      f"({w['period'][0][:10]} to {w['period'][1][:10]}, {w['hours']:,} hourly records), "
      "coastline from OpenStreetMap, everything else computed.\n")

    a("## Why this is computable without a current model\n")
    a("In a shallow bay the thing that lifts sediment off the bed is orbital motion under "
      "waves, and that follows from wind speed, direction, fetch and depth. Currents "
      "redistribute what the waves have already lifted — important, and not done here, "
      "because it needs data behind registration.\n")
    a("The chain: wind → fetch by direction (ray-cast to the OSM coastline) → fetch-limited "
      "wave height and period (Young & Verhagen 1996, shallow-water form) → bottom orbital "
      "velocity (linear wave theory) → bed shear stress (Swart friction factor) → compared "
      "against the critical stress for a living bed and a dead one.\n")

    a("## Fetch: Køge Bugt is a southeast-facing funnel\n")
    fe = os.path.join(ROOT, "data", "raw", "weather", "fetch.json")
    if os.path.exists(fe):
        tab = read_json(fe)
        a("| Wind from | Fetch |")
        a("|---|---:|")
        for lbl, deg in (("N", 0), ("NE", 45), ("E", 90), ("SE", 135),
                         ("S", 180), ("SW", 225), ("W", 270), ("NW", 315)):
            km = tab[str(deg)] / 1000
            bold = "**" if km > 50 else ""
            a(f"| {lbl} | {bold}{km:.1f} km{bold} |")
        a("")
    a("Southeast runs to 120 km — the open Baltic approach — against under 20 km in almost "
      "every other direction. Southeast is also the **onshore** direction for the western "
      "shore. The bay's longest wave fetch and its stranding direction are the same.\n")

    a("## A dead bed resuspends several times more often\n")
    tc = w["critical_shear_Pa"]
    keys = list(tc)
    a(f"Critical bed shear stress: **{tc[keys[0]]} Pa** with no biology, **{tc[keys[1]]} Pa** "
      "with biofilm, tube fauna and eelgrass binding the grains. Same weather, same waves — "
      "the only variable is whether the benthos is alive.\n")
    a("| Depth | Live bed | Dead bed | Ratio |")
    a("|---|---:|---:|---:|")
    for d in w["depths_m"]:
        r = w["by_depth"][str(float(d))]["exceedance"]
        lv = r[keys[1]]["hours_per_year"]
        dd = r[keys[0]]["hours_per_year"]
        a(f"| {d:.0f} m | {lv:,.0f} h/yr | {dd:,.0f} h/yr | **{dd/max(lv,0.1):.1f}×** |")
    a("")
    a("At 10 m the difference is nearly sevenfold — and the deeper, quieter water is exactly "
      "where the fine organic sulphidic mud settles.\n")
    a("That matters because resuspending sulphidic sediment is **itself an oxygen sink**, "
      "with no nitrogen and no algae in it. At 50 µmol AVS per gram dry sediment, stirring "
      "5 cm consumes about 80 g O₂/m² — the entire oxygen content of a 10 m water column. "
      "A storm over a dead bed can strip the water on its own.\n")

    a("### Which produces the loop\n")
    for i, s in enumerate([
        "iltsvind, toxicants or trawling kill the benthos",
        "the erosion threshold falls — the bed becomes loose",
        "storms resuspend more sediment, more often",
        "buried sulphide and metals are re-oxidised and remobilised",
        "resuspended sulphide consumes oxygen; turbidity blocks light",
        "less eelgrass, less benthos — back to step 2",
    ], 1):
        a(f"{i}. {s}")
    a("")

    a("## Seasonality: the bed is stirred hardest in autumn and winter\n")
    d5 = w["by_depth"]["5.0"]["exceedance"]
    a("Hours per year above the resuspension threshold at 5 m:\n")
    a("| Month | Live bed | Dead bed | Ratio |")
    a("|---|---:|---:|---:|")
    for i, m in enumerate(MONTHS, 1):
        lv = d5[keys[1]]["by_month"][str(i)]
        dd = d5[keys[0]]["by_month"][str(i)]
        a(f"| {m} | {lv:,.0f} | {dd:,.0f} | {dd/max(lv,0.1):.1f}× |")
    a("")
    a("October through January runs roughly double July. The resuspension season coincides "
      "with the overflow season and with the autumn overturn — three things converging in "
      "the same weeks, and the wave physics says so independently of anything about sewage.\n")
    a("Note the ratio column: biology protects most in summer (nearly 9× in July) and least "
      "in a January gale. Losing the benthos costs you most in the calm season; in a storm "
      "the bed moves regardless.\n")

    a("## Which winds do the work\n")
    a("| Sector | Mean fetch | Hours/yr resuspending | Share |")
    a("|---|---:|---:|---:|")
    for s, v in w["by_sector"].items():
        a(f"| {s} | {v['fetch_km']:.1f} km | {v['hours_per_year']:,.0f} | "
          f"{v['share_of_resuspension_pct']:.1f}% |")
    a("")
    a("Southwest and southeast each drive about a quarter — but for opposite reasons. "
      "Southwesterlies are frequent and short-fetch; southeasterlies are rare and run 89 km. "
      "**Southwest does the routine work, southeast does the damage**, and only southeast "
      "pushes toward the shore rather than away from it.\n")

    if on:
        a("## The accumulation term, which iltsvind does not have\n")
        a("Fedtemøg requires the biomass to *pile up somewhere*. A bay that produces the same "
          "algae and flushes it out does not get fedtemøg. So retention and stranding are "
          "part of the causal chain in a way they never are for oxygen depletion.\n")
        a("Wind from roughly 70–200° drives surface water, floating mats and their odour onto "
          "the western shore and inland:\n")
        a("| Month | Onshore hours | Onshore **and warm** | Onshore **and strong** |")
        a("|---|---:|---:|---:|")
        for m in MONTHS:
            v = on[m]
            a(f"| {m} | {v['onshore_h']:,.0f} | {v['onshore_warm_h']:,.0f} "
              f"| {v['onshore_strong_h']:,.0f} |")
        a("")
        a("Onshore wind is near-constant at 28–40% of hours year round. What changes is what "
          "it carries. **Warm-and-onshore peaks July to September** — growth and rotting "
          "conditions. **Strong-and-onshore peaks October to January** — the stranding "
          "conditions.\n")
        a("Which gives a sequence rather than a single season: mats grow and begin to "
          "putrefy through August and September in warm, weakly-mixed water, and are then "
          "driven ashore by the first autumn gales in October and November. That is one "
          "phenomenon with two phases, in two different months, and neither is measured.\n")

    a("## What is not here\n")
    a("Currents. The convergence of wind-driven southward transport against the Baltic "
      "outflow is a coherent mechanism for accumulation and would explain why fine sediment "
      "and floating material collect in this bay, but it needs current fields that are "
      "behind registration. Everything above is wave physics from wind, and says nothing "
      "about what arrives from elsewhere.\n")
    a("Also absent: any measurement. These are computed exceedance frequencies against "
      "literature values for critical shear stress, not observations of sediment moving. "
      "The ratio between a live and dead bed is robust; the absolute hours depend on a "
      "threshold that varies with mud composition.\n")

    path = os.path.join(ROOT, "docs", "SEABED.md")
    text = "\n".join(o)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    log(f"wrote docs/SEABED.md ({len(text):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
