#!/usr/bin/env python3
"""Generate docs/SEABED.md - wind, waves, and whether the bed stays where it is.

Iltsvind and fedtemøg are different endpoints with different geography. Oxygen depletion
needs depth and a sealed bottom layer. Fedtemøg needs shallow water, light, retention and
a shore to strand on. Køge Bugt is shallow, so it fails the first test and passes the
second - and the national instrument measures the first.

This document covers what can be computed from wind alone: wave-driven bed shear stress,
how much more often a dead bed resuspends than a live one, and how often the wind drives
surface material onto the shore.

Every number on the page is read live from waves.json (scripts/waves.py), the fetch
table, onshore.json, or seabed.json - the last written here, holding the stated
constants of the sulphide illustration so that they too print with their reasons.

Usage:  python3 scripts/seabed.py   (after waves.py)
"""
import calendar
import os
import statistics
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import DERIVED, RAW, ROOT, log, write_doc, write_json
import live

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
WAVES = os.path.join(DERIVED, "waves.json")
ONSHORE = os.path.join(DERIVED, "onshore.json")
FETCH = os.path.join(RAW, "weather", "fetch.json")
OWN = os.path.join(DERIVED, "seabed.json")
OUT = os.path.join(ROOT, "docs", "SEABED.md")
PAGE0 = "4469fc7"            # the last committed version of this page
# The sulphide illustration: stated values, not measurements of Køge Bugt.
ILLUSTRATION = {
    "avs_umol_per_g": 50,          # acid-volatile sulphide in sulphidic mud, per g dry
    "stir_depth_cm": 5,            # sediment a storm is taken to stir
    "dry_bulk_density_g_cm3": 0.5, # soft mud
    "o2_per_sulphide": 2,          # H2S + 2 O2 -> sulphate: two O2 per sulphide
    "mm_o2_g_per_mol": 31.998,     # molar mass of O2
    "o2_g_per_m3": 8,              # a well-oxygenated water column, mg per litre
    "column_m": 10,                # the water column compared against
}


def main():
    if not os.path.exists(WAVES):
        log("run scripts/waves.py first")
        return 1
    write_json(OWN, {"_what": "Stated constants of the sulphide illustration on SEABED.md.",
                     "illustration": ILLUSTRATION})
    w = live.live_json(WAVES)
    on = live.live_json(ONSHORE) if os.path.exists(ONSHORE) else None
    tab = live.live_json(FETCH) if os.path.exists(FETCH) else None
    il = live.live_json(OWN)["illustration"]
    o2 = live.chem("O2")
    o = []
    a = o.append

    a("# The seabed, the wind, and what stays put\n")
    a("Generated by `scripts/seabed.py`. Wind from the Open-Meteo ERA5 archive "
      f"({str(w['period'][0])[:10]} to {str(w['period'][1])[:10]}, {w['hours']:,} hourly "
      "records), coastline from OpenStreetMap, everything else computed.\n")

    a("## Why this is computable without a current model\n")
    a("In a shallow bay the thing that lifts sediment off the bed is orbital motion under "
      "waves, and that follows from wind speed, direction, fetch and depth. Currents "
      "redistribute what the waves have already lifted — important, and not done here, "
      "because it needs data behind registration.\n")
    a("The chain: wind → fetch by direction (ray-cast to the OSM coastline) → fetch-limited "
      "wave height and period (Young & Verhagen 1996, shallow-water form) → bottom orbital "
      "velocity (linear wave theory) → bed shear stress (Swart friction factor) → compared "
      "against the critical stress for a living bed and a dead one.\n")

    a("## Fetch: Køge Bugt is a southeast-facing funnel\n")
    if tab:
        a("| Wind from | Fetch |")
        a("|---|---:|")
        rows = []
        for lbl, deg in (("N", 0), ("NE", 45), ("E", 90), ("SE", 135),
                         ("S", 180), ("SW", 225), ("W", 270), ("NW", 315)):
            km = tab[str(deg)] / 1000
            rows.append((lbl, km))
            bold = "**" if km > 50 else ""
            a(f"| {lbl} | {bold}{km:.1f} km{bold} |")
        a("")
        se = dict(rows)["SE"]
        rest = statistics.median(km for lbl, km in rows if lbl != "SE")
        a(f"Southeast runs to {se:.0f} km — the open Baltic approach — against a median of "
          f"{rest:.0f} km over the other directions in the table. Southeast is also the "
          "**onshore** direction for the western shore. The bay's longest wave fetch and "
          "its stranding direction are the same.\n")

    a("## A dead bed resuspends several times more often\n")
    tc = w["critical_shear_Pa"]
    keys = list(tc)
    a(f"Critical bed shear stress: **{tc[keys[0]]} Pa** with no biology, **{tc[keys[1]]} Pa** "
      "with biofilm, tube fauna and eelgrass binding the grains. Same weather, same waves — "
      "the only variable is whether the benthos is alive.\n")
    a("| Depth | Live bed | Dead bed | Ratio |")
    a("|---|---:|---:|---:|")
    ratio = {}
    for d in w["depths_m"]:
        r = w["by_depth"][str(float(d))]["exceedance"]
        lv = r[keys[1]]["hours_per_year"]
        dd = r[keys[0]]["hours_per_year"]
        ratio[float(d)] = (d, dd / max(lv, 0.1))
        a(f"| {d:.0f} m | {lv:,.0f} h/yr | {dd:,.0f} h/yr | **{dd / max(lv, 0.1):.1f}×** |")
    a("")
    deep, deep_ratio = ratio[max(ratio)]
    a(f"At {deep:.0f} m the dead bed resuspends {deep_ratio:.1f} times as often as the live "
      "one — and the deeper, quieter water is exactly where the fine organic sulphidic "
      "mud settles.\n")
    a("There is a name for what that looks like. Under severe oxygen depletion, white "
      "filamentous sulphur bacteria (*Beggiatoa*) spread across the bed in milky "
      "sheets, oxidising hydrogen sulphide to sulphate using oxygen taken from the "
      "water. Danish calls them **liglagen** — corpse shroud — and they appear in late "
      "summer. The mat is the sulphide oxygen sink, visible.\n")
    mass = il["stir_depth_cm"] * il["dry_bulk_density_g_cm3"] * 10000     # g dry per m²
    need = il["avs_umol_per_g"] / 1e6 * mass * il["o2_per_sulphide"] * il["mm_o2_g_per_mol"]
    have = il["o2_g_per_m3"] * il["column_m"]
    a("That matters because resuspending sulphidic sediment is **itself an oxygen sink**, "
      f"with no nitrogen and no algae in it. At {il['avs_umol_per_g']} µmol acid-volatile "
      f"sulphide per gram of dry sediment and a dry bulk density of "
      f"{il['dry_bulk_density_g_cm3']} g/cm³, stirring {il['stir_depth_cm']} cm consumes "
      f"about {need:.0f} g {o2}/m², against {have:.0f} g {o2}/m² in a "
      f"{il['column_m']} m water column holding {il['o2_g_per_m3']} mg/L. A storm over a "
      "dead bed can strip the water on its own. (These are stated values for an "
      "illustration, not measurements of Køge Bugt.)\n")

    a("### Which produces the loop\n")
    for s in [
        "iltsvind, toxicants or trawling kill the benthos",
        "the erosion threshold falls — the bed becomes loose",
        "storms resuspend more sediment, more often",
        "buried sulphide and metals are re-oxidised and remobilised",
        "resuspended sulphide consumes oxygen; turbidity blocks light",
        "less eelgrass, less benthos — and the threshold falls again",
    ]:
        a(f"- {s}")
    a("")

    mid = w["depths_m"][1]
    d5 = w["by_depth"][str(float(mid))]["exceedance"]
    a("## Seasonality: the bed is stirred hardest in autumn and winter\n")
    a(f"Hours per year above the resuspension threshold at {mid:.0f} m:\n")
    a("| Month | Live bed | Dead bed | Ratio |")
    a("|---|---:|---:|---:|")
    dead_m, live_m = {}, {}
    for i, m in enumerate(MONTHS, 1):
        lv = d5[keys[1]]["by_month"][str(i)]
        dd = d5[keys[0]]["by_month"][str(i)]
        dead_m[m], live_m[m] = dd, lv
        a(f"| {m} | {lv:,.0f} | {dd:,.0f} | {dd / max(lv, 0.1):.1f}× |")
    a("")
    winter = (dead_m["Oct"] + dead_m["Nov"] + dead_m["Dec"] + dead_m["Jan"]) / 4
    a(f"October through January averages {winter / dead_m['Jul']:.1f} times July on a dead "
      "bed.\n")
    a("*Corrected.* An earlier version of this document said the resuspension season "
      f"coincides with the overflow season. {live.was(PAGE0, 'docs/SEABED.md', 'overflow season. @@ it does')} "
      "it does not: rain intense enough to overflow a combined sewer peaks in **June to "
      "August**, because intensity in Denmark is convective. Resuspension peaks in "
      "**October to January**. See [CURRENTS.md](CURRENTS.md) — the two are separated by a "
      "residence time, not simultaneous, and the sequence is deposit in summer, mobilise "
      "in autumn.\n")
    jul = dead_m["Jul"] / max(live_m["Jul"], 0.1)
    jan = dead_m["Jan"] / max(live_m["Jan"], 0.1)
    a(f"Note the ratio column: biology protects most in summer ({jul:.1f}× in July) and "
      f"least in a January gale ({jan:.1f}×). Losing the benthos costs you most in the "
      "calm season; in a storm the bed moves regardless.\n")

    a("## Which winds do the work\n")
    a("| Sector | Mean fetch | Hours/yr resuspending | Share |")
    a("|---|---:|---:|---:|")
    for s, v in w["by_sector"].items():
        a(f"| {s} | {v['fetch_km']:.1f} km | {v['hours_per_year']:,.0f} | "
          f"{v['share_of_resuspension_pct']:.1f}% |")
    a("")
    sw, se_s = w["by_sector"]["SW"], w["by_sector"]["SE"]
    a(f"Southwest and southeast drive {sw['share_of_resuspension_pct']:.0f}% and "
      f"{se_s['share_of_resuspension_pct']:.0f}% of the resuspension — but for opposite "
      f"reasons. Southwesterlies come over {sw['fetch_km']:.0f} km of water; "
      f"southeasterlies run {se_s['fetch_km']:.0f} km. **Southwest does the routine work, "
      "southeast does the damage**, and only southeast pushes toward the shore rather "
      "than away from it.\n")

    if on:
        a("## The accumulation term, which iltsvind does not have\n")
        a("Fedtemøg requires the biomass to *pile up somewhere*. A bay that produces the same "
          "algae and flushes it out does not get fedtemøg. So retention and stranding are "
          "part of the causal chain in a way they never are for oxygen depletion.\n")
        a(f"Wind from {live.was(PAGE0, 'docs/SEABED.md', 'Wind from @@ drives surface')} drives surface "
          "water, floating mats and their odour onto the western shore and inland:\n")
        a("| Month | Onshore hours | Onshore **and warm** | Onshore **and strong** |")
        a("|---|---:|---:|---:|")
        share = []
        for i, m in enumerate(MONTHS, 1):
            v = on[m]
            share.append(100 * v["onshore_h"] / (calendar.monthrange(2001, i)[1] * 24))
            a(f"| {m} | {v['onshore_h']:,.0f} | {v['onshore_warm_h']:,.0f} "
              f"| {v['onshore_strong_h']:,.0f} |")
        a("")
        warm = max(MONTHS, key=lambda m: on[m]["onshore_warm_h"])
        strong = max(MONTHS, key=lambda m: on[m]["onshore_strong_h"])
        a(f"Onshore wind blows {min(share):.0f}–{max(share):.0f}% of the hours in every month "
          f"of the year. What changes is what it carries. **Warm-and-onshore peaks in "
          f"{calendar.month_name[MONTHS.index(warm) + 1]}** — growth and rotting conditions. "
          f"**Strong-and-onshore peaks in {calendar.month_name[MONTHS.index(strong) + 1]}** — "
          "the stranding conditions.\n")
        a("Which gives a sequence rather than a single season: mats grow and begin to "
          "putrefy in late summer in warm, weakly-mixed water, and are then driven ashore "
          "by the first autumn gales. That is one phenomenon with two phases, in two "
          "different months, and neither is measured.\n")

    a("## What is not here\n")
    a("Currents. The convergence of wind-driven southward transport against the Baltic "
      "outflow is a coherent mechanism for accumulation and would explain why fine sediment "
      "and floating material collect in this bay, but it needs current fields that are "
      "behind registration. Everything above is wave physics from wind, and says nothing "
      "about what arrives from elsewhere.\n")
    a("Also absent: any measurement. These are computed exceedance frequencies against "
      "literature values for critical shear stress, not observations of sediment moving. "
      "The ratio between a live and dead bed is robust; the absolute hours depend on a "
      "threshold that varies with mud composition.\n")

    try:
        write_doc(OUT, "\n".join(o) + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote docs/SEABED.md ({os.path.getsize(OUT):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
