#!/usr/bin/env python3
"""Generate docs/SEABED.md - wind, waves, and whether the bed stays where it is.

Iltsvind and fedtemøg are different endpoints with different geography. Oxygen depletion
needs depth and a sealed bottom layer. Fedtemøg needs shallow water, light, retention and
a shore to strand on. Køge Bugt is shallow, so it fails the first test and passes the
second - and the national instrument measures the first.

This document covers what can be computed from wind alone: wave-driven bed shear stress,
how much more often a dead bed resuspends than a live one, and how often the wind drives
surface material onto the shore.

Every number on the page is read live from waves.json (scripts/waves.py), the fetch
table, onshore.json, currents_rain.json (scripts/currents.py) or seabed.json - the last written here, holding the stated
constants of the sulphide illustration so that they too print with their reasons.

Usage:  python3 scripts/seabed.py   (after waves.py)
"""
import calendar
import os
import statistics
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import DERIVED, RAW, ROOT, log, write_doc, write_json
import live

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
WAVES = os.path.join(DERIVED, "waves.json")
ONSHORE = os.path.join(DERIVED, "onshore.json")
FETCH = os.path.join(RAW, "weather", "fetch.json")
OWN = os.path.join(DERIVED, "seabed.json")
OUT = os.path.join(ROOT, "docs", "SEABED.md")
RAIN = os.path.join(DERIVED, "currents_rain.json")   # the rain climate, scripts/currents.py
# The sulphide illustration: stated values, not measurements of Køge Bugt.
ILLUSTRATION = {
    "avs_umol_per_g": 50,          # acid-volatile sulphide in sulphidic mud, per g dry
    "stir_depth_cm": 5,            # sediment a storm is taken to stir
    "dry_bulk_density_g_cm3": 0.5, # soft mud
    "o2_per_sulphide": 2,          # H2S + 2 O2 -> sulphate: two O2 per sulphide
    "mm_o2_g_per_mol": 31.998,     # molar mass of O2
    "o2_g_per_m3": 8,              # a well-oxygenated water column, mg per litre
    "column_m": 10,                # the water column compared against
}


def _run(months, values):
    """The first and last month of `months` if they form one run of the calendar, read
    round the year end; refused otherwise, or if the next month in `values` ties the
    last one kept (then which months form the season is not settled by the data)."""
    ranked = sorted(MONTHS, key=lambda m: -values[m])
    k = len(months)
    if values[ranked[k - 1]] == values[ranked[k]]:
        raise live.Unjustified(f"seabed: {ranked[k - 1]} and {ranked[k]} tie at the edge of the "
                               "season - the season claims must be reworded")
    idx = {MONTHS.index(m) for m in months}
    starts = [i for i in idx if (i - 1) % 12 not in idx]
    if len(starts) != 1:
        raise live.Unjustified(f"seabed: the months {sorted(months)} are not one run of the "
                               "calendar - the season claims must be reworded")
    s = starts[0]
    return MONTHS[s], MONTHS[(s + k - 1) % 12]


def main():
    if not os.path.exists(WAVES):
        log("run scripts/waves.py first")
        return 1
    write_json(OWN, {"_what": "Stated constants of the sulphide illustration on SEABED.md.",
                     "illustration": ILLUSTRATION})
    w = live.live_json(WAVES)
    on = live.live_json(ONSHORE) if os.path.exists(ONSHORE) else None
    tab = live.live_json(FETCH) if os.path.exists(FETCH) else None
    rain = live.live_json(RAIN)
    il = live.live_json(OWN)["illustration"]
    o2 = live.chem("O2")
    C = live.claim
    ref = live.ref
    month = lambda m: calendar.month_name[MONTHS.index(m) + 1]
    o = []
    a = o.append

    a("# The seabed, the wind, and what stays put\n")
    a(C("C-FR-SB-WHAT", "Generated by `scripts/seabed.py`. Wind from the Open-Meteo ERA5 archive "
        f"at a single grid point ({str(w['period'][0])[:10]} to {str(w['period'][1])[:10]}, "
        f"{w['hours']:,} hourly records), a table of fetch by direction and a table of onshore "
        "hours are read from files; the wave chain is computed, and its thresholds and the "
        "sulphide illustration are stated values.") + "\n")

    a("## What is computed, and from what\n")
    a(C("C-FR-SB-MECH", "The page follows the mechanism " + ref("D7", title=True) + " names: "
        "waves stirring the bed in shallow water. It computes the orbital motion under waves "
        "from wind speed, direction, fetch and depth, and takes the shear it puts on the bed as "
        "what lifts sediment; currents are not computed here, and [CURRENTS.md](CURRENTS.md) "
        "takes them up.") + "\n")
    a(C("C-FR-SB-CHAIN", "The chain: wind → fetch by direction, from the fetch table → "
        "fetch-limited wave height and period (Young & Verhagen 1996, shallow-water form) → "
        "bottom orbital velocity (linear wave theory) → bed shear stress (Swart friction factor) "
        "→ compared against the critical stress for a living bed and a dead one.") + "\n")

    a("## Fetch by direction\n")
    if tab:
        a("| Wind from | Fetch |")
        a("|---|---:|")
        rows = []
        for lbl, deg in (("N", 0), ("NE", 45), ("E", 90), ("SE", 135),
                         ("S", 180), ("SW", 225), ("W", 270), ("NW", 315)):
            km = tab[str(deg)] / 1000
            rows.append((lbl, km))
            bold = "**" if km > 50 else ""
            a(f"| {lbl} | {bold}{km:.1f} km{bold} |")
        a("")
        se = dict(rows)["SE"]
        rest = statistics.median(km for lbl, km in rows if lbl != "SE")
        top = max(float(tab[k]) for k in tab)
        if float(tab["135"]) != top:
            raise live.Unjustified("seabed: south-east no longer holds the fetch table's largest "
                                   "value - reword the fetch claim")
        at = sorted(int(k) for k in tab if float(tab[k]) == top)
        a(C("C-FR-SB-FETCH", f"South-east holds the table's longest fetch, {se:.0f} km, against "
            f"a median of {rest:.0f} km over the other directions in the table. "
            f"{live.live(len(at), FETCH, 'cap.n_at_max')} of the table's "
            f"{live.live(len(tab), FETCH, 'cap.n_directions')} directions hold exactly that "
            f"value, all between {live.live(at[0], FETCH, 'cap.first_deg_at_max')}° and "
            f"{live.live(at[-1], FETCH, 'cap.last_deg_at_max')}°, so it reads as a ceiling where "
            "the rays were stopped rather than as the distance to a coast: the fetch in those "
            "directions is not recorded.") + "\n")

    a("## A live bed and a dead bed\n")
    tc = w["critical_shear_Pa"]
    keys = list(tc)
    if not (keys[0].startswith("dead") and keys[1].startswith("live")):
        raise live.Unjustified("seabed: the critical stresses are no longer dead bed first, live "
                               "bed second - the page reads them in that order")
    a(C("C-FR-SB-TAU", f"The model's critical bed shear stress: **{tc[keys[0]]} Pa** for a bed "
        f"with no biology, **{tc[keys[1]]} Pa** for one bound by biofilm, tube fauna and eelgrass "
        "- stated values in `scripts/waves.py`, whose comment attributes them to the "
        "cohesive-sediment literature without naming a document. Same weather, same waves: the "
        "only thing that differs between the beds is the threshold.") + "\n")
    a("| Depth | Live bed | Dead bed | Ratio |")
    a("|---|---:|---:|---:|")
    ratio = {}
    for d in w["depths_m"]:
        r = w["by_depth"][str(float(d))]["exceedance"]
        lv = r[keys[1]]["hours_per_year"]
        dd = r[keys[0]]["hours_per_year"]
        ratio[float(d)] = (d, dd / max(lv, 0.1))
        a(f"| {d:.0f} m | {lv:,.0f} h/yr | {dd:,.0f} h/yr | **{dd / max(lv, 0.1):.1f}×** |")
    a("")
    deep, deep_ratio = ratio[max(ratio)]
    rs = [ratio[k][1] for k in sorted(ratio)]
    grows = all(x < y for x, y in zip(rs, rs[1:]))
    a(C("C-FR-SB-RATIO", f"At {deep:.0f} m the dead bed crosses its threshold "
        f"{deep_ratio:.1f} times as often as the live one"
        + (", and the ratio grows with depth in the table." if grows else
           "; the ratio does not grow steadily with depth in the table.")) + "\n")
    a(C("C-FR-SB-LIGLAGEN", "Prolonged oxygen depletion can leave white coatings of sulphur "
        "bacteria on the seabed, which DCE call liglagen: the bacteria use the last oxygen in the "
        "bottom water to oxidise hydrogen sulphide that has reached the top millimetres of the "
        "bed to elemental sulphur, and DCE call the mat the last barrier before the sulphide is "
        "released. Mat-forming sulphur bacteria such as *Beggiatoa* can also store nitrate and "
        "couple its reduction to the oxidation of reduced sulphur (Middelburg and Levin).")
      + "\n")
    mass = il["stir_depth_cm"] * il["dry_bulk_density_g_cm3"] * 10000     # g dry per m²
    need = il["avs_umol_per_g"] / 1e6 * mass * il["o2_per_sulphide"] * il["mm_o2_g_per_mol"]
    have = il["o2_g_per_m3"] * il["column_m"]
    a(C("C-FR-SB-SINK", "Resuspending sulphidic sediment is itself an oxygen sink, with no "
        "nitrogen and no algae in it: reduced sulphur that rises into oxygenated water is "
        "oxidised there, most of the oxygen consumed in coastal sediments goes to such "
        "re-oxidation, and a storm can bring sulphidic water up into surface water (Middelburg "
        "and Levin). The register holds the mechanism as " + ref("E1", title=True) + ".")
      + "\n")
    a(C("C-FR-SB-ILLUS", f"At {il['avs_umol_per_g']} µmol acid-volatile sulphide per gram of "
        f"dry sediment and a dry bulk density of {il['dry_bulk_density_g_cm3']} g/cm³, stirring "
        f"{il['stir_depth_cm']} cm would consume about {need:.0f} g {o2}/m² if all the sulphide "
        f"were oxidised to sulphate by the water's oxygen, against {have:.0f} g {o2}/m² in a "
        f"{il['column_m']} m water column holding {il['o2_g_per_m3']} mg/L. These are values "
        "chosen for an illustration, with no source recorded, not measurements of Køge Bugt: the "
        "arithmetic says what they would imply, and nothing here says whether the bay's mud "
        "holds that much sulphide.") + "\n")

    a("### The loop, as hypotheses\n")
    a(C("C-FR-SB-LOOP", "The register holds the links of a loop as hypotheses, not findings: "
        + ref("D8", title=True) + ", " + ref("D7", title=True) + ", " + ref("E1", title=True)
        + " and " + ref("F3", title=True) + ". This page computes how often a bed with and "
        "without that binding crosses its threshold, and tests none of them.") + "\n")

    mid = w["depths_m"][1]
    d5 = w["by_depth"][str(float(mid))]["exceedance"]
    a("## By month\n")
    a(f"Hours per year above each bed's threshold in the model at {mid:.0f} m:\n")
    a("| Month | Live bed | Dead bed | Ratio |")
    a("|---|---:|---:|---:|")
    dead_m, live_m = {}, {}
    for i, m in enumerate(MONTHS, 1):
        lv = d5[keys[1]]["by_month"][str(i)]
        dd = d5[keys[0]]["by_month"][str(i)]
        dead_m[m], live_m[m] = dd, lv
        a(f"| {m} | {lv:,.0f} | {dd:,.0f} | {dd / max(lv, 0.1):.1f}× |")
    a("")
    # the season is the page's reading of the table: the four months with most dead-bed
    # hours, and the three with most overflow-scale rain; each must be one run of the
    # calendar with no tie at its edge, or the page is refused (see _run)
    top_dead = sorted(MONTHS, key=lambda m: -dead_m[m])[:4]
    d0, d1 = _run(top_dead, dead_m)
    low = min(MONTHS, key=lambda m: dead_m[m])
    mean_top = sum(dead_m[m] for m in top_dead) / len(top_dead)
    a(C("C-FR-SB-SEASON", f"On a dead bed the model's hours peak from {month(d0)} to "
        f"{month(d1)} and are fewest in {month(low)}: those months average "
        f"{mean_top / dead_m[low]:.1f} times {month(low)}.") + "\n")
    rm = {m: rain["months"][m]["overflow_scale_h_per_yr"] for m in MONTHS}
    top_rain = sorted(MONTHS, key=lambda m: -rm[m])[:3]
    r0, r1 = _run(top_rain, rm)
    a(C("C-FR-SB-RAINSEASON", "In the same weather record, hours whose preceding "
        f"{rain['rain_window_h']}-hour rain reaches {rain['event_threshold_mm']:g} mm - the rain "
        "[CURRENTS.md](CURRENTS.md) counts as overflow-scale - are most frequent from "
        f"{month(r0)} to {month(r1)}, while the dead bed's hours peak from {month(d0)} to "
        f"{month(d1)}. CURRENTS.md sets the two against the water's retention: if an overflow's "
        "solids settle where they are discharged, delivery and resuspension fall in different "
        "seasons.") + "\n")
    ratio_m = {m: dead_m[m] / max(live_m[m], 0.1) for m in MONTHS}
    hi = max(MONTHS, key=lambda m: ratio_m[m])
    lo = min(MONTHS, key=lambda m: ratio_m[m])
    excess = {m: dead_m[m] - live_m[m] for m in MONTHS}
    ex = max(MONTHS, key=lambda m: excess[m])
    a(C("C-FR-SB-RATIOMONTH", f"The ratio is highest in {month(hi)} ({ratio_m[hi]:.1f}×) and "
        f"lowest in {month(lo)} ({ratio_m[lo]:.1f}×)"
        + (f", but the dead bed's excess over the live one, in hours, is largest in {month(ex)}: "
           f"{excess[ex]:,.0f} hours a year, against {excess[hi]:,.0f} in {month(hi)}. In "
           f"proportion the live bed's threshold matters most in {month(hi)}; in hours, in "
           f"{month(ex)}." if ex != hi else
           ", and the dead bed's excess over the live one, in hours, is largest there too."))
      + "\n")

    a("## Which winds do the work\n")
    a("| Sector | Mean fetch | Hours/yr resuspending | Share |")
    a("|---|---:|---:|---:|")
    for s, v in w["by_sector"].items():
        a(f"| {s} | {v['fetch_km']:.1f} km | {v['hours_per_year']:,.0f} | "
          f"{v['share_of_resuspension_pct']:.1f}% |")
    a("")
    sw, se_s = w["by_sector"]["SW"], w["by_sector"]["SE"]
    pct = rain["wind_all_hours"]["pct"]
    first, second = (("southwest", "SW"), ("southeast", "SE")) if pct["SW"] >= pct["SE"] else \
        (("southeast", "SE"), ("southwest", "SW"))
    a(C("C-FR-SB-SECTORS", f"Southwest and southeast account for "
        f"{sw['share_of_resuspension_pct']:.0f}% and {se_s['share_of_resuspension_pct']:.0f}% of "
        f"the dead bed's resuspending hours at {mid:.0f} m. Southwesterlies blow over a mean fetch "
        f"of {sw['fetch_km']:.0f} km and southeasterlies over {se_s['fetch_km']:.0f} km, and "
        f"{first[0]} is the more frequent wind in the record: {pct[first[1]]:g}% of all hours "
        f"against {pct[second[1]]:g}% from the {second[0]}.") + "\n")

    if on:
        a("## Onshore wind\n")
        a(C("C-FR-SB-FEDT", "Fedtemøg is a popular name for mass occurrences of loose-lying "
            "filamentous brown algae, which attach to stones, grow on into long strands, can tear "
            "loose, and can lie rotting at the water's edge (Danish Wikipedia). Whether wind "
            "drives them ashore is what onshore hours bear on; this page measures no algae.")
          + "\n")
        a(C("C-FR-SB-ONSHORE", "Hours of onshore wind for the bay's western shore come from a "
            "table held without the script that made it: the direction sector it counts as "
            "onshore, and what it counts as warm and as strong, are recorded nowhere in the "
            "repository.") + "\n")
        a("| Month | Onshore hours | Onshore **and warm** | Onshore **and strong** |")
        a("|---|---:|---:|---:|")
        share = []
        for i, m in enumerate(MONTHS, 1):
            v = on[m]
            share.append(100 * v["onshore_h"] / (calendar.monthrange(2001, i)[1] * 24))
            a(f"| {m} | {v['onshore_h']:,.0f} | {v['onshore_warm_h']:,.0f} "
              f"| {v['onshore_strong_h']:,.0f} |")
        a("")
        warm = max(MONTHS, key=lambda m: on[m]["onshore_warm_h"])
        strong = max(MONTHS, key=lambda m: on[m]["onshore_strong_h"])
        a(C("C-FR-SB-ONSHARE", f"By that table, onshore wind blows {min(share):.0f}–"
            f"{max(share):.0f}% of the hours in every month of the year; warm-and-onshore hours "
            f"peak in {month(warm)} and strong-and-onshore hours in {month(strong)}.") + "\n")
        a(C("C-FR-SB-NOSHORE", "No series of shore condition or fedtemøg is among the sources "
            "this project surveyed, so nothing here measures when mats grow, rot or strand.")
          + "\n")

    a("## What is not here\n")
    a(C("C-FR-SB-NOTCURRENTS", "Currents. Whether wind-driven southward transport meets the "
        "Baltic outflow so that Køge Bugt collects material mobilised elsewhere is not "
        "established ([OPEN_PROBLEMS.md](OPEN_PROBLEMS.md)). Everything above is computed from "
        "wind, and says nothing about what arrives from elsewhere.") + "\n")
    a(C("C-FR-SB-NOMEASURE", "Also absent: any measurement. These are counts of hours in which "
        "the model's bed shear exceeds stated thresholds, not observations of sediment moving; "
        "the hours, and the ratio between the beds, depend on those thresholds and on the wave "
        "model, and nothing here checks either against an observation.") + "\n")

    try:
        write_doc(OUT, "\n".join(o) + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote docs/SEABED.md ({os.path.getsize(OUT):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
