#!/usr/bin/env python3
"""Generate docs/SOLUTIONS.md - what would actually stop the discharge, from the city's
own data.

Everything else in this project measures the problem. This measures the response: how
much of Copenhagen still drains sewage and rain down the same pipe, how much the plan
proposes to change that, how much has actually been disconnected, and what the city
built instead.

The one result that decides where to start: the register of overflow structures is
extremely concentrated. A small number of them hold most of the volume, which means a
small number of interventions - and a small number of measurements - would cover most of
the problem. It also means a sample designed to be representative cannot estimate the
mean, which is what the national concentration figures are built on.

Usage:  python3 scripts/solutions.py
"""
import collections
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import RAW, ROOT, log, read_json

LONM = 111320.0 * math.cos(math.radians(55.68))
SURFACE = {"Grønne veje", "Skybrudsveje", "Forsinkelsesveje"}
# Categories in kloaksystem_status/_plan, grouped by what they mean for the sea.
COMBINED = "Fælleskloakeret"
RECONNECTED = "Separatkloakeretopland tilkoblet fællessystemet"


def geo(name):
    return read_json(os.path.join(RAW, f"{name}.geojson"))["features"]


def line_len(g):
    if not g:
        return 0.0
    def seg(c):
        return sum(math.hypot((b[0] - a[0]) * LONM, (b[1] - a[1]) * 111320.0)
                   for a, b in zip(c, c[1:]))
    if g["type"] == "LineString":
        return seg(g["coordinates"])
    if g["type"] == "MultiLineString":
        return sum(seg(c) for c in g["coordinates"])
    return 0.0


def num(v):
    try:
        return float(str(v).strip().replace(",", "."))
    except (TypeError, ValueError):
        return 0.0


def short(s, n=44):
    s = str(s)
    return s if len(s) <= n else s[:n - 1] + "…"


def main():
    o = []
    a = o.append

    # ------------------------------------------------------------ the sewer
    catch = [x["properties"] for x in geo("sp_kloakoplande")]
    def agg(key, areakey, pekey):
        A, P, N = collections.defaultdict(float), collections.defaultdict(float), collections.Counter()
        for p in catch:
            k = p.get(key) or "ikke oplyst"
            A[k] += p.get(areakey) or 0
            P[k] += p.get(pekey) or 0
            N[k] += 1
        return A, P, N
    As, Ps, Ns = agg("kloaksystem_status", "befaestet_areal_status", "pe_status")
    Ap, Pp, Np = agg("kloaksystem_plan", "befaestet_areal_plan", "pe_plan")
    ta, tp = sum(As.values()), sum(Ps.values())
    comb_a, comb_p = As[COMBINED], Ps[COMBINED]

    a("# What would actually stop it\n")
    a("Generated by `scripts/solutions.py` from Københavns Kommune's own catchment and "
      "cloudburst layers and the national overflow register. Everything else here "
      "measures the problem; this measures the response.\n")

    a("## 1. Copenhagen is a combined sewer\n")
    a("Rain that falls on a Copenhagen street mostly does not go to a river. It goes "
      "into the same pipe as the sewage, and when that pipe fills, the mixture leaves "
      "through an overflow structure without passing a treatment works.\n")
    a("| Sewer system | Catchments | Impervious area | Population equivalent |")
    a("|---|---:|---:|---:|")
    for k in sorted(As, key=lambda x: -As[x]):
        if As[k] < 0.5 and Ps[k] < 100:
            continue
        a(f"| {short(k)} | {Ns[k]:,} | {As[k]:,.0f} ha ({As[k]/ta*100:.1f}%) | "
          f"{Ps[k]:,.0f} ({Ps[k]/tp*100:.1f}%) |")
    a("")
    a(f"**{comb_p/tp*100:.1f}% of the city's population equivalent, and "
      f"{comb_a/ta*100:.1f}% of its impervious area, sits on a combined system.** That "
      f"is {comb_a:,.0f} hectares of roof and pavement whose runoff is, by design, mixed "
      "with sewage before it can go anywhere.\n")
    a("It is the single most consequential fact about the city's relationship with the "
      "sea, and it is not a fact about agriculture, nutrients or nitrogen. It is a "
      "plumbing decision made a century ago.\n")

    # ------------------------------------------------------------ the plan
    trans = collections.Counter((p.get("kloaksystem_status"), p.get("kloaksystem_plan"))
                                for p in catch)
    leaving = [(b, n) for (aa, b), n in trans.items() if aa == COMBINED and b != COMBINED]
    leaving.sort(key=lambda x: -x[1])
    n_comb = sum(n for (aa, _b), n in trans.items() if aa == COMBINED)
    n_stay = trans[(COMBINED, COMBINED)]
    n_recon = trans.get((COMBINED, RECONNECTED), 0)
    n_true = sum(n for b, n in leaving if b != RECONNECTED)

    a("## 2. The plan does not separate it\n")
    a(f"Every catchment carries both a current sewer type and a planned one. Of the "
      f"**{n_comb} combined catchments**:\n")
    a("| Planned outcome | Catchments | What it means for the sea |")
    a("|---|---:|---|")
    a(f"| Stays combined | **{n_stay}** | nothing changes |")
    a(f"| *Separatkloakeret opland tilkoblet fællessystemet* | **{n_recon}** | "
      "separated inside the catchment — **and reconnected to the combined system.** "
      "The rain is still in the sewage pipe by the time it reaches an overflow. |")
    a(f"| Genuine separation, stormwater to a recipient | **{n_true}** | the rain leaves "
      "the sewage system |")
    a("")
    a("The middle row is the finding, and the category's own name says it. Separating "
      "the pipes within a catchment and then joining them again upstream of the overflow "
      "changes what happens inside the block and changes nothing at the outfall.\n")
    net = (As[COMBINED] - Ap[COMBINED]) - Ap.get(RECONNECTED, 0)
    a(f"By impervious area: combined drops from {As[COMBINED]:,.0f} ha to "
      f"{Ap[COMBINED]:,.0f} ha, but {Ap.get(RECONNECTED,0):,.0f} ha of that goes into "
      f"the reconnected category. **Net area actually leaving the combined system: about "
      f"{net:,.0f} ha, or {net/As[COMBINED]*100:.1f}%.**\n")

    # ------------------------------------------------------------ LAR
    lar = [x["properties"] for x in geo("lar_registreringer")]
    lar_tot = sum(num(p.get("afkoblet_areal_m2")) for p in lar)
    inuse = sum(num(p.get("afkoblet_areal_m2")) for p in lar
                if str(p.get("tilladelse_taget_i_brug")).strip().lower() == "ja")
    a("## 3. What has actually been disconnected\n")
    a("The other route off the combined system is local infiltration — soakaways, rain "
      "gardens, green roofs — each of which takes a specific area of roof or pavement "
      "off the sewer. The city registers them individually, with the disconnected area "
      "in square metres.\n")
    a(f"| | |")
    a("|---|---:|")
    a(f"| Registered installations | {len(lar):,} |")
    a(f"| Total disconnected area | **{lar_tot/1e4:,.0f} ha** |")
    a(f"| Of which confirmed in use | {inuse/1e4:,.0f} ha |")
    a(f"| Combined-sewered impervious area | {comb_a:,.0f} ha |")
    a(f"| **Share disconnected** | **{lar_tot/1e4/comb_a*100:.1f}%** "
      f"(confirmed in use: {inuse/1e4/comb_a*100:.1f}%) |")
    a("")
    a("So after however many years of the policy, between one and five per cent of the "
      "relevant area has been taken off the pipe. At the pace implied by the confirmed "
      "figure this is a multi-century programme, and nothing about that is a criticism "
      "of infiltration as a technique — it is a statement about scale.\n")

    # ------------------------------------------------------------ surface
    veje = geo("skp_veje_tunneller_kk")
    L, N = collections.defaultdict(float), collections.Counter()
    byyear = collections.defaultdict(float)
    for x in veje:
        t = x["properties"]["typologi"]
        l = line_len(x["geometry"])
        L[t] += l
        N[t] += 1
        byyear[x["properties"].get("forventet_ibrugtagning")] += l
    tl = sum(L.values())
    surf = sum(v for k, v in L.items() if k in SURFACE)
    pipe = L.get("Skybrudsledning", 0.0)

    a("## 4. Copenhagen did build rivers — for the wrong rain\n")
    a("The cloudburst plan is not mostly pipes. It is mostly surface: streets reshaped "
      "into channels, green roads, squares that hold water. Deliberate rainwater rivers, "
      "at city scale, already designed and partly built.\n")
    a("| Type | Segments | Length | |")
    a("|---|---:|---:|---|")
    for k in sorted(L, key=lambda x: -L[x]):
        tag = "**surface**" if k in SURFACE else ("pipe" if "ledning" in k.lower() else "mixed")
        a(f"| {k} | {N[k]:,} | {L[k]/1000:,.1f} km | {tag} |")
    a(f"| **Total** | **{len(veje):,}** | **{tl/1000:,.1f} km** | |")
    a("")
    a(f"**{surf/1000:,.0f} km of surface conveyance against {pipe/1000:,.0f} km of pipe "
      f"— {surf/pipe:.1f} to 1.** The idea is not missing from Copenhagen's plan. It is "
      "the plan's dominant form.\n")
    a("### But a skybrudsvej is sized for the rain that does not cause overflows\n")
    a("The cloudburst plan is designed against a hundred-year event. A skybrudsvej is a "
      "route for water that has nowhere else to go — it activates when the system is "
      "already overwhelmed, a handful of times a decade.\n")
    a("Overflows are not a hundred-year phenomenon. They happen on ordinary heavy rain, "
      "many times a year, and that rain still goes down the gully into the combined "
      "pipe exactly as it always did. The surface network was built for the flood risk "
      "to the city, which is a different problem with a different design storm.\n")
    a("The everyday-rain component is the green roads and the infiltration — "
      f"{L.get('Grønne veje',0)/1000:,.0f} km and {lar_tot/1e4:,.0f} ha respectively — "
      "against 3,447 ha that needs disconnecting.\n")
    done = sum(v for y, v in byyear.items() if str(y).isdigit() and int(y) <= 2025)
    later = sum(v for y, v in byyear.items() if str(y).isdigit() and int(y) > 2025)
    undated = tl - done - later
    a(f"Delivery, on the city's own expected-in-service dates: **{done/1000:,.0f} km by "
      f"the end of 2025**, {later/1000:,.0f} km scheduled through 2038, and "
      f"{undated/1000:,.0f} km with no date at all.\n")

    # ------------------------------------------------------------ the tail
    # The national register, not the Copenhagen clip - the sampling argument is national.
    pts = [x["properties"] for x in
           read_json(os.path.join(RAW, "national", "punkt_rbu_udl.geojson"))["features"]]
    cph_pts = [x["properties"] for x in geo("vp3_basis_2019_punkt_rbu_udl")]
    vols = sorted((p.get("vol_sb") or 0) for p in pts)
    vols = [v for v in vols if v > 0]
    vols.sort(reverse=True)
    tot_v = sum(vols)
    a("## 5. Why a representative sample cannot measure this\n")
    a(f"The national register holds **{len(pts):,} rain-dependent discharge points** "
      f"across {len(set(p.get('komm_navn') for p in pts))} municipalities "
      f"({len(cph_pts):,} of them inside the Copenhagen clip used elsewhere here). "
      f"Only **{len(vols):,}** of them carry a recorded basin volume; the other "
      f"{len(pts)-len(vols):,} have the field empty. Among those that do have a number, "
      "the distribution is extreme:\n")
    a("| Share of structures | Count | Share of stored volume |")
    a("|---|---:|---:|")
    for frac in (0.01, 0.05, 0.10, 0.20, 0.50):
        n = max(1, int(len(vols) * frac))
        a(f"| top {frac*100:.0f}% | {n:,} | **{sum(vols[:n])/tot_v*100:.1f}%** |")
    a("")
    n1 = max(1, int(len(vols) * 0.01))
    a(f"**{n1} structures hold {sum(vols[:n1])/tot_v*100:.0f}% of the recorded volume.** "
      f"The largest is {vols[0]:,.0f} m³; the median is {vols[len(vols)//2]:,.0f} m³. "
      "That is a heavy tail, and heavy tails break sampling.\n")
    a("The national pollutant concentrations — the typetal applied to all "
      f"{len(pts):,} points — come from **6 combined-overflow stations and 5 stormwater "
      "stations**, in catchments *deliberately chosen* to represent households and "
      "residential areas, and explicitly excluding industrial areas and heavily "
      "trafficked roads. The same report notes the highest median metal concentrations "
      "in sludge from basins, and the typetal explicitly cover only discharges without "
      "prior settling.\n")
    a("Put those together. In a heavy-tailed distribution the mean is set by the tail, "
      "so an estimate of the mean is an estimate of the tail. This sampling design "
      "removed the tail on purpose, then used the remainder to estimate the mean, then "
      "multiplied it by every discharge point in the country.\n")
    a("The same structure is well known in the ocean-plastic literature, where a small "
      "minority of rivers carries the large majority of the input, and any uniform "
      "per-river assumption is wrong by an order of magnitude. There is no reason a "
      "sewer network should be more evenly behaved than a river network, and this "
      "register says it is not.\n")

    # ------------------------------------------------------------ how fast
    a("## 6. How fast could any of this move?\n")
    a("The concentration in section 5 cuts both ways. It is what makes the measurement "
      "invalid, and it is also what makes the problem tractable — because if a few "
      "structures dominate, then a few interventions cover most of it.\n")
    a("| | Timescale | Why |")
    a("|---|---|---|")
    a(f"| Measure the tail | **weeks** | Flow-proportional samplers on the largest "
      f"{n1} structures. That is videnniveau 5, the best method in Miljøstyrelsen's own "
      "hierarchy, at 30% uncertainty instead of 135%. It has never been done because "
      "nobody is required to. |")
    a("| Publish event-level data | **weeks** | The event counts are already recorded in "
      "PULS. The flow rates are not recorded at all, which is a decision, not a limit. |")
    a("| Empty basins before the season | **months** | Accumulated sludge is exported "
      "when flow scours it. Removing it in advance is an operating procedure, not "
      "construction. |")
    a("| Intercept fat at source | **months** | Grease separators are already a legal "
      "requirement for food businesses. Enforcement is regulatory. |")
    a("| Disconnect roofs at scale | **years to decades** | 1–5% done. |")
    a("| Genuinely separate the network | **decades** | Nine catchments of three hundred "
      "are planned for it. |")
    a("| Deliver the surface network | **to 2038** | on the city's own dates |")
    a("")
    a("So the honest answer to *how fast* is that it splits in two. **The measurement "
      "problem could be fixed in a season**, and until it is, nobody can say which of "
      "the slow interventions is worth the money. **The infrastructure problem cannot "
      "be fixed quickly by anyone**, and the plan on the books does not attempt it — "
      "it holds water back rather than routing it away.\n")
    a("Which is the case for doing the cheap thing first. Instrument the tail, find out "
      "whether a handful of structures dominates the load the way a handful dominates "
      "the volume, and the argument about what to build next becomes an argument with "
      "evidence in it.\n")

    a("---\n")
    a("*Sources: `sp_kloakoplande`, `lar_registreringer` and `skp_veje_tunneller_kk` "
      "from Københavns Kommune's WFS; `vp3_basis_2019_punkt_rbu_udl` from Miljøgis. "
      "Typetal provenance in `data/manual/monitoring.json`. Lengths are computed from "
      "the geometries; areas and volumes are the values the publishers recorded.*")

    path = os.path.join(ROOT, "docs", "SOLUTIONS.md")
    text = "\n".join(o)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    log(f"wrote docs/SOLUTIONS.md ({len(text):,} chars)")
    log(f"  combined: {comb_p/tp*100:.1f}% of PE, {comb_a:,.0f} ha impervious")
    log(f"  of {n_comb} combined catchments: {n_stay} stay, {n_recon} reconnected, "
        f"{n_true} truly separated")
    log(f"  LAR disconnected {lar_tot/1e4:,.0f} ha = {lar_tot/1e4/comb_a*100:.1f}%")
    log(f"  surface {surf/1000:,.0f} km vs pipe {pipe/1000:,.0f} km")
    log(f"  top {n1} of {len(vols):,} structures hold {sum(vols[:n1])/tot_v*100:.0f}% of volume")
    return 0


if __name__ == "__main__":
    sys.exit(main())
