#!/usr/bin/env python3
"""docs/AREAS.md - water bodies are management units; what the stations say.

Top to bottom: (1) water bodies are management units, with the enclosure-against-
homogeneity point and the Roskilde Fjord spreads; (2) what the stations' own
co-movement supports, from data/derived/synchrony.json; (3) whether the stations
are alike, and (4) a first grouping along a causal line, livestock, both from
data/derived/livestock_baskets.json; (5) water-body numbers where a management
question needs them, labelled administrative, with the per-area record published
as a file; (6) the cross-water-body correlation as a correlation across management
units, pointing to its lineage (docs/data/lineage/cum_hoc_r.json).

The ledger numbers come from data/derived/areas.json (scripts/areas.py), the station
facts from data/derived/station_places.json, the register size from
docs/data/areas/stations.json. Figures from other people's documents are read from
their pinned text. Every assertion is a checked claim, registered in
data/manual/claims.d/w1-ar.json (wording kept from wave one) and
data/manual/claims.d/w4-ar.json (this version, and what it retired to ARCHIVE.md).
See LIVE_NUMBERS.md, sections 2 and 11.

    python3 scripts/pages/areas.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import DERIVED, MANUAL, ROOT, log, read_json, write_doc
import claims
import live
import refs

OUT = os.path.join(ROOT, "docs", "AREAS.md")
AREAS = os.path.join(DERIVED, "areas.json")
SP = os.path.join(DERIVED, "station_places.json")
REG = os.path.join(ROOT, "docs", "data", "areas", "stations.json")
SYNC = os.path.join(DERIVED, "synchrony.json")
LIVE = os.path.join(DERIVED, "livestock_baskets.json")
LINEAGE = os.path.join(ROOT, "docs", "data", "lineage", "cum_hoc_r.json")
B, E, C = live.claim_begin, live.CLAIM_END, live.claim
BAND_REASON = ("The central band of a null distribution that livestock_baskets.py's "
               "place() counts as the noise floor: a contrast inside the band between the "
               "null's `0.025` and `0.975` quantiles does not beat it.")


def refify(text):
    """Text from a data file, with register IDs made checked references and an
    open-problem item number written as the identifier it is."""
    text = re.sub(r"open problem (\d+)", r"open problem `\1`", text)
    reg = refs.registry()
    return refs.TOKEN.sub(lambda m: live.ref(m.group(1)) if m.group(1) in reg
                          else m.group(0), text)


def share(part, whole):
    return live.step("K-SUBSET-SHARE", part / whole * 100)


def verdict(x):
    return str(x["verdict"])


def main():
    A = live.live_json(AREAS)
    rec, ch, sm = A["areas"], A["cum_hoc"], A["summary"]
    hz, sets = A["hazardous_layer"], sm["sets"]
    sea = sm["sea_km2"]
    sp = live.live_json(SP)
    cov, rosk = sp["coverage"], sp["roskilde"]
    reg = live.live_json(REG)
    lines = {int(x["min_years"]): x for x in cov["lacking_long_station"]}
    long_line = lines[max(lines)]
    nei = sets["neither"]
    S = live.live_json(SYNC)
    LS = live.live_json(LIVE)
    LIN = live.live_json(LINEAGE)
    # other people's figures, read from their pinned documents
    cd = claims.load()[0]
    cache = {}

    def read(ph):
        return claims.resolve(cd, ph, cache)[0]
    agri = read("{read:DANVA-2024:69.6|hvor landbruget alene står for 69,6 %}")
    every = read("{read:DHI-MODEL-DEL1-2015:119|For hvert af de 119 vandområder}")
    crit = read("{read:DCE-STATMOD-2015:4|koncentrationen af ilt i vandet er under 4 mg/L}")
    band = live.stated("w4ar_central_band_pct", 95, "95", BAND_REASON)

    o = []
    a = o.append
    a("# There is no Denmark\n")
    a("*Generated by `scripts/pages/areas.py` from `data/derived/areas.json`, "
      "`data/derived/synchrony.json` and `data/derived/livestock_baskets.json`.*\n")

    # ---- 1. water bodies are management units --------------------------------
    a("## Water bodies are management units\n")
    a(C("C-W4AR-UNITS", f"**The {sets['all']['n']} marine water bodies are management units.** "
        "They exist so that an authority can be made responsible for an area of sea and "
        "given a target for it. Nothing in the data discovered them, and a number computed "
        "per water body is a number about the administration until something shows "
        "otherwise.") + "\n")
    a(B("C-AR-AGG") + "The national argument is made in aggregates: one land-borne load, and one "
      f"share of it for agriculture - {agri}% in the figure DANVA cites from Miljøstyrelsen "
      "and Aarhus University. Aggregation is where the information goes: a figure true of "
      "Denmark need not hold for any one water body inside it." + E + "\n")

    a("### Two meanings of \"a body of water\", and the switch between them\n")
    a(B("C-AR-ENCLOSURE") + "\"Roskilde Fjord\" is not an arbitrary line on a map, and it is "
      "worth saying so plainly before objecting to anything. It names a real hydrographic "
      "object: an inlet bounded by land that opens to the sea through Isefjorden. That is a "
      "**claim about enclosure**, it is physical, and it is true." + E + "\n")
    a(C("C-AR-HOMOGENEITY", "The assessment then uses the same word to mean something else "
        "entirely: that a measurement taken anywhere in it stands for the whole of it. That is "
        "a **claim about homogeneity**, and it is statistical. One sense is about where the "
        "water is bounded; the other is about whether the water inside those bounds is alike. "
        "Nothing carries you from the first to the second, and the name does the carrying "
        "unnoticed because the same three words serve both.") + "\n")
    a(B("C-AR-PHYSICS") + "**And where exchange is restricted, the physics runs against the "
      "transfer, not with it.** Restricted exchange is what *preserves* a gradient. A basin "
      "with freshwater entering at its head and little exchange at its mouth holds salinity, "
      "residence-time and oxygen gradients along its length because it does not flush; open "
      "water erases such differences by mixing. So the better the enclosure, the weaker the "
      "homogeneity assumption becomes: the two senses **pull in opposite directions**, and the "
      "enclosures that most deserve their names are the ones least entitled to be treated as "
      "single units." + E + "\n")
    a(B("C-AR-TWO-UNITS") + "The partition half-concedes this without following it through. "
      f"Roskilde Fjord appears here as two water bodies, `DKCOAST1` (ydre, "
      f"{rec['DKCOAST1']['area_km2']:.0f} km²) and `DKCOAST2` (indre, "
      f"{rec['DKCOAST2']['area_km2']:.0f} km²) — an admission that one enclosure is at least "
      "two units." + E + " " + B("C-AR-SPLIT-UNSTATED") + "The documents this project holds "
      "give the general basis for water bodies' boundaries — the water framework directive "
      "asks member states to set them, and the plans sort coastal waters into types with a "
      "catchment each — but none of them says why this fjord is two units rather than one or "
      "three, or what measurement would settle it." + E + " " + B("C-AR-X22") + "A boundary "
      "drawn inside a fjord is a hypothesis about where the water changes, and it can be "
      "tested: `X22` in [EXPERIMENTS.md](EXPERIMENTS.md) sets out how, using pairs of "
      "measurements at matched separation either side of a line." + E + "\n")
    a("> " + C("C-AR-POSITION", "The practical rule that follows, and the reason the "
               "station-level series exist: **the unit of observation is a position.** "
               "Everything else — this page included — is an aggregate computed inside "
               "somebody's polygon, and should be read as a statement about that polygon as "
               "much as about the sea.") + "\n")

    a("### The switch, measured in the fjord it is named after\n")
    a(B("C-AR-ROSK-METHOD") + "The station-level series make this checkable rather than "
      "arguable. Both halves of Roskilde Fjord carry several stations, so for any month where "
      f"{rosk['min_stations']} or more measured, the disagreement *between* stations can be "
      "set against the variation *across* months. *Spread between stations* is the population "
      "standard deviation across the stations in a month, averaged over the months, beside the "
      "median range; *spread across months* is the standard deviation of the monthly means."
      + E + "\n")
    a(f"| variable | basket | months with {rosk['min_stations']}+ stations | spread between "
      "stations, same month | spread across months | ratio |")
    a("|---|---|---:|---:|---:|---:|")
    rows = list(rosk["rows"])
    best = {}
    for r in rows:
        k = str(r["variable"])
        if k not in best or r["ratio"] > best[k]["ratio"]:
            best[k] = r
    for r in rows:
        ratio = f"{r['ratio']:.2f}"
        if best[str(r["variable"])] is r:
            ratio = f"**{ratio}**"
        a(f"| {str(r['label']).lower()} {r['depth']} | {r['half']} `{r['waterbody']}` | "
          f"{r['months']} | sd {r['sd_between']:.2f}, median range "
          f"{r['range_between_median']:.2f} | {r['sd_across']:.2f} | {ratio} |")
    a("")

    def rr(var, wb):
        return next(r for r in rows if r["variable"] == var and r["waterbody"] == wb)
    oi, oy = rr("oxy_bed", "DKCOAST2"), rr("oxy_bed", "DKCOAST1")
    si, sy = rr("sal_surf", "DKCOAST2"), rr("sal_surf", "DKCOAST1")
    a(C("C-AR-ILTSVIND", f"In Denmark, oxygen below {crit} mg/L is called iltsvind.") + " "
      + B("C-AR-ROSK-OXY") + "**The inner fjord's own stations disagree about bottom oxygen by "
      f"a median of {oi['range_between_median']:.2f} mg/l within a single month.** "
      "A spread that size is most of the distance from zero to that "
      "threshold, so in a month when the fjord's bottom water is near it, one station can read "
      "below and another above — and whether that body \"has iltsvind\" can then depend on "
      "which of its own stations is read. The ratio puts it another way: the spread between "
      f"stations is **{oi['ratio'] * 100:.0f}% of the spread of the monthly means across "
      "months**." + E + "\n")
    a(B("C-AR-ROSK-HALVES") + "**And the two halves fail on different variables.** The inner "
      f"fjord's stations disagree for oxygen ({oi['ratio']:.2f}) and agree for salinity "
      f"({si['ratio']:.2f}); the outer fjord's are the reverse — close for oxygen "
      f"({oy['ratio']:.2f}), apart for salinity ({sy['ratio']:.2f}). Within this one fjord, a "
      "boundary drawn to serve one variable does not serve the other. That is one case, not a "
      "proof about every partition; it is the case `X22` would test systematically." + E + "\n")
    a(C("C-AR-ROSK-SOURCE", "Computed by `scripts/station_places.py` from "
        "`docs/data/areas/stations_series.*`, which carry no partition at all — the water-body "
        "assignment used here is loaded separately from `station_waterbody_overlay.json`, on "
        "purpose, so that using it is a deliberate act.") + "\n")

    # ---- 2. what the stations' own behaviour supports ------------------------
    sc = S["construction"]
    alpha, near_km = sc["alpha"], sc["near_km"]
    ox, sa = S["variables"]["oxy_bed"], S["variables"]["sal_bed"]
    oc, nf = ox["counts"], ox["near_far"]
    so = ox["within_vs_across_matched_distance"]["share_beyond_chance"]
    to = ox["within_vs_across_matched_distance"]["mean_tau"]
    ss = sa["within_vs_across_matched_distance"]["share_beyond_chance"]
    ts = sa["within_vs_across_matched_distance"]["mean_tau"]
    a("## What the stations' own behaviour supports\n")
    a(C("C-W4AR-SYNC-METHOD", "Only moving together over time is tested here, never similar "
        "levels. Each station's own seasonal cycle is removed - its median for each calendar "
        "month - and each pair of stations is compared month by month on what is left "
        "(Kendall's tau). Chance is one station's series shifted against the other's by whole "
        "years, which keeps each series intact and breaks only the tie in time. A pair moves "
        f"together beyond chance when it beats its shifted copies at the {alpha * 100:.0f}% "
        "level, so that share of pairs passes by chance alone. Distances are straight lines "
        "between stations; land is ignored.") + " "
      + C("C-W4AR-SYNC-THIN", f"For bed oxygen, {oc['pairs_decidable']:,} pairs of stations "
          f"share a window long enough for the test, involving "
          f"{oc['stations_in_decidable_pairs']} stations; another "
          f"{oc['pairs_too_thin_for_null']:,} pairs overlap too briefly to be shifted, and are "
          "left undecided.") + "\n")
    a(C("C-W4AR-NEAR-FAR", "**Stations near each other move together far more often than "
        f"stations far apart.** Of the {nf['near_pairs']} bed-oxygen pairs less than "
        f"{near_km:.0f} km apart, {nf['share_near_co_moving'] * 100:.1f}% move together beyond "
        f"chance; of the {nf['far_pairs']:,} pairs farther apart, "
        f"{nf['share_far_co_moving'] * 100:.1f}%.") + "\n")
    a(C("C-W4AR-MATCHED", "**At the same distance apart, pairs inside one water body move "
        "together more often than pairs across a line.** For bed oxygen, the share moving "
        "together beyond chance is higher inside by "
        f"{so['pooled_within_minus_across'] * 100:.1f} percentage points, pooled over "
        "distance bins (standard error "
        f"{so['jackknife_se_leave_one_waterbody_out'] * 100:.1f}, leaving out one water body "
        "at a time). With finer bins the gain is "
        f"{so['fine_bins_pooled_within_minus_across'] * 100:.1f} points: part of it was "
        "distance left over inside the bins.") + " "
      + C("C-W4AR-WATER-MASSES", "**But bed salinity, which says nothing about an ailment, "
          f"gains about as much** - {ss['pooled_within_minus_across'] * 100:.1f} points "
          f"(standard error {ss['jackknife_se_leave_one_waterbody_out'] * 100:.1f}) - and in "
          "the average size of the co-movement it gains more than oxygen: a tau "
          f"{ts['pooled_within_minus_across']:.3f} higher inside, against "
          f"{to['pooled_within_minus_across']:.3f} for oxygen. So the lines follow differences "
          "in the water itself, the kind a sill or a fjord mouth makes, and the oxygen gain is "
          "no larger than the water's. Nothing here shows a shared ailment on top of shared "
          "water.") + "\n")
    sdo = ox["same_day_sampling"]
    hc = sdo["how_common"]["same_day"]
    dd = sdo["different_day"]["gap_ge_1_days"]
    ddo = dd["within_vs_across_matched_distance"]["share_beyond_chance"]
    dds = sa["same_day_sampling"]["different_day"]["gap_ge_1_days"][
        "within_vs_across_matched_distance"]["share_beyond_chance"]
    gap5 = sc["different_day_min_gap_days"][1]
    d5 = sdo["different_day"][f"gap_ge_{int(gap5)}_days"]["counts"][
        "decidable_pairs_same_waterbody"]
    a(C("C-W4AR-SAME-DAY", "**Part of that could be the sampling trip.** Stations in one water "
        "body share a sampling day in "
        f"{hc['within_same_waterbody']['share_same_day'] * 100:.1f}% of their pair-months for "
        "bed oxygen, pairs across a line in "
        f"{hc['across_waterbodies']['share_same_day'] * 100:.1f}%. On months the two stations "
        "were sampled on different days, same-body pairs still move together more often than "
        "pairs across a line at the same distance - by "
        f"{ddo['pooled_within_minus_across'] * 100:.1f} percentage points for oxygen (standard "
        f"error {ddo['jackknife_se_leave_one_waterbody_out'] * 100:.1f}) and "
        f"{dds['pooled_within_minus_across'] * 100:.1f} for salinity (standard error "
        f"{dds['jackknife_se_leave_one_waterbody_out'] * 100:.1f}). The gain persists, but for "
        f"oxygen it now rests on {ddo['pooled_weight_within_pairs']} same-body pairs, where the "
        f"full test had {so['pooled_weight_within_pairs']}. With samples at least {gap5} days "
        f"apart, only {d5} same-body oxygen pairs remain: too few to answer.") + "\n")
    g = ox["graph"]
    ccs = g["connected_components"]["summary"]
    lv = g["louvain"]
    lvs = lv["summary"]
    nwb = [x["n_waterbodies"] for x in lv["groups"]]
    ends = [x["median_last_year"] for x in lv["groups"]]
    a(C("C-W4AR-OWN-GROUPS", "**The groups the stations draw for themselves do not follow the "
        "lines.** Joining every pair that moves together beyond chance links "
        f"{ccs['stations_in_largest_group']} of the {g['n_nodes']} tested oxygen stations into "
        "one group. Split into communities by the strength of their co-movement (Louvain), "
        f"they form {lvs['n_groups']} groups, each spanning between {min(nwb)} and {max(nwb)} "
        f"water bodies; {lvs['groups_2plus_contiguous']} of them form a contiguous patch of "
        f"sea. Of the {lvs['waterbodies_with_2plus_stations']} water bodies with two or more "
        f"tested stations, {lvs['waterbodies_split_across_2plus_groups']} are split between "
        "groups. And the groups partly sort by when their stations were measured: one group's "
        f"records end, at the median, in {min(ends):.0f}, the largest group's in "
        f"{lv['groups'][0]['median_last_year']:.0f}.") + "\n")
    wyf = ox["within_year"]["near_far"]["share_far_co_moving"]
    a(C("C-W4AR-NATIONAL", "**And distance does not end it.** "
        f"{nf['share_far_co_moving'] * 100:.1f}% of bed-oxygen pairs {near_km:.0f} km or more "
        f"apart move together beyond chance, where chance alone gives {alpha * 100:.0f}%. With "
        f"each station's own yearly level also removed, {wyf * 100:.1f}% still do; on months "
        f"the two were sampled on different days, {dd['near_far']['share_far'] * 100:.1f}%. "
        "What moves stations everywhere at once is common to the whole population: a "
        "national signal, not a property of any place in it.") + " "
      + C("C-W4AR-WEATHER", "Shared weather is the obvious candidate; it is not tested "
          "here.") + "\n")

    # ---- 3. are the stations alike? -------------------------------------------
    rb = LS["repeat_vs_between"]["oxy_bed"]
    rA = rb["repeat_A_same_station_consecutive_summer_months_abs_diff"]["q50"]
    bB = rb["between_B_two_stations_same_year_month_abs_diff"]
    iq = rb["interchangeability_null_for_station_medians"]["by_set"]["all"]
    rd = LS["readings"]
    if rd["oxy_bed"]["stations_interchangeable_overall"] or \
            rd["oxysat_bed"]["stations_interchangeable_overall"]:
        raise SystemExit("the stations now read as interchangeable: rewrite section 3")
    a("## Are the stations alike?\n")
    a(C("C-W4AR-READINGS", "A grouping that does no better than random baskets has two "
        "readings. The grouping may be bad; or the stations may be alike, so that no grouping "
        "could do better and treating them as one kind drops nothing that matters. One "
        "comparison decides between them: the spread among stations against the spread of "
        "one station measured again.") + "\n")
    a(C("C-W4AR-ALIKE", f"For summer bed oxygen, one station changes by a median of {rA:.2f} "
        "mg/l from one summer month to the next - more than its measurement noise alone, "
        "since that includes real change within a summer. Two stations in the same water "
        f"body, in the same month, differ by {bB['same_water_body']['q50']:.2f}: about as "
        f"much. Any two stations differ by {bB['all_pairs']['q50']:.2f}. And the stations' own "
        "summer medians spread over an interquartile range of "
        f"{iq['observed_iqr_of_station_medians']:.2f} mg/l, where shuffling which station "
        "measured what, among the stations measured in the same month, gives "
        f"{iq['null_iqr_if_interchangeable']['q50']:.2f}; "
        f"{iq['draws_with_null_iqr_ge_observed']} of {iq['null_iqr_if_interchangeable']['n']} "
        "shuffles reached the real spread.") + "\n")
    a(C("C-W4AR-READING-A", "**So the stations are not one kind.** They differ beyond a "
        "station's own month-to-month change, and the differences sit between water bodies "
        "rather than within them. That is the first reading: the population is not uniform, "
        "and a grouping has to explain the differences between water bodies - which, for "
        "livestock, the next section shows it does not. Oxygen saturation gives the same "
        "answer.") + "\n")

    # ---- 4. a grouping along a causal line: livestock -------------------------
    fm, na, cch = LS["farms"], LS["near_absent_catchments"], LS["construction_choices"]
    bd = LS["baskets"]["definition_on_stations_with_summer_bed_oxygen"]
    co = LS["comparison_all_years"]["oxy_bed"]
    ct = co["contrasts"]
    n_na = live.live(len(na["catchments"]), LIVE, "near_absent_catchments.catchments.[len]")
    cats = sorted(na["catchments"], key=lambda c: -float(c["area_km2"]))
    gaps = [float(cats[k]["area_km2"]) - float(cats[k + 1]["area_km2"])
            for k in range(len(cats) - 1)]
    cut = gaps.index(max(gaps)) + 1            # the widest gap in land area
    big, rest = cats[:cut], cats[cut:]
    nwb_b = bd["low"]["water_bodies"] + bd["mid"]["water_bodies"] + bd["high"]["water_bodies"]
    n_st = LS["stations"]["basketable_with_summer_bed_oxygen"]
    a("## A grouping along a causal line: livestock\n")
    a(C("C-W4AR-LS-NAIVE", "Stations are grouped here by the livestock on the land that "
        "drains to their water body: the first basket drawn along a causal line, and **a naive "
        "one**. The livestock is where herds are registered, in the 2024 register, not where "
        "their manure is spread, counted in the regulatory unit DE rather than as nitrogen, "
        "against station records that span decades. Each catchment is linked to the water "
        "body it touches along the coast, a link built here, and an outer fjord does not "
        "inherit its inner fjord's land. And low-livestock land is not low-load land: urban "
        "and sewage loads are not in this grouping. Livestock figures on this page are totals "
        "over areas of land, never a single farm.") + "\n")
    a(C("C-W4AR-LS-ABSENT", "**Where livestock is near-absent was set before looking:** a "
        "catchment with less than "
        f"{cch['near_absent_fraction_of_national'] * 100:.0f}% of the national density of "
        f"{fm['national_density_DE_per_km2']:.1f} DE per km², that is below "
        f"{na['threshold_DE_per_km2']:.1f}. {n_na} catchments meet it. The largest of them, "
        f"from {big[-1]['area_km2']:.0f} to {big[0]['area_km2']:.0f} km² of land, are in "
        "north-east Zealand, around and north of Copenhagen: "
        + "; ".join(str(c["op_navn"]) for c in big) + ". The rest are small, none over "
        f"{rest[0]['area_km2']:.0f} km²: islands, nors, and small fjords and bays.") + " "
      + C("C-W4AR-LS-BASKETS", "Every station in a water body that land drains to, with at "
          f"least {cch['min_summer_station_months']} summer months of bed oxygen, enters a "
          "basket: thirds of the stations by the density of the land behind their water body "
          f"- low up to {bd['cuts_DE_per_km2'][0]:.1f} DE per km², high above "
          f"{bd['cuts_DE_per_km2'][1]:.1f} - with the near-absent end inside the low third. "
          f"That is {n_st} stations in {nwb_b} water bodies; {bd['near_absent']['stations']} "
          f"of them sit in the {bd['near_absent']['water_bodies']} near-absent water "
          "bodies.") + "\n")
    if not ct["median_high_minus_median_low"] < 0:
        raise SystemExit("the heavy basket is no longer below the low one: rewrite section 4")
    a(C("C-W4AR-LS-LEVELS", "**Summer bed oxygen barely differs in the middle:** the heavy "
        f"basket's median station is {abs(ct['median_high_minus_median_low']):.2f} mg/l below "
        "the low basket's. The difference is in the low tail: the heavy basket's tenth "
        f"percentile is {co['high']['q10']:.2f} mg/l, the low basket's "
        f"{co['low']['q10']:.2f}.") + "\n")
    nfl = co["noise_floor"]
    st_nh = nfl["station_level"]["median_near_absent_minus_median_high"]
    bl = nfl["water_body_block_level"]
    bl_nh = bl["median_near_absent_minus_median_high"]
    keys = ("median_high_minus_median_low", "median_near_absent_minus_median_high",
            "P(high station < low station)")
    if not all(verdict(bl[k]).startswith("inside the central") for k in keys):
        raise SystemExit("a contrast now leaves the water-body band: rewrite section 4")
    a(C("C-W4AR-LS-FLOOR", "**Counted as independent stations, livestock looks strong.** The "
        f"near-absent basket's median station has {ct['median_near_absent_minus_median_high']:.2f} "
        "mg/l more bed oxygen than the heavy basket's, and "
        f"{st_nh['draws_at_or_above_real']} of {st_nh['draws']:,} random baskets of the same "
        f"sizes reached that. But the {n_st} stations sit in only {nwb_b} water bodies and "
        "move with them. Shuffling the densities between whole water bodies instead, each "
        f"keeping its stations together, puts every contrast inside the central {band}% of "
        f"the random results: {bl_nh['draws_at_or_above_real']:,} of {bl_nh['draws']:,} draws "
        "gave a near-absent lead at least as large. **For bed oxygen the livestock line does "
        "not beat the noise floor.**") + " "
      + C("C-W4AR-LS-NOTHING", "Nor does the basket add to the difference between stations: "
          "two stations in different water bodies, in the same month, differ by "
          f"{bB['different_water_body_same_basket']['q50']:.2f} mg/l when they share a basket "
          f"and {bB['different_basket']['q50']:.2f} when they do not.") + "\n")
    up = LS["ubiquitous_seasonal_profile_bed_oxygen"]
    mm = up["month_of_minimum_across_random_baskets"]
    if list(mm) != ["8"] or any(int(v) != 8 for v in up["month_of_minimum_real"].values()):
        raise SystemExit("the seasonal minimum is no longer August everywhere: rewrite")
    hq = co["ubiquitous_part"]["by_basket_size"]["high"]["q10"]
    a(C("C-W4AR-LS-UBIQ", "What every random basket shows is common to all the stations, "
        f"whatever the membership: bed oxygen bottoms out in August in {mm['8']:,} of "
        f"{up['random_basket_count']:,} random baskets, and in the real ones. Only the heavy "
        f"basket's low tail is unusual: its tenth percentile, {hq['real_basket']:.2f} mg/l, is "
        "near the lowest any random basket of its size gave, "
        f"{hq['random_baskets']['min']:.2f}.") + "\n")
    sr = LS["strata"]["results"]
    brk, shl = "brackish_bed_salinity_lt_20", "shallow_depth_le_10m"
    dbk, sal = "brackish_bed_salinity_lt_20 & deep_depth_gt_10m", "marine_bed_salinity_ge_20"

    def strat(k):
        return sr[k]["oxy_bed"]

    def wbv(k):
        return verdict(strat(k)["noise_floor"]["water_body_block_level"][
            "median_high_minus_median_low"])
    if not (all(wbv(k).startswith("outside the central") for k in (brk, shl, dbk))
            and all(not wbv(k).startswith("outside the whole") for k in sr
                    if isinstance(strat(k)["noise_floor"], dict))
            and strat(sal)["contrasts"]["median_high_minus_median_low"] > 0):
        raise SystemExit("the strata verdicts changed: rewrite section 4")
    s10 = LS["sensitivity"][f"oxy_bed_summers_from_{int(cch['period_sensitivity_from'])}"]
    a(C("C-W4AR-LS-STRATA", "**Within strata, cut before looking at a bed salinity of "
        f"{cch['bed_salinity_cut']:.0f}‰ and a depth of {cch['depth_cut_m']:.0f} m,** the "
        "heavy basket's median falls further below the low basket's: in brackish water by "
        f"{abs(strat(brk)['contrasts']['median_high_minus_median_low']):.2f} mg/l, in shallow "
        f"water by {abs(strat(shl)['contrasts']['median_high_minus_median_low']):.2f}, in deep "
        f"brackish water by {abs(strat(dbk)['contrasts']['median_high_minus_median_low']):.2f}. "
        f"There it reaches the edge of the water-body random band - outside its central "
        f"{band}%, inside its full range - and never clearly past it. In salty bottom water it "
        "reverses: the heavy basket's median is "
        f"{strat(sal)['contrasts']['median_high_minus_median_low']:.2f} mg/l above the low "
        f"one's. Using only summers from {cch['period_sensitivity_from']}, closer to the 2024 "
        "register, the gap shrinks to "
        f"{abs(s10['contrasts']['median_high_minus_median_low']):.2f} mg/l.") + " "
      + C("C-W4AR-LS-SALTY", "A reading, not tested here: in salty bottom water oxygen is set "
          "more by the layering of the water and by inflow than by the land nearby.") + "\n")
    rk = next(w for w in LS["water_bodies"] if w["ov_id"] == "DKCOAST132")
    allmed = co["all_basketed"]["q50"]
    if not (rk["DE_per_km2"] > bd["cuts_DE_per_km2"][1]
            and rk["median_summer_bed_oxygen_of_stations"] > allmed):
        raise SystemExit("Ringkøbing Fjord no longer shows what the page says: rewrite")
    a(C("C-W4AR-LS-DOES", "**What this shows, and what it does not.** Heavy-livestock water "
        "has the worse low tail. Heavy-livestock land does not mean low oxygen everywhere: "
        f"Ringkøbing Fjord has {rk['DE_per_km2']:.0f} DE per km² behind it and a median "
        f"summer bed oxygen of {rk['median_summer_bed_oxygen_of_stations']:.2f} mg/l across "
        f"its stations, above the {allmed:.2f} of all basketed stations. It does not show "
        "that livestock lowers bed oxygen: it compares levels, and similar levels are not a "
        "shared cause. The test of one is whether stations move together along the line, and "
        "that has not yet been run for livestock.") + "\n")
    fl = LS["comparison_all_years"]["fluo"]
    fnf = fl["noise_floor"]
    if not all(verdict(fnf[lvl]["median_high_minus_median_low"]).startswith("outside the whole")
               for lvl in ("station_level", "water_body_block_level")):
        raise SystemExit("fluorescence no longer clears both floors: rewrite section 4")
    a(C("C-W4AR-LS-FLUO", "**Fluorescence is the one measure the livestock baskets separate "
        f"clearly.** The heavy basket's median station reads {fl['high']['q50']:.2f}, the low "
        f"basket's {fl['low']['q50']:.2f}; a heavy station reads below a low one in "
        f"{fl['contrasts']['P(high station < low station)'] * 100:.0f}% of pairs; and the "
        "contrast lies outside the whole range of both kinds of random basket.") + " "
      + C("C-W4AR-LS-FLUO-CAVEAT", "It carries a caveat nobody has checked: the panel's "
          "fluorescence is a whole-cast value in relative units, so a difference between "
          "instruments or monitoring programmes could produce the same separation.") + "\n")

    # ---- 5. water-body numbers where a management question needs them ----------
    a("## Water-body numbers, where a management question needs them\n")
    a(C("C-W4AR-ADMIN", "**The numbers in this section are administrative:** counts of "
        "management units, and what stands behind the targets they are given - not findings "
        "about the sea.") + "\n")
    a("### The state of knowledge, counted\n")
    a("| | areas | km² | share of sea |")
    a("|---|---:|---:|---:|")
    for lab, key in (("All marine water bodies in the national marine layer", "all"),
                     ("…with a DHI statistical model (see below)", "modelled"),
                     ("…with bathing-water stations, repeated over years", "with_bathing"),
                     ("…with three or more informative bathing stations", "testable"),
                     ("…with neither the flag nor a bathing station", "neither")):
        s = sets[key]
        a(f"| {lab} | {s['n']} | {s['km2']:,.0f} | {share(s['km2'], sea):.1f}% |")
    a("")
    a(B("C-AR-MODEL-MATCH") + "**The model flag follows DHI's list.** A water body counts as "
      "modelled when DHI's 2015 method report lists it among the water bodies with a "
      "station-level statistical model, matched to this layer by DHI's water-body number, "
      "with every name read against the layer's own (`data/manual/statistical_models.json`). "
      "One of DHI's models covers five Limfjord bredninger together, so all five are counted; "
      "one water body it lists, Randers Fjord's Grund Fjord, is not in the marine layer used "
      "here." + E + "\n")
    a(B("C-AR-NEITHER") + f"Counted with that flag, {nei['n']} water bodies covering "
      f"{nei['km2']:,.0f} km² ({share(nei['km2'], sea):.0f}% of Danish sea) carry neither the "
      "flag nor a repeated observation **in the two layers counted here** — bathing water, "
      "and the hazardous-substance layer, which holds no marine point." + E + " "
      + C("C-AR-REQUIREMENT", "A requirement does not wait for either: in the method behind "
          f"the second water plans, every one of its {every} water bodies was given an "
          "indsatsbehov, whether it had a statistical model or not.") + "\n")

    a("### What an absence can be counted over\n")
    a(C("C-AR-ABSENCE-RULE", "**A claim of absence is only as wide as the search behind it**, "
        "and this search was two layers deep.") + "\n")
    a(B("C-AR-REGISTER") + f"ODA's station register holds **{reg['n']:,} positioned marine "
      "stations**." + E + " " + B("C-W4AR-SERIES-COVERAGE") + "The part of it this page can "
      "place in water bodies is the station series behind the co-movement tests and the "
      f"livestock baskets above — {cov['series_stations']:,} stations with a monthly record, "
      f"{cov['stations_inside']:,} of them inside a water body by point in polygon — and "
      f"**{cov['waterbodies_with_station']} of the {cov['waterbodies']} water bodies contain "
      "at least one of those.** Counted over that series: " + ", ".join(
          f"{x['waterbodies']} water bodies contain no station with data in "
          f"{x['min_years']} or more distinct years" for x in cov["lacking_long_station"])
      + "." + E + "\n")
    a(B("C-AR-NOT-PERCENT") + "**Those are counts, and they are deliberately not "
      f"percentages.** Saying *{share(long_line['km2'], sea):.0f}% of the sea has no long "
      "observation* would be the missing-denominator error this project exists to point at. "
      f"The denominator is known — the sea is {sea:,.0f} km². The numerator is not, because it "
      "is the extent of an absence, and an absence can only be measured against a search that "
      "was exhaustive. Ours was ODA plus two layers; ICES and EMODnet sit outside it, and so "
      "does whatever university, municipal or unpublished series exist." + E + "\n")
    a("The test is whether **the category named is the same width as the corpus searched.**\n")
    a("- " + B("C-AR-SAME-WIDTH") + "**Same width — an exact statement is fine, including of "
      f"an absence.** *None of the {sets['all']['n']} water bodies has a marine point in the "
      f"national hazardous-substance layer: its {hz['points']} points are {hz['lake']} lake "
      f"and {hz['river']} river.* The category is that layer and the count is of all of it, "
      "so its complement is exact." + E)
    a("- " + B("C-AR-WIDER") + "**Category wider than corpus — only a count is honest.** "
      f"*{share(nei['km2'], sea):.0f}% of the sea has no marine observation* would name a "
      "category — marine observation — far wider than the two layers actually searched, and "
      "report the leftover after subtracting what we happened to find as though it were "
      "measured, which is the operation [RESIDUAL.md](RESIDUAL.md) is about." + E + "\n")
    a(C("C-AR-NAMED-CORPUS", "So absence is reported here as a count over a named corpus, "
        "and the corpus is named every time.") + "\n")
    a(B("C-AR-GAPS") + "**And the corpus is named together with what is missing from it.** A "
      "coverage figure has a numerator nobody can measure — the evidence that exists — so "
      "counting what we assembled gives a *lower bound on evidence* and therefore an *upper "
      "bound on absence*. That is only interpretable beside the terms we know belong in the "
      "numerator and cannot add. They are kept in `data/manual/coverage_gaps.json`, a "
      "hand-kept record, in three kinds:" + E + "\n")
    a("| | source | what it would add | why we do not have it |")
    a("|---|---|---|---|")
    for gp in read_json(os.path.join(MANUAL, "coverage_gaps.json"))["gaps"]:
        a(f"| `{gp['class']}` | **{gp['id']}** | {refify(gp['would_add'])} | "
          f"{refify(gp['barrier'])} |")
    a("")
    a(B("C-AR-GAP-CLASSES") + "The distinction inside that table matters as much as the "
      "table. `closed` is a gap in the world's availability; `open_unassembled` is a gap in "
      "our effort and is nobody's fault but ours; `absent` is the only one where a search was "
      "run to the end, and even that is bounded by the search." + E + " " + B("C-AR-PULS")
      + f"**PULS is the sharpest case.** It holds the per-event overflow volumes that "
      f"{live.ref('B1')} calls the single most valuable missing series — volumes that are "
      "themselves largely modelled, by this project's source register — and an access "
      "attempt with a private MitID was refused because no CVR or VAT number attached to it "
      "was valid, so this is not a login anyone has neglected to perform. Access appears to "
      "require a registered business or authority, in which case a private citizen cannot "
      "obtain it." + E + "\n")

    bm = A["bathing_match"]
    lr = bm["left_out_by_reason"]
    a("### How things are put into water bodies\n")
    a(C("C-W4AR-ASSIGN", "**Pressures are put into water bodies by nearest point on the "
        "marine boundary:** each outfall, treatment plant, aquaculture outlet, dumping ground "
        "and extraction area goes to the water body owning the nearest boundary vertex within "
        f"{A['assignment']['max_km']:.0f} km, searched to that distance in every direction, and "
        "to none beyond it. **Bathing stations are not placed by distance:** each goes to the "
        "water body its own record names, its `wbid`, matched exactly to the marine layer's "
        f"code. Of {bm['stations']:,} bathing stations with a classed year, {bm['matched']} are "
        f"placed and {bm['left_out']} left out: {lr['lake_code']} carry a lake code, "
        f"{lr['coastal_code_not_in_marine_layer']} a coastal code the marine layer does not "
        f"hold, {lr['no_wbid']} no code, and {lr['code_in_another_form']} a code written "
        "another way.") + "\n")

    r2 = rec["DKCOAST2"]
    b2 = r2["observation"]["bathing"]
    if not (r2["has_statistical_model"] and r2["n_gaps"] == 1
            and "hazardous" not in r2["observation"]):
        raise SystemExit("the Roskilde Fjord indre record changed shape: rewrite section 5")
    a("### The record of each water body\n")
    a(C("C-AR-RECORD", "The full record for each area — every pressure, every stream with its "
        "years, and the written-out list of what cannot be modelled there — is in "
        "`data/derived/areas.json`, which `scripts/areas.py` writes locally and the repository "
        "does not ship, and drawn with its timeline on [the map](areas.html).") + " "
      + C("C-W4AR-DOWNLOAD", "A copy trimmed to what the map draws - each water body's "
          "pressures, bathing observation, streams with their years, and the reasons it cannot "
          "be modelled - is published for download as [areas.json](data/areas/areas.json).")
      + "\n")
    a(C("C-W4AR-ONE-ROW", f"**One record, read through.** `DKCOAST2`, {r2['name']}, is "
        f"{r2['area_km2']:.1f} km² of water and one of the water bodies with a DHI statistical "
        f"model. It holds {b2['stations']} bathing stations classed between "
        f"{b2['first_year']} and {b2['last_year']}; of those, the "
        f"{b2['informative_stations']} whose classes vary enough to correlate have yearly "
        f"classes that correlate, pair by pair, at {b2['internal_r']:.2f} on average. By "
        "nearest boundary it is assigned "
        f"{r2['pressure']['rbu']['n']} rain-conditioned outfalls and "
        f"{r2['pressure']['rens']['pe']:,} approved person-equivalents of treatment-plant "
        "capacity - a permitted figure, not a load. And its record gives "
        f"{r2['n_gaps']} written-out reason it cannot be modelled: it has no marine "
        "hazardous-substance monitoring point, which no water body has. Every other record in "
        "the file is built the same way.") + "\n")

    # ---- 6. the cross-water-body correlation ----------------------------------
    t = ch["tests"][2]
    per = ch["by_period"]["periods"]
    old, new = per["old_labels"], per["new_labels"]
    t_old, t_new = old["tests"][2], new["tests"][2]
    for x in (t, t_old, t_new):
        if (str(x["predictor"]), str(x["outcome"])) != ("log10(1+pe_per_km2)", "sub_excellent"):
            raise SystemExit("cum_hoc.tests[2] is no longer the traced test: rewrite section 6")
    rv = [x["value"] for x in LIN["robustness"]]
    a("## The cross-water-body correlation\n")
    a(C("C-W4AR-CUMHOC", f"The water bodies with two or more bathing stations number "
        f"{ch['n_areas']}, and a correlation can be computed across them - across management "
        "units, each weighted alike whatever its size or number of stations. That is not an "
        "effect of anything.") + " "
      + C("C-AR-CUMHOC-DESIGN", "This sets bathing-water quality against sewage pressure — "
          "outfall, treatment-plant and basin density per km² — because both sides of that "
          "pair exist per area. It is **cum hoc**: a correlation across places at one time, "
          "with no control for coast type, flushing, or population.") + "\n")
    a(C("C-W4AR-CUMHOC-R", "One pairing is traced end to end: the share of station-years "
        "classed below \"Excellent\" against approved treatment-plant capacity per km² of "
        f"water body, log-scaled, **r = {t['r']:+.3f}** across the {t['n']} water bodies. The "
        "other pairings, computed the same way, are in the downloadable file.") + " "
      + C("C-W4AR-POOLING", f"The bathing labels change in {new['from']}: to {old['to']} the "
          f"file has \"Good or Sufficient\", from {new['from']} \"Good\" and \"Sufficient\" "
          "apart, and the share pools both. On each period alone the same correlation is "
          f"{t_old['r']:+.3f} for {old['from']}–{old['to']} and {t_new['r']:+.3f} for "
          f"{new['from']}–{new['to']}: weaker under the newer labels.") + "\n")
    a(C("C-W4AR-RERUNS", "How r was made - the records it rests on in their own words, each "
        "step with its code and the reason given for it, and where each branch ends - is in "
        "its \"How it was made\" view: open the number's menu. Reruns there each change one "
        f"choice, and move r between {min(rv):+.3f} and {max(rv):+.3f}.") + "\n")

    a("## What this is not\n")
    a(C("C-W4AR-NOT", "This page is not a causal model, and a water body is not the unit a "
        "cause is found in: water bodies are where responsibility sits, and the stations' "
        "co-movement draws a different map. A cause would show as stations moving together "
        "along its line; no causal line has yet been tested that way here."))
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
