#!/usr/bin/env python3
"""docs/AREAS.md - there is no Denmark.

Written from data/derived/areas.json (scripts/areas.py) and read back with its
chains, so every number on the page links to the field it came from. The station
facts - the Roskilde Fjord spread and how long each water body's longest station
series runs - come from data/derived/station_places.json; the partition scores
from docs/data/areas/partition_score.json; the size of ODA's station register from
docs/data/areas/stations.json. Figures from other people's documents are read from
their pinned text. Every assertion is a checked claim registered in
data/manual/claims.d/w1-ar.json, and what could not be justified is retired to
ARCHIVE.md. See LIVE_NUMBERS.md, sections 2 and 11.

    python3 scripts/pages/areas.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import DERIVED, MANUAL, ROOT, log, read_json, write_doc
import claims
import live
import refs

OUT = os.path.join(ROOT, "docs", "AREAS.md")
AREAS = os.path.join(DERIVED, "areas.json")
SP = os.path.join(DERIVED, "station_places.json")
PS = os.path.join(ROOT, "docs", "data", "areas", "partition_score.json")
REG = os.path.join(ROOT, "docs", "data", "areas", "stations.json")
B, E, C = live.claim_begin, live.CLAIM_END, live.claim


def refify(text):
    """Text from a data file, with register IDs made checked references and an
    open-problem item number written as the identifier it is."""
    text = re.sub(r"open problem (\d+)", r"open problem `\1`", text)
    reg = refs.registry()
    return refs.TOKEN.sub(lambda m: live.ref(m.group(1)) if m.group(1) in reg
                          else m.group(0), text)


def share(part, whole):
    return live.step("K-SUBSET-SHARE", part / whole * 100)


def main():
    A = live.live_json(AREAS)
    rec, ch, sm = A["areas"], A["cum_hoc"], A["summary"]
    hz, sets = A["hazardous_layer"], sm["sets"]
    sea = sm["sea_km2"]
    sp = live.live_json(SP)
    cov, rosk = sp["coverage"], sp["roskilde"]
    ps = live.live_json(PS)
    reg = live.live_json(REG)
    lines = {int(x["min_years"]): x for x in cov["lacking_long_station"]}
    long_line = lines[max(lines)]
    nei = sets["neither"]
    # other people's figures, read from their pinned documents
    cd = claims.load()[0]
    cache = {}

    def read(ph):
        return claims.resolve(cd, ph, cache)[0]
    agri = read("{read:DANVA-2024:69.6|hvor landbruget alene står for 69,6 %}")
    every = read("{read:DHI-MODEL-DEL1-2015:119|For hvert af de 119 vandområder}")
    crit = read("{read:DCE-STATMOD-2015:4|koncentrationen af ilt i vandet er under 4 mg/L}")

    o = []
    a = o.append
    a("# There is no Denmark\n")
    a("*Generated by `scripts/pages/areas.py` from `data/derived/areas.json`.*\n")
    a(B("C-AR-AGG") + "The national argument is made in aggregates: one land-borne load, and one "
      f"share of it for agriculture - {agri}% in the figure DANVA cites from Miljøstyrelsen "
      "and Aarhus University. Aggregation is where the information goes: a figure true of "
      "Denmark need not hold for any one water body inside it." + E + "\n")
    a(C("C-AR-SCOPE", "This page refuses the aggregate. One record per marine water body: what "
        "presses on it, what is observed in it, **over which years each of those streams "
        "exists**, and what cannot be modelled there.") + "\n")
    a(B("C-AR-ASSIGN") + "Assignment is by nearest point on the marine boundary, one rule for "
      "every layer, with the largest distance kept for each layer in each area and anything "
      f"beyond {A['assignment']['max_km']:.0f} km dropped." + E + "\n")

    a("## The state of knowledge, counted\n")
    a("| | areas | km² | share of sea |")
    a("|---|---:|---:|---:|")
    for lab, key in (("All marine water bodies in the national marine layer", "all"),
                     ("…with a DHI statistical model (see below)", "modelled"),
                     ("…with bathing-water stations, repeated over years", "with_bathing"),
                     ("…with three or more informative bathing stations", "testable"),
                     ("…with neither the flag nor a bathing station", "neither")):
        s = sets[key]
        a(f"| {lab} | {s['n']} | {s['km2']:,.0f} | {share(s['km2'], sea):.1f}% |")
    a("")
    a(B("C-AR-MODEL-MATCH") + "**The model flag follows DHI's list.** A water body counts as "
      "modelled when DHI's 2015 method report lists it among the water bodies with a "
      "station-level statistical model, matched to this layer by DHI's water-body number, "
      "with every name read against the layer's own (`data/manual/statistical_models.json`). "
      "One of DHI's models covers five Limfjord bredninger together, so all five are counted; "
      "one water body it lists, Randers Fjord's Grund Fjord, is not in the marine layer used "
      "here." + E + "\n")
    a(B("C-AR-NEITHER") + f"Counted with that flag, {nei['n']} water bodies covering "
      f"{nei['km2']:,.0f} km² ({share(nei['km2'], sea):.0f}% of Danish sea) carry neither the "
      "flag nor a repeated observation **in the two layers counted here** — bathing water, "
      "and the hazardous-substance layer, which holds no marine point." + E + " "
      + C("C-AR-REQUIREMENT", "A requirement does not wait for either: in the method behind "
          f"the second water plans, every one of its {every} water bodies was given an "
          "indsatsbehov, whether it had a statistical model or not.") + "\n")

    a("## What an absence can be counted over\n")
    a(C("C-AR-ABSENCE-RULE", "**A claim of absence is only as wide as the search behind it**, "
        "and this search was two layers deep.") + "\n")
    a(B("C-AR-REGISTER") + f"ODA's station register holds **{reg['n']:,} positioned marine "
      "stations**." + E + " " + B("C-AR-SERIES-COVERAGE") + "The part of it this page can "
      "place in water bodies is the station series behind the partition tests below — "
      f"{cov['series_stations']:,} stations with a monthly record, {cov['stations_inside']:,} "
      f"of them inside a water body by point in polygon — and **{cov['waterbodies_with_station']} "
      f"of the {cov['waterbodies']} water bodies contain at least one of those.** Counted over "
      "that series: " + ", ".join(
          f"{x['waterbodies']} water bodies contain no station with data in "
          f"{x['min_years']} or more distinct years" for x in cov["lacking_long_station"])
      + "." + E + "\n")
    a(B("C-AR-NOT-PERCENT") + "**Those are counts, and they are deliberately not "
      f"percentages.** Saying *{share(long_line['km2'], sea):.0f}% of the sea has no long "
      "observation* would be the missing-denominator error this project exists to point at. "
      f"The denominator is known — the sea is {sea:,.0f} km². The numerator is not, because it "
      "is the extent of an absence, and an absence can only be measured against a search that "
      "was exhaustive. Ours was ODA plus two layers; ICES and EMODnet sit outside it, and so "
      "does whatever university, municipal or unpublished series exist." + E + "\n")
    a("The test is whether **the category named is the same width as the corpus searched.**\n")
    a("- " + B("C-AR-SAME-WIDTH") + "**Same width — an exact statement is fine, including of "
      f"an absence.** *None of the {sets['all']['n']} water bodies has a marine point in the "
      f"national hazardous-substance layer: its {hz['points']} points are {hz['lake']} lake "
      f"and {hz['river']} river.* The category is that layer and the count is of all of it, "
      "so its complement is exact." + E)
    a("- " + B("C-AR-WIDER") + "**Category wider than corpus — only a count is honest.** "
      f"*{share(nei['km2'], sea):.0f}% of the sea has no marine observation* would name a "
      "category — marine observation — far wider than the two layers actually searched, and "
      "report the leftover after subtracting what we happened to find as though it were "
      "measured, which is the operation [RESIDUAL.md](RESIDUAL.md) is about." + E + "\n")
    a(C("C-AR-NAMED-CORPUS", "So absence is reported here as a count over a named corpus, "
        "and the corpus is named every time.") + "\n")
    a(B("C-AR-GAPS") + "**And the corpus is named together with what is missing from it.** A "
      "coverage figure has a numerator nobody can measure — the evidence that exists — so "
      "counting what we assembled gives a *lower bound on evidence* and therefore an *upper "
      "bound on absence*. That is only interpretable beside the terms we know belong in the "
      "numerator and cannot add. They are kept in `data/manual/coverage_gaps.json`, a "
      "hand-kept record, in three kinds:" + E + "\n")
    a("| | source | what it would add | why we do not have it |")
    a("|---|---|---|---|")
    for g in read_json(os.path.join(MANUAL, "coverage_gaps.json"))["gaps"]:
        a(f"| `{g['class']}` | **{g['id']}** | {refify(g['would_add'])} | "
          f"{refify(g['barrier'])} |")
    a("")
    a(B("C-AR-GAP-CLASSES") + "The distinction inside that table matters as much as the "
      "table. `closed` is a gap in the world's availability; `open_unassembled` is a gap in "
      "our effort and is nobody's fault but ours; `absent` is the only one where a search was "
      "run to the end, and even that is bounded by the search." + E + " " + B("C-AR-PULS")
      + f"**PULS is the sharpest case.** It holds the per-event overflow volumes that "
      f"{live.ref('B1')} calls the single most valuable missing series — volumes that are "
      "themselves largely modelled, by this project's source register — and an access "
      "attempt with a private MitID was refused because no CVR or VAT number attached to it "
      "was valid, so this is not a login anyone has neglected to perform. Access appears to "
      "require a registered business or authority, in which case a private citizen cannot "
      "obtain it." + E + "\n")

    a("## Two meanings of \"a body of water\", and the switch between them\n")
    a(B("C-AR-ENCLOSURE") + "\"Roskilde Fjord\" is not an arbitrary line on a map, and it is "
      "worth saying so plainly before objecting to anything. It names a real hydrographic "
      "object: an inlet bounded by land that opens to the sea through Isefjorden. That is a "
      "**claim about enclosure**, it is physical, and it is true." + E + "\n")
    a(C("C-AR-HOMOGENEITY", "The assessment then uses the same word to mean something else "
        "entirely: that a measurement taken anywhere in it stands for the whole of it. That is "
        "a **claim about homogeneity**, and it is statistical. One sense is about where the "
        "water is bounded; the other is about whether the water inside those bounds is alike. "
        "Nothing carries you from the first to the second, and the name does the carrying "
        "unnoticed because the same three words serve both.") + "\n")
    a(B("C-AR-PHYSICS") + "**And where exchange is restricted, the physics runs against the "
      "transfer, not with it.** Restricted exchange is what *preserves* a gradient. A basin "
      "with freshwater entering at its head and little exchange at its mouth holds salinity, "
      "residence-time and oxygen gradients along its length because it does not flush; open "
      "water erases such differences by mixing. So the better the enclosure, the weaker the "
      "homogeneity assumption becomes: the two senses **pull in opposite directions**, and the "
      "enclosures that most deserve their names are the ones least entitled to be treated as "
      "single units." + E + "\n")
    a(B("C-AR-TWO-UNITS") + "The partition half-concedes this without following it through. "
      f"Roskilde Fjord appears here as two water bodies, `DKCOAST1` (ydre, "
      f"{rec['DKCOAST1']['area_km2']:.0f} km²) and `DKCOAST2` (indre, "
      f"{rec['DKCOAST2']['area_km2']:.0f} km²) — an admission that one enclosure is at least "
      "two units." + E + " " + B("C-AR-SPLIT-UNSTATED") + "The documents this project holds "
      "give the general basis for water bodies' boundaries — the water framework directive "
      "asks member states to set them, and the plans sort coastal waters into types with a "
      "catchment each — but none of them says why this fjord is two units rather than one or "
      "three, or what measurement would settle it." + E + " " + B("C-AR-X22") + "A boundary "
      "drawn inside a fjord is a hypothesis about where the water changes, and it can be "
      "tested: `X22` in [EXPERIMENTS.md](EXPERIMENTS.md) sets out how, using pairs of "
      "measurements at matched separation either side of a line." + E + "\n")
    a("> " + C("C-AR-POSITION", "The practical rule that follows, and the reason the "
               "station-level series exist: **the unit of observation is a position.** "
               "Everything else — this page included — is an aggregate computed inside "
               "somebody's polygon, and should be read as a statement about that polygon as "
               "much as about the sea.") + "\n")

    a("### The switch, measured in the fjord it is named after\n")
    a(B("C-AR-ROSK-METHOD") + "The station-level series make this checkable rather than "
      "arguable. Both halves of Roskilde Fjord carry several stations, so for any month where "
      f"{rosk['min_stations']} or more measured, the disagreement *between* stations can be "
      "set against the variation *across* months. *Spread between stations* is the population "
      "standard deviation across the stations in a month, averaged over the months, beside the "
      "median range; *spread across months* is the standard deviation of the monthly means."
      + E + "\n")
    a(f"| variable | basket | months with {rosk['min_stations']}+ stations | spread between "
      "stations, same month | spread across months | ratio |")
    a("|---|---|---:|---:|---:|---:|")
    rows = list(rosk["rows"])
    best = {}
    for r in rows:
        k = str(r["variable"])
        if k not in best or r["ratio"] > best[k]["ratio"]:
            best[k] = r
    for r in rows:
        ratio = f"{r['ratio']:.2f}"
        if best[str(r["variable"])] is r:
            ratio = f"**{ratio}**"
        a(f"| {str(r['label']).lower()} {r['depth']} | {r['half']} `{r['waterbody']}` | "
          f"{r['months']} | sd {r['sd_between']:.2f}, median range "
          f"{r['range_between_median']:.2f} | {r['sd_across']:.2f} | {ratio} |")
    a("")

    def rr(var, wb):
        return next(r for r in rows if r["variable"] == var and r["waterbody"] == wb)
    oi, oy = rr("oxy_bed", "DKCOAST2"), rr("oxy_bed", "DKCOAST1")
    si, sy = rr("sal_surf", "DKCOAST2"), rr("sal_surf", "DKCOAST1")
    a(C("C-AR-ILTSVIND", f"In Denmark, oxygen below {crit} mg/L is called iltsvind.") + " "
      + B("C-AR-ROSK-OXY") + "**The inner fjord's own stations disagree about bottom oxygen by "
      f"a median of {oi['range_between_median']:.2f} mg/l within a single month.** "
      "A spread that size is most of the distance from zero to that "
      "threshold, so in a month when the fjord's bottom water is near it, one station can read "
      "below and another above — and whether that body \"has iltsvind\" can then depend on "
      "which of its own stations is read. The ratio puts it another way: the spread between "
      f"stations is **{oi['ratio'] * 100:.0f}% of the spread of the monthly means across "
      "months**." + E + "\n")
    a(B("C-AR-ROSK-HALVES") + "**And the two halves fail on different variables.** The inner "
      f"fjord's stations disagree for oxygen ({oi['ratio']:.2f}) and agree for salinity "
      f"({si['ratio']:.2f}); the outer fjord's are the reverse — close for oxygen "
      f"({oy['ratio']:.2f}), apart for salinity ({sy['ratio']:.2f}). Within this one fjord, a "
      "boundary drawn to serve one variable does not serve the other. That is one case, not a "
      "proof about every partition; it is the case `X22` would test systematically." + E + "\n")
    a(C("C-AR-ROSK-SOURCE", "Computed by `scripts/station_places.py` from "
        "`docs/data/areas/stations_series.*`, which carry no partition at all — the water-body "
        "assignment used here is loaded separately from `station_waterbody_overlay.json`, on "
        "purpose, so that using it is a deliberate act.") + "\n")

    a("## What are the baskets predictive FOR? — and how easily that question is "
      "answered wrongly\n")
    a(B("C-AR-PART-STAT") + "A partition is not right or wrong in general; it is predictive "
      "*for a variable*. So the question is what the water bodies encode. The statistic, "
      "computed within month by `scripts/partition_score.py`, is a **ratio of mean squares**: "
      "the between-basket mean square over the sum of the between- and within-basket mean "
      "squares. One means stations in the same basket agree completely. With labels that carry "
      "no information both mean squares estimate the same variance and the ratio sits near one "
      "half, not zero — so no value in the table below can be read on its own, only its "
      "difference from a null." + E + "\n")
    a(C("C-AR-WITHIN-MONTH", "Within month is essential. Every station in Denmark shares a "
        "season, so pooling across months puts the seasonal signal into the between-basket "
        "term and makes every partition look excellent, including an absurd one.") + "\n")
    a(C("C-AR-THREE-RANKINGS", "**The result depends almost entirely on what it is compared "
        "against, and three reasonable comparisons give three different rankings.**") + "\n")
    a("| variable | real | shuffled | latitude stripes | size- and shape-matched | "
      "**lift over the last** | spread of its three runs |")
    a("|---|---:|---:|---:|---:|---:|---:|")
    res = sorted(ps["results"], key=lambda r: -r["lift_over_compact"])
    top2 = {id(r) for r in res[:2]}
    for r in res:
        lift = f"{r['lift_over_compact']:+.3f}"
        if id(r) in top2 or r["lift_over_compact"] < 0:
            lift = f"**{lift}**"
        cmp_ = r["size_matched_compact"]
        a(f"| {str(r['depth']).replace('near the ', '')} {str(r['label']).lower()} | "
          f"{r['water_bodies']['icc']:.3f} | {r['shuffled']['icc']:.3f} | "
          f"{r['latitude_bands']['icc']:.3f} | {cmp_['icc']:.3f} | {lift} | "
          f"{cmp_['spread']:.3f} |")
    a("")
    a(B("C-AR-NULLS") + "The three nulls answer three different questions. **Shuffled** "
      "permutes station labels while keeping basket sizes, so it destroys geography and keeps "
      "the size structure. **Latitude stripes** are equal-count horizontal bands, as many as "
      "there are real baskets, so they keep compactness and equal sizes but ignore hydrography. "
      "**Size- and shape-matched** baskets have the same size distribution as the real ones "
      "and are grown from random seeds by nearest neighbour, three times over, so they are "
      "compact blobs of the right sizes following no hydrography at all — the only control "
      "that varies one thing at a time." + E + " " + C("C-AR-WINNERS", "Against the shuffle, "
                                                         "salinity gains most, by a distance; "
                                                         "against the stripes, surface oxygen "
                                                         "saturation does.") + "\n")
    sal = next(r for r in ps["results"] if r["variable"] == "sal_surf")
    osat = next(r for r in ps["results"] if r["variable"] == "oxysat_surf")
    flu = next(r for r in ps["results"] if r["variable"] == "fluo")
    a(B("C-AR-REVERSAL") + "Against the matched blobs the ordering **reverses**: surface "
      f"oxygen saturation gains most ({osat['lift_over_compact']:+.3f}), surface salinity "
      f"little ({sal['lift_over_compact']:+.3f}), and fluorescence's lift is below zero "
      f"({flu['lift_over_compact']:+.3f}) — but the three blob runs themselves spread by "
      f"{flu['size_matched_compact']['spread']:.3f} for fluorescence, so for it the official "
      "partition does no better than random compact blobs, and whether it does worse is not "
      "shown." + E + "\n")
    a(B("C-AR-READING") + "One reading fits these numbers, and it is not tested here: if "
      "salinity is spatially smooth, any compact grouping predicts it well "
      f"({sal['size_matched_compact']['icc']:.3f} from random blobs) and the real boundaries "
      "have little left to add; if oxygen is spatially rough, blobs do poorly and boundaries "
      "that follow enclosure carry real information." + E + " " + C("C-AR-LIFT-RULE", "A "
                                                                      "partition's value is "
                                                                      "not how well it "
                                                                      "predicts, but **how "
                                                                      "much better it predicts "
                                                                      "than its own shape "
                                                                      "alone would**.") + "\n")
    a("> " + C("C-AR-SAMPLED", "One further limit bounding every row: stations are not placed "
               "at random and are far denser in some baskets than others, so this scores the "
               "partition *as sampled*. It cannot distinguish a well-drawn basket from one "
               "whose stations happen to sit close together.") + "\n")

    a("## The cum hoc estimate, across areas instead of across years\n")
    a(B("C-AR-CUMHOC") + "A national time series has one unit of replication. The water "
      f"bodies with two or more bathing stations number {ch['n_areas']}, so an effect size can "
      "be estimated across them." + E + " " + B("C-AR-CUMHOC-DESIGN") + "This sets "
      "bathing-water quality against sewage pressure — outfall, treatment-plant and basin "
      "density per km² — because both sides of that pair exist per area. It is **cum hoc**: a "
      "correlation across places at one time, with no control for coast type, flushing, or "
      "population." + E + "\n")
    a("| predictor | outcome | r | $R^2$ | areas |")
    a("|---|---|---:|---:|---:|")
    for t in ch["tests"]:
        a(f"| `{t['predictor']}` | {t['outcome']} | {t['r']:+.3f} | {t['r2']:.3f} | "
          f"{t['n']} |")
    a("")

    a("## Every area, on its own terms\n")
    a(B("C-AR-TABLE-KEY") + "`model` — a DHI statistical model, as described above "
      "(DCE fitted its statistical models on 1990–2012). `bath` — bathing stations, and the "
      "years they span. `r` — the mean correlation between the yearly classes of a water "
      "body's informative bathing stations, where there are three or more. `RBU` — "
      "rain-conditioned outfalls. `PE` — approved treatment-plant load. `gaps` — the number of "
      "written-out reasons this area cannot be modelled." + E + "\n")
    a("| km² | area | model | bath (years) | r | RBU | PE | gaps |")
    a("|---:|---|:-:|---|---:|---:|---:|---:|")
    for r in sorted(rec.values(), key=lambda r: -r["area_km2"]):
        b = r["observation"].get("bathing")
        rbu = r["pressure"].get("rbu")
        rens = r["pressure"].get("rens")
        bath = f"{b['stations']} ({b['first_year']}–{b['last_year']})" if b else "—"
        rv = f"{b['internal_r']:+.2f}" if b and b.get("internal_r") is not None else "—"
        # an official name with a zone in it ("Anholt, 12 sm") is an identifier
        name = f"`{r['name']}`" if re.search(r"\d", str(r["name"])) else r["name"]
        a(f"| {r['area_km2']:,.1f} | {name} | "
          f"{'✓' if r['has_statistical_model'] else '·'} | {bath} | {rv} | "
          f"{format(rbu['n'], ',') if rbu else '—'} | "
          f"{format(rens['pe'], ',') if rens and rens.get('pe') else '—'} | {r['n_gaps']} |")
    a("")
    a(C("C-AR-RECORD", "The full record for each area — every pressure, every stream with its "
        "years, and the written-out list of what cannot be modelled there — is in "
        "`data/derived/areas.json`, which `scripts/areas.py` writes locally and the repository "
        "does not ship, and drawn with its timeline on [the map](areas.html).") + "\n")
    a("## What this is not\n")
    a(C("C-AR-NOT", "It is not a causal model per area. It is the ledger you need before you "
        "can build one: which areas have enough observation to support a claim, which have "
        "none, and over which years each stream exists — so that an analysis published in 2025 "
        "cannot quietly rest on a relation fitted to 1990–2012 without a reader seeing the "
        "gap."))
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
