#!/usr/bin/env python3
"""docs/CATEGORY.md - the category that was never measured.

Every number on it is checked: the partition scores are read from
docs/data/areas/partition_score.json, the size of the hypothesis register from
data/derived/hypotheses.json, other people's figures from their pinned documents,
and the one judgment threshold is stated as a choice with its reason. Every
assertion is a checked claim registered in data/manual/claims.d/w1-ar.json, and
what could not be justified is retired to ARCHIVE.md. See LIVE_NUMBERS.md,
sections 2 and 11.

    python3 scripts/pages/category.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import DERIVED, ROOT, log, write_doc
import claims
import live

OUT = os.path.join(ROOT, "docs", "CATEGORY.md")
PS = os.path.join(ROOT, "docs", "data", "areas", "partition_score.json")
HY = os.path.join(DERIVED, "hypotheses.json")
B, E, C = live.claim_begin, live.CLAIM_END, live.claim


def count(path, key):
    """The number of entries in a list field of a data file, as a live number."""
    return live.live(len(live.live_json(path)[key]), path, f"{key}.[len]")


def main():
    ps = live.live_json(PS)
    nvar = count(PS, "results")
    nhyp, ngrp = count(HY, "hypotheses"), count(HY, "groups")
    sat = next(r for r in ps["results"] if r["variable"] == "oxysat_surf")
    real = sat["water_bodies"]["icc"]
    split = live.stated("category_split_threshold", 12, "12",
                        "A judgment, not a derivation: with fewer independent features "
                        "than this, disjoint halves of the feature space are too small "
                        "to cluster on, and a shape-matched null is the stronger test.")
    cd = claims.load()[0]
    cache = {}

    def read(ph):
        return claims.resolve(cd, ph, cache)[0]
    within = read("{read:EDWARDS-2003:85|about 85% of the total genetical}")
    between = read("{read:EDWARDS-2003:15|only 15% to differences}")

    o = []
    w = o.append
    w("# The category that was never measured\n")
    w("Generated by `scripts/pages/category.py`. " + C("C-AR-CAT-COMPANION", "This is the "
      "companion to [RESIDUAL.md](RESIDUAL.md), and the same shape of mistake one column to the "
      "left. That page is about a *number* nobody measured being treated as one. This is about "
      "a *category* nobody measured being treated as one.") + "\n")
    w("You do not need to care about Denmark to use it.\n")
    w("---\n")
    w("## The tell\n")
    w(B("C-AR-TELL") + "Open the Danish marine monitoring archive this project holds. Its "
      "measured columns come with what a measurement comes with: a sonde serial number, a "
      "sampling instrument, an analysis method, a laboratory, a quality level, and a mark for a "
      "value below what the method could detect." + E + "\n")
    w("Now look at the categorical columns. Water body `DKCOAST2`. Citizenship `DK`. "
      "Sector `C10.51`. Diagnosis `E11.9`. Species *Fucus vesiculosus*. Land use "
      "`arable`.\n")
    w(B("C-AR-NO-ERRORBAR") + "**Not one of them has an error bar, and not one of them was "
      "measured.** Each is the output of a model — a polygon someone drew, a legal test someone "
      "applied, a classification someone wrote down — presented in the same table, in the same "
      "typeface, as the quantities that came off an instrument. The instrument reading is an "
      "observation with a known error. The category is a claim with an unstated one." + E + "\n")
    w("## What the category is actually doing\n")
    w(C("C-AR-TWO-THINGS", "Every basket carries two things that are easy to conflate, and the "
        "conflation is the whole problem:") + "\n")
    w("1. " + B("C-AR-MEMBERSHIP") + "**A membership rule.** Who is in. This is usually sound,\n"
      "   often precise, and frequently a genuine fact about the world. Roskilde Fjord really is\n"
      "   an enclosure. Danish citizenship really is a determinate legal status. A postcode\n"
      "   really is a postcode." + E + "\n"
      "2. " + B("C-AR-ATTRIBUTION") + "**An attribution.** What members are taken to share. "
      "This is a\n   *statistical* claim, and nothing in the membership rule establishes it."
      + E + "\n")
    w(C("C-AR-QUESTION", "The name serves both functions, so the switch between them goes "
        "unnoticed. Asking \"is this a real category?\" answers the first question and is "
        "almost always yes. The question that has content is different:") + "\n")
    w("> **Does membership predict the thing you are using it to predict — and does it\n"
      "> predict better than a same-shaped arbitrary grouping would?**\n")
    w("## The measurement\n")
    w(B("C-AR-ICC-FAMILY") + "There is a standard family of statistics for this: the "
      "**intraclass correlation** and its relatives. Pick two members of the population at "
      "random. If they are in the same basket, how much more alike are they than two picked "
      "without regard to basket? For the intraclass correlation, one means membership tells "
      "you everything and zero means it tells you nothing. The scores this project computes "
      "are a relative — a ratio of mean squares, on which no information reads near one half "
      "rather than zero — which is one more reason to read only their difference from a null."
      + E + "\n")
    w("Two things make it usable rather than decorative.\n")
    w(B("C-AR-CONDITION") + "**Condition on what everything shares.** Every marine station in "
      "Denmark experiences the same season. Pool across months and the seasonal signal lands "
      "in the between-basket term and *every* partition scores well — including a deliberately "
      "absurd one. The same applies wherever a common driver exists: compare within year, "
      "within cohort, within whatever the members hold in common regardless of basket." + E
      + "\n")
    w(B("C-AR-SHAPE-NULL") + "**Compare against a null that matches the basket's shape.** This "
      "is the part that gets skipped, and skipping it is how a defensible number comes out "
      "backwards." + E + "\n")
    w("## The statistic is a model too, and on its own it is circular\n")
    w(C("C-AR-DEFECT", "The measurement above has a defect that has to be stated before the "
        "worked example, because it applies to every number on this page.") + "\n")
    w(B("C-AR-FST-CIRCLE") + "**The intraclass correlation takes the partition as an input.** "
      "So does $F_{\\mathrm{ST}}$, a statistic of the same family in population-genetics "
      "clothing: $F_{\\mathrm{ST}} = (H_T - H_S)/H_T$, and $H_S$ — the variation *within "
      "subpopulations* — cannot be computed until the subpopulations have been declared. "
      "Citing an $F_{\\mathrm{ST}}$ value as evidence that populations are distinct therefore "
      "assumes what it sets out to show, unless it is set against what partitions not chosen "
      "to be real would give." + E + "\n")
    w(B("C-AR-SAMPLING") + "The partition can come from the **sampling design** itself. "
      "Collect fifty Danes and fifty Dutch and \"Danish\" and \"Dutch\" are your groups by "
      "construction; the statistic then reports on a boundary the fieldwork drew." + E + " "
      + B("C-AR-ESTIMATORS") + "Nor is it one statistic. After Wright's, papers gave differing "
      "definitions and estimators, and published estimates for the same pairs of populations "
      "have moved more than twofold with the estimation method, the way estimates are combined "
      "across loci and the choice of loci. It is an aggregation function over a chosen metric, "
      "presented as an observable." + E + "\n")
    w(C("C-AR-RESCUE", "**This is why the null is not optional: without it the measurement "
        "cannot even show that the grouping beats noise - and beating noise is still not a "
        "shared cause.**") + "\n")
    w(B("C-AR-DIFFERENCE") + "Compared against a *shape-matched null*, a circular statistic at "
      "least stops rewarding a partition for its shape: the **difference** says how far the "
      "chosen partition sits above noise of the same shape. That is a floor, not a test that "
      "its members share a cause - a random basket shares none, so beating it shows only that "
      "the grouping beats noise (statistical-methods, section 6b). It is also "
      "why a single reported value — a bare $F_{\\mathrm{ST}}$, a bare intraclass correlation, "
      "a bare $R^2$ between groups — cannot by itself say whether the groups are anything."
      + E + "\n")
    w("## Three nulls, three answers — a worked example\n")
    w(f"Denmark's marine water bodies, scored for {nvar} measured variables, within "
      "month:\n")
    w("| null | what it holds fixed | what it destroys | which variable gains most |")
    w("|---|---|---|---|")
    w("| shuffled labels | basket sizes | geography entirely | salinity, by a distance |")
    w("| latitude stripes | compactness, equal sizes | hydrography | surface oxygen "
      "saturation |")
    w("| size- and shape-matched blobs | **both** sizes and compactness | hydrography only "
      "| surface oxygen saturation |")
    w("")
    w(B("C-AR-WINNERS") + "The winners are read from the scores, and the first two disagree, "
      "not marginally: surface oxygen saturation gains "
      f"**{real - sat['shuffled']['icc']:+.3f}** over the shuffle and "
      f"**{real - sat['latitude_bands']['icc']:+.3f}** over the stripes, while against the "
      "shuffle salinity gains most." + E + " " + B("C-AR-REVERSAL") + "Only the third varies "
      "one thing at a time, and against it the ordering from the first **reverses** — oxygen "
      "saturation gains most, salinity little — and fluorescence's lift is below zero but "
      "inside the spread of the three blob runs, so for fluorescence the official partition "
      "does no better than random compact blobs." + E + "\n")
    w("The reading that survives is not about which variable matters:\n")
    w("> " + C("C-AR-LIFT-RULE", "**Beating its own shape is the least a partition must do: a "
               "grouping that predicts no better than random groups of the same shape adds nothing "
               "to its outline. Beating them is a floor, not proof that its members share a "
               "cause.**") + "\n")
    w(C("C-AR-READING", "A reading was offered here: if salinity is spatially smooth, *any* "
        "compact grouping predicts it and real boundaries add little, while boundaries that "
        "follow enclosure carry information about oxygen. The co-movement test on "
        "[AREAS.md](AREAS.md) does not bear it out: at matched distance the water-body lines add "
        "about as much for salinity as for bed oxygen, so they follow water masses rather than "
        "separating an oxygen process.") + "\n")
    w("## Two methods, and the condition that chooses between them\n")
    w(C("C-AR-NULL-LIMIT", "The null comparison above is not the strongest test available. It "
        "is the strongest test available *when the feature space is small*.") + "\n")
    w(C("C-AR-NULL-CONDITIONED", "A null answers: **given these measurements, does this "
        "grouping beat chance?** The answer is still conditioned on which measurements were "
        "taken, so it cannot separate a property of the entities from an artifact of what "
        "someone chose to record.") + "\n")
    w("There is a test that can, and it assumes no partition at all:\n")
    w("> Cluster the entities using a **random subset** of the measured features.\n"
      "> Cluster them again using a **disjoint** random subset.\n"
      "> Ask how much the two agree — and whether agreement **rises** as the subsets "
      "grow.\n")
    w(C("C-AR-SPLIT-TEST", "A grouping that appears only when one particular measurement is "
        "included is an artifact of that measurement. A grouping that appears whichever "
        "features are drawn is a property of the entities. Convergence as the subsets widen is "
        "the signal; flat agreement near chance means there is nothing to converge on. The "
        "official partition is then scored on the same axis — its agreement with each "
        "derivation — so it is one candidate among them rather than the standard they are "
        "marked against.") + "\n")
    w(C("C-AR-SMALL-SPACE", "A feature space of three or four measurements cannot be split "
        "into disjoint halves: there is nothing to hold out, and a null is the only test "
        "available.") + " " + C("C-AR-WHERE-MANY", "Where many measurements accumulate on the "
                                "same entities, the stronger test is available and the weaker "
                                "one is a habit.") + "\n")
    w(B("C-AR-THRESHOLD") + f"**So the rule is a threshold, not a preference.** Below {split} "
      "independent features — a judgment, stated as one — use a shape-matched null and accept "
      "that it cannot distinguish the entities from the instrument. Above that, split the "
      "feature space, because you can." + E + "\n")
    w("*" + B("C-AR-OWN-EXAMPLE") + f"This page's own worked example sits below that threshold — "
      f"{nvar} variables, so {nvar // 2} per half, and far from independent: oxygen and its "
      "saturation, the same quantity at two depths — which is why the marine result is "
      "suggestive only. The method wants a case with dozens of characters per entity, which "
      "is what `../organism` exists to try." + E + "*\n")
    w("## You have read this category in other clothes\n")
    w("One line each, with no claim that any is wrong — only that each has a membership rule "
      "doing one job and an attribution doing another:\n")
    w("- " + B("C-AR-CITIZENSHIP") + "**Citizenship.** A legal status, acquired by the routes a\n"
      "  country's law sets out. It can be used as a proxy for population, culture, ancestry,\n"
      "  or behaviour — none of which the membership rule tracks. The rule is *legal*; the\n"
      "  attribution is *biological or cultural*." + E + "\n"
      "- " + B("C-AR-RACE") + "**Race.** A dispute in the literature turns on exactly this\n"
      f"  statistic. By Edwards's account it is often stated, after Lewontin in 1972, that about\n"
      f"  {within}% of human genetic variation lies within populations and only {between}%\n"
      "  between them. Edwards (2003) replied that the information distinguishing populations\n"
      "  lies in the correlations between loci, so classification can be accurate anyway — the\n"
      "  shape of the compact-null finding above, where compact groupings of a smooth field\n"
      "  score well wherever they are cut. Rosenberg et al. (2002) found clusters without using\n"
      "  the individuals' origins; Serre & Pääbo (2004), sampling individuals homogeneously\n"
      "  across the globe, found gradients rather than discrete clusters. Sampling design,\n"
      "  again." + E + "\n"
      "- " + B("C-AR-SPECIES") + "**Species.** Species concepts agree that a species is a\n"
      "  separately evolving lineage but disagree about which further property makes one —\n"
      "  reproductive isolation, diagnosability, monophyly — so the same organisms can be\n"
      "  sorted differently. Which concept to use is argued over; which one predicts a given\n"
      "  trait is a question with an answer." + E + "\n"
      "- " + B("C-AR-SECTOR") + "**Industrial sector** (SIC, NACE). A code attached to each\n"
      "  firm from a classification; productivity and emissions can then be compared \"within\n"
      "  sector\"." + E + "\n"
      "- " + B("C-AR-ICD") + "**Diagnosis codes.** For more than a century the basis for\n"
      "  comparable statistics on causes of death and disease, and now also used for\n"
      "  resource allocation and reimbursement — a membership rule built for counting, used\n"
      "  to stand for a condition." + E + "\n"
      "- " + B("C-AR-POSTCODE") + "**Deprivation by postcode.** An area statistic attributed to\n"
      "  the individuals in it — which is the ecological fallacy, and the same error\n"
      "  [AREAS.md](AREAS.md) reports for Denmark." + E + "\n")
    w("## What to demand instead\n")
    w("Three questions, and they are cheap:\n")
    w("1. **What is the membership rule?** Say it out loud. Legal, geometric,\n"
      "   administrative, self-reported?\n"
      "2. **What is being attributed to members?** And is that the same kind of thing as\n"
      "   the rule?\n"
      "3. **What is the lift over a same-shaped null?** Not the raw statistic — the raw\n"
      "   statistic took the category as an input and cannot testify about it. The lift.\n")
    w(C("C-AR-DEMAND", "If the answer to the third is unknown, the category is being used as "
        "data when it is a model, and any figure computed inside it is a statement about the "
        "basket at least as much as about the world.") + "\n")
    w("---\n")
    w("*Companion pages: [RESIDUAL.md](RESIDUAL.md) for the same error committed on a "
      "number, [AREAS.md](AREAS.md) for the measured Danish case, `X22` in "
      "[EXPERIMENTS.md](EXPERIMENTS.md) for the test that would settle it here. And the "
      "obvious self-application: " + B("C-AR-SELF-APPLY") + f"this project sorts {nhyp} "
      f"mechanisms into {ngrp} groups, which is a partition it has not scored either." + E
      + "*")
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
