#!/usr/bin/env python3
"""docs/DATA_SOURCES.md - what is public, what is not, and what each source is good for.

A catalogue is where typed numbers go stale quietly: a layer gains features, a file is
re-fetched, a count done once by hand stays on the page. Here every count is read from
the fetch manifest or a derived file: data/derived/ds_facts.json counts the traps in
the ODA extracts over every row, data/derived/ds_probes.json records what each service
answered and when, and what other people's documents say is read from their pinned
text. Every assertion is a checked claim (data/manual/claims.d/w1-ds.json); what could
not be justified was retired to docs/ARCHIVE.md, not kept.

    python3 scripts/pages/data_sources.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from common import DERIVED, MANUAL, RAW, ROOT, log, write_doc
import claims as _claims
import live

OUT = os.path.join(ROOT, "docs", "DATA_SOURCES.md")
SHEET_NAMES = {"amager": "Amager", "bispebjerg": "Bispebjerg", "indre-by": "Indre By",
               "kbhvest": "KBH Vest", "ladegaardsaaen": "Ladegårdsåen", "norrebro": "Nørrebro",
               "osterbro": "Østerbro"}
CATEGORY_NAMES = {"afloebssystem": "afløbssystem", "renseanlaeg": "renseanlæg"}
TA = "https://ecos.au.dk/fileadmin/ecos/Fagdatacentre/Marin/TA_NOVA_1998/Kap0{}.doc"
DP02 = "https://mst.dk/media/bnkdidho/dta-dp02-rbu-version-4-2024.pdf"
# Phrases located in pinned documents. The technical instruction's .doc text was
# pinned with its Danish letters already lost upstream, so those phrases carry the
# replacement character exactly as the pin does.
READ = {
    "dp_bi5": "{read:DTA-DP02-2024:30|BI5 25 160 30}",
    "dp_cod": "{read:DTA-DP02-2024:180|COD 160 320 180}",
    "dp_n": "{read:DTA-DP02-2024:12|Tot-N 10 43 12}",
    "dp_p": "{read:DTA-DP02-2024:2.0|Tot-P 1,8 7 2,0}",
    "ler_hours": "{read:LER-GRAVE:2|Ledningsejere har 2 timer til at besvare}",
    "k4_depth": "{read:TA-NOVA-1998-K4:1|Winkler-m�lingen i 1 m dybde benyttes til kalibrering}",
    "k4_limit": "{read:TA-NOVA-1998-K4:0.3|st�rre end 0,3 mg O2/l}",
    "k5_010": "{read:TA-NOVA-1998-K5:0–10|Integreret pr�ve fra 0-10 m dybde}",
    "k5_025": "{read:TA-NOVA-1998-K5:0–25|dybdeintervallet 0-25 m}",
    "k1_faktor": "{count:TA-NOVA-1998-K1:faktor}",
    "flood_event": "{read:FLOOD2012-AMAGER:100|ved en 100 års hændelse i 2010}",
    "flood_licence": "{read:FLOOD2012-CKAN:4.0|Creative Commons Attribution 4.0}",
}


def J(*p):
    return live.live_json(os.path.join(*p))


def main():
    meta, man = J(DERIVED, "meta_facts.json"), J(RAW, "_manifest.json")
    en, cc = J(DERIVED, "enums.json"), J(DERIVED, "clock_convention.json")
    of, dc = J(DERIVED, "outfalls.json"), J(DERIVED, "depth_clock.json")
    sheets, ext = J(DERIVED, "floodmaps", "_sheets.json"), J(DERIVED, "floodmaps", "_extract.json")
    F, P = J(DERIVED, "ds_facts.json"), J(DERIVED, "ds_probes.json")
    chem, C, CB, CE = live.chem, live.claim, live.claim_begin, live.CLAIM_END
    cd, _, _ = _claims.load()
    cache = {}
    R = {k: _claims.resolve(cd, v, cache)[0] for k, v in READ.items()}
    checked = P["checked"]

    def feat(layer):
        return next(m["features"] for m in man if m["layer"] == layer)

    o = []

    def w(s=""):
        o.append(s)

    w("# Data sources for Copenhagen's water system")
    w()
    w(CB("C-DS-INTRO") + "What is public, what needs an account, what does not exist in open form, and what")
    w("each thing is good for. Everything marked **fetched** is pulled by the scripts in `scripts/`")
    w("and lands in `data/raw/`. Generated by `scripts/pages/data_sources.py`: every count is read")
    w("from the fetch manifest or a derived file, and every statement opens what it rests on." + CE)
    w()
    # ------------------------------------------------------------------ 1
    kb, www = P["kbhkort_wfs"], P["opendata_www_api"]
    w("## 1. Københavns Kommune — Kbhkort WFS  *(fetched)*")
    w()
    w(CB("C-DS-KBH-SERVER") + f"`https://wfs-kbhkort.kk.dk/k101/ows` answered an anonymous capabilities request on")
    w(f"{checked} with {kb['layers']} layers." + CE + " " + CB("C-DS-CKAN") + "The city's CKAN catalogue answers at")
    w("`https://admin.opendata.dk/api/3/action/package_search?q=organization:city-of-copenhagen`;")
    w(f"the same path on `www.opendata.dk` answered `{int(www['status'])}`." + CE)
    w()
    w(CB("C-DS-KBH-FETCHED") + "Layer names come from `?service=WFS&version=1.1.0&request=GetCapabilities`.")
    w(f"The {meta['kbhkort_layers_fetched']} this project fetches are listed, with their feature counts and")
    w("properties, in `data/raw/_manifest.json`." + CE)
    w()
    w(C("C-DS-KBH-TABLE", "What each fetched layer is, from the title, note and properties the fetch "
        "records for it, and why it matters here:"))
    w()
    w("| Layer | What it is | Why it matters |")
    w("|---|---|---|")
    w(f"| `sp_kloakoplande` | {feat('sp_kloakoplande')} sewer catchments | The backbone. Tells you whether a block is **fælleskloakeret** (combined — sewage and rain in one pipe, so heavy rain means sewage overflow) or **separatkloakeret**, plus the receiving treatment plant and impervious fraction. |")
    w(f"| `skp_bassiner_pladser_kk` | {feat('skp_bassiner_pladser_kk')} cloudburst basins and retention squares | Planned storage. Carries `klima_id`. |")
    w(f"| `skp_veje_tunneller_kk` | {feat('skp_veje_tunneller_kk')} cloudburst roads, pipes, tunnels | Alignments including the skybrudsledninger. Carries `klima_id`. |")
    w(f"| `skp_skybrudsoplande` / `skp_deloplande` | {feat('skp_skybrudsoplande')} catchments / {feat('skp_deloplande')} sub-catchments | The organising unit of the whole cloudburst plan. |")
    w(f"| `skp_terraenaend` | {feat('skp_terraenaend')} planned terrain modifications | Where the street surface itself is reshaped to steer water. |")
    w(f"| `skp_igangsatte_prj_kk` / `skp_afsluttede_prj_kk` | {feat('skp_igangsatte_prj_kk')} in progress / {feat('skp_afsluttede_prj_kk')} completed | Build status. Both carry the key (`klima_id`, and `klimaid` on the completed layer — note the spelling difference). |")
    w(f"| `lar_registreringer` | {feat('lar_registreringer')} local infiltration installations | The decentralised half of the rainwater story. |")
    w(f"| `dp_regnvandsafledning_p/l/f` | {feat('dp_regnvandsafledning_p')} points, {feat('dp_regnvandsafledning_l')} lines, {feat('dp_regnvandsafledning_f')} polygons | Surface conveyance in public space: gullies, swales, channels. |")
    w("| `grundvand_pejlinger_2021`, `grundvand_potentialelinjer_2021`, `terraen_minus_gvs` | Groundwater observations, contours, depth-to-water | The practical ceiling on how deep anything can be dug. |")
    w("| `vand_oversigtskort`, `havn`, `kbh_kysttyper` | Lakes, watercourses, harbour, coast | Where the invisible system finally discharges. |")
    w(f"| `hmax263_dige`, `hmax285_dige` | Storm-surge dike lines, named for two maximum water levels; the features carry only a grid code, no height | {meta['dike_raw_mb']:.0f} MB of the {meta['kbhkort_raw_mb']:.0f} MB fetched from this server. Coastal flooding, not rainfall — peripheral to this project. |")
    w()
    w(C("C-DS-AXIS", "**Gotcha:** asked in WFS `1.0.0` this server returns `EPSG:4326` as `[lon, lat]`, "
        "and `1.1.0` flips the axis order. `scripts/common.py` detects which arrived rather than "
        "trusting either."))
    w()
    # ------------------------------------------------------------------ 2
    vp = P["vp3_wfs"]
    w("## 2. Miljøstyrelsen MiljøGIS — Vandområdeplan (VP3) basisanalyse  *(fetched)*")
    w()
    w(CB("C-DS-VP3-SERVER") + "`https://wfs2-miljoegis.mim.dk/vp3basis2019/ows` — national; it answered an")
    w(f"anonymous capabilities request on {checked} with {vp['layers']} layers." + CE)
    w()
    w(C("C-DS-VP3-WHAT", "This is the **discharge end** of the system: the points where rain-dependent "
        "overflows and outfalls, treatment plants, industry and scattered dwellings release water."))
    w()
    w(C("C-DS-VP3-TABLE", "What each layer holds within metro Copenhagen, from the features the fetch "
        "kept and the properties it records:"))
    w()
    w("| Layer | Metro Copenhagen | Notes |")
    w("|---|---|---|")
    w(f"| `vp3_basis_2019_punkt_rbu_udl` | **{meta['vp3_rbu_points']} points** ({meta['vp3_rbu_kobenhavn']} in København) | Rain-dependent discharges: combined sewer overflow structures and stormwater outfalls. `bgv_type` gives the structure type, `vol_sb` the attached basin volume in m³. {meta['vp3_rbu_with_volume']} points carry a volume, totalling **{meta['vp3_rbu_volume_m3']:,} m³**. |")
    w(f"| `vp3_basis_2019_punkt_rens_udl` | {feat('vp3_basis_2019_punkt_rens_udl')} | Treatment plants. `godk_pe` = approved capacity in person-equivalents. |")
    w(f"| `vp3_basis_2019_punkt_ind_udl` | {feat('vp3_basis_2019_punkt_ind_udl')} | Industrial discharges. |")
    w(f"| `vp3_basis_2019_punkt_spredt_udl` | {feat('vp3_basis_2019_punkt_spredt_udl')} | Scattered dwellings — mostly peri-urban. |")
    w(f"| `vp3basis2019_badevand` | {feat('vp3basis2019_badevand')} | Bathing water stations: the public-health consequence, useful for sanity-checking overflow claims. |")
    w()
    w(C("C-DS-CLIP", "Layers here are national, so `fetch_wfs.py` clips them — by `komm_navn` where "
        "that column exists, otherwise by bounding box; the layers without a municipality column "
        "would come back empty without the bounding-box fallback."))
    w()
    w(CB("C-DS-BGV") + "**`bgv_type` decoding** is in `data/manual/codelists.json`, from Miljøstyrelsen's")
    w(f"[Datateknisk anvisning DP02 v4 (2024)]({DP02}). Its table of the data PULS requires for")
    w("combined-sewer overflows defines `OV`, `OS`, `OF`, `OK`, `Bypass` and `Skybrud`; its list for")
    w("separate-sewer outfalls defines `SE` (separate rainwater) and `SF` (separate rainwater with a")
    w(f"detention basin), which make up {meta['vp3_rbu_se_sf']} of our {meta['vp3_rbu_points']} points." + CE)
    w()
    w(CB("C-DS-TYPETAL") + "The same document's table 1 gives the concentrations to assume for overflow")
    w(f"water ({chem('BI5')} {R['dp_bi5']}, COD {R['dp_cod']}, Tot-N {R['dp_n']}, Tot-P {R['dp_p']} mg/l),")
    w("type values derived from monitoring of water from combined systems — which is how a volume")
    w("becomes a load." + CE)
    w()
    # ------------------------------------------------------------------ 3
    cats = meta["plan_categories"]
    w("## 3. Spildevandsplan 2018 project register — planer.kk.dk  *(fetched)*")
    w()
    w(C("C-DS-PLAN-PAGES", f"`https://planer.kk.dk/spildevandsplan-2018/projekter/` — {meta['plan_pages']} "
        "project pages, enumerable from `https://planer.kk.dk/sitemap.xml`. Categories: "
        + ", ".join(f"{CATEGORY_NAMES.get(k, k)} ({cats[k]})" for k in cats.keys()) + "."))
    w()
    w(CB("C-DS-PLAN-PARSE") + "This is the prose record of each project in the plan: purpose, dimensions,")
    w("stated volumes, ownership, and the affected land parcels by matrikel number.")
    w("`fetch_plan_projects.py` parses it into structured JSON and pulls out stated quantities with the")
    w("sentence each came from, so a human can judge the figure." + CE)
    w()
    w(CB("C-DS-JOIN") + "**The join problem.** Copenhagen keys these two worlds differently, and neither")
    w("source carries a mapping between them:" + CE)
    w()
    w("* plan pages use a plan number — `A1.14`, `K1.57`")
    w("* the map layers use a cloudburst number — `klima_id`: `BIR7.5`, `KV86`, `VEL45`")
    w()
    w(CB("C-DS-RECOVER") + "The pages *cite* the klima_id in their titles and body text (\"`A3.3` Regnvandsledning i")
    w("Bispebjerg Bakke, `BIR 7.5`\"). `build_registry.py` recovers the link by scanning for ids that")
    w("actually exist in the geometry, which stops stray tokens inventing matches. The recovered")
    w("mapping is a **reconstruction, not an official crosswalk** — treat it as such." + CE)
    w()
    # ------------------------------------------------------------------ 4
    n_cso, n_sep = of["layers"]["combined_overflow"]["n"], of["layers"]["separate_stormwater"]["n"]
    w("## 4. PULS — Punktkilder og spildevand  *(not directly accessible)*")
    w()
    w(C("C-DS-PULS", "The national point-source database, run by Danmarks Miljøportal. Every "
        "rain-dependent discharge is reported in it with its master data, and its discharged "
        "volumes of water and substance are to be determined every year; DP02 grades how each "
        "volume was found, from a simple mass balance to measurement at the structure."))
    w(C("C-DS-PULS-EXTRACT", f"The public spildevandsdata extract carries {n_cso:,} combined-sewer "
        f"overflow structures and {n_sep:,} separate stormwater outfalls."))
    w()
    w(C("C-DS-PULS-ACCESS", "Access to PULS goes through the IT coordinator of one's own organisation, "
        "as DP02's system overview has it; this project holds no such access and reads the public "
        "extract."))
    w()
    # ------------------------------------------------------------------ 5
    w("## 5. LER — Ledningsejerregistret  *(deliberately not used)*")
    w()
    w(CB("C-DS-LER-RULE") + "The utilities' pipe information is requested here by a dig inquiry, made as a")
    w(f"user logged in with MitID; LER's page for excavators gives the owners {R['ler_hours']} hours to answer, and")
    w("digging waits until all of them have." + CE + " "
      + CB("C-DS-LER-POLICY") + "This project")
    w("does not query it: an inquiry is for an intended excavation, and this project digs nothing. It is")
    w("documented as a drop-in slot for those who hold access — see")
    w("[IF_YOU_HAVE_THE_DATA.md](IF_YOU_HAVE_THE_DATA.md)." + CE)
    w()
    w(C("C-DS-NO-INVERTS", "This is the limit on the 3D ambition: **none of the open sources in this "
        "catalogue gives surveyed invert levels for Copenhagen's sewers.** Depths in this project "
        "come from what the plan documents state in prose, and are labelled as claims."))
    w()
    # ------------------------------------------------------------------ 6
    w("## 6. HOFOR  *(narrative only)*")
    w()
    w(C("C-DS-HOFOR", "The utility. Its page for contractors sends requests for pipe information to "
        "LER, and `hofor.dk` is used here as a citation source for the manual register of "
        "structures, not as a data source."))
    w()
    # ------------------------------------------------------------------ 7
    w("## 7. Elevation — Dataforsyningen  *(fetched with a token)*")
    w()
    w(C("C-DS-DHM", "`scripts/terraincheck.py` fetches the national elevation model's terrain "
        "(`dhm_terraen`) from Dataforsyningen's WCS, `https://api.dataforsyningen.dk/dhm_wcs_DAF`, "
        "with a token kept on this machine and at the resolution it asks for, to check the 2012 "
        "flood sheets against the ground."))
    w()
    w(C("C-DS-FLOWINPUT", "It is also the input for **modelling where rain flows**: fill the terrain's "
        "sinks, compute flow direction and accumulation, and surface flow paths and ponding "
        "depressions come out directly, rather than being inferred from the plan."))
    w()
    # ------------------------------------------------------------------ 8
    first_sheet = next(iter(ext.values()))
    bands = [f"`{b}`" for b in first_sheet["bands"].keys()]
    scales = {k: v["map_scale"] for k, v in sheets.items()}
    lo_k, hi_k = min(scales, key=lambda k: scales[k]), max(scales, key=lambda k: scales[k])
    bars = sorted({float(v["scalebar_m"]) for v in sheets.values()})
    bar_vals = [next(v["scalebar_m"] for v in sheets.values() if float(v["scalebar_m"]) == b) for b in bars]
    areas = sorted(((k, v["flooded_m2"]) for k, v in ext.items()), key=lambda kv: -kv[1])
    n_sheets = meta["floodmap_pdfs"]
    w("## 8. Modelled flood extents — published as pictures  *(recovered)*")
    w()
    w(CB("C-DS-FLOOD-WHAT") + "`Oversvømmelsesscenarier for vandoplande` on opendata.dk: flood scenarios")
    w("from the city's cloudburst plans for each water catchment, based on calculations, for a")
    w(f"{R['flood_event']}-year event, banded " + " / ".join(bands) + ". Which model produced them, over what")
    w("terrain, is not stated." + CE)
    w()
    w(CB("C-DS-FLOOD-PDFS") + f"It is published as **{n_sheets} raster PDFs** — amager, bispebjerg, indre-by,")
    w(f"kbhvest, ladegaardsaaen, norrebro, osterbro — from {meta['floodmap_pdf_mb_min']:.0f} to "
      f"{meta['floodmap_pdf_mb_max']:.0f} MB each, an orthophoto")
    w("with the depth bands painted over it. The dataset record says the calculations are from 2012,")
    w("and each sheet's title puts the event in 2010." + CE)
    w()
    w(C("C-DS-FLOOD-UNUSABLE", "This is the most important thing in this catalogue and the least "
        "usable. Where rain ponds in Copenhagen was calculated at municipal scale and published as "
        "an image: no coordinates this project could use, no vector extents, no depth values - so "
        "nothing can be overlaid, intersected or queried until each sheet is placed and read."))
    w()
    w("**Recovered** by `scripts/floodmaps.py`:")
    w()
    w("* " + C("C-DS-SCALES", f"The sheets are at **a different scale each**, with scale denominators "
               f"from {scales[lo_k]:,} ({SHEET_NAMES[lo_k]}) to {scales[hi_k]:,} ({SHEET_NAMES[hi_k]}), "
               "and scale bars of " + " or ".join(f"{b:.0f} m" for b in bar_vals) + ". Each sheet "
               "carries a real text layer, so the bar length is read, not guessed."))
    w("* " + C("C-DS-PALETTE", "The depth ramp is the Blues palette: `#f7fbff #d1e2f2 #9ac7e0 "
               "#519ccc #1c6bb0 #08306b` for the six bands, and every sheet carries the same six "
               "legend labels."))
    w("* " + C("C-DS-LEGEND", "The legend is masked before the depth is read, or its swatches would "
               "count as flooding; its position moves between sheets, so it is located from the "
               "text layer."))
    w("* " + C("C-DS-PALE", "The palest band is nearly white and matches pale roofs on colour alone; "
               "`floodmaps.py` separates it by its blue cast."))
    w()
    w(C("C-DS-AREAS", "Extracted flooded area: " + ", ".join(
        f"{SHEET_NAMES[k]} {a / 1e6:.2f}" + (" km²" if i == 0 else "") for i, (k, a) in enumerate(areas)) + "."))
    w()
    w(CB("C-DS-PLACED") + f"All {n_sheets} sheets are placed. `data/derived/floodmaps/_georef.json` records")
    w("for each how — by matching the orthophoto's water against the city's water polygons, or by")
    w("control points, some supplied by readers — and its stated error; see")
    w("[OPEN_PROBLEMS.md](OPEN_PROBLEMS.md). `viz/georef.html` still takes control points and reports")
    w("residuals, so a bad registration is visible." + CE)
    w()
    w(C("C-DS-LICENCE", "CKAN id `oversvommelsesscenarier-for-vandoplande`; its record gives the "
        f"licence as Creative Commons Attribution {R['flood_licence']}."))
    w()
    # ------------------------------------------------------------------ 9
    w("## 9. Observed surface water  *(not in any source here; we collect it)*")
    w()
    w(C("C-DS-NO-OBS", "None of the sources in this catalogue records where water is actually seen "
        "standing or running in Copenhagen's streets.") + " "
      + C("C-DS-DP02-CALIB", "Miljøstyrelsen's technical standard (dTA DP02) calibrates a model on "
          "measurement *at the overflow structure*: at least five clearly separable overflow events "
          "must be in the measured data.") + " "
      + C("C-DS-NO-STREET", "Calibration happens inside the pipes; nothing in the reporting chain "
          "observes a street surface."))
    w()
    w(C("C-DS-CORNER", "So a modelled depth at a street corner is never checked against the water "
        "actually standing there.") + " "
      + CB("C-DS-OBSLOG") + "`viz/log.html` (a phone-friendly, offline field logger) and")
    w("`scripts/observations.py` collect that layer. Records use the 2012 legend's depth classes up to")
    w("one metre, with everything deeper as one class, and flag drains that are *surcharging* —")
    w("water rising out of the gully, meaning the pipe below is full. They are stored in")
    w("`data/manual/observations.geojson`, hand-collected, never overwritten by a fetch script." + CE)
    w()
    # ------------------------------------------------------------------ 10
    kemi_rows, kemi_clock, ctd_rows = en["kemi"]["rows"], en["kemi"]["nonblank"]["Startklok"], en["ctd"]["rows"]
    attr = en["kemi"]["categorical"]["ResultatAttribut"]
    cls = cc["classes"]
    eras = list(cls.keys())
    visits = sum(cls[e][c] for e in eras for c in cls[e].keys())
    defaults = sum(cls[e]["default"] for e in eras if "default" in cls[e])
    mixed = sum(cls[e]["ambiguous"] for e in eras if "ambiguous" in cls[e])
    cs = dc["clock_source"]
    k, ct, ly, md = F["kemi"], F["ctd"], F["lys"], F["maaledybde"]
    y0 = min(x["years"][0] for x in (k, ct, ly, md))
    y1 = max(x["years"][1] for x in (k, ct, ly, md))
    U = k["units"]
    ortho, pp = U["Orthophosphat"], U["Primær produktion assimilieret Carbon, integreret"]
    chl = U["Klorofyl a"]
    single = all(p not in U for p in ("Oxygen indhold", "Oxygenmætning", "Nitrogen,total N"))
    w("## 10. ODA — what the archive does not warn you about  *(fetched; read this before using it)*")
    w()
    w(CB("C-DS-ODA-EXTRACTS") + f"Four extracts are on disk: `kemi` (water chemistry, {kemi_rows:,} rows),")
    w(f"`ctd` ({ctd_rows:,}), `lys` (light attenuation, {ly['rows_read']:,}) and `maaledybde`")
    w(f"({md['rows_read']:,}), with dates from {y0} to {y1}." + CE + " " + CB("C-DS-ENUMS")
      + "`scripts/enums.py` counts every")
    w("distinct value of every column of `kemi` and `ctd`, and `scripts/ds_facts.py` counts the traps")
    w("below over every row of all four, because reading the top few values of a column is how a rare")
    w("sentinel survives." + CE)
    w()
    w(CB("C-DS-UNITS") + f"**Units are per row, not per parameter. {k['parameters_multi_unit']} of "
      f"{k['parameters']} `kemi` parameters carry")
    w(f"more than one.** `Orthophosphat` is {ortho['µg/l']:,} rows in µg/l against {ortho['mg/l']:,} in mg/l.")
    w(f"Integrated primary production splits {pp['mg/(m2*d)']:,} mg/(m²·d) against {pp['mg/(m3*d)']:,}")
    w("mg/(m³·d), *per area against per volume*, which cannot be reconciled without a depth.")
    w(f"`Klorofyl a` is {chl['µg/l']:,} rows in µg/l and {chl['mg/l']} in mg/l — and no range filter can")
    w("catch that, because a plausible mg/l value is also a plausible µg/l value. **Check `Enhed` on")
    w("every row.**" + (" Oxygen, saturation and total nitrogen are single-valued throughout, which is luck"
                         " rather than a guarantee." if single else "") + CE)
    w()
    top, hi = md["deepest_stations"][0], md["hirtshals_15m"]
    w(CB("C-DS-SENTINELS") + f"**Sentinels, undeclared — and one announced but absent.** In `lys`, the")
    w(f"migration note on {ly['yintercept_note_rows']:,} rows says `YIntercept` was set to `9999999` because the")
    w(f"source lacked it; on {ly['yintercept_note_blank_rows']:,} of them the column is blank, and it holds")
    w(f"`9999999` on {ly['yintercept_9999999']:,} rows of the extract. In `kemi`,")
    w(f"`GennemsnitsDybde_m` is exactly `99` on {k['depth_exactly_99']:,} rows, with nothing on the row to")
    w("say whether that depth was measured." + CE + " " + CB("C-DS-BOTTOM") + "In `maaledybde`, `BundDybde_m`")
    w(f"reaches {top['max_m']:g} m at `{top['station']}`, where the station's {top['readings']:,} readings "
      f"have a median of {top['median_m']:g} m,")
    w(f"and {hi['max_m']:g} m at a station named `Hirtshals 15 m`, whose readings have a median of "
      f"{hi['median_m']:g} m." + CE)
    w(CB("C-DS-LIGHT") + f"`Lysprocent` exceeds {ly['light_threshold_pct']:g}% of surface light on "
      f"{ly['light_above_threshold']:,} rows and peaks at")
    w(f"{ly['light_max_pct']:g}. In `kemi`, oxygen saturation reaches {k['saturation_max_pct']:g}%." + CE)
    w()
    nd = k["not_detected_by_parameter"]
    nd_pfas = sum(v for p, v in nd.items() if "PFAS" in p or "Perfluor" in p or "perfluor" in p)
    w(CB("C-DS-CENSOR") + "**Censoring hidden behind column names that do not say so.** `ResultatAttribut`")
    w(f"is `<` on {attr['<']:,} `kemi` rows, where `Resultat` holds *the detection limit, not the")
    w("measurement* — read as a value it biases the parameter high." + CE + " " + CB("C-DS-NOTDETECTED")
      + f"(`ikke påvist`, {attr['ikke påvist']} rows, is")
    w(f"different: an analysis that found nothing; {nd_pfas} of them are PFAS results.)" + CE + " "
      + CB("C-DS-SECCHI") + "In `maaledybde`,")
    w(f"`SigtTilBund` is true on {md['secchi_to_bottom']:,} Secchi readings, meaning the disc reached the")
    w("bottom and the water was clearer than the number says. `SigtDybdeMedVandkikkert` marks")
    w(f"{md['secchi_by_water_telescope']:,} readings taken through a water telescope, a different instrument." + CE)
    w()
    w(C("C-DS-EMPTYCOLS", "**Columns that carry nothing.** `TekniskAnvisningAnvendt` is "
        "single-valued across every row of the three extracts that carry it, and `Afsluttet` across "
        "both that carry it, so neither can be used to filter for protocol compliance."))
    w()
    w(CB("C-DS-INTEGRATED") + "**Sample type decides what a depth means.** The technical instruction's")
    w(f"sampling chapter ([Kap. 5]({TA.format(5)})) prescribes integrated samples over {R['k5_010']} m,")
    w(f"over {R['k5_025']} m, or down to the depth of the photic zone. In `kemi`, {k['integrated_shallow']:,} of the")
    w(f"{k['integrated']:,} `Dybdeintegreret prøve` rows carry a nominal depth of {k['shallow_threshold_m']:g} m "
      "or less and will")
    w("enter a surface filter as though they were point measurements. An integral is not a")
    w("measurement at its midpoint." + CE)
    w()
    w(CB("C-DS-UTC") + "**What the instruction asks for and the archive does not deliver.** The nutrient")
    w(f"chapter ([Kap. 6]({TA.format(6)})) lists *\"Prøvetagningsdato og tidspunkt i UTC\"* among the station")
    w("data to report, and wherever that can be tested the archive's times are not UTC.")
    w("`scripts/clockzone.py` compares every station with itself at each summer-time change and finds")
    w("Danish wall-clock times from the early two-thousands, wall-clock times with the summer or winter")
    w(f"offset *added* before that, and filled-in defaults on {defaults:,} of {visits:,} sampling visits, with")
    w(f"{mixed:,} more from suppliers whose convention is mixed." + CE + " " + C("C-DS-CLOCKPY",
      "Every analysis that places a water-chemistry sample in time takes the instant from "
      "`scripts/clock.py`, which returns one UTC instant or says why there is none."))
    w(CB("C-DS-STARTKLOK") + f"`Startklok` has a value on every genuine `kemi` row — the {kemi_rows - kemi_clock} rows")
    w("without one are fragments of a broken note field — and ODA offers no clock field at all for")
    w("`ctd`, `lys` or `maaledybde`." + CE + " " + CB("C-DS-DETLIMIT") + "The same chapter asks for values below the")
    w("detection limit to be reported as measured, not as zero or as the limit with `<`. Yet")
    w(f"{k['nutrient_rows_censored_lt']:,} of the {k['nutrient_rows']:,} nutrient, TOC and POC rows in `kemi` carry `<` —")
    w("though which rows were sampled under this chapter the archive cannot say, since")
    w("`TekniskAnvisningAnvendt` carries one value throughout." + CE)
    w()
    fl, te, sa = (ct["by_parameter"][p] for p in ("Fluorescens", "Temperatur", "Salinitet"))
    lo_b, hi_b = ct["factor_band"]
    fl_share = live.step("K-SUBSET-SHARE", fl["outside_band"] / fl["with_factor"] * 100)
    w(CB("C-DS-KFAKTOR") + "**`KorrektionsFaktor` is not one thing.** In `ctd`, `KorrigeretResultat` equals")
    w(f"`OriginalResultat × KorrektionsFaktor`, to within the rounding of the stored value, on "
      f"{ct['rows_where_product_holds']:,}")
    w(f"of the {ct['rows_with_all_three']:,} rows carrying all three, and not on the other "
      f"{ct['rows_with_all_three'] - ct['rows_where_product_holds']:,} — so a wrong factor corrupts the value")
    w("silently and by construction. But what the factor *means* differs per parameter, and the")
    w("technical instructions say so:" + CE)
    w()
    w("* " + CB("C-DS-KF-OXYGEN") + f"**Oxygen** ([Kap. 4]({TA.format(4)})): instrument bias compensation. The")
    w(f"  electrode profile is checked against a Winkler titration on a bottle from {R['k4_depth']} m, and if")
    w(f"  they disagree by more than {R['k4_limit']} mg {chem('O2')}/l every value in the profile is multiplied by")
    w("  the ratio of the two. Where the Winkler bottle fell inside a gradient, the profile is corrected")
    w("  instead by the mean factor from profiles measured the same day at other stations — so some")
    w("  corrected oxygen carries a calibration derived at a different station." + CE)
    w("* " + CB("C-DS-KF-FLUOR") + f"**Fluorescence** ([Kap. 2]({TA.format(2)})): **not** bias compensation. The")
    w("  instruction states that a fluorescence signal *\"kan derfor ikke direkte omsættes til en")
    w("  pigment koncentration\"*, whatever the manufacturers' software reports, and that a varying")
    w("  ratio of fluorescence to chlorophyll *\"[er] ikke et udtryk for instrument problemer\"* — so the")
    w(f"  factor is a calibration against measured chlorophyll, and large factors can be correct. "
      f"{fl['outside_band']:,}")
    w(f"  of its {fl['with_factor']:,} factored rows ({fl_share:.1f}%) fall outside {lo_b:g}–{hi_b:g}, to a "
      f"maximum of {fl['max_factor']:g}×.")
    w("  **Do not filter fluorescence on this column.**" + CE)
    w("* " + CB("C-DS-KF-CTD") + f"**CTD temperature, conductivity, pressure** ([Kap. 1]({TA.format(1)})): calibration")
    w("  lives in the sensor's own coefficients, checked against reference measurements; the word")
    w(f"  *faktor* occurs {R['k1_faktor']} times in the chapter, so **no post-hoc multiplicative factor is")
    w(f"  described.** Yet {te['factor_not_1']:,} temperature rows carry a factor other than one, up to "
      f"{te['max_factor']:g}×, and")
    w(f"  {sa['factor_not_1']:,} salinity rows, up to {sa['max_factor']:g}× — with no basis in the instruction." + CE)
    w()
    f_ex = live.stated_value("ds_example_factor", 0.5, "an example factor of one half")
    t_ex = live.stated_value("ds_example_temp_c", 18, "an example summer surface temperature, in °C")
    w(C("C-DS-RANGE", f"A physical range check will not catch a bad factor: {f_ex} applied to {t_ex} °C "
        f"gives {f_ex * t_ex:g} °C, an unremarkable Danish sea temperature that happens to be wrong."))
    w()
    w(CB("C-DS-BORROW") + "**Lending a clock, with a caveat.** If a station-day is one moment — which is")
    w("assumed, not checked — the clock can be lent from `kemi` to `ctd`, the only route in the data")
    w("held to putting a time on oxygen at depth. `scripts/depth_clock.py` does it through")
    w("`scripts/clock.py`, lending only a `kemi` clock that is an observed time:")
    w(f"{cs['borrowed']:,} CTD oxygen measurements are placed that way, and {cs['none']:,} have no usable")
    w("clock to borrow. The first count is taken after the script's quality filters and the second")
    w("before them, so the two are not shares of one population." + CE)
    w()
    w("## Practical notes")
    w()
    w("* " + C("C-DS-PRACTICAL", "No script uses GDAL or geopandas, and the viewers load MapLibre from "
               "a CDN (cdnjs)."))
    w("* " + C("C-DS-NOCRED", "Apart from the elevation model, the fetched sources on this page are "
               "fetched without credentials; `data/manual/` is hand-authored."))
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
