#!/usr/bin/env python3
"""docs/hypodrafts/L3.md - what the data held here can and cannot show about L3.

Every number is read from data (live_json), is a stated design value with its
reason, or is arithmetic on those; every assertion is a checked claim
(LIVE_NUMBERS.md section 11), registered in data/manual/claims.d/w3-il.json with what
it rests on, and every field printed has a declared construction. What the draft
once said and could not justify is in docs/ARCHIVE.md, not here. The page is written
through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_l3.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED
import claims
import live

C = live.claim
R = live.ref


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("L3: " + msg)


def text():
    params = claims.load()[0]["params"]

    def P(name):
        """A design value the test chooses, declared with its reason."""
        p = params[name]
        return live.stated_value(name, p["value"], p["reason"])

    first, last = P("il_l3_first_year"), P("il_l3_last_year")
    wmin, sims = P("il_l3_min_window"), P("il_l3_sims")
    nyears = last - first + 1
    # every run of consecutive years at least wmin long inside the index period
    nwin = live.step("K-IL-WINDOWS", (nyears - wmin + 1) * (nyears - wmin + 2) // 2)
    if int(nwin) != sum(int(nyears) - L + 1 for L in range(int(wmin), int(nyears) + 1)):
        refuse("the closed form for the window count no longer matches the enumeration")

    ss = J("drafts_b_counts.json")["stations_series"]
    for key in ("oxy_bed", "oxysat_bed"):
        if key not in ss["variables"]:
            refuse(f"the panel no longer carries {key}")
    total, nbytes = ss["total_station_months"], ss["bin_bytes"]
    if int(total) != sum(int(v["n"]) for v in ss["variables"].values()):
        refuse("the panel's total is no longer the sum of its variables' counts")
    if int(nbytes) != int(total) * 8:
        refuse("stations_series.bin no longer holds eight bytes per station-month")
    ob, osat = ss["variables"]["oxy_bed"], ss["variables"]["oxysat_bed"]
    hf = J("hypodraft_facts.json")
    y0 = hf["series_by_variable"]["year0"]
    sf = hf["sign_flips"]
    ctd = J("hypodraft_ctd.json")["c1"]
    if int(ctd["first_year"]) >= int(y0):
        refuse("the CTD extract no longer reaches back before the panel's first year")

    o = []
    w = o.append
    w(f"# {R('L3', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_l3.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Status.** "
      + C("C-IL-L3-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes it."))
    w("")
    w("## The observable consequence, stated so it can fail")
    w("")
    w(C("C-IL-L3-READINGS", f"{R('L3')} has a weak reading and a strong reading, and only "
        "the strong one is a claim about the sea."))
    w("")
    w(C("C-IL-L3-WEAK", "**Weak:** *a slope fitted to a Danish series changes when you move "
        "the cut.* That is true of any noisy series, whatever the sea did, and is not worth "
        "testing."))
    w("")
    w(C("C-IL-L3-STRONG", "**Strong:** *the window-dependence exceeds what a single "
        "constant rate plus the series' own autocorrelated noise would produce* — i.e. the "
        "record contains genuinely different eras, so \"the trend\" is not a well-defined "
        "quantity and reporting one number is a category error."))
    w("")
    w(C("C-IL-L3-FALSIFY", "**Falsified if:** over the full space of admissible windows, "
        "the spread of fitted slopes, and the fraction of them that are positive, both fall "
        "inside the interval generated by simulating one constant slope with matched "
        "`AR(1)` noise. Then the window-dependence is noise around a single rate, the number "
        f"is estimable, and {R('L3')}'s strong reading is not established for this "
        "variable."))
    w("")
    w(C("C-IL-L3-SUPPORT", "**Supported if:** the observed surface is more dispersed, or "
        "its sign-share further from a single-trend expectation, than that simulation "
        "allows."))
    w("")
    w("## The data held")
    w("")
    w(C("C-IL-L3-PANEL", f"`docs/data/areas/stations_series.json` holds {total:,} "
        f"station-months, the sum of its {ss['n_variables']} variables' counts, at "
        f"{ss['n_stations']:,} stations, in {ss['months']} month slots from January {y0}; "
        f"`stations_series.bin` is {nbytes:,} bytes, {nbytes / total:.0f} per "
        "station-month, as the declared layout of a `uint16` station index, a `uint16` "
        "month index and a `float32` value requires."))
    w("")
    w(C("C-IL-L3-OXY", f"Variable used: **`oxy_bed`**, near-bed oxygen in mg/l: "
        f"{ob['n']:,} station-months at {ob['stations']:,} stations.")
      + " "
      + C("C-IL-L3-RANGE", "`stations_series.py` takes the median of every value in the "
          "deepest quarter of each cast's depth range, with no test of range, so values no "
          "instrument could give, which the extracts are known to carry, reach the panel; "
          f"the flag record marks {sf['station_months']} station-months at "
          f"{sf['stations']} stations as a sign inversion ({R('I7')}) and removes nothing. "
          "A test must set its own bounds and say how many values they drop."))
    w("")
    w(C("C-IL-L3-STRUCT", "Two further faults are structural and are not fixed, only "
        "declared. The panel is a monthly median per station, so within-month spread and "
        "any daily oxygen cycle are gone from it, and the CTD extract it is built from "
        "carries a date and no hour.")
      + " "
      + C("C-IL-L3-RESID", "Both inflate the year-to-year residual; the null below is "
          "matched to the residual actually observed, so they widen the null rather than "
          "being smuggled into the signal.")
      + " "
      + C("C-IL-L3-SATCHK", "The saturation cross-check uses `oxysat_bed`, which is "
          "computed from oxygen, temperature and salinity, and is reported as a robustness "
          "check only."))
    w("")
    w("## The constraint, and therefore the null")
    w("")
    w(C("C-IL-L3-CONSTR", f"Constraint: annual index years **{first}–{last}** "
        f"({nyears} years), windows of **at least {wmin} years**, giving **{nwin:,} "
        "admissible windows**."))
    w("")
    w(C("C-IL-L3-INDEX", "Index = two-way fixed effects (station + calendar month, "
        "alternating demeaning to convergence), then the annual mean of residuals.")
      + " "
      + C("C-IL-L3-LEVELS", "Station effects absorb level differences, so composition "
          "change in *levels* cannot drive the index."))
    w("")
    w(C("C-IL-L3-NULLPROC", "**The null is not \"zero sensitivity\".** For each station "
        f"set, estimate ρ and σ from the detrended index, then simulate {sims:,} `AR(1)` "
        f"series of the same length and compute the same {nwin:,}-window surface. Two "
        "nulls:"))
    w("")
    w("- " + C("C-IL-L3-H0", "**`H0`, no trend at all.** Each window's slope is then "
               "noise, as likely positive as negative, so finding both signs across the "
               "windows is expected with no trend at all: *a sign flip on its own does not "
               "tell a trend from none.*"))
    w("- " + C("C-IL-L3-H1", "**`H1`, one constant slope equal to the fitted full-window "
               "slope, plus matched noise.** This is the null that "
               f"{R('L3')}'s strong reading must beat."))
    w("")
    w("## The two confounds")
    w("")
    w(C("C-IL-L3-COMP", f"**Composition.** If the stations reporting change over the "
        f"record ({R('I1')}), station effects absorb their levels but not their seasonal "
        "timing. A split into summer-peaked and year-round stations must then state its "
        "rule, including a minimum number of observations: a station seen in a single "
        "calendar month has a seasonal resultant of exactly one by construction, and would "
        "count as perfectly seasonal.")
      + " "
      + C("C-IL-L3-CORE", "The test is to be repeated on a fixed core of stations reporting "
          "throughout the index period, which a change of composition cannot move."))
    w("")
    w(C("C-IL-L3-SAT", f"**Thermometer.** The same surface can be computed on "
        f"`oxysat_bed` ({osat['n']:,} station-months at {osat['stations']:,} stations): "
        "oxygen as a share of what the water holds at saturation, at its temperature and "
        "salinity. A decline in concentration that is absent in saturation points to "
        "solubility rather than oxygen supply. Not computed here."))
    w("")
    w("## What it would license")
    w("")
    w(C("C-IL-L3-LICENSE", "Licensed, once run: whether near-bed oxygen in this panel "
        "shows window-dependence beyond one constant rate with matched autocorrelation, for "
        "this variable and these stations. Nothing is licensed yet."))
    w("")
    w(C("C-IL-L3-NOTLIC", "Not licensed: anything about chlorophyll, nutrient loading, or "
        f"the modelled reference condition, which is where {R('L3')}'s stake actually lies "
        f"({R('L1')}, {R('L2')}). Nothing causal."))
    w("")
    w(C("C-IL-L3-PRE", f"Nor anything before the panel's first year, {y0}, which "
        "`cube.py` fixes: the CTD extract it is built from holds station-days with "
        f"temperature and salinity from {ctd['first_year']}, and those earlier years are "
        f"not in the panel. {R('L3')} is about where monitoring records begin, so the "
        "earlier years matter to it."))
    w("")
    w(C("C-IL-L3-SLOPE", "Whatever the result, a single slope is not licensed on its own: "
        "any published rate needs its window and its `H1` interval printed beside it."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/L3.md", page))
