#!/usr/bin/env python3
"""docs/hypodrafts/K1.md - what the data held here can and cannot show about K1.

Every number is read from data (live_json) as the page is built; every assertion is
a checked claim (LIVE_NUMBERS.md section 11), registered in
data/manual/claims.d/w3-kd.json with what it rests on, and every field printed has a
declared construction. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_k1.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED
import live

C = live.claim
R, CH = live.ref, live.chem
PFT = ("DIATO", "DINO", "MICRO", "NANO", "PICO")


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def text():
    pk = J("drafts_b_counts.json")["plankton"]
    # the page names the variables and says the first year is the partial one;
    # refuse it if the files stop saying so
    if set(pk["variables"]) != {"CHL", "CYANOBLOOM", *PFT}:
        raise live.Unjustified(f"K1: the plankton files now hold {list(pk['variables'])}, "
                               "not the variables the page names")
    if [int(y) for y in pk["partial_years"]] != [int(pk["first_year"])]:
        raise live.Unjustified("K1: the page says the first plankton year is the partial "
                               f"one; the files mark {list(pk['partial_years'])}")
    rs = J("rescore.json")
    fs = rs["matrix"]["K1"]["fetch_supplied"]
    si, nox, nh4 = fs["si"], fs["nox"], fs["nh4"]
    by_year = rs["tests"]["K1_si_din_molar_surface"].items()
    lo_y, lo = min(by_year, key=lambda t: t[1]["n"])
    hi_y, hi = max(by_year, key=lambda t: t[1]["n"])

    o = []
    w = o.append
    w(f"# {R('K1', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_k1.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Draft, not a result.** "
      + C("C-KD-K1-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes it.") + " "
      + C("C-KD-K1-NEEDS", f"{R('K1')} needs dissolved silicate alongside N and P at the "
          "same stations and dates, and species-level phytoplankton counts. The silicate "
          "half is held; the counts are not."))
    w("")
    w("## The plankton files on disk cannot carry this hypothesis")
    w("")
    w(C("C-KD-K1-FILES", f"`data/raw/cmems/grid/` holds {pk['n_files']} yearly files, "
        f"{pk['first_year']} to {pk['last_year']}, the first of them partial, of the "
        "Copernicus Marine product `OCEANCOLOUR_BAL_BGC_L3_MY_009_133`, the newest of them "
        "with "
        f"{pk['n_variables']} variables: total chlorophyll (`CHL`), the functional types "
        "`DIATO`, `DINO`, `MICRO`, `NANO` and `PICO`, and a cyanobacteria bloom mask "
        "(`CYANOBLOOM`). They are daily satellite retrievals of ocean colour, not cell "
        "counts."))
    w("")
    w(C("C-KD-K1-DERIVED", "Each functional-type variable carries, in the file itself, the "
        "provider's note that it is *derived from chl as in Brando et al. (2021)*, and the "
        "product's description says the functional types are evaluated by a region-specific "
        "algorithm. A field computed from total chlorophyll cannot move where chlorophyll "
        f"does not, so {R('K1')}'s distinguishing prediction — *composition moves while "
        "total biomass need not* — cannot be expressed in these files, let alone tested. "
        "They are a chlorophyll field, not an observation of who the biomass is."))
    w("")
    w("## What is held, and what is not")
    w("")
    w(C("C-KD-K1-SILICATE", "The water-chemistry extract held here, "
        f"`data/raw/oda/kemi.csv.gz`, carries silicon (`Silicium`) on {si['n']:,} samples "
        f"that `scripts/rescore.py` accepts, at {si['stations']:,} stations over "
        f"{si['years']}, beside {CH('NO2-')}+{CH('NO3-')} on {nox['n']:,} and "
        f"{CH('NH4+')} on {nh4['n']:,}: one value per sample, joinable by station and "
        "date.") + " "
      + C("C-KD-K1-POOLED", "The only Si:DIN computed from it is `rescore.py`'s yearly "
          "median of surface Si:DIN pooled over every month: not the January–February "
          "pre-bloom quantity specified below, and not a test of the premise (see "
          "[C-SIDIN](../CLAIMS.md#C-SIDIN))."))
    w("")
    w(C("C-KD-K1-DOME", "The ICES Phytoplankton Community dataset is published through the "
        "EurOBIS repository as sampling events with occurrence and extended "
        "measurement-or-fact records, under a Creative Commons Attribution licence.") + " "
      + C("C-KD-K1-NOCOUNTS", "Species-level phytoplankton counts are not held here, so the "
          "assemblage half cannot be scored; whether that dataset's measurement records "
          "carry cell counts for Danish samples has not been checked against anything "
          "held."))
    w("")
    w("## The observable consequence, stated so it can be falsified")
    w("")
    w(C("C-KD-K1-DENOM", "The denominator must be built, not assumed: a community count can "
        "hold heterotrophs such as bacteria and ciliates, and records identified only above "
        "class cannot be placed in a group. Denominator = records resolving inside the "
        "autotrophic protist groups; the unassignable fraction is reported, not "
        "distributed."))
    w("")
    w("> " + C("C-KD-K1-TEST", "At a **sampling position** (never a water body), the "
               "pre-bloom silicon pool sets the diatom fraction the following bloom can "
               "reach. Regress the **March–April diatom share of phytoplankton carbon** on "
               "the **preceding January–February median surface Si:DIN** at the same "
               f"position, with position fixed effects. {R('K1')} predicts a positive slope "
               "**that survives conditioning on total chlorophyll**: the share must move "
               "where biomass does not."))
    w("")
    w(C("C-KD-K1-FALSIFY", "**Falsified if:** the slope is indistinguishable from the null "
        "below, or it vanishes once chlorophyll is conditioned on — which would say "
        "composition only tracks biomass."))
    w("")
    w("## The null")
    w("")
    w(C("C-KD-K1-NULLRULE", "Not the statistic's nominal null. A yearly series of pre-bloom "
        "Si:DIN can persist from one year to the next, and a persistent series crosses a "
        "threshold set for independent years more often than that threshold allows. The "
        "threshold must come from surrogates that keep the series' own persistence — "
        "circular shifts of the years, and phase-randomised series with its spectrum — "
        "computed on the series actually used; neither has been computed here."))
    w("")
    w(C("C-KD-K1-PANEL", "**A second null to absorb:** the panel is not fixed. The surface "
        "cells (one station, date and depth) behind `rescore.py`'s pooled yearly Si:DIN "
        f"median number {lo['n']:,} in {lo_y} and {hi['n']:,} in {hi_y}, among the years it "
        "keeps, so an across-year statistic on pooled medians is partly a statistic about "
        "how much was sampled.") + " "
      + C("C-KD-K1-FIXED", "Hence position fixed effects and a balanced panel; a "
          "station-level permutation is *not* conservative enough, because neighbouring "
          "stations can share water."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-KD-K1-P1", "Fetch the counts with their measurement records, paged to "
                "disk by year, never held in memory at once."))
    w("2. " + C("C-KD-K1-P2", "Group by sample event; **keep only events where every "
                "occurrence carries an abundance**, and report how many events that drops."))
    w("3. " + C("C-KD-K1-P3", "Normalise to cells per litre by each record's own unit, never "
                "by a unit assumed for the column or the file."))
    w("4. " + C("C-KD-K1-P4", "Convert to carbon with a published biovolume list, report the "
                "share of abundance records that match it, and resolve synonyms and "
                "higher-rank identifications before relying on that share."))
    w("5. " + C("C-KD-K1-P5", "**The currency is not neutral.** Report the diatom share both "
                "by carbon and by cell number, and state the rule for what counts as one "
                "individual."))
    w("6. " + C("C-KD-K1-P6", "Chemistry: take it from the held water-chemistry extract, "
                "which joins to a station by identity rather than by distance and date."))
    w("")
    w("## Direction, which a correlation does not give")
    w("")
    w(C("C-KD-K1-DRAWDOWN", "Diatoms take up dissolved silicon to build their cell walls, so "
        "a contemporaneous correlation fits either arrow, and the trivial one: a bloom draws "
        "Si down, so *low Si with many diatoms* is drawdown, not limitation.")
      + " What would license direction:")
    w("")
    w("1. " + C("C-KD-K1-D1", "**Temporal ordering** — the winter pool before the bloom, "
                "cross-lagged both ways: if the reverse path (last spring's share → this "
                "winter's Si) is as strong, the design has failed and says so."))
    w("2. " + C("C-KD-K1-SHIFTER", "**An exogenous shifter** — silicon delivered by rivers "
                "is set upstream, not by marine diatoms. The source register records ODA's "
                "river-transport topic (*Vandløb / Stoftransport*) as carrying `Silicium` "
                "monthly per station with discharge; it is not fetched here. Discharge also "
                "delivers N, P and stratification, so this is a partial instrument and must "
                "be reported as one."))
    w("3. " + C("C-KD-K1-SHOCK", "**An asymmetric policy shock** — where nitrogen was cut by "
                "policy and silicon was not, a step in Si:DIN driven by the N term alone is "
                "exogenous to diatoms in a way the Si term is not."))
    w("")
    w("## What it would and would not license")
    w("")
    w(C("C-KD-K1-LICENSE", "A coefficient — diatom carbon share against pre-bloom Si:DIN, at "
        "sampling-position level, against a persistence-aware null, for a stated denominator "
        "and currency. **Not** a statement about total production, oxygen, any water body, "
        f"or whether cutting nitrogen helps: {R('K1')}'s appeal is that cutting N raises "
        "Si:N, and this measures an association, not that intervention."))
    w("")
    w("## Still blocked")
    w("")
    w(C("C-KD-K1-BGC-LIST", "Copernicus Marine's Baltic Sea biogeochemistry reanalysis "
        "(`BALTICSEA_MULTIYEAR_BGC_003_012`) describes its variables as including nitrate, "
        "phosphate, ammonium, dissolved oxygen, pH, chlorophyll-a, Secchi depth, surface "
        f"partial {CH('CO2')} pressure and net primary production, and the catalogue record "
        "of its daily dataset lists exactly those: `chl`, `nh4`, `no3`, `nppv`, `o2`, `o2b`, "
        "`ph`, `po4`, `spco2` and `zsd`.") + " "
      + C("C-KD-K1-BGC", "Silicate is not among them, so the reanalysis cannot stand in for "
          "the silicon side."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/K1.md", page))
