#!/usr/bin/env python3
"""docs/hypodrafts/D7.md - what the data held here can and cannot show about D7.

Every number is read from data (live_json) or is a stated design value with its
reason; every assertion is a checked claim (LIVE_NUMBERS.md section 11), registered
in data/manual/claims.d/w3-kd.json with what it rests on, and every field printed
has a declared construction. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_d7.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED
import claims
import live

C = live.claim
R = live.ref
PANEL = {"fluo", "oxy_bed", "oxy_surf", "oxysat_bed", "oxysat_surf", "sal_bed",
         "sal_surf", "temp_bed", "temp_surf"}
FINE = ("Mud and sandy mud", "Muddy sand", "Quaternary clay and silt")
COARSE = ("Sand", "Gravel and coarse sand", "Till/diamicton", "Sedimentary rock")
DEAD = "dead bed (no biology)"


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("D7: " + msg)


def text():
    params = claims.load()[0]["params"]

    def P(name):
        """A design value the test chooses, declared with its reason."""
        p = params[name]
        return live.stated_value(name, p["value"], p["reason"])

    lag, sh, dp = P("kd_d7_lag_days"), P("kd_d7_shallow_m"), P("kd_d7_deep_m")
    rl, sd, nb = P("kd_d7_relax_days"), P("kd_d7_shift_days"), P("kd_d7_nbhd_km")

    dc = J("drafts_b_counts.json")
    ss, md = dc["stations_series"], dc["maaledybde"]
    if set(ss["variables"]) != PANEL:
        refuse(f"the panel's variables are now {sorted(ss['variables'])}, not those the page names")
    if set(dc["seabed"]["by_class"]) != set(FINE + COARSE):
        refuse("the seabed layer's classes are not the ones the page names")
    rows = md["rows"]
    if md["rows_x_equals_x1"] != rows:
        refuse("not every Secchi record repeats its easting column any more")

    wv = J("waves.json")
    if DEAD not in wv["critical_shear_Pa"]:
        refuse("waves.json no longer has a dead-bed threshold")
    depths = wv["depths_m"]
    d0 = depths[0]
    pct = wv["by_depth"][str(float(d0))]["exceedance"][DEAD]["pct_of_time"]
    if pct <= 50:
        refuse("the page says the shallowest depth exceeds the dead-bed threshold in most "
               "hours; it no longer does")
    p0, p1 = wv["period"][0][:10], wv["period"][1][:10]

    lt = J("light.json")
    sc = lt["secchi"]
    bands = sc["bands"]
    edges = {float(b["to"]) for b in bands}
    if float(sh) not in edges or float(dp) not in edges:
        refuse("the arms' depths are no longer band edges in light.json")
    shallow = [b for b in bands if b["to"] <= sh]
    deep = [b for b in bands if b["from"] >= dp]
    if min(b["at_bed_pct"] for b in shallow) <= max(b["at_bed_pct"] for b in deep):
        refuse("the disc no longer reaches the bed more often in the shallow bands")
    bandline = " · ".join(f"{b['from']:g}–{b['to']:g} m {b['n']:,}" for b in bands)
    share = lambda bs: " and ".join(f"{b['at_bed_pct']:.1f}% at {b['from']:g}–{b['to']:g} m"
                                    for b in bs)
    ds = J("ds_facts.json")["maaledybde"]
    lys = J("hypodraft_facts.json")["lys"]
    en = J("enums.json")
    ctd_p, kemi_p = en["ctd"]["categorical"]["Parameter"], en["kemi"]["categorical"]["Parameter"]
    fd = J("hypodraft_ctd.json")["fdom"]
    dlist = ", ".join(f"{d:g}" for d in depths[:-1]) + f" and {depths[-1]:g} m"

    o = []
    w = o.append
    w(f"# {R('D7', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_d7.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Status.** "
      + C("C-KD-D7-PANEL", f"`stations_series.json`, the monthly panel this project "
          f"analyses, carries {ss['n_variables']} variables — temperature, salinity, oxygen "
          "and oxygen saturation at surface and bed, and fluorescence — none of them "
          "turbidity, each a monthly median per station.") + " "
      + C("C-KD-D7-WAVESHARE", f"The wave model held here puts the modelled bed shear at "
          f"{d0:g} m above the dead-bed threshold in {pct:.0f}% of all hours, so a monthly "
          "median describes a mixture, not an event.") + " "
      + C("C-KD-D7-MONTHLY", f"**The monthly product cannot test {R('D7')}.** The dated raw "
          "record can:") + " "
      + C("C-KD-D7-TRANSP", "it holds transparency series — Secchi depths, "
          "light-attenuation profiles and CTD turbidity. The first two feed this project's "
          "light analysis; none has been set against modelled bed shear."))
    w("")
    w("## The observable consequence, stated so it can fail")
    w("")
    w(C("C-KD-D7-MECH", f"Under {R('D7')}, resuspension is depth-limited — in the wave "
        "model held here the orbital velocity at the bed falls with depth through sinh *kh* "
        "— substrate-limited, since only mobile fine sediment suspends, and it *relaxes* as "
        "that sediment settles again. The predictions, per station-visit, net of station "
        "mean, month-of-year and year:"))
    w("")
    w("1. " + C("C-KD-D7-P-DEPTH", f"**Depth.** Clarity is degraded in the {lag:g} days "
                "after an hour of critical-shear exceedance at that station, scaling with the "
                f"depth attenuation term: large where the bed is at most {sh:g} m deep, zero "
                f"within noise where it is deeper than {dp:g} m, **in the same storms**."))
    w("2. " + C("C-KD-D7-P-SUB", "**Substrate.** Present over GEUS "
                + " / ".join(f"*{c}*" for c in FINE) + "; absent over "
                + " / ".join(f"*{c}*" for c in COARSE)
                + " (the layer is described in [`D1.md`](D1.md))."))
    w("3. " + C("C-KD-D7-P-RELAX", f"**Relaxation.** The coefficient decays monotonically "
                f"over the {rl:g} days after an exceedance; a step persisting for weeks is a "
                "season, not a storm."))
    w("")
    w(C("C-KD-D7-FALSIFY", "**Falsified if** the within-station coefficient lies inside the "
        f"null below; **or** the control deeper than {dp:g} m moves as much as the arm at "
        f"most {sh:g} m deep; **or** the coarse-substrate coefficient equals the mud one; "
        "**or** the lag profile is flat. Together these predictions separate "
        f"{R('D7')} from \"winter is murkier.\""))
    w("")
    w("## The data held, counted here")
    w("")
    w(C("C-KD-D7-SECCHI", "**Response — Secchi depth.** `data/raw/oda/maaledybde.csv.gz` "
        f"holds {rows:,} records; {sc['n_paired']:,} carry a positive Secchi depth, a "
        f"positive bottom depth and a year, {sc['years'][0]} to {sc['years'][1]}. By bottom "
        f"depth: {bandline}."))
    w("")
    w("- " + C("C-KD-D7-CENSOR", "*Censored at the bed, and unequally between the arms.* "
               "Comparing the two depths each record carries, the share of readings in which "
               f"the disc reached the bottom is {share(shallow)}, against {share(deep)}; the "
               "supplier's own flag "
               f"`SigtTilBund` is set on {ds['secchi_to_bottom']:,} of all {rows:,} "
               "records.") + " "
      + C("C-KD-D7-TOBIT", "The disc hits bottom exactly when the water is clear, so "
          "censoring correlates with the predictor *and* differs between the arms: an "
          "uncensored fit would manufacture the depth prediction from censoring alone. Model "
          "it interval-censored (\"at least the bottom depth\")."))
    w("- " + C("C-KD-D7-SCOPE", "`SigtDybdeMedVandkikkert` — read through a water telescope "
               f"— is True on {ds['secchi_by_water_telescope']:,} records, so the Secchi "
               "column holds readings taken two ways; a test models the flag or keeps one "
               "kind."))
    w("- " + C("C-KD-D7-NOCLOCK", "The extract has a date and no clock field.") + " "
      + C("C-KD-D7-XUTM", f"In all {rows:,} records the second easting column `X_UTM321` "
          "repeats `X_UTM32`, and there is no northing column, so a position comes from the "
          "station register."))
    w("- " + C("C-KD-D7-TAIL", "**Visits are not drawn at random over the weather.** Hence a "
               "test on the relaxation tail, not the storm hour: a design consequence, not a "
               "caveat."))
    w("")
    w(C("C-KD-D7-KD", "**Second response.** `lys.csv.gz` holds "
        f"{lys['rows']:,} records of light-attenuation profiles "
        f"(`LyssvaekkelsesKoefficient`, K_d) at {lys['stations_with_coordinates']:,} stations "
        f"with a position; this project's light analysis counts {lt['n_casts_total']:,} "
        "casts in them with a positive K_d and a date, and its growing-season casts run "
        f"from {lt['years'][0]} to {lt['years'][1]}.") + " "
      + C("C-KD-D7-KDPATH", "Whether the profiles come from an instrument separate from the "
          "CTD cast is not established here; this project's list of independent production "
          "paths does not count them."))
    w("")
    w(C("C-KD-D7-TURB", "**Third response — turbidity is in the archive.** The CTD extract "
        f"carries `Turbiditet` on {ctd_p['Turbiditet']:,} rows and `FDOM` on "
        f"{ctd_p['FDOM']:,} rows, the latter from {fd['first_year']} to {fd['last_year']}; "
        "neither reaches the monthly panel.") + " "
      + C("C-KD-D7-TURBPATH", "It is **not a separate production path**: it comes from the "
          "same CTD casts as the oxygen channel — another channel of the same path."))
    w("")
    w(C("C-KD-D7-PREDICTOR", "**Predictor.** Bed shear is a model output, not an "
        "observation, and this repository has one: `scripts/waves.py` → "
        f"`data/derived/waves.json`, hourly from {p0} to {p1} ({wv['hours']:,} hours): ERA5 "
        "wind → the fetch in the wind's direction, read from a table "
        "(`data/raw/weather/fetch.json`) that no script in the repository produces → wave "
        "growth by Young and Verhagen (1996) → orbital velocity at the bed → Swart "
        "friction.") + " "
      + C("C-KD-D7-UNCHECKED", f"It is computed for Køge Bugt only, at fixed depths of "
          f"{dlist}, and has **never been confronted with an observation** of sediment "
          "moving.") + " "
      + C("C-KD-D7-MARINE", "The Open-Meteo marine files under `data/raw/marine/` carry "
          "hourly wave height and sea-surface temperature beside the currents `currents.py` "
          "reads; those wave heights are a model output too, and nothing here sets them "
          "against transparency.") + " "
      + C("C-KD-D7-WIND", "Wind is the end of the chain closer to observation, so τ is "
          "driven from wind, not from a wave field."))
    w("")
    w("## Sources beyond those held, and whether each is a separate path")
    w("")
    w("- " + C("C-KD-D7-SRC-DMI", "**DMI oceanObs** — the source register records DMI's "
               "open API as serving sea level observed at its stations, unauthenticated in "
               "testing. Wind "
               "setup in a shallow bay is *observed* storm forcing, independent of ERA5 and of "
               "any wave model: the anchor τ lacks. **A separate path.**"))
    w("- " + C("C-KD-D7-SRC-WAV", "**Copernicus Marine `BALTICSEA_MULTIYEAR_WAV_003_015`** "
               "— an hourly hindcast of significant wave height, period and direction from the "
               "wave model WAM with surface forcing from ECMWF's ERA5, over the Baltic "
               "including the Danish Belts, the Kattegat and Skagerrak.") + " "
      + C("C-KD-D7-SRC-WAV-PATH", "**Not a separate path**: the same atmosphere as the held "
          "wind; only the wave step differs."))
    w("- " + C("C-KD-D7-SRC-OC", "**Copernicus Marine `OCEANCOLOUR_BAL_BGC_L3_MY_009_133`** "
               "— daily satellite observations of plankton, reflectance and transparency as "
               "the diffuse attenuation coefficient of light (`KD490`).") + " "
      + C("C-KD-D7-SRC-OC-PATH", "**A separate path**: satellite radiometry, daily, so it "
          "can resolve a storm's tail where cloud allows."))
    w("- " + C("C-KD-D7-SRC-SS", "**ODA water chemistry**, held (`kemi.csv.gz`): suspended "
               f"solids (`Suspenderede stoffer`) on {kemi_p['Suspenderede stoffer']:,} rows and "
               f"turbidity on {kemi_p['Turbiditet']:,}, from water samples. **A separate "
               "path** from the sonde."))
    w("")
    w("## Procedure")
    w("")
    w(C("C-KD-D7-PROC", "Compute fetch per station from the held OSM coastline "
        "(`data/raw/osm/coastline.json`) for the shallow stations and the deep controls; run "
        "`waves.py`'s chain per station at its own `BundDybde_m`, giving τ(station, hour). "
        "Per visit form E_ℓ = max τ in day ℓ before the visit, for ℓ up to "
        f"{rl:g}. Fit an interval-censored (Tobit) Secchi model on E_ℓ — station, "
        "month-of-year, year absorbed — interacted with depth and substrate; repeat on K_d "
        "and on `Turbiditet`."))
    w("")
    w("## The null, under the constraint actually imposed")
    w("")
    w(C("C-KD-D7-NULLCONSTR", "The constraint: visits sit where and when they sit, and "
        "storms are autocorrelated. A shuffle of τ across visits breaks both, and scores any "
        "seasonal cycle that storms and transparency share as signal."))
    w("")
    w("- " + C("C-KD-D7-NULL-TIME", "**The time null.** Circular-shift the whole hourly τ "
               f"series by whole years ± up to {sd:g} days, re-deriving the lags each draw. "
               "Preserves the seasonal cycle and storm autocorrelation exactly; destroys only "
               "the registration between *this* storm and *this* visit."))
    w("- " + C("C-KD-D7-NULL-DEPTH", "**The depth null.** Keep τ and the visits intact; "
               "permute *bottom depth* among stations within substrate class and a "
               f"{nb:g} km neighbourhood. Kills the depth prediction and preserves the rest, "
               "including any tendency of shallow stations to lie near the coast."))
    w("- " + C("C-KD-D7-EFFN", "**Effective n is events, not visits.** One weather system "
               "can cover the whole domain, so stations sampled in its wake observe the same "
               "storm. Report distinct exceedance events and stations per event — never the "
               "number of visits."))
    w("")
    w("## What it would license, and what it would not")
    w("")
    w(C("C-KD-D7-LICENSE", "Licensed: *a coefficient, at station-visit level, for the lagged "
        "transparency deficit per unit exceedance, with a depth gradient and a substrate "
        "contrast, against those two nulls* — and, if Secchi, K_d and satellite attenuation "
        "agree, a stability coefficient across them.") + " "
      + C("C-KD-D7-NOTOXY", f"Not licensed: anything about oxygen — transparency is not "
          f"sulphide, and {R('D7')}'s oxygen outcome needs the chemistry of the resuspended "
          "material, which is not held, and for which `fetch_oda.py` lists no topic.") + " "
      + C("C-KD-D7-NOSHORE", f"Nor fedtemøg reaching a shore, {R('D7')}'s other outcome, "
          "which needs a series of shore condition; none was found in any source this "
          "project surveyed."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/D7.md", page))
