#!/usr/bin/env python3
"""docs/hypodrafts/I3.md - generated from the hand-written draft as committed at c601feb.

The prose is the draft's, moved here verbatim and then made checkable: counts of
files held in this repository read live from data/derived/drafts_b_counts.json;
counts the drafting session made from external sources or one-off runs carried as
quotations of that commit (located references, {was:COMMIT:FILE:phrase with @@}); register IDs as {ref:}; chemical species
as {chem:}. See scripts/pages/drafts_b_page.py and LIVE_NUMBERS.md.

    python3 scripts/pages/hypodraft_i3.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from drafts_b_page import render
import live

TEXT = r'''# {ref:I3|title}

*Generated by `scripts/pages/hypodraft_i3.py` from the draft as committed at `c601feb`. Counts of files held in this repository are read live. Counts that session made from external sources or from one-off runs are quotations of that commit - what the draft reported, shown as such, not re-derived by the build.*


**Claim (HYPOTHESES.md).** "A deficit indicator built from the worst month is biased by
how often you sampled that month. More visits find more extremes." Outcome {ref:O1}.

Neighbour {ref:I1} asks *which stations*. This asks *how often, and when in the year* — temporal
aliasing of a quantity that varies faster than the sampling interval.

## The hypothesis splits in two, and only one half is scoreable

**I3a — count and window.** An extremal indicator (annual minimum, worst-month value,
days-below-threshold) is a first-order statistic. Its expectation moves with the number of
draws and with which months the draws fall in. Testable in full.

**I3b — diel phase.** Oxygen has a diel cycle; daylight at {was:c601feb:docs/hypodrafts/I3.md:cycle; daylight at @@°N runs}°N runs ~{was:c601feb:docs/hypodrafts/I3.md:at 55°N runs ~@@ h (December) to ~17} h (December) to
~{was:c601feb:docs/hypodrafts/I3.md:h (December) to ~@@ h (June), so working-hours} h (June), so working-hours sampling walks the diel phase with season. **There is no
time-of-day column anywhere in the archive.** Verified across all four ODA exports:
`ctd.csv.gz` ({was:c601feb:docs/hypodrafts/I3.md:`ctd.csv.gz` (@@ fields), `lys.csv.gz`} fields), `lys.csv.gz` ({was:c601feb:docs/hypodrafts/I3.md:`lys.csv.gz` (@@), `maaledybde.csv.gz`}), `maaledybde.csv.gz` ({was:c601feb:docs/hypodrafts/I3.md:`maaledybde.csv.gz` (@@), `stations.csv`}), `stations.csv` ({was:c601feb:docs/hypodrafts/I3.md:`stations.csv` (@@) — every})
— every temporal field is `YYYYMMDD`. Class 6, absent dimension: not recoverable, not
boundable, not countable. I3b is **unscoreable, not unsupported**, and no result below
speaks to it. Nothing here licenses a claim that the diel confound is absent or small.

## Observable consequence (I3a), stated to be falsified

If I3a is right, an extremal severity indicator computed under **fixed effort and a fixed
calendar window** will show a different temporal pattern than the same indicator computed
on whatever visits each station-year happens to contain. If the two paths coincide inside
the resampling envelope, I3a is refuted as an explanation of the {ref:O1} trend.

Two directions must be separated, because they push opposite ways and the data show they
nearly cancel:

- **Count.** More draws, lower minimum, mechanically.
- **Window.** Sparse programmes are not thin versions of dense ones — they are
  late-summer-targeted. Station-years with ≤{was:c601feb:docs/hypodrafts/I3.md:with ≤@@ near-bed oxygen} near-bed oxygen months put {was:c601feb:docs/hypodrafts/I3.md:oxygen months put @@% of their}% of their
  observations in August–September; station-years with ≥{was:c601feb:docs/hypodrafts/I3.md:with ≥@@ months are} months are near-flat ({was:c601feb:docs/hypodrafts/I3.md:near-flat (@@%–8.8% per}%–{was:c601feb:docs/hypodrafts/I3.md:near-flat (7.2%–@@% per}%
  per month). Sparse sampling therefore *finds* hypoxia while having few chances to.

## Data, with counts I verified

`docs/data/areas/stations_series.{json,bin}` — {fig:dbx_ss_total} station-months, {fig:dbx_ss_stations} stations,
{fig:dbx_ss_nvars} variables, 1980–2026, month index {was:c601feb:docs/hypodrafts/I3.md:month index @@–560. Variable}–{was:c601feb:docs/hypodrafts/I3.md:month index 0–@@. Variable `oxy_bed`:}. Variable `oxy_bed`: **{fig:dbx_ss_oxy_bed}** station-months,
**{was:c601feb:docs/hypodrafts/I3.md:station-months, **@@** station-years.}** station-years.

- Class 1, value error: {was:c601feb:docs/hypodrafts/I3.md:value error: @@ values ≤} values ≤ {was:c601feb:docs/hypodrafts/I3.md:432 values ≤ @@ and 40 >} and {was:c601feb:docs/hypodrafts/I3.md:≤ 0 and @@ > 20 mg/l.} > {was:c601feb:docs/hypodrafts/I3.md:and 40 > @@ mg/l. Dropped; 76,508} mg/l. Dropped; {was:c601feb:docs/hypodrafts/I3.md:mg/l. Dropped; @@ retained. - Class} retained.
- Class 3, aggregation: the product is a **monthly median**, so within-month replication is
  gone. It is not gone from the archive. The complete visit register
  `data/raw/oda/maaledybde.csv.gz` ({fig:dbx_md_rows} soundings, {fig:dbx_md_stations} stations, 1980–2026) has
  **{was:c601feb:docs/hypodrafts/I3.md:stations, 1980–2026) has **@@%** of its 83,011}%** of its {was:c601feb:docs/hypodrafts/I3.md:its @@ station-months} station-months carrying ≥{was:c601feb:docs/hypodrafts/I3.md:carrying ≥@@ distinct sampling} distinct sampling days. Oxygen rows
  specifically, over a {was:c601feb:docs/hypodrafts/I3.md:over a @@M-row prefix}M-row prefix of `ctd.csv.gz` ({was:c601feb:docs/hypodrafts/I3.md:`ctd.csv.gz` (@@ stations,} stations, {was:c601feb:docs/hypodrafts/I3.md:stations, @@ station-months —} station-months —
  a prefix, **not** a population estimate): **{was:c601feb:docs/hypodrafts/I3.md:population estimate): **@@%**. So the}%**. So the monthly panel can test count
  and window; it cannot test sub-monthly variance, and the raw file can.
- Class 6: no time of day (above). Class 7 applies to `oxysat_*` (computed from
  oxygen+temperature+salinity) — not used here.

Visits per station-year, `oxy_bed`, all {was:c601feb:docs/hypodrafts/I3.md:`oxy_bed`, all @@:}: 1→{was:c601feb:docs/hypodrafts/I3.md:`oxy_bed`, all 11,289: 1→@@ · 2→956 · 3→730} · {was:c601feb:docs/hypodrafts/I3.md:all 11,289: 1→1,496 · @@→956 · 3→730 ·}→{was:c601feb:docs/hypodrafts/I3.md:11,289: 1→1,496 · 2→@@ · 3→730 · 4→842} · {was:c601feb:docs/hypodrafts/I3.md:1→1,496 · 2→956 · @@→730 · 4→842 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 2→956 · 3→@@ · 4→842 · 5→1,154} · {was:c601feb:docs/hypodrafts/I3.md:2→956 · 3→730 · @@→842 · 5→1,154 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 3→730 · 4→@@ · 5→1,154 · 6→609} · {was:c601feb:docs/hypodrafts/I3.md:3→730 · 4→842 · @@→1,154 · 6→609 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 4→842 · 5→@@ · 6→609 · 7→336} ·
{was:c601feb:docs/hypodrafts/I3.md:4→842 · 5→1,154 · @@→609 · 7→336 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 5→1,154 · 6→@@ · 7→336 · 8→383} · {was:c601feb:docs/hypodrafts/I3.md:5→1,154 · 6→609 · @@→336 · 8→383 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 6→609 · 7→@@ · 8→383 · 9→527} · {was:c601feb:docs/hypodrafts/I3.md:6→609 · 7→336 · @@→383 · 9→527 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 7→336 · 8→@@ · 9→527 · 10→764} · {was:c601feb:docs/hypodrafts/I3.md:7→336 · 8→383 · @@→527 · 10→764 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 8→383 · 9→@@ · 10→764 · 11→1,113} · {was:c601feb:docs/hypodrafts/I3.md:8→383 · 9→527 · @@→764 · 11→1,113 ·}→{was:c601feb:docs/hypodrafts/I3.md:· 9→527 · 10→@@ · 11→1,113 · 12→2,379.} · {was:c601feb:docs/hypodrafts/I3.md:9→527 · 10→764 · @@→1,113 · 12→2,379. ##}→{was:c601feb:docs/hypodrafts/I3.md:· 10→764 · 11→@@ · 12→2,379. ## The} · {was:c601feb:docs/hypodrafts/I3.md:10→764 · 11→1,113 · @@→2,379. ## The null}→{was:c601feb:docs/hypodrafts/I3.md:· 11→1,113 · 12→@@. ## The null}.

## The null under the constraint I impose

**Constraint:** station-years with all twelve calendar months present — **{was:c601feb:docs/hypodrafts/I3.md:months present — **@@** of 11,289. Effort}** of {was:c601feb:docs/hypodrafts/I3.md:present — **2,314** of @@. Effort is fixed}.
Effort is fixed at {was:c601feb:docs/hypodrafts/I3.md:fixed at @@ and station} and station composition is fixed inside each unit, so nothing is
compared across differently-observed units.

**The null is computed, not assumed, and the naive one is wrong.** Marginally, minima do
*not* fall with visit count: median annual minimum is {was:c601feb:docs/hypodrafts/I3.md:annual minimum is @@ mg/l at 3} mg/l at {was:c601feb:docs/hypodrafts/I3.md:4.73 mg/l at @@ visits and 6.30} visits and {was:c601feb:docs/hypodrafts/I3.md:3 visits and @@ at 12. A} at {was:c601feb:docs/hypodrafts/I3.md:visits and 6.30 at @@. A null of}.
A null of "severity rises with count" would be inverted by the window effect. Within the
{was:c601feb:docs/hypodrafts/I3.md:Within the @@ fixed units,} fixed units, drawing month-sets from each station-year's own twelve values ({was:c601feb:docs/hypodrafts/I3.md:values (@@ Monte Carlo} Monte
Carlo draws):

| indicator on the same {was:c601feb:docs/hypodrafts/I3.md:same @@ station-years} station-years | mean min (mg/l) | P(min < {was:c601feb:docs/hypodrafts/I3.md:(mg/l) | P(min < @@) | |---|---|---| |}) |
|---|---|---|
| min over all {was:c601feb:docs/hypodrafts/I3.md:over all @@ months |} months | {was:c601feb:docs/hypodrafts/I3.md:12 months | @@ | 0.250 |} | {was:c601feb:docs/hypodrafts/I3.md:| 5.69 | @@ | | E[min} |
| E[min over {was:c601feb:docs/hypodrafts/I3.md:E[min over @@ months drawn} months drawn at random] | {was:c601feb:docs/hypodrafts/I3.md:at random] | @@ | 0.058 |} | {was:c601feb:docs/hypodrafts/I3.md:| 7.23 | @@ | | min} |
| min over the fixed window {Jul, Aug, Sep} | ⟨julsep⟩ | {was:c601feb:docs/hypodrafts/I3.md:| 5.93 | @@ | Count alone} |

Count alone moves exceedance by **{was:c601feb:docs/hypodrafts/I3.md:exceedance by **@@×**; fixing the}×**; fixing the window to Jul–Sep recovers almost all
of the {was:c601feb:docs/hypodrafts/I3.md:of the @@-month signal}-month signal from {was:c601feb:docs/hypodrafts/I3.md:signal from @@ draws. That} draws. That table *is* the null: the per-station-year
resampling distribution of the indicator, against which any observed path is scored.

## Procedure

1. Build the effort-matched panel: station-years containing all of Jul, Aug and Sep —
   **{was:c601feb:docs/hypodrafts/I3.md:and Sep — **@@** units; **8,771** have}** units; **{was:c601feb:docs/hypodrafts/I3.md:— **6,802** units; **@@** have ≥2 of}** have ≥{was:c601feb:docs/hypodrafts/I3.md:have ≥@@ of the three.} of the three. {was:c601feb:docs/hypodrafts/I3.md:the three. @@ stations carry} stations carry ≥{was:c601feb:docs/hypodrafts/I3.md:carry ≥@@ such years,} such years,
   {was:c601feb:docs/hypodrafts/I3.md:such years, @@ carry} carry ≥{was:c601feb:docs/hypodrafts/I3.md:years, 225 carry ≥@@, spanning 1980–2026 (789/2,411/2,006/1,697/1,091}, spanning 1980–2026 ({was:c601feb:docs/hypodrafts/I3.md:≥15, spanning 1980–2026 (@@/2,411/2,006/1,697/1,091 by decade band).} / {was:c601feb:docs/hypodrafts/I3.md:≥15, spanning 1980–2026 (789/@@/2,006/1,697/1,091 by decade band).} / {was:c601feb:docs/hypodrafts/I3.md:≥15, spanning 1980–2026 (789/2,411/@@/1,697/1,091 by decade band).} / {was:c601feb:docs/hypodrafts/I3.md:≥15, spanning 1980–2026 (789/2,411/2,006/@@/1,091 by decade band).} / {was:c601feb:docs/hypodrafts/I3.md:spanning 1980–2026 (789/2,411/2,006/1,697/@@ by decade band).} by decade band).
2. Compute the severity indicator twice per station-year: (a) on all available months,
   (b) on exactly {Jul, Aug, Sep}. Never aggregate to water bodies; the unit is the station.
3. For each unit, draw {was:c601feb:docs/hypodrafts/I3.md:draw @@ month-sets} month-sets of the same size from that unit's own values to get
   the null envelope for (a). Score the observed path of (a) against it.
4. Regress each indicator on year with station fixed effects. Compare slopes and the year-
   to-year path of (a) and (b).
5. Repeat with the Aug–Sep window and with a {was:c601feb:docs/hypodrafts/I3.md:and with a @@-of-3 window, as}-of-{was:c601feb:docs/hypodrafts/I3.md:with a 2-of-@@ window, as sensitivity.} window, as sensitivity.

## What a result would and would not license

**Would.** If (b) is flat where (a) trends, or the slopes differ beyond the envelope, then
the {ref:O1} severity trend is partly a trend in sampling design, and every extremal indicator in
this project must be recomputed effort-matched. If (a) and (b) agree, I3a is falsified for
extremal indicators at monthly resolution — a real result, and the stronger one.

**Would not.** It says nothing about (i) I3b, the diel confound, which stays unscoreable;
(ii) sub-monthly variance, which needs the raw daily file, not this panel; (iii) *rate*
indicators, already shown robust to effort and station composition here — this test is
about extremal statistics only, where the count dependence is structural; (iv) which
stations were observed, which is {ref:I1}'s.
'''

if __name__ == "__main__":
    # the old table cell sits after "{Jul, Aug, Sep}", and a was-placeholder cannot
    # carry braces, so this one quotation is located in Python
    sys.exit(render("docs/hypodrafts/I3.md", TEXT.replace("⟨julsep⟩", live.was(
        "c601feb", "docs/hypodrafts/I3.md", "fixed window {Jul, Aug, Sep} | @@ |"))))
