#!/usr/bin/env python3
"""docs/hypodrafts/I3.md - what the data held here can and cannot show about I3.

Every number is read from data (live_json) or is a stated design value with its
reason; every assertion is a checked claim (LIVE_NUMBERS.md section 11), registered
in data/manual/claims.d/w3-il.json with what it rests on, and every field printed
has a declared construction. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_i3.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED
import claims
import live

C = live.claim
R = live.ref


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("I3: " + msg)


def text():
    params = claims.load()[0]["params"]

    def P(name):
        """A design value the test chooses, declared with its reason."""
        p = params[name]
        return live.stated_value(name, p["value"], p["reason"])

    draws = P("il_i3_draws")

    ss = J("drafts_b_counts.json")["stations_series"]
    for key in ("oxy_bed", "oxysat_bed"):
        if key not in ss["variables"]:
            refuse(f"the panel no longer carries {key}")
    ob = ss["variables"]["oxy_bed"]
    hf = J("hypodraft_facts.json")
    y0 = hf["series_by_variable"]["year0"]
    sf = hf["sign_flips"]
    dl = J("hypotheses_evidence.json")["daylight"]
    if sorted(d[5:7] for d in dl["days"]) != ["06", "12"]:
        refuse("the day lengths are no longer those of the June and December solstices")
    ctd = J("hypodraft_ctd.json")["c1"]

    o = []
    w = o.append
    w(f"# {R('I3', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_i3.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w(C("C-IL-I3-NEIGHBOUR", f"{R('I1')} asks *which stations* were observed; "
          f"{R('I3')} asks *how often, and when in the year*: the aliasing of a quantity "
          "that can vary faster than it is sampled."))
    w("")
    w("**Status.** "
      + C("C-IL-I3-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes it."))
    w("")
    w("## The hypothesis splits in two, and only one half can be scored on the panel")
    w("")
    w(C("C-IL-I3-A", "**Count and window.** An extremal indicator — an annual minimum, a "
        "worst-month value — is an order statistic of the draws. Its expectation moves with "
        "the number of draws and with the months they fall in.")
      + " "
      + C("C-IL-I3-A-PANEL", "The monthly panel records, for each station, which months "
          "carry a value, so both the count and the window can be read off it."))
    w("")
    w(C("C-IL-I3-B-SUN", f"**Daily phase.** Daylight at {dl['lat']:.0f}°N runs from "
        f"{dl['shortest_h']:.0f} h at the December solstice to {dl['longest_h']:.0f} h at "
        "the June solstice, so if oxygen follows the sun, sampling held to working hours "
        "meets a different phase of its daily cycle as the season moves; the "
        "water-chemistry samples whose clock is an observed time rarely visit night or "
        "twilight.")
      + " "
      + C("C-IL-I3-CLOCK", "The CTD extract this panel is built from carries a date and no "
          "hour, and so do the Secchi and light-attenuation extracts. The water-chemistry "
          "extract carries a clock value per sample, and where a CTD cast shares a "
          "station-day with a bottle whose clock is an observed time, `depth_clock.py` "
          "lends the cast that time, on the unchecked assumption that the two share a "
          "moment.")
      + " "
      + C("C-IL-I3-B", "So the daily phase cannot be scored on the panel, whose values "
          "carry no hour; it could be bounded only through borrowed clocks, which nothing "
          "on this page uses, and nothing in the archive constrains the pre-dawn minimum. "
          "Nothing here licenses a claim that the daily-cycle confound is absent or "
          "small."))
    w("")
    w("## The observable consequence, stated so it can fail")
    w("")
    w(C("C-IL-I3-TEST", "If the count-and-window half is right, an extremal severity "
        "indicator computed under **fixed effort and a fixed calendar window** will follow "
        "a different path through the years than the same indicator computed on whatever "
        "visits each station-year happens to contain. If the two paths coincide inside the "
        f"resampling envelope, it is refuted as an explanation of the {R('O1')} trend."))
    w("")
    w(C("C-IL-I3-TWO", "Two directions must be separated, because they can push opposite "
        "ways:"))
    w("")
    w("- " + C("C-IL-I3-COUNT", "**Count.** More draws, lower minimum, mechanically."))
    w("- " + C("C-IL-I3-WINDOW", "**Window.** Which months the draws fall in matters as "
               "well: a programme that samples only in the months when oxygen is lowest "
               "meets low values with few draws, and one spread over the year dilutes the "
               "same number of draws with months when oxygen is high. How the panel's "
               "sparsely sampled station-years spread over the calendar has not been "
               "counted here."))
    w("")
    w("## The data held")
    w("")
    w(C("C-IL-I3-PANEL", f"`docs/data/areas/stations_series.json` holds "
        f"{ss['total_station_months']:,} station-months at {ss['n_stations']:,} stations "
        f"over {ss['n_variables']} variables: one monthly median per station and variable, "
        f"in {ss['months']} month slots from January {y0}. Near-bed oxygen, `oxy_bed`, has "
        f"{ob['n']:,} station-months at {ob['stations']:,} stations."))
    w("")
    w("- " + C("C-IL-I3-RANGE", "**Values are not range-checked.** `stations_series.py` "
               "takes the median of every value in the deepest quarter of each cast's "
               "depth range, with no test of range, so values no instrument could give, "
               "which the extracts are known to carry, reach the panel. The flag record "
               f"marks {sf['station_months']} station-months at {sf['stations']} stations "
               f"as a sign inversion ({R('I7')}) and removes nothing."))
    w("- " + C("C-IL-I3-REPLIC", "**The panel is a monthly median**, so within-month "
               "replication is gone from it. The CTD extract keeps each cast with its date, "
               "so whatever replication there is survives there: `hypodraft_ctd.py` counts "
               f"{ctd['station_days_ts']:,} station-days with temperature and salinity "
               f"there, at {ctd['stations']:,} stations. How many station-months hold more "
               "than one sampling day has not been counted here. So the panel can test "
               "count and window, and only the extract can test variance within a month."))
    w("- " + C("C-IL-I3-SAT", "`oxysat_bed` is computed from oxygen, temperature and "
               "salinity, so it is not an independent measurement; it is not used here."))
    w("")
    w("## The null, under the constraint imposed")
    w("")
    w(C("C-IL-I3-CONSTR", "**Constraint:** station-years with every calendar month "
        "present. Effort is then fixed, and station composition is fixed inside each unit, "
        "so nothing is compared across differently observed units."))
    w("")
    w(C("C-IL-I3-NULL", "**The null is computed, not assumed.** Within the fixed units, "
        "draw month-sets from each station-year's own values; the distribution of the "
        "indicator over those draws is the null against which any observed path is scored. "
        "That severity rises with count is not assumed, since the window effect can run "
        "the other way. The null has not been computed here."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-IL-I3-P1", "Build the effort-matched panel: station-years containing "
                "all of July, August and September; count them, and the stations carrying "
                "them, by decade."))
    w("2. " + C("C-IL-I3-P2", "Compute the severity indicator twice per station-year: (a) "
                "on all available months, (b) on exactly July, August and September. Never "
                "aggregate to water bodies; the unit is the station."))
    w("3. " + C("C-IL-I3-P3", f"For each unit, draw {draws} month-sets of the same size "
                "from that unit's own values to get the null envelope for (a). Score the "
                "observed path of (a) against it."))
    w("4. " + C("C-IL-I3-P4", "Regress each indicator on year with station fixed effects. "
                "Compare slopes and the year-to-year path of (a) and (b)."))
    w("5. " + C("C-IL-I3-P5", "Repeat with the August–September window and with a window "
                "of at least two of the three months, as sensitivity."))
    w("")
    w("## What a result would and would not license")
    w("")
    w(C("C-IL-I3-WOULD", "**Would.** If (b) is flat where (a) trends, or the slopes differ "
        f"beyond the envelope, then the {R('O1')} severity trend is partly a trend in "
        "sampling design, and every extremal indicator in this project must be recomputed "
        "effort-matched. If (a) and (b) agree, the count-and-window half is falsified for "
        "extremal indicators at monthly resolution — a real result, and the stronger one."))
    w("")
    w(C("C-IL-I3-WOULDNOT", "**Would not.** It says nothing about (i) the daily phase, "
        "which stays unscored; (ii) variance within a month, which needs the extract, not "
        "this panel; (iii) *rate* indicators, which it does not examine: it is about "
        "extremal statistics only, where the count dependence is structural; (iv) which "
        f"stations were observed, which is {R('I1')}'s."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/I3.md", page))
