#!/usr/bin/env python3
"""docs/hypodrafts/C6.md - what the data held here can and cannot show about C6.

Every number is read from data or from a pinned document as the page is built, or
is a stated design value with its reason; every assertion is a checked claim
(LIVE_NUMBERS.md section 11), registered in data/manual/claims.d/w3-cc.json with
what it rests on. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/draftkit.py.

    python3 scripts/pages/hypodraft_c6.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
import draftkit
import live

C = live.claim
REL = "docs/hypodrafts/C6.md"


def text():
    o = []
    w = o.append
    w("# {ref:C6|title}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_c6.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Draft, not a result.** "
      + C("C-CC-C6-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes it. The counts it prints are read from held outputs."))
    w("")
    w("## What is not in dispute")
    w("")
    w(C("C-CC-C6-CEILING", "Oxygen solubility is a function of temperature and salinity (and "
        "of pressure), computed from published equations; Weiss (1970) proposed the set this "
        "draft uses. That half of {ref:C6} needs no test.")
      + " " + C("C-CC-C6-RESIDUE", "The testable residue is the Q10 half: **at constant "
                "organic supply, does warmer bottom water sit further below its own ceiling?**"))
    w("")
    w("## The observable consequence, stated so it can be falsified")
    w("")
    w("Define the near-bed apparent deficit, per station-month:")
    w("")
    w("> " + C("C-CC-C6-DEF", "`D = C_sat(T_bed, S_bed) − O_bed` (mg/l), with `C_sat` from "
               "Weiss's equations in ml/l, converted at "
               "{read:CC-USGS-OWQ-2011-03:1.42905|that factor should have been 1.42905 mg/mL} "
               "mg per ml."))
    w("")
    w(C("C-CC-C6-NEUTRAL", "`D` is solubility-neutral by construction: if temperature acted "
        "on near-bed oxygen *only* through the ceiling, `D` would not depend on `T`."))
    w("")
    w(C("C-CC-C6-FALSIFY", "**What would falsify it:** *within a fixed station and a fixed "
        "calendar month, across years, `D` does not rise with that year's near-bed "
        "temperature* — a pooled within-cell slope β̂ that is not positive, or one the "
        "permutation null below cannot tell from none. That falsifies {ref:C6}'s "
        "non-thermodynamic content at the resolution this archive has."))
    w("")
    w(C("C-CC-C6-SUBSID", "**Subsidiary, about the iltsvind threshold:** *the `< 4 mg/l` "
        "flag ranks stations by consumption, not by ceiling height.* Falsified if station-level "
        "flag rates under `O < 4` and under a deficit flag with the same overall rate rank "
        "stations differently."))
    w("")
    w("## The data held")
    w("")
    w(C("C-CC-C6-SERIES", "`docs/data/areas/stations_series.{json,bin}` holds "
        "{fig:da_series_months} station-months — the sum over its {fig:cc_series_vars} "
        "variables — at {fig:da_series_stations} stations, in {fig:cc_series_slots} monthly "
        "slots from January {fig:cc_series_year0}. Near-bed: `oxy_bed` {fig:da_oxy_bed_n} · "
        "`temp_bed` {fig:da_temp_bed_n} · `sal_bed` {fig:da_sal_bed_n} · `oxysat_bed` "
        "{fig:da_oxysat_bed_n}.")
      + " " + C("C-CC-C6-JOIN-NORUN", "No script here joins the three near-bed arrays, so how "
                "many station-months carry all three, how many pass the plausibility filter, "
                "and how many cells have enough years are not known."))
    w("")
    w("**What is wrong with the data, and what the test does about it.**")
    w("")
    w("- " + C("C-CC-C6-FLAGS", "**Impossible values.** The panel holds values no water can "
               "hold — the flag record marks the sign-inverted oxygen of May and June 2005 — so "
               "the plausibility filter comes before anything else."))
    w("- " + C("C-CC-C6-QUANT", "**Quantisation.** Raw `Temperatur` is written with at most "
               "one decimal on {fig:da_tdec_one} of {fig:da_tdec_rows} rows of the whole CTD "
               "extract ({calc@K-SUBSET-SHARE:da_tdec_one / da_tdec_rows * 100|.0f}%); how much "
               "that rounding moves `C_sat` has not been computed here."))
    w("- " + C("C-CC-C6-AGG", "**Aggregation.** These are monthly *medians*, `_bed` is the "
               "deepest quarter of each cast's depth range, and each variable's median is taken "
               "separately, so the T, S and O medians of one station-month need not come from "
               "the same cast."))
    w("- " + C("C-CC-C6-UNFILLED", "**Unfilled.** At least "
               "{calc:da_oxy_bed_n - da_oxysat_bed_n|,} `oxy_bed` station-months carry no "
               "saturation — the difference of the two counts, a lower bound — and `SondeNr` is "
               "`999`, probe unknown, on "
               "{calc@K-SUBSET-SHARE:hy_ctd_999 / hy_ctd_rows * 100|.1f}% of the CTD extract."))
    w("- " + C("C-CC-C6-NOCLOCK", "**No time of day.** The raw header "
               "(`data/raw/oda/ctd.csv.gz`, {fig:da_ctd_columns} columns) has `Dato` as "
               "`19701013` — a date, no hour — and no other time field.")
      + " " + C("C-CC-C6-HOUR", "Within a station and calendar month, where the test works, the "
                "season's pull on the hour of sampling is held fixed; what remains is any change "
                "in that hour from year to year, which the detrending absorbs only where it is a "
                "trend. It is not correctable from this archive, and it caps what any result "
                "licenses."))
    w("- " + C("C-CC-C6-NOWB", "**The unit is a station, never a water body.**"))
    w("")
    w("## Circularity, handled")
    w("")
    w(C("C-CC-C6-NOTOUTCOME", "The archive's `oxysat_bed` is **never the outcome here**: "
        "saturation is oxygen as a share of what the water can hold at its temperature, so "
        "regressing it on temperature would put temperature on both sides.")
      + " " + C("C-CC-C6-SATSRC", "How ODA computes the saturation it supplies — "
                "`Oxygenmætning`, a parameter of its own in the CTD extract — is not documented "
                "in anything held or pinned here, so whether it rests on the same equations as "
                "`C_sat` is not known."))
    w("")
    w(C("C-CC-C6-DELIBERATE", "`D` contains T through `C_sat` deliberately — that is the "
        "*removal* of the solubility channel, not circularity, because `C_sat` is a fixed "
        "published function, not fitted to these data.")
      + " " + C("C-CC-C6-USGS", "The U.S. Geological Survey has replaced Weiss's equations "
                "with those of Benson and Krause for its own oxygen work."))
    w("")
    w(C("C-CC-C6-EIV", "The residual risk is errors-in-variables: an error ε in T enters `D` "
        "through `C_sat`, which falls as temperature rises, and enters the regressor unchanged, "
        "so it pulls β̂ toward a **negative** value as well as toward none. The test is "
        "therefore conservative in the direction that matters. Salinity, derived from "
        "conductivity and temperature, carries temperature error too; the size of either "
        "effect has not been computed here."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-CC-C6-P1", "Read the three near-bed arrays at the offsets in the `.json`; "
                "key on `station_index × 1000 + month_index`; keep {param:cc_c6_o_min} ≤ O ≤ "
                "{param:cc_c6_o_max} mg/l, {param:cc_c6_t_min} ≤ T ≤ {param:cc_c6_t_max} °C and "
                "{param:cc_c6_s_min} ≤ S ≤ {param:cc_c6_s_max}, and report what the filter "
                "removes."))
    w("2. " + C("C-CC-C6-P2", "Compute `C_sat` and `D`. Keep cells with at least "
                "{param:cc_c6_min_years} distinct years."))
    w("3. " + C("C-CC-C6-P3", "Centre T and D on their cell means. Estimate β̂ = "
                "Σ(t̃·d̃)/Σ(t̃²) — the station × calendar-month fixed-effects slope of deficit "
                "on temperature, mg/l per °C."))
    w("4. " + C("C-CC-C6-P4", "**Null, computed under the constraint actually imposed.** "
                "{param:cc_c6_perms} permutations: within each cell independently, permute D "
                "across years with T held in place. This keeps cell means, the seasonal cycle, "
                "every station effect and both marginals, destroying only the within-cell T–D "
                "pairing. Two-sided p = fraction with |β*| ≥ |β̂|. Report the permutation SD "
                "*and* the OLS SE and their ratio: near-bed deficits at neighbouring stations in "
                "the same month can be the same water mass sampled twice, so the textbook SE "
                "assumes an independence the data need not have. That ratio is the size of the "
                "error a quoted null would have made."))
    w("5. " + C("C-CC-C6-P5", "Repeat with D linearly detrended on year within each cell, so "
                "that a trend temperature and deficit share across the years cannot "
                "manufacture β̂. Report both, and the variants with at least "
                "{param:cc_c6_years_low} and at least {param:cc_c6_years_high} years."))
    w("6. " + C("C-CC-C6-P6", "Subsidiary: per station, the flag rate under `O < 4` and under "
                "a deficit threshold set so that it flags the same share of station-months; "
                "Spearman ρ over the stations; count the stations flagged by one and not the "
                "other. Null: permute calendar-month labels within station."))
    w("7. " + C("C-CC-C6-P7", "Confirmatory version, if step 4 clears: rebuild `D` from the "
                "temperature, salinity and oxygen of the *same cast* by streaming the CTD "
                "extract, removing the pairing gap that monthly medians leave."))
    w("")
    w("## What a result would and would not license")
    w("")
    w(C("C-CC-C6-WOULD", "**Would.** A positive β̂ surviving the permutation null and the "
        "detrending licenses: near-bed temperature moves near-bed oxygen beyond solubility, "
        "within station and within calendar month, in this archive — the gap {ref:C6} names, "
        "since the standing statistical models carry surface temperature only."))
    w("")
    w(C("C-CC-C6-NOTRESP", "**Would not.** It does not identify respiration: DCE name wind "
        "mixing as slowing oxygen depletion and high temperature as promoting it, and a warm "
        "year can also be a calm one, so a larger deficit may be failed ventilation rather "
        "than Q10.")
      + " " + C("C-CC-C6-NOQ10", "It cannot calibrate Q10 at all: converting a respiration "
                "*rate* to a standing deficit needs a ventilation timescale this archive does "
                "not record.")
      + " " + C("C-CC-C6-NOWBODY", "It says nothing about water bodies.")
      + " " + C("C-CC-C6-NULLRES", "And a slope indistinguishable from none would **not** "
                "refute {ref:C6} in nature; it would refute it at the resolution of monthly "
                "medians taken at an unrecorded hour."))
    return "\n".join(o) + "\n"


def main(argv):
    return 0 if draftkit.build(REL, text()) is not None else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
