#!/usr/bin/env python3
"""docs/hypodrafts/C4.md - what the data held here can and cannot show about C4.

Every number is read from data or from a pinned document as the page is built, or
is a stated design value with its reason; every assertion is a checked claim
(LIVE_NUMBERS.md section 11), registered in data/manual/claims.d/w3-cc.json with
what it rests on. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. Before writing, the generator checks the two things
the page says of files no derived output describes: that the monthly panel's
binary file is exactly the layout its .json declares, and the span and
completeness of the Baltic wind files. The page is written through
scripts/pages/draftkit.py.

    python3 scripts/pages/hypodraft_c4.py
"""
import json
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
import draftkit
import live
from common import ROOT

C = live.claim
REL = "docs/hypodrafts/C4.md"
# the depth the published inflow statistics read the eastern Gotland Basin at
DEPTH = "{read:CC-MOHRHOLZ-2018:200|the eastern Gotland Basin (200 m)}"
WIND = [os.path.join(ROOT, "data", "raw", "marine", f"wind_baltic_{p}.json") for p in "ncs"]


def refuse(msg):
    raise live.Unjustified("C4: " + msg)


def check_series():
    """The page says the .bin is exactly the layout the .json declares: each
    variable's block - station and month indices as uint16, values as float32,
    as its _layout says - starts where the previous one ends, and the last ends
    at the end of the file."""
    base = os.path.join(ROOT, "docs", "data", "areas")
    s = json.load(open(os.path.join(base, "stations_series.json"), encoding="utf-8"))
    if "uint16 station" not in s["_layout"] or "float32 values" not in s["_layout"]:
        refuse("stations_series.json no longer declares the layout the check assumes")
    point = struct.calcsize("<HHf")
    at = 0
    for v in s["variables"]:
        if v["offset"] != at:
            refuse(f"stations_series.bin: {v['key']} does not start where the block before it ends")
        at += v["n"] * point
    if at != os.path.getsize(os.path.join(base, "stations_series.bin")):
        refuse("stations_series.bin is not exactly as long as the layout its .json declares")


def wind_span():
    """First and last hour of the Baltic wind files, refusing the page if they
    disagree with each other or any speed or direction is missing."""
    spans = set()
    for f in WIND:
        h = json.load(open(f, encoding="utf-8"))["hourly"]
        for k in ("wind_speed_10m", "wind_direction_10m"):
            if len(h[k]) != len(h["time"]) or any(x is None for x in h[k]):
                refuse(f"{os.path.basename(f)}: {k} has a missing value")
        spans.add((h["time"][0], h["time"][-1]))
    if len(spans) != 1:
        refuse(f"the Baltic wind files cover different spans: {sorted(spans)}")
    return spans.pop()


def text():
    check_series()
    t0, t1 = wind_span()
    o = []
    w = o.append
    w("# {ref:C4|title}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_c4.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Draft, not a result.** "
      + C("C-CC-C4-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes it."))
    w("")
    w("## The observable consequence")
    w("")
    w(C("C-CC-C4-ORDER", "The falsifiable half of {ref:C4} is **ordered propagation**: a "
        "wind-forced inflow event at month τ produces a bottom-salinity anomaly whose **peak "
        "lag increases along the path** Belts/Øresund → Arkona → Bornholm → Gotland Deep, "
        "read there at " + DEPTH + " m, the depth at which the published inflow statistics "
        "read the eastern Gotland Basin. The test is whether the peaks fall in that order."))
    w("")
    w(C("C-CC-C4-FALSIFY", "**Falsified if** the peak lags are not in path order, or the "
        "Gotland salinity peak comes no later than the event month, or the ordering statistic "
        "— Kendall τ of peak lag against the sites' order along the path — lies inside the "
        "null below."))
    w("")
    w(C("C-CC-C4-SECONDARY", "Secondary: an event should raise `sal_bed` more than "
        "`sal_surf`. If both rise alike, the salinity difference between bed and surface at "
        "the Danish stations does not grow, and the part of {ref:C4} that has the pulses "
        "strengthen stratification above them is not seen at the Danish end."))
    w("")
    w("## The data held")
    w("")
    w("- " + C("C-CC-C4-SERIES", "`docs/data/areas/stations_series.{json,bin}`, the monthly "
               "panel: `sal_bed` on {fig:da_sal_bed_n} station-months at {fig:da_sal_bed_st} "
               "stations, `oxy_bed` on {fig:da_oxy_bed_n} at {fig:da_oxy_bed_st}, `sal_surf` on "
               "{fig:da_sal_surf_n}; the `.bin` is exactly as long as the layout its `.json` "
               "declares.")
      + " " + C("C-CC-C4-BEDBIN", "Each value is a station's monthly median, and `_bed` is "
                "the deepest quarter of each cast's depth range, so *near the bed* is a band "
                "whose depth changes from cast to cast; the extract behind it has no time of "
                "day."))
    w("- " + C("C-CC-C4-FLAGS", "The panel holds values no water can hold — the flag record "
               "marks the sign-inverted oxygen of May and June 2005 — so it is read with the "
               "flag record beside it."))
    w("- " + C("C-CC-C4-MAAL", "`data/raw/oda/maaledybde.csv.gz` gives `BundDybde_m` per "
               "visit: {fig:da_maal_rows} records, with a bottom depth at "
               "{fig:da_maal_stations_bottom} stations."))
    w("- " + C("C-CC-C4-MBIFILE", "`data/raw/cmems/indicators/omi_health_tempsaloxy_baltic_"
               "mbi_bottom_salinity_arkona_bornholm_P20250527.nc` holds `sob_ark` and "
               "`sob_bor`, daily from 1993-01-01 to 2024-12-31 with no value missing. Its "
               "title reads *bottom salinity from Reanalysis* and its source is "
               "`BALTICSEA_MULTIYEAR_PHY_003_011`: **a model output, not an observation**."))
    w("- " + C("C-CC-C4-GOTFILE", "`…_mbi_sto2tz_gotland_P20250527.nc` holds `so`, `to` and "
               "`oxy` against depth at the Gotland Deep, on a monthly step and a one-metre "
               "depth step; its title ends *from Observations Reprocessing*, and its comment "
               "says the measurements were regridded onto that grid, so fine vertical "
               "structure is interpolation between discrete samples. Salinity and temperature "
               "run from 1993-01 to 2024-11; oxygen, declared as a volume fraction in units of "
               "`0.001` (ml/l), fills {fig:cc_gotland_months} months from 2005-11 to "
               "2025-01."))
    w("- " + C("C-CC-C4-WIND", "`data/raw/marine/wind_baltic_n.json`, `_c` and `_s` each hold "
               "hourly `wind_speed_10m` (km/h) and `wind_direction_10m` from " + t0 + " to "
               + t1 + " with no value missing, each at one point; all three points lie east of "
               "Bornholm, so none is over the Kattegat or the Belts.")
      + " " + C("C-CC-C4-WINDSRC", "No script in this repository fetched them and `data/raw/` "
                "is not under version control, so what model or observation lies behind this "
                "wind is not recorded here."))
    w("- " + C("C-CC-C4-IOW", "**The published inflow record is not held.** IOW's Major "
               "Baltic Inflow statistics (Mohrholz) are registered as an open download — a daily "
               "barotropic transport series with a list of dated events — for {ref:A5}, "
               "{ref:C1} and {ref:C4}, and the register calls them the published inflow record "
               "{ref:C4} needs.") + " See [DATA_QUEUE.md](../DATA_QUEUE.md).")
    w("")
    w("**A trap in the files.** "
      + C("C-CC-C4-FILL", "Both netCDF files mark a missing cell with the fill value `1e36` "
          "(`_FillValue`); a reader that does not mask it averages fill into the result.")
      + " " + C("C-CC-C4-GOTUNITS", "`docs/data/baltic/gotland.json`, the project's copy of "
                "the Gotland profiles, converts the oxygen from ml/l to mg/l and records the "
                "product as in-situ profiles regridded onto a grid, not a reanalysis.")
      + " " + C("C-CC-C4-CHAIN", "So the Gotland file is observation-derived and the Arkona "
                "and Bornholm file is not: the observations run from the Danish stations to the "
                "Gotland Deep, and `sob_ark` and `sob_bor` serve only as a model check."))
    w("")
    w("## The station panel")
    w("")
    w(C("C-CC-C4-PANEL", "**The rule.** Stations inside {param:cc_c4_lon_w}–{param:cc_c4_lon_e} "
        "°E and {param:cc_c4_lat_s}–{param:cc_c4_lat_n} °N whose median bottom depth is at least "
        "{param:cc_c4_depth_m} m and which carry at least {param:cc_c4_months} monthly `sal_bed` "
        "medians in 1993–2024, each listed individually, never merged into a water body.")
      + " " + C("C-CC-C4-PANEL-N", "No script here applies the rule, so how many stations pass "
                "it, and in which months they were sampled, is not known."))
    w("")
    w("## The event index")
    w("")
    w(C("C-CC-C4-INDEX", "Eastward wind at the southern point (`wind_baltic_s.json`), from "
        "speed and direction, as a daily mean; its {param:cc_c4_burst_days}-day running sum is "
        "the westerly burst, multiplied by the easterly deficit of the "
        "{param:cc_c4_deficit_days} days before it, with a gap of {param:cc_c4_gap_days} days "
        "between them, as preconditioning. Winter maxima of the index give the event onsets.")
      + " " + C("C-CC-C4-INDEX-NORUN", "No script here computes the index, so which winters it "
                "ranks highest is not known, and whether its maxima are the published inflow "
                "events can be checked only against the IOW record, which is not held."))
    w("")
    w("## The null, under the constraint actually imposed")
    w("")
    w(C("C-CC-C4-NULLRULE", "Not the statistic's nominal null. Deep water in the central "
        "Baltic is renewed by major inflows and otherwise stagnates, so a Gotland deep series "
        "persists from one month to the next, and a threshold set for independent months is "
        "crossed more often than it allows. The null is computed on surrogates that keep the "
        "series' own persistence."))
    w("")
    w("- " + C("C-CC-C4-N1", "**`N1`, primary: circular shift of the event index by whole "
               "years**, over the years from 1995, when the wind begins, that the index and the "
               "responses share. Whole years keep event seasonality, any seasonal pattern of "
               "sampling and every series' autocorrelation; only the alignment dies. The "
               "smallest p it can give is one over the number of alignments, the true one "
               "included — state it, never exceed it."))
    w("- " + C("C-CC-C4-N2", "**`N2`: {param:cc_c4_surrogates} amplitude-adjusted "
               "phase-randomised surrogates** of each response.")
      + " " + C("C-CC-C4-RP", "Random phases keep a series' periodogram, its linear "
                "correlation; the amplitude-adjusted version (AAFT) tries to keep its "
                "distribution of values as well.")
      + " " + C("C-CC-C4-BOUND", "`N1` and `N2` bound the answer from two sides; take the more "
                "conservative."))
    w("- " + C("C-CC-C4-PANELNULL", "**The panel's stations are not replicates.** Neighbouring "
               "positions sampled in the same months can see the same water, so the statistic "
               "is the median across positions of a per-station z-anomaly, the panel shifts as "
               "one, and the null is over **time only**: spread across stations buys precision, "
               "not degrees of freedom. The sensitivity run is one fit per station, reported as "
               "a *distribution of lags*, not as separate tests. If only the composite shows the "
               "signal, the composite made it."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-CC-C4-P1", "Build the wind index above; take its winter maxima and the top "
                "*k* onsets, for k = {param:cc_c4_k_a}, {param:cc_c4_k_b} and {param:cc_c4_k_c}, "
                "declared before seeing the answer."))
    w("2. " + C("C-CC-C4-P2", "Per station, subtract that station's **own** month-of-year "
                "median from `sal_bed`, `sal_surf` and `oxy_bed`; divide by its interquartile "
                "range. Never pool before de-seasoning."))
    w("3. " + C("C-CC-C4-P3", "Same for `sob_ark` and `sob_bor` as monthly means, and for the "
                "Gotland `so` and `oxy` at " + DEPTH + " m, after masking the fill value, in the "
                "file's own units."))
    w("4. " + C("C-CC-C4-P4", "Superposed-epoch composite at lags from "
                "−{param:cc_c4_lag_before} to +{param:cc_c4_lag_after} months per site; record "
                "the peak lag."))
    w("5. " + C("C-CC-C4-P5", "Statistic: Kendall τ of peak lag against the sites' order along "
                "the path — Belts, Arkona, Bornholm, Gotland. τ depends only on ranks, so the "
                "order gives the same statistic as any distances that keep it."))
    w("6. " + C("C-CC-C4-P6", "Recompute τ under `N1` and `N2`."))
    w("7. " + C("C-CC-C4-P7", "Secondary: the same on `sal_bed − sal_surf`; and a check on "
                "`oxy_bed` for a rise followed by a fall — the pulse ventilating, then "
                "stratifying."))
    w("")
    w("## What a result would and would not license")
    w("")
    w(C("C-CC-C4-WOULD", "**Would.** A clean falsification if the order breaks — cheap, and "
        "robust to any error that shifts or rescales a series without moving when its peak "
        "falls, because τ uses only the order of the peak lags. Otherwise weak corroboration, "
        "capped at `N1`'s p floor."))
    w("")
    w("**Would not.** "
      + C("C-CC-C4-NOT-N", "(a) The effective sample is the number of inflow events, not the "
          "number of months, so no effect size is estimable; and the Gotland oxygen record "
          "begins in 2005-11, so the oxygen limb sees only the events after that — how many, "
          "the published chronology would say.")
      + " " + C("C-CC-C4-NOT-O1", "(b) Nothing about {ref:C4}'s contribution to **{ref:O1}** in "
                "Danish water: the design follows salinity along the path toward the Gotland "
                "Deep and has no step from there to oxygen at Danish stations.")
      + " " + C("C-CC-C4-NOT-EXO", "(c) It does not test *entirely exogenous to Danish "
                "policy*: exogeneity of the wind is assumed, and exogeneity of the consequences "
                "is a different claim.")
      + " " + C("C-CC-C4-NOT-THREE", "(d) `sal_bed`, `temp_bed` and `oxysat_bed` come from the "
                "same CTD casts; salinity is estimated from conductivity, and saturation is "
                "oxygen as a share of what water holds at its temperature and salinity: they are "
                "**one** piece of evidence, not three."))
    w("")
    w(C("C-CC-C4-NEXT", "**Smallest improvement:** fetch the IOW Major Baltic Inflow "
        "statistics, replacing a self-built proxy with the published chronology {ref:C4} "
        "names."))
    return "\n".join(o) + "\n"


def main(argv):
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        return 1
    return 0 if draftkit.build(REL, page) is not None else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
