#!/usr/bin/env python3
"""docs/hypodrafts/D1.md - what the data held here can and cannot show about D1.

Every number is read from data (live_json), from a pinned document ({read:}) or is a
stated design value with its reason; every assertion is a checked claim
(LIVE_NUMBERS.md section 11), registered in data/manual/claims.d/w3-dz.json with what
it rests on, and every field printed has a declared construction. What the draft once
said and could not justify is in docs/ARCHIVE.md, not here. The page is written
through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_d1.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED, ROOT
import claims
import live

C = live.claim
R = live.ref
FINE = ("Mud and sandy mud", "Muddy sand", "Quaternary clay and silt")
COARSE = ("Sand", "Gravel and coarse sand", "Till/diamicton", "Sedimentary rock")
ORDER = ("Sand", "Till/diamicton", "Gravel and coarse sand", "Muddy sand",
         "Quaternary clay and silt", "Mud and sandy mud", "Sedimentary rock")
USED = {"oxy_bed", "oxy_surf", "fluo", "temp_bed", "sal_bed"}
# the archive's size, as the pinned figshare record states it
ZIP_BYTES = "{read:HY-FIGSHARE-D1:23,051,366|\"size\": 23051366}"


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("D1: " + msg)


def text():
    params = claims.load()[0]["params"]

    def P(name):
        """A design value the test chooses, declared with its reason."""
        p = params[name]
        return live.stated_value(name, p["value"], p["reason"])

    nodata, draws = P("dz_d1_nodata_pct"), P("dz_d1_draws")

    dc = J("drafts_b_counts.json")
    ss, sb = dc["stations_series"], dc["seabed"]
    v = ss["variables"]
    if not USED <= set(v):
        refuse(f"the panel no longer holds all of {sorted(USED)}")
    if set(sb["by_class"]) != set(FINE + COARSE):
        refuse("the seabed layer's classes are not the ones the page names")
    hf = J("hypodraft_facts.json")
    lo, hi = hf["seabed"]["scale_min"], hf["seabed"]["scale_max"]
    if int(lo) >= int(hi):
        refuse("the seabed layer is no longer compiled at more than one map scale")
    n_lo, n_hi = sb["by_scale"][str(int(lo))], sb["by_scale"][str(int(hi))]
    year0 = hf["series_by_variable"]["year0"]
    mb = hf["layers"]["ctd_bytes"] / 1e6
    chl = J("enums.json")["kemi"]["categorical"]["Parameter"]["Klorofyl a"]
    pc = live.live_json(os.path.join(ROOT, "docs", "data", "areas",
                                     "partition_contiguous.json"))["graphs"]["knn"]

    o = []
    w = o.append
    w(f"# {R('D1', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_d1.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Draft, not a result.** "
      + C("C-DZ-D1-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes it, and the fishing-effort layers it needs are not "
          "fetched.") + " "
      + C("C-DZ-D1-ZIP", "They are one archive on figshare, "
          f"`2022_helcom_spatial_effort_intensity.zip`, of {ZIP_BYTES} bytes, under "
          "`CC BY 4.0`."))
    w("")
    w("## The observable consequence, stated so it can fail")
    w("")
    w(C("C-DZ-D1-MECH", f"Read as an oxygen mechanism rather than a fauna one, {R('D1')} "
        "says gear dragged over fine reduced sediment resuspends sulphide and labile organic "
        "matter, which consume oxygen where they are released: at the bed, within weeks, "
        "**and only where fine reduced sediment exists.** Per station-quarter:"))
    w("")
    w("1. " + C("C-DZ-D1-P-WITHIN", "**Within station.** Near-bed oxygen anomaly is lower in "
                "a station's own quarters following a high subsurface swept-area ratio "
                "(`subsur_sar`) in its c-square than in its own quarters following a low one, "
                "after removing station mean, month-of-year and year."))
    w("2. " + C("C-DZ-D1-P-SUB", "**Substrate interaction.** The effect is present on "
                + " / ".join(f"*{c}*" for c in FINE) + " and absent on "
                + " / ".join(f"*{c}*" for c in COARSE) + "."))
    w("3. " + C("C-DZ-D1-P-PLACEBO", "**Placebo.** No comparable effect in near-**surface** "
                "oxygen at the same stations."))
    w("")
    w(C("C-DZ-D1-FALSIFY", "**Falsified if:** the within-station coefficient lies inside the "
        "null distribution below; **or** the coarse-substrate coefficient is indistinguishable "
        "from the mud one; **or** the surface placebo moves with effort as strongly as the "
        "bed. The substrate interaction and the surface placebo are what make this a test of "
        "trawling rather than of where fish are."))
    w("")
    w("## The data held here, counted")
    w("")
    w(C("C-DZ-D1-PANEL", "**The panel.** `docs/data/areas/stations_series.json`, the monthly "
        f"panel this project analyses, holds {ss['total_station_months']:,} station-months "
        f"across its {ss['n_variables']} variables at {ss['n_stations']:,} stations, over "
        f"{ss['months']} months from {year0}: one median per station, month and variable, so "
        "a station-quarter built from it is a median of medians. Near-bed oxygen (`oxy_bed`) "
        f"fills {v['oxy_bed']['n']:,} station-months and near-surface oxygen (`oxy_surf`), "
        f"the placebo, {v['oxy_surf']['n']:,}."))
    w("")
    w(C("C-DZ-D1-FLUO", f"Fluorescence (`fluo`), the productivity covariate, fills "
        f"{v['fluo']['n']:,} station-months. It is a sensor channel of the CTD cast, not the "
        "laboratory chlorophyll the water-chemistry extract carries separately as "
        f"`Klorofyl a`, on {chl:,} rows.") + " "
      + C("C-DZ-D1-OVERLAP", "How many of the panel's station-months fall in the effort "
          "layers' years, at how many stations and in how many c-squares, is not counted by "
          "any script here: the overlap is the first thing the test must count."))
    w("")
    w(C("C-DZ-D1-META", "**The effort layers.** HELCOM's metadata record for them says they "
        "are based on VMS data, processed by ICES's working group on spatial fisheries data "
        "(WGSFD) to c-square products, by year and by quarter; for the mobile "
        "bottom-contacting gear groups — dredge, demersal seine and otter trawl, and their "
        "total — they give swept area and the surface and subsurface swept-area ratio "
        "(`sur_sar`, `subsur_sar` in the shapefiles), and these, unlike weight, value and "
        "fishing hours, are never withheld for anonymity.") + " "
      + C("C-DZ-D1-SARMODEL", "Swept-area ratio is computed, not observed; how fishing is told "
          "from steaming and how each gear's width is set is not described in either record "
          "pinned here.") + " "
      + C("C-DZ-D1-FLEET", "Vessels without VMS are not in the layers, and which vessels "
          "carried it in these years is not established from any document pinned here, so "
          "how much of the inshore fleet is missing is unknown.") + " "
      + C("C-DZ-D1-QUARTER", "The layers are totals per c-square, gear group and quarter, so "
          "timing within a quarter is gone and the test's lag can only be a whole quarter."))
    w("")
    w(C("C-DZ-D1-SEABED", "**Substrate.** `data/raw/geus/seabed_sediment_dk.gpkg`, layer "
        f"`Seabed_sedimen`, holds {sb['features']} polygons in {sb['classes']} classes of the "
        "field `sedimenten`: "
        + ", ".join(f"{c} {sb['by_class'][c]}" for c in ORDER)
        + " — counts of polygons, not of area.") + " "
      + C("C-DZ-D1-SCALE", "The layer is compiled from surveys at map scales whose "
          f"denominators, in the `scale` field, run from {lo:,} to {hi:,}, with {n_lo} "
          f"polygons at the finest scale and {n_hi} at the coarsest, so boundary precision "
          "is not uniform.") + " "
      + C("C-DZ-D1-BOUNDARY", "Carry distance to a class boundary as a covariate, and test "
          "stations near a boundary separately."))
    w("")
    w(C("C-DZ-D1-POSITION", "**Depth and position.** The CTD extract, "
        f"`data/raw/oda/ctd.csv.gz` ({mb:.1f} MB compressed), has columns beside each "
        "station's coordinates (`X_UTM32`, `Y_UTM32`) for the depth (`Dybde (m)`) and the "
        "position (`MålingX_UTM32`, `MalingY_UTM32`) of each measurement row, so one streamed "
        "pass can place each cast in the c-square it was taken in, with its depth.") + " "
      + C("C-DZ-D1-POSGAP", "How often a measurement's position differs from its station's is "
          "not counted here."))
    w("")
    w("## The null, under the constraint actually imposed")
    w("")
    w(C("C-DZ-D1-NULLWHY", "The test has a spatial arm and a within-station arm, each with its "
        "own constraint and null, and **neither null is a plain shuffle.** Effort is "
        "spatially autocorrelated and so is bathymetry, and contiguity alone makes partitions "
        f"agree: on this project's nearest-neighbour graph of {pc['stations']} stations, "
        "random connected partitions with group sizes matched to the official water bodies "
        f"agree with each other at a mean adjusted Rand index of {pc['contiguous_null_ari']} "
        "(`docs/data/areas/partition_contiguous.json`, `contiguous_null` in "
        "`scripts/partition_contiguous.py`), where the index corrects for chance against "
        "arbitrary partitions, not contiguous ones. A cell-wise shuffle of effort would "
        "repeat that mistake."))
    w("")
    w("- " + C("C-DZ-D1-NULL-SPATIAL", "**Spatial arm** (cross-sectional, the weak one). "
               "Constraint: stations sit where they sit and effort has the structure it has. "
               "Null: keep the effort field whole and break only its *registration* with the "
               "stations — random rotations and toroidal translations within a Danish sea "
               f"mask, rejecting draws that put more than {nodata:g}% of stations on no-data; "
               "plus a second null by `contiguous_null`-style connected block resampling on "
               "the c-square adjacency graph with matched block sizes. At least "
               f"{draws:,} draws, reported against both."))
    w("- " + C("C-DZ-D1-NULL-WITHIN", "**Within-station arm** (primary). Constraint: station "
               "identity, month-of-year and year are absorbed. Null: circular shifts of each "
               "station's own effort series by whole years, plus a cluster bootstrap over "
               "stations. This preserves each station's effort marginal, the seasonal cycle "
               "and effort's serial correlation, breaking only the time alignment."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-DZ-D1-S1", "Fetch and unzip the archive named above; keep the mobile "
                "bottom-contacting gear groups the record lists; count the c-squares that "
                "intersect the stations' bounding box."))
    w("2. " + C("C-DZ-D1-S2", "Assign each cast to its own c-square from its measurement "
                "coordinates; roll to station-quarter medians of the variables used below."))
    w("3. " + C("C-DZ-D1-S3", "Join `subsur_sar` of the *preceding* quarter; keep "
                "fluorescence same-quarter, not lagged."))
    w("4. " + C("C-DZ-D1-S4", "Fit near-bed oxygen on the lagged `log1p(subsur_sar)` with "
                "station, month and year fixed effects and covariates: fluorescence, near-bed "
                "temperature (solubility), near-bed salinity (stratification proxy), depth."))
    w("5. " + C("C-DZ-D1-S5", "Refit with a substrate × effort interaction; repeat the whole "
                "fit on surface oxygen as the placebo."))
    w("6. " + C("C-DZ-D1-S6", "Report every coefficient against both nulls above, never a "
                "textbook p-value."))
    w("")
    w("## What a result would, and would not, license")
    w("")
    w(C("C-DZ-D1-CONFOUND", "The obvious confound: trawlers fish where fish are, and fish are "
        "where productivity is, so any raw effort–oxygen association is that association read "
        "backwards. The within-station fixed effect, fluorescence and the substrate "
        "interaction break it, and only together: the fixed effect removes everything "
        "time-invariant about a place (depth, substrate, mean productivity, distance from a "
        "source); fluorescence absorbs the time-varying part of the same confound; and the "
        "substrate interaction is a prediction the confound does not make, since "
        "productivity-driven effort would depress oxygen wherever trawlers work, while "
        "resuspension can only do it where reduced fines exist."))
    w("")
    w(C("C-DZ-D1-LICENSE", "A mud-confined, bed-only coefficient outside both nulls would "
        "license exactly this: *trawling effort in the preceding quarter is associated with "
        "lower near-bed oxygen at Danish stations, 2016–2021, on fine substrate, beyond a "
        "null preserving the spatial and temporal structure of effort.* Not a budget "
        "attribution; not a causal claim (effort is not randomised, and a quarterly total "
        "cannot separate the trawl pass from what followed it); nothing about the fauna "
        f"outcomes {R('O3')} and {R('O7')}, since no fauna variable is here; nothing about "
        "vessels VMS does not see."))
    w("")
    w(C("C-DZ-D1-WEAK", "A null result is weakly informative: quarterly effort, a computed "
        "swept-area ratio and vessels missing from the layers can each hide a real effect. "
        "And there is no baseline before trawling: the layers begin in 2016, so the test is a "
        "contrast across places and quarters, never a before-and-after.") + " "
      + C("C-DZ-D1-CLUSTER", "Stations that share a c-square share its effort, so effort is a "
          "shared regressor and errors must cluster on the c-square."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/D1.md", page))
