#!/usr/bin/env python3
"""docs/hypodrafts/Z8.md - what the data held here can and cannot show about Z8.

Every number is read from data (live_json), from a pinned document ({read:}) or is a
stated design value with its reason; every assertion is a checked claim
(LIVE_NUMBERS.md section 11), registered in data/manual/claims.d/w3-dz.json with what
it rests on, and every field printed has a declared construction. What the draft once
said and could not justify is in docs/ARCHIVE.md, not here. The page is written
through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_z8.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED
import claims
import live

C = live.claim
R = live.ref
M06 = "https://ecos.au.dk/fileadmin/ecos/Fagdatacentre/Marin/TA_M06_Lyssvaekkelse_ver3.pdf"
CMEMS = "https://data.marine.copernicus.eu/product/{}/description"
PHOTON = "µmol fotoner/(m2*sek)"


def rd(sid, shown, phrase):
    """A number read from a pinned document: shown as it is, located by the phrase."""
    return "{read:%s:%s|%s}" % (sid, shown, phrase)


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("Z8: " + msg)


def text():
    params = claims.load()[0]["params"]
    p = params["dz_z8_perms"]
    perms = live.stated_value("dz_z8_perms", p["value"], p["reason"])

    lt = J("light.json")
    g0, gl = lt["geometry"][0], lt["geometry"][-1]
    if not g0["ratio"] < gl["ratio"]:
        refuse("the lower-to-upper Kd ratio no longer rises with start depth")
    sd, lp = lt["start_depth"], lt["params"]
    if not sd["z11_shallow_start"] < sd["z11_deep_start"]:
        refuse("shallow-start casts no longer give the shallower depth")
    lys = J("hypodraft_facts.json")["lys"]
    ctd = J("enums.json")["ctd"]
    pa, un = ctd["categorical"]["Parameter"], ctd["categorical"]["Enhed"]
    pm, pr = pa["Photometer måling"], pa["Photometer reference"]
    # the page reads each unit off by matching totals; refuse if a total stops matching
    if un["FTU"] != pa["Turbiditet"] or un["ppb"] != pa["FDOM"]:
        refuse("the FTU or ppb total no longer equals the turbidity or FDOM total")
    if un[PHOTON] != pm + pr:
        refuse("the photon-flux total no longer equals the photometer channels together")
    if un["pct"] != pa["Lysdæmpning"] + pa["Oxygenmætning"]:
        refuse("the percent total no longer equals Lysdæmpning and saturation together")
    if not pm > pr:
        refuse("the photometer reading no longer has more rows than the reference")
    share = live.step("K-SUBSET-SHARE", ctd["categorical"]["SondeNr"]["999"] / ctd["rows"] * 100)
    fd = J("hypodraft_ctd.json")["fdom"]

    o = []
    w = o.append
    w(f"# {R('Z8', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_z8.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Draft, not a result.** "
      + C("C-DZ-Z8-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes it."))
    w("")
    w(f"## Where {R('Z8')} overstates")
    w("")
    w(C("C-DZ-Z8-HALF", f"{R('Z8')} says Denmark measures broadband Kd, *which cannot be "
        "partitioned even in principle*. The first half is the protocol's own rule; the "
        "second holds for the number alone, but the missing partition is set **by "
        "protocol**, not by physics, and the archive holds, on the same casts, channels the "
        "protocol does not use."))
    w("")
    w(C("C-DZ-Z8-M06", "The governing method document is DCE's technical instruction `M06` "
        "*Lyssvækkelse* by Markager and Fossing, version "
        + rd("DZ-TA-M06", "3", "Versionsnummer: 3") + ", valid from "
        + rd("DZ-TA-M06", "04.06.2015", "Gyldig fra: 04.06.2015")
        + f" ([PDF]({M06})):"))
    w("")
    w("- " + C("C-DZ-Z8-M06-PAR", "One band, mandated: *skal der måles fotosyntetisk aktivt "
               "lys i intervallet* "
               + rd("DZ-TA-M06", "400", "i intervallet 400-700 nm også kaldet PAR") + "–"
               + rd("DZ-TA-M06", "700", "i intervallet 400-700 nm også kaldet PAR")
               + " *nm også kaldet PAR* — photosynthetically active light, one broad band."))
    w("- " + C("C-DZ-Z8-M06-SPEC", "Section `2.5.1` names the spectral mechanism and "
               "prescribes deletion as the cure: *Lysets spektrale sammensætning og spredning "
               "ændrer sig med vanddybden … en ikke-lineær hældning. I disse tilfælde kan det "
               "være nødvendigt at udelade lysmålinger fra den nederste del af vandsøjlen* — "
               "the light's spectrum changes with depth, the log-transformed profile can bend, "
               "and the lowest readings may then be left out."))
    w("- " + C("C-DZ-Z8-M06-BED", "It also sets aside the readings nearest the bed where "
               "sediment is stirred up from the bottom (*Nederst i vandsøjlen kan sediment "
               "hvirvles op fra bunden*), and it leaves which readings to drop to the "
               "fitter's experience: *Der kan ikke gives præcise anvisninger til denne "
               "procedure*.") + " "
      + C("C-DZ-Z8-WINDOW", "Leaving out the lowest readings deletes the mineral signal a "
          "partition wants, and where a fit's profile starts matters: this project's light "
          f"analysis finds the median depth at which light falls to {lp['req_lo_pct']}% of "
          f"the surface at {sd['z11_shallow_start']} m in casts whose shallowest reading lies "
          f"above {lp['start_split_m']:g} m, against {sd['z11_deep_start']} m in those "
          "starting deeper."))
    w("- " + C("C-DZ-Z8-M06-FACTOR", "Section `2.5.2`: in Danish waters the empirical "
               "constant converting Secchi depth to Kd varies between "
               + rd("DZ-TA-M06", "1.5", "mellem 1,5 og 3,6") + " and "
               + rd("DZ-TA-M06", "3.6", "mellem 1,5 og 3,6") + ", but can be as low as "
               + rd("DZ-TA-M06", "0.6", "så lav som 0,6") + " in very turbid systems where "
               "scattering matters, and up to " + rd("DZ-TA-M06", "4.1", "op til 4,1")
               + " where dissolved matter dominates the attenuation; in practice it is set "
               "to " + rd("DZ-TA-M06", "2.3", "sættes omregningskonstanten til 2,3") + ".")
      + " " + C("C-DZ-Z8-RANGE", "That range **is** the partition: the constant moves with "
                "what attenuates the light, so fixing it assumes the composition away."))
    w("")
    w("## The falsifiable consequence")
    w("")
    w(C("C-DZ-Z8-PERCAST", "Per **cast** — never a water body, which is why the area files "
        "`val_kd.bin` and `val_secchi.bin`, one value per coastal water body (`DKCOAST…`) "
        "and month, cannot serve here."))
    w("")
    w("1. " + C("C-DZ-Z8-P-ORDER", "**Ordering.** Ranking casts by the chlorophyll proxy does "
                "not reproduce the ranking by Kd, and casts above a Kd threshold fall into "
                "distinct composition types — high-FDOM/low-turbidity and "
                "high-turbidity/low-FDOM — rather than one."))
    w("2. " + C("C-DZ-Z8-P-CONST", "**The constant.** `Kd · z_Secchi` on the same station-day "
                "varies with FDOM and turbidity after station and month are removed. The "
                "instruction's own range predicts this; its fixed constant denies it."))
    w("3. " + C("C-DZ-Z8-P-ART", "**The artefact.** The apparent-Kd decline with depth — in "
                "this project's light analysis the median ratio of lower-half to upper-half Kd "
                f"is {g0['ratio']} for profiles starting between {g0['from']:g} and "
                f"{g0['to']:g} m, rising to {gl['ratio']} for those starting below "
                f"{gl['from']:g} m — **weakens as FDOM rises**, because absorption by "
                "coloured dissolved organic matter at short wavelengths narrows the spread of "
                "K(λ) across the PAR band that produces the decline. The sign is the "
                "prediction; the magnitude needs an assumed K(λ) and is not part of the "
                "test."))
    w("")
    w(C("C-DZ-Z8-EACHFAIL", "Each can fail: the ordering would leave "
        f"{R('Z8')}'s attribution complaint empty here, the constant would make the fixed "
        "constant harmless, and the artefact would refute the spectral reading of the light "
        "analysis."))
    w("")
    w("## The data held, counted")
    w("")
    w(C("C-DZ-Z8-LYS", f"**Light profiles.** `lys.csv.gz` holds {lys['rows']:,} records at "
        f"{lys['stations_with_coordinates']:,} stations with a position; this project's light "
        f"analysis counts {lt['n_casts_total']:,} casts in it with a positive Kd and a date, "
        f"{lt['n_casts_good_fit']:,} of them with a fit correlation of at least "
        f"{lp['min_fit']:g} or none reported.") + " "
      + C("C-DZ-Z8-LYSCOLS", "Each record carries the depths its regression used, `ZMin` and "
          "`ZMax` — the instruction's *øverste* and *nederst dybde som er anvendt* — and its "
          "correlation coefficient: Kd is a regression the operator fitted over a window the "
          "operator chose, a profile collapsed to one slope.") + " "
      + C("C-DZ-Z8-FIT", "Require the fit coefficient: the instruction forbids reporting a Kd "
          "converted from Secchi depth as a Kd value (*må ikke indrapporteres til databasen "
          "som Kd-værdier*), and a fitted correlation shows a record came from a profile, so a "
          "record that broke the rule cannot enter."))
    w("")
    w(C("C-DZ-Z8-CTDPARAM", "**CTD channels.** The CTD extract carries `Lysdæmpning` on "
        f"{pa['Lysdæmpning']:,} rows, `Fluorescens` on {pa['Fluorescens']:,}, `Turbiditet` on "
        f"{pa['Turbiditet']:,} and `FDOM` on {pa['FDOM']:,}, with `Photometer måling` on "
        f"{pm:,} and `Photometer reference` on {pr:,} beside them."))
    w("")
    w(C("C-DZ-Z8-UNITS", "The unit column, `Enhed`, says what they are, by count: `FTU` stands "
        f"on {un['FTU']:,} rows, exactly as many as `Turbiditet`; `ppb` on {un['ppb']:,}, as "
        f"many as `FDOM`; `{PHOTON}` on {un[PHOTON]:,}, as many as the photometer channels "
        f"together ({pm + pr:,}); and `pct` on {un['pct']:,}, as many as `Lysdæmpning` and "
        f"oxygen saturation (`Oxygenmætning`) together "
        f"({pa['Lysdæmpning'] + pa['Oxygenmætning']:,}). So turbidity and FDOM are in sensor "
        "units and the photometers in photon flux, and `Lysdæmpning` is a percentage — "
        "matching the instruction's light value in the water column as a percentage of "
        "surface irradiance (*lysværdi i vandsøjlen i procent af overfladeindstråling*), not "
        "its attenuation coefficient, whose unit is per metre.") + " "
      + C("C-DZ-Z8-REFIT", "The photometer channels — a reading and a reference, in the "
          "photon-flux unit the instruction gives for surface light — look like the "
          "underwater and surface sensors its fit is made from, one value per depth row. If "
          "they are, Kd can be refitted over a *stated* window instead of the operator's, on "
          "the same cast as the composition channels. The reading channel has more rows than "
          "the reference, so not every reading has its reference."))
    w("")
    w(C("C-DZ-Z8-FDOMSPAN", f"`FDOM` runs only from {fd['first_year']} to {fd['last_year']}, "
        "so a test on both composition channels is confined to those years; before them the "
        "extract holds no other channel for dissolved organic matter."))
    w("")
    w(C("C-DZ-Z8-PROXY", "Errors in the proxies: `ppb` and `FTU` are sensor units, not "
        "absorption coefficients; FDOM is fluorescence (fluorescent dissolved organic "
        "matter), not absorption by coloured dissolved organic matter; and turbidity is light "
        "scattered at right angles, not absorption by non-algal particles.") + " "
      + C("C-DZ-Z8-SONDE", f"`SondeNr` is the placeholder `999`, probe unknown, on "
          f"{share:.1f}% of the CTD extract's rows, so on those rows the probe, and any "
          "calibration tied to it, cannot be identified.") + " "
      + C("C-DZ-Z8-NOCLOCK", "Over all of it, the extract has no wavelength column and no "
          "time of day."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-DZ-Z8-S1", "Cast table from `lys.csv.gz` via `formats.num()`: station, "
                "date, Kd, fit, `ZMin`, `ZMax`; keep casts with a fit coefficient."))
    w("2. " + C("C-DZ-Z8-S2", "Stream `ctd.csv.gz` once, cast-contiguous (flush on key "
                "change, count reopened keys), emitting per station and date the depth-median "
                "`Fluorescens`, `FDOM` and `Turbiditet` **over `ZMin…ZMax`** — the layer the "
                "Kd was fitted over, not the whole cast."))
    w("3. " + C("C-DZ-Z8-S3", "Inner-join on station and date; report how the joined subset "
                "differs from all light casts in Kd, station and month — that selection is the "
                "first result."))
    w("4. " + C("C-DZ-Z8-S4", "Apportion Kd's variance among the proxies within station × "
                "month, then fit the ordering and the constant against `maaledybde.csv.gz` "
                "Secchi on the same station-day, and the artefact — each against the "
                "permutation null below, reported as a distribution rather than a p-value. "
                "Repeat with satellite absorption and backscatter retrievals where one reaches "
                "back before the FDOM record."))
    w("")
    w("## The null, under the constraint imposed")
    w("")
    w(C("C-DZ-Z8-NULL", "Not a regression's nominal F-null. Casts are clustered by station, "
        "seasonal and autocorrelated, and the composition channels share a station's mean "
        "level with Kd. **Permute the composition channels together, one row per cast, "
        "across casts within station × calendar month**, preserving each channel's "
        "marginals and the station/season structure, and rebuild the apportionment "
        f"{perms:,} times; the observed unique variance must beat that distribution. Same "
        "permutation for the constant and the artefact; the result is whatever the "
        "permutation returns, reported even when it exceeds the observed statistic.") + " "
      + C("C-DZ-Z8-MATCH", "The satellite arm's null is built on the matched subset: "
          "`matchup.py` records, from its first run, that casts with a same-day satellite "
          "retrieval are clearer than the rest in the same months, so the matched days are "
          "not a random sample of days."))
    w("")
    w("## The residual, named")
    w("")
    w(C("C-DZ-Z8-SUM", "`Kd = K_water + K_phyto + K_CDOM + K_NAP`. On the in-situ arm **none "
        "of the terms is in absorption units**, so this yields a variance apportionment, not "
        "a budget, and the residual holds the start-depth artefact, the operator's window "
        "choice and the time of day.") + " "
      + C("C-DZ-Z8-SATSPLIT", "The satellite arm cannot split dissolved matter from detritus: "
          "its absorption term for them (`adg`) is one combined coefficient.") + " "
      + C("C-DZ-Z8-SHRINK", "A residual is testable only by measuring a part out of it and "
          "checking that it shrinks by exactly that part — which needs absorption in units: "
          "a spectrophotometer or spectroradiometer profile beside the PAR cast.") + " "
      + C("C-DZ-Z8-ACS", "Such profiles have been taken in Danish waters: Gonçalves-Araujo "
          "and Markager (2020) mounted an AC-S spectrophotometer on the CTD frame at stations "
          "of the national monitoring programme (NOVANA) around Fyn, in autumn "
          + rd("DZ-GA-2020", "2017", "visited in the autumn 2017") + " and spring "
          + rd("DZ-GA-2020", "2019", "and spring 2019") + ", and call the instrument's "
          "incorporation into the sampling programme in "
          + rd("DZ-GA-2020", "2017", "to the sampling program in 2017")
          + " a first step toward automated, sensor-based monitoring.") + " "
      + C("C-DZ-Z8-ACSGAP", "None of the CTD extract's `Parameter` values is an absorption, so "
          "no such profile reaches the extract this project holds; until one does, the "
          "shrinkage test is joint with a spectral model."))
    w("")
    w("## What it licenses")
    w("")
    w(C("C-DZ-Z8-WOULD", "**Would:** a statement about the *record* — whether Kd's "
        "cast-to-cast variance at named stations in named months is carried mainly by the "
        "chlorophyll channel, against a permutation null, and whether the instruction's "
        "fixed constant of " + rd("DZ-TA-M06", "2.3", "sættes omregningskonstanten til 2,3")
        + " is composition-free.") + " "
      + C("C-DZ-Z8-WOULDNOT", "**Would not:** a physical budget, a causal attribution, any "
          "per-water-body or national number, or any trend."))
    w("")
    w("## Sources, and whether each is a separate production path")
    w("")
    w("- " + C("C-DZ-Z8-SRC-CTD", "**Held: the CTD extract's light and composition "
               "channels**, per depth. **Not a separate path** from the light profiles: the "
               "instruction says the light sensor is usually mounted on the CTD "
               "(*sædvanligvis monteret på CTD’en*)."))
    w("- " + C("C-DZ-Z8-SRC-131", "**Copernicus Marine "
               f"[`OCEANCOLOUR_BAL_BGC_L3_NRT_009_131`]({CMEMS.format('OCEANCOLOUR_BAL_BGC_L3_NRT_009_131')})**"
               " — near-real-time daily observations from OLCI at "
               + rd("DZ-CMEMS-131", "300", "Spatial resolution**: 300 meters")
               + " m, with an optics dataset of absorption and backscatter by dissolved and "
               "particulate matter and by phytoplankton (`ADG`, `APH`, `BBP`) from the QAA "
               "model; its catalogue record starts in "
               + rd("DZ-CMEMS-131", "2023", '"2023-04-18T00:00:00Z"') + "."))
    w("- " + C("C-DZ-Z8-SRC-208", "**Copernicus Marine "
               f"[`OCEANCOLOUR_BAL_BGC_HR_L4_NRT_009_208`]({CMEMS.format('OCEANCOLOUR_BAL_BGC_HR_L4_NRT_009_208')})**"
               " — `Sentinel-2` MSI at "
               + rd("DZ-CMEMS-208", "100", "at 100m resolution for a 20km coastal zone")
               + " m for a "
               + rd("DZ-CMEMS-208", "20", "at 100m resolution for a 20km coastal zone")
               + " km coastal zone: turbidity, suspended matter, particulate backscatter "
               "(`BBP443`) and chlorophyll, and no absorption variable; its catalogue record "
               "starts in " + rd("DZ-CMEMS-208", "2020", '"2020-01-08T00:00:00Z"') + "."))
    w("- " + C("C-DZ-Z8-SRC-CCI", "**ESA Ocean Colour CCI inherent optical properties, "
               "`v6.0`** ([CEDA](https://catalogue.ceda.ac.uk/uuid/024292dcda5d42ceb326850f89f8b40d/))"
               " — global, at approximately "
               + rd("DZ-CEDA-OCCCI", "4", "at approximately 4 km spatial resolution")
               + " km, in composites from daily to yearly, covering "
               + rd("DZ-CEDA-OCCCI", "1997", "covering the period 1997 - 2022") + " to "
               + rd("DZ-CEDA-OCCCI", "2022", "covering the period 1997 - 2022")
               + ": total absorption and backscatter, and absorption by detrital and dissolved "
               "matter and by phytoplankton, the dissolved-and-detrital term from the QAA "
               "model."))
    w("- " + C("C-DZ-Z8-SRC-MODIS", "**NASA Aqua MODIS `L3` inherent optical properties, "
               "version `2022.0`** "
               "([Earthdata](https://www.earthdata.nasa.gov/data/catalog/ob-cloud-modisa-l3m-iop-2022.0))"
               " — retrieved with the GIOP model framework, not QAA: phytoplankton absorption "
               "and combined CDOM and detritus absorption (`aph_443`, `adg_443`), from "
               + rd("DZ-NASA-IOP", "2002", '"time_start":"2002-07-04') + "."))
    w("")
    w(C("C-DZ-Z8-SRC-PATH", "Every satellite product above is a retrieval of optical "
        "properties from reflectance — a model applied to radiometry from orbit — so each is a "
        "separate production path from the ship's casts, and none is a measurement of "
        "absorption in the water."))
    w("")
    w(C("C-DZ-Z8-SRC-133", "The Baltic multiyear product already fetched, "
        "`OCEANCOLOUR_BAL_BGC_L3_MY_009_133`, names plankton, reflectances and transparency in "
        "its title and no optics, where its near-real-time sibling's title adds optics.")
      + " " + C("C-DZ-Z8-SEARCH", "Beyond these, the source register records searches of "
                "PANGAEA and of that product for spectral absorption in Danish water, with a "
                "Roskilde Fjord series as the only positive: an absence over those searches, "
                "*not a finding that none exists*."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/Z8.md", page))
