#!/usr/bin/env python3
"""docs/hypodrafts/AUDIT.md - the audit of the hypothesis drafts.

Every verdict is a checked claim (LIVE_NUMBERS.md section 11), registered in
data/manual/claims.d/w3-af.json: an argued judgement of ours, resting on what each
draft says as committed (history nodes read out of git) and, where a verdict says
something about the data, on the data claims that carry it. What the audit once said
and could not justify is in docs/ARCHIVE.md, not here. The page is written through
scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_audit.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
import claims
import live

C = live.claim
R = live.ref


def text():
    o = []
    w = o.append
    w("# Audit of the drafts")
    w("")
    w("*Generated by `scripts/pages/hypodraft_audit.py`. Each marked statement links to "
      "what it rests on.*")
    w("")
    w(C("C-AF-AU-SCOPE", "This audit reads each draft in `hypodrafts/` and each open problem "
        f"in `openproblems/` as committed at `7c4dd30`, and {R('Z8')}, first committed later, "
        "at `0138743`, against the standards in [`../AGENT_BRIEF.md`](../AGENT_BRIEF.md): "
        "what kind of thing a quantity is, a null computed rather than quoted, and the "
        "steelman rule."))
    w("")
    w("Verdicts are **sound** / **needs a stated fix** / **has an error**. Only defects are "
      "listed. Nothing here rewrites a draft.")
    w("")
    w("---")
    w("")
    w("## Per draft")
    w("")
    w(C("C-AF-AU-A1", f"**{R('A1')} — not settled here.** Its scoping is right: it says its "
        "finding *does not show the attribution is wrong*, only that one published figure "
        "cannot be what shows it is right — and the chain it examines is the one [what the "
        "sea actually receives](../NITROGEN.md) sets out, where DK-QNP takes the field "
        "surplus as a key input. Whether it misses independent support for the attribution "
        "cannot be judged here: that support would be Windolf and colleagues' paired "
        "catchment-and-estuary study, whose text could not be read."))
    w("")
    w(C("C-AF-AU-A1B", "**A1b — sound.** It states what a result would and would not "
        "license, and it names the field surplus a norm product."))
    w("")
    w(C("C-AF-AU-B1", f"**{R('B1')} — needs a stated fix.** The design is strong: exposure "
        "enters only as the combined-vs-separate class of the nearest outfall and as an "
        "*a-priori* critical rainfall depth, so rainfall cancels in the contrast.") + " "
      + C("C-AF-AU-B1-EEA", "**But its central data claim is unverified here.** Its data row "
          "counts a table of EEA bathing-water samples that nothing in this repository holds "
          "or queries, so every figure in that row, and its `shortTermPollutionSample` "
          "count, stands unchecked. **Fix:** mark the EEA row unverified until the table is "
          "fetched and counted."))
    w("")
    w(C("C-AF-AU-C1", f"**{R('C1')} — needs a stated fix.** It refuses the published "
        "iltsvind extent as a response on the ground that DCE's criterion puts "
        "stratification inside the response's definition; DCE define iltsvind by oxygen "
        "concentration alone and name stratified water as where it develops, so the extent "
        "is not circular by construction. Its choice of raw per-measurement oxygen stands on "
        "the design's own unit, the cast. Its null work is sound: it names a non-zero floor, "
        "the fully ventilated saturation, rather than assuming zero."))
    w("")
    w(C("C-AF-AU-C4", f"**{R('C4')} — sound.** It checks the Gotland file's units and "
        "provenance against the source netCDF, states its permutation floor, and gives its "
        "effective event count among what the design would not license."))
    w("")
    w(C("C-AF-AU-C6", f"**{R('C6')} — sound.** It never uses the archived `oxysat_bed` as "
        "its outcome, because it is computed from oxygen, temperature and salinity and so "
        "shares inputs with the statistic, and uses it once, as a consistency check."))
    w("")
    w(C("C-AF-AU-D1", f"**{R('D1')} — sound.** It breaks the productivity confound with a "
        "within-station fixed effect, fluorescence for the confound's time-varying part, "
        "and a substrate × effort interaction that the confound does not predict."))
    w("")
    w(C("C-AF-AU-D7", f"**{R('D7')} — sound.** It says the *monthly panel* carries no "
        "turbidity while identifying `Turbiditet` in the raw CTD — those are not in "
        "conflict — and it models the Secchi censoring that differs between its arms, which "
        "this project's light analysis counts."))
    w("")
    w(C("C-AF-AU-F3", f"**{R('F3')} — needs a stated fix.** It avoids the clarity-indicator "
        "circularity by using cover rather than depth limit, and states the part it could "
        "not remove. That part, the eelgrass light requirement, has no source here, so its "
        "adequacy call is only as good as a requirement nobody has pinned."))
    w("")
    w(C("C-AF-AU-G1", f"**{R('G1')} — sound.** It re-derived the station split on a rule it "
        "states, set the result beside the split on file, and called the split "
        "threshold-dependent. That is the correct handling, and the other drafts that use "
        "the split should have done the same."))
    w("")
    w(C("C-AF-AU-I1", f"**{R('I1')} — needs a stated fix.** It opens on the summer-peaked / "
        "year-round split carried on file as prior work, without stating the rule behind it "
        f"or noting that {R('G1')} and {R('L3')} derived other splits. **Fix:** state the "
        "rule inline and cite the brief's stated convention, as one convention among "
        "several. Its own methodological work is sound: it dissolves the classification "
        "circularity by defining the balanced panel on *presence*, which is observable per "
        "era."))
    w("")
    w(C("C-AF-AU-I3", f"**{R('I3')} — needs a stated fix.** It records that there is no "
        "time-of-day column anywhere in the archive. That is true of the **CTD extract** "
        "and not of ODA as a whole: the water-chemistry extract carries a clock value per "
        "sample. **Fix:** scope the claim to the CTD extract."))
    w("")
    w(C("C-AF-AU-K1", f"**{R('K1')} — sound.** Its point that the satellite functional types "
        "cannot carry the hypothesis stands on the files' own note that each is derived "
        "from chlorophyll. Its claim that OBIS returns cell counts through a measurement "
        "extension remains unchecked: no phytoplankton counts are held."))
    w("")
    w(C("C-AF-AU-L3", f"**{R('L3')} — needs a stated fix.** It classifies stations as "
        "summer-peaked or year-round on thresholds of the raw Rayleigh resultant length R, "
        "and states no minimum number of observations. Under such a rule a station with a "
        "single observation has the largest R possible and counts as summer-peaked whenever "
        "that observation fell in summer, so the split can measure scarcity rather than "
        "season. **Fix:** redo the split under the brief's convention, which classifies on "
        "Z = N·R² and calls a station year-round only when it has enough observations, or "
        "drop the split arm and rely on the core panel.") + " "
      + C("C-AF-AU-L3-HEAD", "**The draft's headline is not touched by this:** it reports its "
          "no-trend simulation null on a fixed core panel as well as on the split arms, and "
          "the core panel does not use the split."))
    w("")
    w(C("C-AF-AU-Z8", f"**{R('Z8')} — sound.** It extracted `TA M06` as a primary document "
        "rather than summarising it, and names its residual honestly: *so this yields a "
        "variance apportionment, not a budget*."))
    w("")
    w(C("C-AF-AU-A7", f"**{R('A7')} — sound.** It downloaded and parsed the flux dataset "
        "rather than citing it, and reports none of its stations in the Kattegat, the "
        "Belts, the Sound or any Danish fjord: a negative it counted rather than asserted."))
    w("")
    w(C("C-AF-AU-E7", f"**{R('E7')} — sound.** It pre-commits to a reclassification test "
        "that would make the file wrong."))
    w("")
    w(C("C-AF-AU-J1", f"**{R('J1')} — sound.** It took the new-metric option seriously, "
        "wrote the metric down precisely enough to be rejected, then rejected it for reasons "
        "it computed rather than by asserting absence."))
    w("")
    w(C("C-AF-AU-R6", f"**{R('R6')} — sound.** It reports that Denmark had a written national "
        "method for its own variables and stopped running it, and it states a "
        "reclassification test in advance."))
    w("")
    w("---")
    w("")
    w("## What the set gets systematically wrong")
    w("")
    w("1. " + C("C-AF-AU-W1", "**Inherited figures are not re-derived, and the one "
                f"convention that matters was written down in none of them.** {R('G1')}, "
                f"{R('I1')} and {R('L3')} each split the stations into summer-peaked and "
                f"year-round: {R('G1')} on the share of a station's months falling in "
                f"May–October, {R('L3')} on thresholds of the raw resultant length, "
                f"{R('I1')} on the split carried on file. **This is the applefication failure "
                "in its purest form: a category everyone uses and nobody defines.** The "
                "brief's section on stated conventions fixes one: classify on Z = N·R², and "
                "call a station year-round only when it has enough observations for the test "
                "to reject."))
    w("2. " + C("C-AF-AU-W2", "**Absence is scoped to the search, not the world — except "
                f"where it isn't.** {R('D7')} gets this right (*the monthly panel carries no "
                f"turbidity*), {R('I3')} gets it wrong (*no time of day* anywhere in the "
                "archive). The difference is a clause.") + " "
      + C("C-AF-AU-W2-RULE", "Every absence claim in these files should name the *file* it "
          "is absent from, never \"the archive\"."))
    w("3. " + C("C-AF-AU-W3", "**Quantity kinds are named case by case, not by rule.** "
                f"{R('A1')} calls its attribution a residual, A1b calls the field surplus a "
                f"norm product, {R('B1')} calls per-outfall discharge volume a model output "
                f"and {R('G1')} names its estimator; {R('C6')} keeps a derived channel out of "
                f"its outcome and {R('Z8')} calls its residual a variance apportionment. The "
                "brief asks for the kind beside every quantity."))
    w("4. " + C("C-AF-AU-W4", f"**The open problems pre-commit.** {R('E7')} and {R('R6')} "
                "each state in advance the reclassification test that would move them."))
    w("5. " + C("C-AF-AU-W5", "**Nobody checked anyone else.** The station split is a defect "
                "no single draft could show: it appears only when the drafts are read side by "
                "side. **This audit is the missing step, and it should run after every batch "
                "rather than once.**"))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except (live.Unjustified, claims.Refused) as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/AUDIT.md", page))
