#!/usr/bin/env python3
"""docs/hypodrafts/D1.md - generated from the hand-written draft as committed at c601feb.

The prose is the draft's, moved here verbatim and then made checkable: counts of
files held in this repository read live from data/derived/drafts_b_counts.json;
counts the drafting session made from external sources or one-off runs carried as
quotations of that commit (located references, {was:COMMIT:FILE:phrase with @@}); register IDs as {ref:}; chemical species
as {chem:}. See scripts/pages/drafts_b_page.py and LIVE_NUMBERS.md.

    python3 scripts/pages/hypodraft_d1.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from drafts_b_page import render

TEXT = r'''# {ref:D1|title}

*Generated by `scripts/pages/hypodraft_d1.py` from the draft as committed at `c601feb`. Counts of files held in this repository are read live. Counts that session made from external sources or from one-off runs are quotations of that commit - what the draft reported, shown as such, not re-derived by the build.*


**Status: testable.** HYPOTHESES.md calls VMS/AIS effort "the single most important
missing layer in this whole register". It is a {was:c601feb:docs/hypodrafts/D1.md:It is a @@ MB CC BY} MB `CC BY 4.0` zip. Nothing here has
been run and nothing downloaded; the fetch is step 1.

## The observable consequence, stated so it can fail

Trawling as an oxygen mechanism (not a fauna mechanism) says: gear dragging fine reduced
sediment resuspends sulphide and labile organics, which consume oxygen where released — at
the bed, within weeks, **and only where fine reduced sediments exist.** Per station-quarter:

1. **Within station.** Near-bed oxygen anomaly is lower in that station's own quarters
   following high subsurface swept-area ratio (SubsurfSAR) in its c-square than in its
   own quarters following low SubsurfSAR, after removing station mean, month-of-year and
   year.
2. **Substrate interaction.** The effect is present on *Mud and sandy mud* / *Muddy sand*
   / *Quaternary clay and silt* and absent on *Sand* / *Gravel and coarse sand* /
   *Till* / *Sedimentary rock*.
3. **Placebo.** No comparable effect in near-**surface** oxygen at the same stations.

**Falsified if:** the within-station coefficient lies inside the null distribution below;
**or** the coarse-substrate coefficient is indistinguishable from the mud one; **or** the
surface placebo moves with effort as strongly as the bed. The substrate interaction and the surface placebo are what make this a
test of trawling rather than of where fish are.

## The data, named, counted, and classed

**In repo.** `docs/data/areas/stations_series.{json,bin}` — {fig:dbx_ss_total} station-months, {fig:dbx_ss_stations}
stations, 1980–2026, monthly median per station per variable. Verified by reading the
binary: `oxy_bed` {fig:dbx_ss_oxy_bed} station-months total, **{was:c601feb:docs/hypodrafts/D1.md:station-months total, **@@ in 2016–2021 at} in 2016–2021 at {was:c601feb:docs/hypodrafts/D1.md:in 2016–2021 at @@ stations**, of which} stations**, of
which {was:c601feb:docs/hypodrafts/D1.md:of which @@ stations cover} stations cover ≥{was:c601feb:docs/hypodrafts/D1.md:cover ≥@@ distinct quarters,} distinct quarters, {was:c601feb:docs/hypodrafts/D1.md:≥8 distinct quarters, @@ ≥12, 140 ≥16,} ≥{was:c601feb:docs/hypodrafts/D1.md:distinct quarters, 180 ≥@@, 140 ≥16, 79}, {was:c601feb:docs/hypodrafts/D1.md:quarters, 180 ≥12, @@ ≥16, 79 ≥20.} ≥{was:c601feb:docs/hypodrafts/D1.md:180 ≥12, 140 ≥@@, 79 ≥20. Stations}, {was:c601feb:docs/hypodrafts/D1.md:≥12, 140 ≥16, @@ ≥20. Stations occupy} ≥{was:c601feb:docs/hypodrafts/D1.md:140 ≥16, 79 ≥@@. Stations occupy **791}. Stations occupy
**{was:c601feb:docs/hypodrafts/D1.md:Stations occupy **@@ distinct 0.05° cells**;} distinct {was:c601feb:docs/hypodrafts/D1.md:occupy **791 distinct @@° cells**; 215}° cells**; {was:c601feb:docs/hypodrafts/D1.md:cells**; @@ carry `oxy_bed`} carry `oxy_bed` in-window, {was:c601feb:docs/hypodrafts/D1.md:`oxy_bed` in-window, @@ in} in ≥{was:c601feb:docs/hypodrafts/D1.md:in-window, 175 in ≥@@ quarters. `fluo` 7,694 in-window} quarters. `fluo`
{was:c601feb:docs/hypodrafts/D1.md:quarters. `fluo` @@ in-window station-months,} in-window station-months, **{was:c601feb:docs/hypodrafts/D1.md:station-months, **@@ of them} of them sharing a station-month with `oxy_bed`** —
the productivity covariate is nearly complete on the response. `oxy_surf` {fig:dbx_ss_oxy_surf} total
(placebo). {was:c601feb:docs/hypodrafts/D1.md:76,963 total (placebo). @@ of 1,415 stations} of {fig:dbx_ss_stations} stations lie east of {was:c601feb:docs/hypodrafts/D1.md:lie east of @@°E. *Class}°E. *Class 3 (aggregation):* monthly medians
over irregular casts, so a station-quarter is a median of medians. *Class 2* for `fluo`, a
relative proxy, not chlorophyll.

**To fetch (small).** ICES/HELCOM VMS product, figshare `20310255`,
`2022_helcom_spatial_effort_intensity.zip`, **{was:c601feb:docs/hypodrafts/D1.md:`2022_helcom_spatial_effort_intensity.zip`, **@@ MB, CC} MB, `CC BY 4.0`** (size and licence from
the figshare API). Fields per HELCOM metadata record
`0195e2c6-6b83-49ea-a0db-41f14a316c87`: `c-square`, `mid_lat`, `mid_lon`, `Year`, `quarter`,
`geargroup`, `SurfSAR`, `SubsurfSAR`, `Fishing_ho` — **{was:c601feb:docs/hypodrafts/D1.md:`Fishing_ho` — **@@° c-square, quarterly,}° c-square, quarterly,
2016–2021**, HELCOM area, covering every station east of {was:c601feb:docs/hypodrafts/D1.md:station east of @@°E. *Class}°E.
*Class 7 (model-as-datum):* SAR is not measured — pings are interpolated to tracks, fishing
inferred from a speed rule, gear width imputed from vessel length by métier. *Class 6
(absent dimension):* VMS is mandatory only above {was:c601feb:docs/hypodrafts/D1.md:only above @@ m, with} m, with {was:c601feb:docs/hypodrafts/D1.md:above 12 m, with @@–15 m exemptions inside}–{was:c601feb:docs/hypodrafts/D1.md:m, with 12–@@ m exemptions inside} m exemptions inside
territorial waters, so the small inshore fleet is structurally absent — in the Belt Sea and
Øresund that is the fleet. *Class 3:* quarterly per-gear-group totals; within-quarter timing
is gone.

**Optional, larger.** ICES/OSPAR annual layers 2009–2020, figshare `18601508`, **{was:c601feb:docs/hypodrafts/D1.md:2009–2020, figshare 18601508, **@@ MB**, CC BY 4.0} MB**,
`CC BY 4.0` — annual only, and only for the {was:c601feb:docs/hypodrafts/D1.md:for the @@ North Sea} North Sea stations. Attended work.

**Substrate.** `data/raw/geus/seabed_sediment_dk.gpkg`, layer `Seabed_sedimen`, EPSG:25832
— verified: **{fig:dbx_sb_features} polygons**, field `sedimenten`, {fig:dbx_sb_classes} classes (Sand {fig:dbx_sb_sand}, Till/diamicton {fig:dbx_sb_till},
Gravel and coarse sand {fig:dbx_sb_gravel}, Muddy sand {fig:dbx_sb_muddysand}, Quaternary clay and silt {fig:dbx_sb_clay}, Mud and sandy mud {fig:dbx_sb_mud},
Sedimentary rock {fig:dbx_sb_rock}). *Class 4 (schema conflation):* one field compiled from surveys at
{was:c601feb:docs/hypodrafts/D1.md:compiled from surveys at @@}:{was:c601feb:docs/hypodrafts/D1.md:surveys at 1:@@ through 1:500,000 (`scale`:} through {was:c601feb:docs/hypodrafts/D1.md:surveys at 1:5,000 through @@:500,000 (`scale`: 58 at}:{was:c601feb:docs/hypodrafts/D1.md:at 1:5,000 through 1:@@ (`scale`: 58 at 25k,} (`scale`: {was:c601feb:docs/hypodrafts/D1.md:through 1:500,000 (`scale`: @@ at 25k, 26} at {was:c601feb:docs/hypodrafts/D1.md:1:500,000 (`scale`: 58 at @@k, 26 at 100k,}k, {was:c601feb:docs/hypodrafts/D1.md:58 at 25k, @@ at 100k, 7} at {was:c601feb:docs/hypodrafts/D1.md:at 25k, 26 at @@k, 7 at 5k,}k, {was:c601feb:docs/hypodrafts/D1.md:26 at 100k, @@ at 5k, 7} at {was:c601feb:docs/hypodrafts/D1.md:at 100k, 7 at @@k, 7 at 500k,}k, {was:c601feb:docs/hypodrafts/D1.md:7 at 5k, @@ at 500k, 5} at {was:c601feb:docs/hypodrafts/D1.md:at 5k, 7 at @@k, 5 at 400k,}k, {was:c601feb:docs/hypodrafts/D1.md:7 at 500k, @@ at 400k, 5} at {was:c601feb:docs/hypodrafts/D1.md:at 500k, 5 at @@k, 5 at 200k),}k,
{was:c601feb:docs/hypodrafts/D1.md:5 at 400k, @@ at 200k), so} at {was:c601feb:docs/hypodrafts/D1.md:at 400k, 5 at @@k), so boundary precision}k), so boundary precision is not uniform. Carry distance-to-boundary as a covariate
and test near-boundary stations separately.

**Depth and true position.** `data/raw/oda/ctd.csv.gz` ({was:c601feb:docs/hypodrafts/D1.md:`data/raw/oda/ctd.csv.gz` (@@ MB gzip)} MB gzip) carries `Dybde (m)`
and `MålingX_UTM32`/`MalingY_UTM32` per measurement. With {was:c601feb:docs/hypodrafts/D1.md:per measurement. With @@% of measurements}% of measurements at coordinates
differing from their station's, the station→c-square join is itself an error source; one
streamed pass places each cast in the c-square it was taken in and yields cast depth.

## The null, under the constraint actually imposed

Two arms, two constraints, two nulls, **neither a plain shuffle.** Effort is spatially
autocorrelated and so is bathymetry; this project has measured what that alone buys — two
contiguity-constrained partitions of these stations agree at ARI {was:c601feb:docs/hypodrafts/D1.md:agree at ARI @@ against a nominal} against a nominal {was:c601feb:docs/hypodrafts/D1.md:nominal @@ (`docs/data/areas/partition_contiguous.json`,}
(`docs/data/areas/partition_contiguous.json`, `contiguous_null` in
`scripts/partition_contiguous.py`). A cell-wise shuffle repeats that mistake.

- **Spatial arm** (cross-sectional, the weak one). Constraint: stations sit where they sit
  and effort has the structure it has. Null: keep the effort field whole, break only its
  *registration* with the stations — random rotations and toroidal translations within a
  Danish sea mask, rejecting draws putting >{was:c601feb:docs/hypodrafts/D1.md:draws putting >@@% of stations}% of stations on no-data; plus a second null by
  `contiguous_null`-style connected block resampling on the c-square adjacency graph with
  matched block sizes. ≥{was:c601feb:docs/hypodrafts/D1.md:sizes. ≥@@ draws, reported} draws, reported against both.
- **Within-station arm** (primary). Constraint: station identity, month-of-year and year
  are absorbed. Null: circular shifts of each station's own effort series by whole years,
  plus a cluster bootstrap over stations. This preserves each station's effort marginal, the
  seasonal cycle and effort's serial correlation, breaking only the time alignment.

## Procedure

1. Fetch and unzip the {was:c601feb:docs/hypodrafts/D1.md:unzip the @@ MB product;} MB product; keep `geargroup` in the mobile bottom-contacting
   set (otter trawl, beam trawl, dredge); count c-squares intersecting the station bounding
   box — **not established here.**
2. Assign each cast to its own c-square from its measurement coordinates; roll to
   station-quarter medians of the five variables used below.
3. Join SubsurfSAR of the *preceding* quarter; keep fluorescence same-quarter, not lagged.
4. Fit near-bed oxygen on lagged log({was:c601feb:docs/hypodrafts/D1.md:lagged log(@@+SubsurfSAR) with}+SubsurfSAR) with station, month and year fixed
   effects and covariates: fluorescence, near-bed temperature (solubility), near-bed
   salinity (stratification proxy), depth.
5. Refit with a substrate × effort interaction; repeat the whole fit on surface oxygen as
   the placebo.
6. Report every coefficient against the two nulls above, never a textbook p-value.

## What a result would, and would not, license

The obvious confound: trawlers fish where fish are, and fish are where productivity is, so
any raw effort–oxygen association is that association read backwards. Three things break it,
and only together — the within-station fixed effect removes everything time-invariant about
a place (depth, substrate, mean productivity, distance from a source); fluorescence absorbs
the time-varying part of the same confound; and the substrate interaction is a prediction
the confound does not make, since productivity-driven effort would depress oxygen wherever
trawlers work, while resuspension can only do it where reduced fines exist.

A mud-confined, bed-only coefficient outside both nulls would license exactly this:
*trawling effort in the preceding quarter is associated with lower near-bed oxygen at Danish
stations, 2016–2021, on fine substrate, beyond a null preserving the spatial and temporal
structure of effort.* Not a budget attribution; not a causal claim (effort is not randomised,
and quarterly SAR cannot separate the trawl pass from what followed it); nothing about fauna
outcomes {ref:O3} and {ref:O7}, since no fauna variable is here; nothing about the fleet VMS cannot see.

A null is weakly informative: six years, {was:c601feb:docs/hypodrafts/D1.md:six years, @@ observations, quarterly} observations, quarterly effort and a
modelled SAR missing the inshore fleet can all fail to see a real effect. And there is no
pre-trawling baseline — trawling predates the 1980 record start, so this is contrast across
places and quarters, never before-and-after.

**Overlap, precisely.** Effort is quarterly 2016–2021 against a monthly 1980–2026 record:
{was:c601feb:docs/hypodrafts/D1.md:monthly 1980–2026 record: @@ quarters, 8,396 near-bed} quarters, {was:c601feb:docs/hypodrafts/D1.md:quarters, @@ near-bed} near-bed station-months, {was:c601feb:docs/hypodrafts/D1.md:near-bed station-months, @@% of}% of `oxy_bed`. OSPAR's 2009–2020 layers
would raise that to {was:c601feb:docs/hypodrafts/D1.md:that to @@ station-months at} station-months at {was:c601feb:docs/hypodrafts/D1.md:station-months at @@ stations, but} stations, but at **annual** resolution,
destroying the lag structure that makes the within-station arm a test rather than a
correlation. The {was:c601feb:docs/hypodrafts/D1.md:correlation. The @@° cell}° cell is coarse against the station field — {was:c601feb:docs/hypodrafts/D1.md:the station field — @@} of {was:c601feb:docs/hypodrafts/D1.md:— 262 of @@ cells hold more} cells hold more
than one station — so effort is a shared regressor and errors must cluster on the c-square.
'''

if __name__ == "__main__":
    sys.exit(render("docs/hypodrafts/D1.md", TEXT))
