#!/usr/bin/env python3
"""docs/hypodrafts/I1.md - what the data held here can and cannot show about I1.

Every number is read from data (live_json) or is a stated design value with its
reason; every assertion is a checked claim (LIVE_NUMBERS.md section 11), registered
in data/manual/claims.d/w3-gi.json with what it rests on, and every field printed
has a declared construction. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_i1.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED
import claims
import live

C = live.claim
R = live.ref
FIRST, LAST = 1985, 2024


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("I1: " + msg)


def text():
    params = claims.load()[0]["params"]

    def P(name):
        """A design value the test chooses, declared with its reason."""
        p = params[name]
        return live.stated_value(name, p["value"], p["reason"])

    era, reps, band = P("gi_i1_era_years"), P("gi_i1_reps"), P("gi_i1_band")
    if (LAST - FIRST + 1) % int(era):
        refuse("the eras no longer tile 1985-2024")

    ss = J("drafts_b_counts.json")["stations_series"]
    ob = ss["variables"]["oxy_bed"]
    if int(J("hypodraft_facts.json")["series_by_variable"]["year0"]) != 1980:
        refuse("the page says the panel's months count from January 1980; it no longer does")
    per_point = ss["bin_bytes"] / ss["total_station_months"]
    if float(per_point) != 8.0:
        refuse("the binary is no longer eight bytes per station-month")

    ev = J("hypotheses_evidence.json")["register"]
    reg = J("hypodraft_facts.json")["stations_register"]
    if ev["rows"] != reg["rows"]:
        refuse("the two readers of the station register now count different rows")
    same = live.step("K-SUBSET-SHARE", ev["rows_start_equals_end"] / ev["rows_with_both_dates"] * 100)
    if float(same) < 99:
        refuse("the page says StartDato equals SlutDato on nearly every row; it no longer does")

    o = []
    w = o.append
    w(f"# {R('I1', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_i1.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w(f"**Hypothesis.** {R('I1')}: stations were added, moved and dropped over the record, "
      "so a published trend can be a trend in where you looked.")
    w("")
    w("**Draft, not a result.** "
      + C("C-GI-I1-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes the June–September counts per era, the balanced panel "
          "or either trajectory, so no count of them, no band and no p-value is reported "
          "here."))
    w("")
    w("## The observable consequence, stated so it can fail")
    w("")
    w(C("C-GI-I1-DESIGN", "Hold the station set fixed and the season fixed, and recompute "
        f"the June–September near-bed oxygen trajectory {FIRST}–{LAST} in eras of {era:g} "
        "years."))
    w("")
    w("- " + C("C-GI-I1-SUPPORT", f"**{R('I1')} is supported** if the era-to-era change "
               "measured on the fixed set differs from the change measured on the full "
               "pooled record by more than the fixed set's own sampling band — that is, the "
               "pooled trajectory lies outside the band in at least one era."))
    w("- " + C("C-GI-I1-FAIL", f"**{R('I1')} fails** if the two trajectories track each "
               "other inside the band in every era — a real possible outcome, and the "
               "interesting one: the network's turnover would then not have moved the "
               "number, and the composition objection could be set aside for this variable."))
    w("")
    w("## The data held, counted here")
    w("")
    w(C("C-GI-I1-PANEL", "`docs/data/areas/stations_series.{json,bin}` holds "
        f"{ss['total_station_months']:,} station-months at {ss['n_stations']:,} stations, in "
        f"{ss['months']:,} monthly slots from January 1980, for {ss['n_variables']:,} "
        f"variables; the `.bin` is {ss['bin_bytes']:,} bytes, exactly {per_point:.0f} bytes "
        "per station-month, as the layout's `uint16` station index, `uint16` month index and "
        "`float32` value per point imply. The variable used, `oxy_bed`, is held on "
        f"{ob['n']:,} station-months at {ob['stations']:,} stations."))
    w("")
    w(C("C-GI-I1-BALRULE", "**Balanced panel:** the stations with a June–September "
        "`oxy_bed` value in *every* era. Its size, and the share of June–September values "
        "outside it, have not been computed here."))
    w("")
    w("**What the values carry.**")
    w("")
    w("- " + C("C-GI-I1-AGG", "*Aggregation.* Each value is already a median per station, "
               "month and depth layer, over every value in that layer of every cast that "
               "month; how many casts went into it is not stored, so "
               f"{R('I3')}'s effort confound cannot be controlled inside this file: a station "
               "visited once and one visited often weigh the same."))
    w("- " + C("C-GI-I1-EVENMED", "*Resolution.* Where a station-month holds an even number "
               "of values, its median is the mean of the two middle values, so a stored value "
               "can sit between the steps the raw values were reported in."))
    w("- " + C("C-GI-I1-CLOCK", "*Hour.* The CTD extract the panel is built from has no "
               "time of day in any row and no column for it, so the diel oxygen swing "
               "aliases into whichever hour the boat went, per station. The water-chemistry "
               "extract does carry clock values, which can bound the hour only where a cast "
               "shares its day with a bottle."))
    w("")
    w(C("C-GI-I1-REGISTER", "**The station register cannot supply station lifespans.** "
        f"`data/raw/oda/stations.csv` holds {ev['rows']:,} rows and {reg['stations']:,} "
        "distinct `ObservationsstedNr`, and carries only "
        f"{ev['series_stations_in_register']:,} of the {ev['series_stations']:,} series "
        f"stations. `StartDato` equals `SlutDato` on {ev['rows_start_equals_end']:,} of the "
        f"{ev['rows_with_both_dates']:,} rows with both dates ({same:.1f}%): the field holds a "
        "visit date, not a station lifespan — a column named as a validity period carrying "
        "an event date.") + " "
      + C("C-GI-I1-PRESENCE", f"So the start and end dates {R('I1')} needs are not held; "
          "presence must be derived from the observation record itself, era by era."))
    w("")
    w("## The null, under the constraint actually imposed")
    w("")
    w(C("C-GI-I1-NULLCONSTR", "The constraint is *a fixed station set × a fixed season "
        "window*, which shrinks n and clusters it into as many groups as the panel has "
        "stations. The relevant null is therefore **not** the sampling distribution of a "
        "median over independent draws, and no published standard error applies."))
    w("")
    w(C("C-GI-I1-BOOT", "**Primary null.** `H0`: the pooled trajectory is what the fixed "
        "network would have shown. Cluster bootstrap over the panel's stations — draw as "
        "many stations as the panel holds, *with replacement*, carrying each station's "
        "entire era-by-era June–September value set, and recompute Δ_fixed(e) = med(e) − "
        f"med(first era). {reps:,.0f} replicates give a percentile band per era; reject "
        f"`H0` where Δ_pooled(e) falls outside the {band:g}% band.") + " "
      + C("C-GI-I1-UNIT", "The station is the resampling unit because observations are not "
          "independent within it; resampling observations would understate the band, by up "
          "to a factor of √(observations per station) when a station's observations move "
          "together."))
    w("")
    w(C("C-GI-I1-SECONDARY", "**Secondary null, for the season channel.** Month-stratified "
        "station-label permutation: within each (era, calendar-month) cell, permute station "
        "labels among observations. Era n, month composition and every visit schedule stay "
        "fixed; only the association between *which* station and *what value* is destroyed. "
        "It will almost certainly reject — stations differ in depth and level by "
        f"construction — so it is a check on the season channel, not a test of {R('I1')}. "
        "Do not present rejection here as support."))
    w("")
    w(C("C-GI-I1-MULT", "**Multiplicity.** Pre-register the contrast between the last era "
        "and the first as primary; treat the intermediate eras as descriptive, "
        "Holm-corrected."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-GI-I1-P1", "Read `stations_series.bin` at the `oxy_bed` offset the "
                "`.json` gives; decode the `uint16` station index, the `uint16` month index "
                "and the `float32` value; `year = 1980 + month//12`, calendar month = "
                "`month%12 + 1`."))
    w("2. " + C("C-GI-I1-P2", f"Keep June–September, {FIRST}–{LAST}. Assign eras."))
    w("3. " + C("C-GI-I1-P3", "Balanced panel = the intersection of the per-era station "
                "sets."))
    w("4. " + C("C-GI-I1-P4", "Compute Δ_pooled(e) and Δ_fixed(e)."))
    w("5. " + C("C-GI-I1-P5", "Run both nulls above."))
    w("6. " + C("C-GI-I1-P6", "Repeat for `oxysat_bed`, `sal_bed` and `temp_bed`. Salinity "
                "and oxygen saturation are computed (from conductivity and temperature, and "
                "from oxygen, temperature and salinity), so these are not independent "
                "replications: a consistent result across them is one result, not several."))
    w("")
    w(C("C-GI-NOLABEL", "No script in this repository defines a split of the stations by "
        "the season they are sampled in, so no such label enters this design.") + " "
      + C("C-GI-I1-CIRC", "**On the classification circularity.** A label that sorts "
          "stations by the season of their sampling, made on each station's *whole* record, "
          "labels a station that switched regime by its aggregate — contaminated by the very "
          "time-variation under test. This design avoids the problem rather than fixing it: "
          "the balanced panel is defined by **presence**, observable per era, and no "
          "behavioural label enters the primary test. Any secondary analysis wanting such a "
          "label must assign it **within era**, and report the switch rate before using a "
          "pooled label."))
    w("")
    w("## What a result would and would not license")
    w("")
    w(C("C-GI-I1-WOULD", "**Would license.** Whether, at the positions watched in every era, "
        "the June–September near-bed oxygen change is the change the pooled record reports "
        "— and if not, a quantified size for the composition contribution."))
    w("")
    w("**Would not license.**")
    w("")
    w("- " + C("C-GI-I1-NOTWB", "Any statement about a water body. The panel's stations are "
               "wherever they happen to be; they are not a designed sample of anything, and "
               "aggregating them into Vandområder would import the model assumption this "
               "repository refuses."))
    w("- " + C("C-GI-I1-NOTTRUE", "A claim that the fixed-panel trajectory is the *true* "
               "trend. The panel is survivorship-selected: stations present in every era may "
               "differ from the ones that came and went, in depth, programme or place. "
               "Holding the network fixed trades a composition bias for a selection bias; it "
               "does not remove bias. The honest reading of agreement is “turnover did not "
               "move this number”, not “this is what the sea did”."))
    w("- " + C("C-GI-I1-NOTCAUSE", "Anything about oxygen *causes*. Composition is an "
               "instrument question."))
    w("- " + C("C-GI-I1-NOTTRANSFER", "Transfer to other variables, other seasons, or the "
               f"years before {FIRST}, which the design leaves out."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/I1.md", page))
