#!/usr/bin/env python3
"""docs/hypodrafts/G1.md - what the data held here can and cannot show about G1.

Every number is read from data (live_json) or is a stated design value with its
reason; every assertion is a checked claim (LIVE_NUMBERS.md section 11), registered
in data/manual/claims.d/w3-gi.json with what it rests on, and every field printed
has a declared construction. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/hypodraft_g1.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED
import claims
import live

C = live.claim
R = live.ref
NEED = ("oxy_bed", "temp_bed", "sal_bed", "temp_surf", "sal_surf")


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("G1: " + msg)


def text():
    params = claims.load()[0]["params"]

    def P(name):
        """A design value the test chooses, declared with its reason."""
        p = params[name]
        return live.stated_value(name, p["value"], p["reason"])

    miny, span = P("gi_g1_min_years"), P("gi_g1_min_span")

    ss = J("drafts_b_counts.json")["stations_series"]
    v = ss["variables"]
    if not set(NEED) | {"oxysat_bed"} <= set(v):
        refuse(f"the panel's variables are now {sorted(v)}, not those the page names")
    if int(J("hypodraft_facts.json")["series_by_variable"]["year0"]) != 1980:
        refuse("the page says the panel's months count from January 1980; it no longer does")
    if not v["oxysat_bed"]["n"] < v["oxy_bed"]["n"]:
        refuse("the page says saturation is held on fewer bed station-months than oxygen")
    n = {k: v[k]["n"] for k in NEED}
    rarest = min(n.values())

    td = J("hypodraft_ctd.json")["temperature_decimals"]
    le1, trows = td["at_most_one_decimal"], td["rows"]
    if not le1 * 2 < trows:
        refuse("the page says most CTD temperature rows carry more than one decimal")
    pct = live.step("K-SUBSET-SHARE", le1 / trows * 100)

    o = []
    w = o.append
    w(f"# {R('G1', title=True)}")
    w("")
    w("*Generated by `scripts/pages/hypodraft_g1.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w("**Draft, not a result.** "
      + C("C-GI-G1-STATUS", "The test this page specifies has not been run: no script in "
          "this repository computes the solubility term, the deficit or their slopes on the "
          "station panel, so no slope, share or null is reported here."))
    w("")
    w("## The hypothesis, and why it needs splitting before it can be tested")
    w("")
    w(f"{R('G1')} predicts “monotone worsening independent of load”, and offers that as "
      "why load reduction has not produced the expected recovery. "
      + C("C-GI-G1-ROUTES", "Warming reaches near-bed oxygen by the routes it names — "
          "**solubility**, **stratification** and the **rate of respiration** — and only the "
          "first lowers near-bed oxygen whatever is consumed there; the other two act through "
          "the consumption beneath the stratified layer, which the load feeds.") + " "
      + C("C-GI-G1-QUESTION", f"So {R('G1')}'s testable content is not *does oxygen fall* "
          "but **what share of the long-term fall is the solubility ceiling falling**."))
    w("")
    w("## The observable consequence, stated so it can be falsified")
    w("")
    w(C("C-GI-G1-CSAT", "Per station-month, `C_sat` is the oxygen solubility at the panel's "
        "near-bed temperature and salinity, from a published solubility equation for "
        "seawater, in mg/l; then `O_bed = C_sat(T_bed, S_bed) − D`, so "
        "`dO/dt ≡ dC_sat/dt − dD/dt`."))
    w("")
    w(C("C-GI-G1-DEFICIT", "`C_sat` is computed from temperature and salinity by an equation "
        "from outside the archive, so the first term is **computed, not estimated** from it. "
        "The deficit `D` is solubility-neutral by construction and carries the rest: "
        "consumption, failed ventilation, advection."))
    w("")
    w(C("C-GI-G1-A", "**`G1-a`:** *the decline is not mostly solubility* — `dC_sat/dt` is a "
        "minority of `dO/dt`. Falsified if the solubility term equals or exceeds the observed "
        "decline."))
    w("")
    w(C("C-GI-G1-B", "**`G1-b`:** *`dD/dt > 0`* — the deficit widens, as it must if warming "
        "drives respiration or stratification faster than ventilation recovers. Falsified by "
        "`dD/dt ≤ 0`, or by a `dD/dt` indistinguishable from the year-block null. `G1-b` "
        "carries the load-independence claim; `G1-a` decides whom the finding is about."))
    w("")
    w("## The data held, counted here")
    w("")
    w(C("C-GI-G1-DATA", "`docs/data/areas/stations_series.{json,bin}` holds "
        f"{ss['total_station_months']:,} station-months at {ss['n_stations']:,} stations, in "
        f"{ss['months']:,} monthly slots from January 1980, each value a median per station "
        "and month. The variables the identity needs are held on: "
        f"`oxy_bed` {n['oxy_bed']:,}, `temp_bed` {n['temp_bed']:,}, `sal_bed` "
        f"{n['sal_bed']:,}, `temp_surf` {n['temp_surf']:,} and `sal_surf` {n['sal_surf']:,} "
        "station-months.") + " "
      + C("C-GI-G1-JOIN", "No script here joins them or applies a plausibility filter; a "
          "station-month carrying every one of them can be no more common than the rarest, "
          f"so the joined panel holds at most {rarest:,} station-months before any filter."))
    w("")
    w(C("C-GI-G1-BEDDEF", "“Near the bed” and “near the surface” are not fixed depths: "
        "`stations_series.py` takes, for each cast, the values in the deepest and in the "
        "shallowest part of the cast's own sampled depth range, cut at the fraction `0.25` "
        "of that range, and puts every such value in a station-month into one median. So "
        "`D` can pair temperature, salinity and oxygen from different casts and depths."))
    w("")
    w(C("C-GI-G1-PANELRULE", f"Trend panel = cells (station × calendar month) with at "
        f"least {miny:g} distinct years **and** a span of at least {span:g} years. Balanced "
        "variant = cells present in both 1990–1999 and 2015–2026. No script here builds "
        "either, so neither's size is known."))
    w("")
    w("## What the values carry")
    w("")
    w("- " + C("C-GI-G1-VALUES", "*Values.* The panel holds values no water has: station-"
               "months of negative oxygen, which the flag record reads as sign inversions. A "
               "plausibility filter must be stated, and what each of its bounds removes "
               "counted, before any slope."))
    w("- " + C("C-GI-G1-DECIMALS", "*Precision.* Temperature in the CTD extract is mostly "
               f"written with more than one decimal: of its {trows:,} temperature rows, "
               f"{le1:,} ({pct:.1f}%) carry at most one decimal in the original result."))
    w("- " + C("C-GI-G1-CLOCK", "*Hour.* The CTD extract the panel is built from has no "
               "time of day in any row and no column for it. If the sampling hour drifted "
               "over the record, the diel oxygen cycle drifted with it, and nothing inside "
               "the panel can correct it: this caps the test rather than bounds it. The "
               "water-chemistry extract does carry clock values, which can bound the hour "
               "only where a cast shares its day with a bottle."))
    w("- " + C("C-GI-G1-UNIT", "*Unit.* The unit is a station: the panel deliberately "
               "carries no water body, and every estimate is within a cell of one station and "
               "one calendar month, so none is needed."))
    w("")
    w("## Circularity, avoided")
    w("")
    w(C("C-GI-G1-SAT", "Archived near-bed oxygen saturation (`oxysat_bed`) is held on "
        f"{v['oxysat_bed']['n']:,} station-months, fewer than the {n['oxy_bed']:,} with "
        "near-bed oxygen.") + " "
      + C("C-GI-G1-CIRC", "It is computed from oxygen, temperature and salinity, so it "
          "already contains temperature. **It is never an outcome here.** `D` contains "
          "temperature through `C_sat` deliberately — that is the *subtraction* of the "
          "solubility channel, the equation coming from outside the archive — and errors in "
          "temperature enter `D` but not the year regressor, so they add noise, not trend.")
      + f" See also {R('C6')}.")
    w("")
    w("## The null, under the constraint actually imposed")
    w("")
    w(C("C-GI-G1-NULLDESIGN", "Not “zero slope”. The estimator is a within-cell "
        "fixed-effect slope on year; the constraint imposed is *within station and within "
        "calendar month*. The null is a **year-block procedure**: resample the calendar "
        "years with replacement, and separately permute year labels attached to whole "
        "years, refitting on each draw. That keeps every station effect, the seasonal cycle "
        "and the within-year common shock, destroying only the ordering of years against "
        "outcome."))
    w("")
    w(C("C-GI-G1-DEPEND", "Whether the dependence the textbook standard error ignores is "
        "temporal — a cell's years following one another — or cross-sectional — every cell "
        "in a year sampling the same weather — has not been measured here; the year-block "
        "null holds under both, and the naive standard error is to be reported beside the "
        "block one, with their ratio."))
    w("")
    w("## Composition, handled")
    w("")
    w(C("C-GI-NOLABEL", "No script in this repository defines a split of the stations by "
        "the season they are sampled in, so no such label enters this design.") + " "
      + C("C-GI-G1-DEFENCES", "If the mix of stations moves, it can tilt a pooled slope; the "
          "defences required are (i) within-cell fixed effects, so a station only competes "
          "with itself, and (ii) the balanced panel, so entry and exit cannot tilt the "
          "slope."))
    w("")
    w("## Procedure")
    w("")
    w("1. " + C("C-GI-G1-P1", "Read `oxy_bed`, `temp_bed`, `sal_bed`, `temp_surf` and "
                "`sal_surf` at the offsets the `.json` gives, keyed `station×1000 + month`; "
                "apply stated plausibility bounds on value, counting what each removes; "
                "compute `C_sat` and `D`; build the trend panel."))
    w("2. " + C("C-GI-G1-P2", "Fixed-effect slopes on year for `O`, `C_sat`, `D`, `T_bed` "
                "and `T_surf − T_bed`. The slopes of `O`, `C_sat` and `D` satisfy the "
                "identity exactly; report the split as a **share of `dO/dt`**, not a "
                "p-value."))
    w("3. " + C("C-GI-G1-P3", "Year-block null (above) for each; report the naive standard "
                "error, the block standard error and their ratio."))
    w("4. " + C("C-GI-G1-P4", "Repeat on the balanced panel, on June–September and on "
                "December–March. **Agreement across the variants is the finding; "
                "disagreement is equally the finding.**"))
    w("5. " + C("C-GI-G1-P5", "Refit `dD/dt` with surface-minus-bed density as a covariate "
                f"— this *uses* {R('C1')}'s variable and does not test it. What survives is "
                "the metabolic-plus-unknown residue, a residue, not a `Q10`."))
    w("")
    w("## What a result would and would not license")
    w("")
    w(C("C-GI-G1-WOULD", "**Would.** If `dC_sat/dt` matches or exceeds `dO/dt` under the "
        "year-block null and across the variants, that licenses: *at the trend panel's "
        "stations the long-term near-bed oxygen decline is accounted for by the solubility "
        "ceiling alone, and the non-thermodynamic deficit did not widen.* That constrains "
        f"{R('G1')}'s headline directly: “monotone worsening independent of load” would be "
        "true of the water and still not evidence that load reduction failed, the falling "
        "term being the one no load policy touches."))
    w("")
    w(C("C-GI-G1-WOULDNOT", "**Would not.** It does not measure respiration and cannot: `D` "
        "is a standing stock, a respiration rate is a rate, and converting between them "
        "needs a ventilation timescale the archive does not hold. A narrowing `D` is equally "
        "consistent with load reduction working *and* with the network drifting toward "
        "better-ventilated positions — the defences bound that, they do not eliminate it. "
        "It says nothing about stratification beyond a difference between the top and the "
        f"bottom of the sampled range, which is no pycnocline ({R('C1')}'s object), nothing "
        "about water bodies, nothing about the stations the span filter drops. And "
        "`dD/dt ≈ 0` refutes `G1-b` only at the resolution of monthly medians taken at an "
        "unrecorded hour."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/hypodrafts/G1.md", page))
