#!/usr/bin/env python3
"""docs/openproblems/R6.md - generated from the hand-written draft as committed at 444fc74.

The prose is the draft's, moved here verbatim and then made checkable: counts of
files held in this repository read live from data/derived/drafts_b_counts.json;
counts the drafting session made from external sources or one-off runs carried as
quotations of that commit (located references, {was:COMMIT:FILE:phrase with @@}); register IDs as {ref:}; chemical species
as {chem:}. See scripts/pages/drafts_b_page.py and LIVE_NUMBERS.md.

    python3 scripts/pages/openproblem_r6.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from drafts_b_page import render

TEXT = r'''# {ref:R6|title}

*Generated by `scripts/pages/openproblem_r6.py` from the draft as committed at `444fc74`. Counts of files held in this repository are read live. Counts that session made from external sources or from one-off runs are quotations of that commit - what the draft reported, shown as such, not re-derived by the build.*


**Missing: experiment, constructive.** {ref:R6}'s discriminator is a *rate* against a *ratio* —
"Fe:S and Fe:P against phosphate release rate" — and its causal clause is comparative:
marine sediment releases more P under anoxia *because of the sulphate*. Nothing in Denmark
varies sulphate while holding organic loading, iron supply and temperature fixed, so the
contrast has to be built. A core incubation is the answer, and it is cheap.

## No water-column observable can reach it, and this should be said plainly

{ref:R6} lives in the millimetre above and below the sulphide front. The archive's finest
observable is a station-month median of near-bed oxygen: `stations_series.json`, verified
here — **{fig:dbx_ss_total} station-months** ({fig:dbx_ss_nvars} variables summing {fig:dbx_ss_fluo} … {fig:dbx_ss_temp_surf}), {fig:dbx_ss_stations} stations,
{fig:dbx_ss_months} monthly slots from 1980; near-bed oxygen is **{fig:dbx_ss_oxy_bed}**. That is four orders of
magnitude coarser than the front it would have to resolve, and the wrong quantity
besides: oxygen is {ref:R6}'s *precondition*, not its consequence. A correlation between bed
oxygen and water-column DIP is equally predicted by {ref:A7}, {ref:R2}, {ref:R5} and plain mineralisation.
**Class 6, absent dimension — unscoreable, not refuted.**

**The `Dihydrogensulfid` series, checked rather than assumed.** Two full independent scans
of `ctd.csv.gz` both return **{was:444fc74:docs/openproblems/R6.md:return **@@ rows**, and} rows**, and they are not a Danish series. **{was:444fc74:docs/openproblems/R6.md:series. **@@ come from} come
from one station** — `93610032` "Dybet", Mariager Fjord midterdel — with {was:444fc74:docs/openproblems/R6.md:— with @@ row each} row each from
three other Mariager sites; **{was:444fc74:docs/openproblems/R6.md:Mariager sites; **@@ casts on} casts on {was:444fc74:docs/openproblems/R6.md:**210 casts on @@ dates**, 2001–2008 and} dates**, 2001–2008 and 2010, nothing since;
µg/l; depths {was:444fc74:docs/openproblems/R6.md:nothing since; µg/l; depths @@–66 m; 432 zeros;}–{was:444fc74:docs/openproblems/R6.md:since; µg/l; depths 2–@@ m; 432 zeros; median} m; {was:444fc74:docs/openproblems/R6.md:depths 2–66 m; @@ zeros; median 27.9,} zeros; median {was:444fc74:docs/openproblems/R6.md:zeros; median @@, max}, max {was:444fc74:docs/openproblems/R6.md:median 27.9, max @@ µg/l. Gear is} µg/l. Gear is `Ketcher` on every
row (a bottle, not a sonde; {was:444fc74:docs/openproblems/R6.md:a sonde; @@ rows carry} rows carry `999 - Ukendt` as instrument). One
permanently stratified silled basin, one authority, nine years: usable for the {chem:H2S}
climatology of Mariager Fjord's monolimnion and nothing comparative. It is also the wrong
side of the mechanism — **free sulphide in the water column is what remains after the
sediment's iron buffer is already spent**, a detector of the endpoint, not of the process.
ODA `vandkemi` carries `Svovlbrinte (sulfid)` at **{fig:dbx_portal_vandkemi_ever} historical stations**: a far
better series, measuring the same endpoint.

## First job — what exists, verified this session

| Source | What it measures | Resolution / coverage | Size, licence | Separate production path? |
|---|---|---|---|---|
| **DCE SR323**, *Sammenhænge i det marine miljø*, `dce2.au.dk/pub/SR323.pdf` | LOI, TN, TP **and iron-bound P** over the top {was:444fc74:docs/openproblems/R6.md:the top @@ cm; sulphide-front} cm; sulphide-front depth; **buffer capacity**; **oxidised iron**, top {was:444fc74:docs/openproblems/R6.md:**oxidised iron**, top @@ cm |} cm | {was:444fc74:docs/openproblems/R6.md:1.5 cm | @@ NOVANA stations, 1999–2003} NOVANA stations, 1999–2003 and 2017–2018, {was:444fc74:docs/openproblems/R6.md:1999–2003 and 2017–2018, @@ fjords + Sydfynske} fjords + Sydfynske Øhav + N. Øresund; front dataset **{was:444fc74:docs/openproblems/R6.md:front dataset **@@ measurements**, 16 areas,} measurements**, {was:444fc74:docs/openproblems/R6.md:measurements**, @@ areas, spring+autumn;} areas, spring+autumn; research series 2005–2015, {was:444fc74:docs/openproblems/R6.md:series 2005–2015, @@ open-water stations} open-water stations | {was:444fc74:docs/openproblems/R6.md:open-water stations | @@ MB PDF, text-extractable} MB PDF, text-extractable ({was:444fc74:docs/openproblems/R6.md:text-extractable (@@ chars) |} chars) | Analysis of NOVANA — **not** separate; the 2005–2015 front series **is** |
| **NOVA teknisk anvisning kap. 14**, `ecos.au.dk/fileadmin/ecos/Fagdatacentre/Marin/TA_NOVA_1998/Kap14.pdf` | The method: `§14.7.1.1` front by silver plate, `§14.7.1.2` buffer capacity, `§14.7.1.3` **oxidised iron in the {chem:H2S} buffer zone**, `§14.6.1.1` iron-bound P, bilag 14.3 photometric {chem:Fe2+} | protocol, 1998 | {was:444fc74:docs/openproblems/R6.md:protocol, 1998 | @@ KB, 138,791 chars} KB, {was:444fc74:docs/openproblems/R6.md:| 389 KB, @@ chars | n/a} chars | n/a — it is the path |
| **ICES DOME sediment, Denmark** — direct GET, no login | `Fe`, `Mn`, `S`, `PTOT`, `CORG`, `LOIGN`, `AL`, `PB210`, grain size | Counted here: **{was:444fc74:docs/openproblems/R6.md:Counted here: **@@ rows**; **47 samples} rows**; **{was:444fc74:docs/openproblems/R6.md:here: **47,019 rows**; **@@ samples at 12 positions} samples at {was:444fc74:docs/openproblems/R6.md:samples at @@ positions carry} positions carry Fe+S+PTOT together, all of them {was:444fc74:docs/openproblems/R6.md:together, all of them @@} Feb 1990 – {was:444fc74:docs/openproblems/R6.md:Feb 1990 – @@ Mar 1991**. Fe} Mar 1991**. Fe elsewhere: {was:444fc74:docs/openproblems/R6.md:1991**. Fe elsewhere: @@ stations | 823} stations | {was:444fc74:docs/openproblems/R6.md:2 stations | @@ KB zip →} KB zip → {was:444fc74:docs/openproblems/R6.md:KB zip → @@ MB CSV, open} MB CSV, open | From Danish VanDa/ODA — **not** separate |
| **PANGAEA `997075`**, Kiel Bight core incubation, 2025 | **Sequential Fe extraction** (poorly-crystalline/crystalline Fe(II)/Fe(III)), total S, {chem:H2S}, sulphate, ³⁵S reduction rate, alkalinity — under controlled oxygen cycling | {was:444fc74:docs/openproblems/R6.md:oxygen cycling | @@ N 10.178 E,} N {was:444fc74:docs/openproblems/R6.md:| 54.572 N @@ E, Feb–Mar 2025,} E, Feb–Mar 2025, {was:444fc74:docs/openproblems/R6.md:Feb–Mar 2025, @@ points |} points | small, CC-BY | **Yes**, GEOMAR |
| **PANGAEA `987329`–`987366`** (AL561, 2021) | TOC, TN, **bulk** TS, porewater **dissolved** Fe and phosphate; **in-situ chamber phosphate flux** | {was:444fc74:docs/openproblems/R6.md:flux** | @@ Kattegat–Skagerrak stations,} Kattegat–Skagerrak stations, one cruise | small, CC-BY | **Yes** |
| **PANGAEA `880132`** (Bornholm SEDEX) | Sequential P fractions incl. Fe-bound P | one borehole, 2013, {was:444fc74:docs/openproblems/R6.md:one borehole, 2013, @@ points | small,} points | small, CC-BY | **Yes** |
| ODA `Sedimentkemi/Sporstof` (`Emne_12_19`) | `Phosphor, Fe-adsorberet`, TP, TN, glødetab | **{fig:dbx_portal_sedimentkemi_sporstof_now} stations now, {fig:dbx_portal_sedimentkemi_sporstof_ever} ever** | small, login | NOVANA, different lab chain |

**Still absent:** any paired sequential Fe *and* S extraction (AVS, CRS, ascorbate/dithionite
Fe) on Danish sediment, and any Danish phosphate release rate outside the {was:444fc74:docs/openproblems/R6.md:rate outside the @@} AL561 chambers.

## The finding that changes {ref:R6}'s status

**Denmark had a written national method for {ref:R6}'s own variables and stopped running it.**
TA kap. 14 (1998) specifies the sulphide front, the sulphide **buffer capacity** — sediment
added to an {chem:H2S} solution of known concentration, uptake measured after a fixed incubation,
reported as µmol {chem:H2S} cm⁻², i.e. a *functional assay of the reactive iron pool* — and the
oxidised iron content in the buffer zone. SR323 reports results: front {was:444fc74:docs/openproblems/R6.md:results: front @@ mm spring} mm spring → {was:444fc74:docs/openproblems/R6.md:mm spring → @@ mm autumn; buffer} mm
autumn; buffer capacity {was:444fc74:docs/openproblems/R6.md:autumn; buffer capacity @@} → {was:444fc74:docs/openproblems/R6.md:capacity 29 → @@ µmol cm⁻²; oxidised} µmol cm⁻²; oxidised Fe in the top {was:444fc74:docs/openproblems/R6.md:the top @@ cm ranging} cm ranging {was:444fc74:docs/openproblems/R6.md:1.5 cm ranging @@ to 2,741 µmol,} to {was:444fc74:docs/openproblems/R6.md:ranging 2 to @@ µmol, geometric mean}
µmol, geometric mean {was:444fc74:docs/openproblems/R6.md:µmol, geometric mean @@ → 2.0 once} → {was:444fc74:docs/openproblems/R6.md:mean 9.3 → @@ once Limfjorden and} once Limfjorden and Ringkøbing are set aside. That is iron
consumed as the sulphide front advances, in Danish sediment, seasonally. The register's
"no Fe speciation for any Danish site" is wrong for 1998–2003 and right for everything
after. Today's ODA sediment topic has six parameters and none is iron.

Two error classes travel with it. **Class 2, censoring:** the buffer assay saturates at
≈{was:444fc74:docs/openproblems/R6.md:saturates at ≈@@ µmol and is} µmol and is then reported as `>x µmol cm⁻²` — right-censored precisely at the
high-iron stations {ref:R6} cares most about. **Class 4, conflation** in DOME: one physical
sample appears twice as `SED63` and `SED2000`, two grain-size fractions with different
values; pooling them shifts any ratio. Values like `16400000.000000002 ug/kg` betray a
unit conversion inside DOME — that precision is manufactured.

## Why experiment, and the null it must be run against

Restoring the 1998 assay would give Fe and S as *state variables* — worth doing, and only a
measurement problem. It still would not test {ref:R6}, which asserts a **causal dependence of P
release on sulphate**, and the field never varies sulphate alone.

**The null, computed under the constraint imposed, not quoted.** The naive null — "anoxic
sediment releases no more P than oxic sediment" — is wrong, and would hand {ref:R6} a win it has
not earned: anoxia releases P by organic mineralisation whether or not sulphide forms. The
constraint an incubation imposes is *same sediment, same anoxia, sulphate varied*. So the
null is **equality of P release per unit mineralisation across sulphate levels** — flux({chem:PO4 3-})
normalised to concurrent flux(DIC) or {chem:NH4+} from the same core, sulphate the only manipulated
term. Under `H0` that ratio is flat in sulphate; {ref:R6} predicts it rises and saturates where
reactive Fe is exhausted. A design without a sulphate-free *anoxic* arm cannot reject
anything, however many replicates it has.

## Smallest unblocking thing

1. **Reinstate the 1998 assay at {was:444fc74:docs/openproblems/R6.md:assay at @@ existing `Bundfauna`} existing `Bundfauna` stations, one spring and one autumn.**
   Silver-plate front, buffer capacity, oxidised Fe, alongside the Fe-adsorbed P already in
   `Sedimentkemi`. Report the censoring threshold with every `>` value. Cost: a protocol that
   already exists in Danish, a syringe and a photometer.
2. **The incubation.** One Danish sediment, homogenised, split across a sulphate dose series
   ~{was:444fc74:docs/openproblems/R6.md:sulphate dose series ~@@} to ~{was:444fc74:docs/openproblems/R6.md:series ~1 to ~@@ mM at fixed ionic} mM at fixed ionic strength by NaCl substitution, so *sulphate* is the treatment.
   Track {chem:PO4 3-}, DIC/{chem:NH4+}, {chem:H2S} and sulphate reduction rate in the overlying water; sequential Fe
   (ascorbate/dithionite) and S (AVS/CRS) on the cores at the end. PANGAEA `997075` makes every
   one of those measurements together, in the western Baltic, in 2025 — current, standard and
   adjacent. Its one omission is phosphorus, which is the whole of {ref:R6}.
3. **Reclassification test, stated in advance.** If the NOVA-era rows (front, buffer, oxidised
   Fe, 1998–2003) are recoverable from the former county archives at ≥{was:444fc74:docs/openproblems/R6.md:archives at ≥@@ stations with} stations with ≥{was:444fc74:docs/openproblems/R6.md:with ≥@@ paired seasons}
   paired seasons *and* a co-located Fe-adsorbed P value, {ref:R6}'s **state** half becomes
   **armchair** and this file is half wrong. The **rate** half stays experimental regardless.

## What it would and would not license

A successful incubation licenses one narrow thing: *in this sediment, sulphate availability
changes P release per unit mineralisation by this factor*. It would **not** license a Danish
phosphorus budget, a water-body allocation, or a claim about the Baltic feedback — one
sediment is one sediment, and {ref:R6}'s unit is depositional history, not a map. Nor the
freshwater comparison {ref:R6} makes in words: that needs the same dose series on lake sediment,
and Danish lake and marine sediments differ in far more than sulphate. The honest limit is
that it tests the *step* — sulphide strips Fe, Fe was holding P — not the *system claim*
that this is what makes the marine case worse.
'''

if __name__ == "__main__":
    sys.exit(render("docs/openproblems/R6.md", TEXT))
