#!/usr/bin/env python3
"""docs/openproblems/R6.md - what the data held here can and cannot show about R6.

Every number is read from data (live_json), from a pinned document ({read:}) or is a
stated design value with its reason; every assertion is a checked claim
(LIVE_NUMBERS.md section 11), registered in data/manual/claims.d/w3-op.json with what it
rests on, and every field printed has a declared construction. What the draft once said
and could not justify is in docs/ARCHIVE.md, not here. The page is written through
scripts/pages/drafts_b_page.py.

    python3 scripts/pages/openproblem_r6.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED, ROOT
import live

C = live.claim
R, CH = live.ref, live.chem
SR, TA, NV = "OQ-SR323", "TA-NOVA-1998-K14", "NOVANA-2327"
TOP_STATION = "93610032"
SEDKEMI = {"Gloedetab, total", "Nitrogen,total N", "Phosphor, Fe-adsorberet",
           "Phosphor, total-P", "Toerstof, total", "Vaegtfylde"}
# the passages of the pinned documents the page reads its numbers from
P_FRONT = "fra en gennemsnitlig dybde på 51 mm om foråret til 25 mm om efteråret"
P_BUF = ("Bufferkapaciteten varierede tilsvarende fra 29 µmol cm-2 om foråret til 15 µmol "
         "cm-2 om efteråret")
P_FE = "varierede meget med værdier fra 2 µmol til 2741 µmol i de øverste 1,5 cm"
P_GM = "oxideret jern på 9,3 og 2,0 µmol i de øverste 1,5 cm om henholdsvis foråret og efteråret"
P_ST = "er der målt sedimentkarakteristika på 12 stationer, både i perioden 1999-2003 og 2017-2018"
P_AR = "Stationerne fordeler sig på 7 danske fjordområder samt det Sydfynske Øhav og Nordlige Øresund"
P_TOP = "jernbundet P i de øverste 10 cm af sedimentet"
P_16 = "I samtlige 16 områder var svovlbrintefronten rykket nærmere"
P_OPEN = "registreret svovlbrinte på 16 ud af 20 stationer"
P_SAT = "forbruger al H2S (≈ 100 µmol)"
P_NV10 = "bestemmes i syv dybder fra de øverste 10 cm af sedimentet"


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def RD(sid, shown, phrase):
    """A number read out of a pinned document, located by a phrase in it."""
    return "{read:%s:%s|%s}" % (sid, shown, phrase)


def refuse(msg):
    raise live.Unjustified("R6: " + msg)


def text():
    dc = J("drafts_b_counts.json")
    ss, portal = dc["stations_series"], dc["oda_portal"]["sedimentkemi_sporstof"]
    year0 = J("hypodraft_facts.json")["series_by_variable"]["year0"]
    h2s = J("hypodraft_ctd.json")["h2s"]
    kemi = J("enums.json")["kemi"]["categorical"]["Parameter"]

    if h2s["top_station"] != TOP_STATION:
        refuse(f"the CTD sulphide rows now come mostly from {h2s['top_station']}")
    reg = json.load(open(os.path.join(ROOT, "data", "manual", "data_sources.json"),
                         encoding="utf-8"))
    reg = reg if isinstance(reg, list) else reg.get("sources", reg)
    sed = next((s for s in reg if s.get("id") == "ODA-SEDKEMI-SPOR"), None)
    if not sed or set(sed.get("parameters", [])) != SEDKEMI:
        refuse("the register no longer lists the sediment topic's parameters the page names")

    o = []
    w = o.append
    w(f"# {R('R6', title=True)}")
    w("")
    w("*Generated by `scripts/pages/openproblem_r6.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w(C("C-OQ-R6-CLASS", f"**Missing: experiment, constructive.** {R('R6')}'s discriminator is "
        "a *rate* against a *ratio* - sediment Fe:S and Fe:P against phosphate release rate - "
        "and its causal clause is comparative: marine sediment releases more phosphate under "
        "anoxia *because of the sulphate*. A field record varies sulphate only together with "
        "salinity, organic loading, iron supply and temperature, so the contrast has to be "
        "built, in a core incubation."))
    w("")
    w("## No water-column observable can reach it, and this should be said plainly")
    w("")
    w(C("C-OQ-R6-PANEL", "The archive's finest routine observable near the bed is a monthly "
        f"median per station: `stations_series.json` holds {ss['total_station_months']:,} "
        f"station-months at {ss['n_stations']:,} stations over {ss['months']} months from "
        f"{year0}, near-bed oxygen on {ss['variables']['oxy_bed']['n']:,} of them.") + " "
      + C("C-OQ-R6-SCALE", f"{R('R6')} lives at the sulphide front, which the national sediment "
          "reports place millimetres to centimetres below the sediment surface; a station-month "
          "median of bottom-water oxygen is far coarser in space and time, and the wrong "
          f"quantity besides: oxygen is {R('R6')}'s *precondition*, not its consequence.") + " "
      + C("C-OQ-R6-CONFOUND", "A correlation between bed oxygen and water-column phosphate is "
          f"equally predicted by {R('A7')}, {R('R2')}, {R('R5')} and plain mineralisation. "
          "**Unscoreable here, not refuted.**"))
    w("")
    w(C("C-OQ-R6-H2S", "**The `Dihydrogensulfid` series, checked rather than assumed.** The CTD "
        f"extract's `Dihydrogensulfid` has {h2s['rows']:,} records at {h2s['stations']} "
        f"stations, {h2s['top_station_rows']:,} of them from station `{TOP_STATION}` in "
        "Mariager Fjord.") + " "
      + C("C-OQ-R6-H2SUSE", "One silled fjord whose inner basin exchanges little water: usable "
          f"for the {CH('H2S')} climatology of Mariager Fjord's bottom water and nothing "
          "comparative.") + " "
      + C("C-OQ-R6-ENDPOINT", "It is also the wrong side of the mechanism: **free sulphide in "
          "the water column is what remains after the sediment's iron buffer is spent**, a "
          "detector of the endpoint, not of the process.") + " "
      + C("C-OQ-R6-KEMIH2S", "The held water-chemistry extract carries sulphide from bottles "
          f"under two names, `Dihydrogensulfid` on {kemi['Dihydrogensulfid']:,} records and "
          f"`Svovlbrinte (sulfid)` on {kemi['Svovlbrinte (sulfid)']:,}: a separate production "
          "path, measuring the same endpoint."))
    w("")
    w("## What exists")
    w("")
    w("- " + C("C-OQ-R6-SR323", "**DCE's SR323**, *Sammenhænge i det marine miljø* "
               "(`dce2.au.dk/pub/SR323.pdf`), analyses the national sediment programme: loss on "
               f"ignition, total N, total P and iron-bound P in the top {RD(SR, '10', P_TOP)} cm "
               f"at {RD(SR, '12', P_ST)} stations measured both in 1999–2003 and in 2017–2018, "
               f"in {RD(SR, '7', P_AR)} Danish fjord areas, the Sydfynske Øhav and northern "
               f"Øresund; the sulphide front and buffer capacity in {RD(SR, '16', P_16)} areas, "
               "spring and autumn; and, in open waters from 2005 to 2015, sulphide at "
               f"{RD(SR, '16', P_OPEN)} of {RD(SR, '20', P_OPEN)} stations."))
    w("- " + C("C-OQ-R6-TA14", "**NOVA teknisk anvisning `kap. 14`** (1998), the national "
               "method: the sulphide front by silver plate (`§14.7.1.1`), the sulphide buffer "
               "capacity (`§14.7.1.2`), oxidised iron in the buffer zone (`§14.7.1.3`), "
               "iron-bound phosphorus (`§14.6.1.1`), and the fluxes of oxygen and nutrients, "
               "ortho-phosphate among them, between incubated cores and the water above them "
               "(`§14.8`)."))
    w("- " + C("C-OQ-R6-DOME", "**ICES DOME**'s Danish sediment contaminant file is an open "
               "download, fed from Danish monitoring and so not a separate production path. "
               "This project's reading of it is a note in the source register, from an analysis "
               "not stored as a script, and the note does not say whether iron, sulphur and "
               "phosphorus were measured on the same samples."))
    w("- " + C("C-OQ-R6-PG997075", "**PANGAEA `997075`**: Kiel Bight sediment cores collected in "
               "February 2025 and incubated under controlled oxygen cycles, with sequential iron "
               "extraction, total sulphur, hydrogen sulphide, sulphate, ammonium, alkalinity and "
               "sulphate reduction rates by radiotracer; from GEOMAR, a production path separate "
               "from Danish monitoring.") + " "
      + C("C-OQ-R6-PG997075-NOP", "Its record lists no phosphorus measurement."))
    w("- " + C("C-OQ-R6-AL561", "**AL561** (GEOMAR, 2021; PANGAEA `987329`–`987366`): sediment "
               "cores and benthic landers at high-accumulation sites in the Skagerrak and "
               "Kattegat; the chamber record at station `AL561_17-1` lists phosphate among its "
               "measured nutrients.") + " "
      + C("C-OQ-R6-AL561-FES", "The source register records the cruise's sulphur as bulk total "
          "sulphur and its iron as dissolved porewater iron, not a sequential extraction, so the "
          f"Fe:S ratio {R('R6')} needs cannot be computed from it."))
    w("- " + C("C-OQ-R6-PG880132", "**PANGAEA `880132`**: sequential phosphorus extraction, "
               "iron-bound phosphorus among its fractions, on one sediment core from the "
               "Bornholm Basin."))
    w("- " + C("C-OQ-R6-ODASED", "**ODA `Sedimentkemi/Sporstof`** (`Emne_12_19`): the source "
               "register records its parameters - loss on ignition, total N, iron-adsorbed P, "
               "total P, dry matter and density, none of them an iron content - and the portal's "
               f"station list at {portal['no_period']} stations with no period set and "
               f"{portal['with_period']} over the whole record. It is not held here."))
    w("")
    w(C("C-OQ-R6-NOVANA", "The national programme for 2023–2027 takes, in sediment, total N, "
        "total P, iron-bound phosphate, dry matter, loss on ignition and density, in layers of "
        f"the top {RD(NV, '10', P_NV10)} cm, once a year, when the sediment is most oxidised, "
        "in January–February.") + " "
      + C("C-OQ-R6-NOVANA-NOBUF", "Neither the sulphide front, the buffer capacity nor oxidised "
          "iron is in its text."))
    w("")
    w(C("C-OQ-R6-ABSENT", "**Still absent from anything found:** a paired sequential iron *and* "
        "sulphur extraction (AVS, CRS, ascorbate/dithionite iron) on Danish sediment.") + " "
      + C("C-OQ-R6-FLUXES", "The 1998 method specifies core-incubation phosphate fluxes, and "
          "DCE's SR323 tabulates a seasonal internal load of DIN and DIP for Roskilde, Odense, "
          "Horsens and Ringkøbing Fjord from summer 1999 to spring 2000, credited to "
          "unpublished data.") + " "
      + C("C-OQ-R6-FLUXDATA", "The measurements behind it were not found in any reachable "
          "dataset."))
    w("")
    w("## What the national method measured")
    w("")
    w(C("C-OQ-R6-METHOD", "The 1998 method specifies the buffer capacity as a titration of the "
        f"sulphide-free surface sediment with {CH('H2S')}, reported as µmol of {CH('H2S')} "
        "consumed per cm², and measures oxidised iron in the same zone so the two can be "
        f"related: a *functional assay of the reactive iron pool* {R('R6')} turns on."))
    w("")
    w(C("C-OQ-R6-RESULTS", "DCE's SR323 reports from it, as means over the areas: the front "
        f"rose from {RD(SR, '51', P_FRONT)} mm below the surface in spring to "
        f"{RD(SR, '25', P_FRONT)} mm in autumn, and the buffer capacity fell from "
        f"{RD(SR, '29', P_BUF)} to {RD(SR, '15', P_BUF)} µmol cm⁻²; its figure's bars give the "
        "spread over 1998–2003. Oxidised iron in the top "
        f"{RD(SR, '1.5', P_FE)} cm ranged from {RD(SR, '2', P_FE)} to {RD(SR, '2,741', P_FE)} "
        f"µmol, with geometric means of {RD(SR, '9.3', P_GM)} in spring and "
        f"{RD(SR, '2.0', P_GM)} in autumn once Limfjorden and Ringkøbing Fjord are set "
        "aside.") + " "
      + C("C-OQ-R6-CONSUMED", "The report reads the two seasonal changes as of the same order - "
          "iron consumed as the sulphide front advances, in Danish sediment, seasonally - while "
          "noting that other substances than oxidised iron add to the buffer capacity and that "
          "the iron was measured only near the surface."))
    w("")
    w(C("C-OQ-R6-CENSOR", "**Censoring.** Where the oxidised zone is deep, the added sediment "
        f"can consume all the {CH('H2S')} added (≈ {RD(TA, '100', P_SAT)} µmol), and the method "
        "then reports the buffer capacity as `>x µmol cm-2`: right-censored precisely at the "
        f"high-iron stations {R('R6')} cares most about."))
    w("")
    w("## Why experiment, and the null it must be run against")
    w("")
    w(C("C-OQ-R6-STATE", "Running the 1998 assay would give iron and sulphur as *state "
        "variables* - worth doing, and only a measurement problem. It still would not test "
        f"{R('R6')}, which asserts a **causal dependence of phosphate release on sulphate**, "
        "and the field never varies sulphate alone."))
    w("")
    w(C("C-OQ-R6-NULL", "The naive null - \"anoxic sediment releases no more phosphate than "
        f"oxic sediment\" - is wrong, and would hand {R('R6')} a win it has not earned: under "
        "anoxia phosphate is released by the breakdown of organic matter, and iron-reducing "
        "bacteria free iron-bound phosphate, whether or not sulphide forms.") + " "
      + C("C-OQ-R6-NULL2", "The constraint an incubation imposes is *same sediment, same "
          "anoxia, sulphate varied*. So the null is **equality of phosphate release per unit "
          f"mineralisation across sulphate levels** - flux({CH('PO4 3-')}) normalised to "
          f"concurrent flux(DIC) or {CH('NH4+')} from the same core, sulphate the only "
          f"manipulated term. Under `H0` that ratio is flat in sulphate; {R('R6')} predicts it "
          "rises and saturates where reactive iron is exhausted. A design without a "
          "sulphate-free *anoxic* arm cannot reject anything, however many replicates it has."))
    w("")
    w("## Smallest unblocking thing")
    w("")
    w("1. " + C("C-OQ-R6-S1", "**Run the 1998 assay at {param:oq_r6_stations} existing "
                "`Bundfauna` stations, one spring and one autumn.** Silver-plate front, buffer "
                "capacity, oxidised iron, beside the iron-adsorbed phosphorus `Sedimentkemi` "
                "already carries. Report the censoring threshold with every `>` value. Cost: a "
                "protocol that already exists in Danish, a syringe and a photometer."))
    w("2. " + C("C-OQ-R6-S2", "**The incubation.** One Danish sediment, homogenised, split "
                "across a sulphate dose series from {param:oq_r6_so4_lo} to "
                "{param:oq_r6_so4_hi} mM at fixed ionic strength by NaCl substitution, so "
                "*sulphate* is the treatment. "
                + f"Track {CH('PO4 3-')}, DIC/{CH('NH4+')}, {CH('H2S')} and sulphate reduction "
                "rate in the overlying water; sequential iron (ascorbate/dithionite) and sulphur "
                "(AVS/CRS) on the cores at the end.") + " "
      + C("C-OQ-R6-S2B", "PANGAEA `997075` makes sulphate, sulphide, ammonium, "
          "sulphate-reduction and sequential-iron measurements together on Kiel Bight sediment "
          f"in 2025; it names no phosphorus measurement, and phosphorus is the whole of "
          f"{R('R6')}."))
    w("3. " + C("C-OQ-R6-S3", "**Reclassification test, stated in advance.** If the NOVA-era "
                "rows (front, buffer, oxidised iron, 1998–2003) are recoverable from the former "
                "county archives at ≥{param:oq_r6_min_stations} stations with "
                "≥{param:oq_r6_min_seasons} paired seasons *and* a co-located iron-adsorbed "
                + f"phosphorus value, {R('R6')}'s **state** half becomes **armchair** and this "
                "page is half wrong. The **rate** half stays experimental regardless."))
    w("")
    w("## What it would and would not license")
    w("")
    w(C("C-OQ-R6-LICENSE", "A successful incubation licenses one narrow thing: *in this "
        "sediment, sulphate availability changes phosphate release per unit mineralisation by "
        "this factor*. It would **not** license a Danish phosphorus budget, a water-body "
        "allocation, or a claim about the Baltic feedback - one sediment is one sediment, and "
        f"{R('R6')}'s unit is depositional history, not a map. Nor the freshwater comparison "
        f"{R('R6')} makes in words: that needs the same dose series on lake sediment, and "
        "Danish lake and marine sediments differ in much more than sulphate. The honest limit "
        "is that it tests the *step* - sulphide strips iron, iron was holding phosphate - not "
        "the *system claim* that this is what makes the marine case worse."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/openproblems/R6.md", page))
