#!/usr/bin/env python3
"""docs/openproblems/J1.md - what the data held here can and cannot show about J1.

Every number is read from data (live_json) or is a stated design value with its
reason; every assertion is a checked claim (LIVE_NUMBERS.md section 11), registered in
data/manual/claims.d/w3-op.json with what it rests on, and every field printed has a
declared construction. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/openproblem_j1.py
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED, ROOT
import live

C = live.claim
R = live.ref
GEL = re.compile(r"TEP|exopolymer|alcian|polysac|\bgel\b|mikrolag|microlayer|overfladefilm", re.I)
PER_METRE = re.compile(r"^(m-1|m⁻¹|1/m|m\^-1|pr\. ?m)$")


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("J1: " + msg)


def text():
    en = J("enums.json")
    ctd = en["ctd"]
    par, unit = ctd["categorical"]["Parameter"], ctd["categorical"]["Enhed"]
    kemi = en["kemi"]["categorical"]["Parameter"]
    meta = J("meta_facts.json")
    hc = J("hypodraft_ctd.json")
    fd, corr = hc["fdom"], hc["correction"]
    ss = J("drafts_b_counts.json")["stations_series"]
    lt = J("light.json")
    sd, split = lt["start_depth"], lt["params"]["start_split_m"]

    # the page's statements about the files, refused if the files stop saying them
    if len(par) != meta["ctd_parameters"]:
        refuse("the Parameter list and meta_facts.json disagree on how many values it has")
    hits = [p for p in list(par) + list(kemi) if GEL.search(p)]
    if hits:
        refuse(f"a gel-like parameter is now held: {hits}")
    L, O, F = par["Lysdæmpning"], par["Oxygenmætning"], par["FDOM"]
    K, V, T = par["Konduktivitet"], par["Vægtfylde"], par["Turbiditet"]
    if unit["pct"] != L + O:
        refuse("pct no longer counts exactly the records of Lysdæmpning and Oxygenmætning")
    if unit["ppb"] != F:
        refuse("ppb no longer counts exactly the records of FDOM")
    if unit["mS/cm"] + unit["mS/m"] != K or unit["g/l"] + unit["kg/m3"] != V:
        refuse("the conductivity or density units no longer sum to their parameter")
    if any(PER_METRE.match(u) for u in unit):
        refuse("a unit per metre is now in the CTD unit column")
    panel = json.load(open(os.path.join(ROOT, "docs", "data", "areas", "stations_series.json"),
                           encoding="utf-8"))
    if {v["key"]: v["unit"] for v in panel["variables"]}.get("fluo") != "rel":
        refuse("the panel no longer gives fluorescence in the unit rel")

    plist = " · ".join(f"{k} {v:,}" for k, v in sorted(par.items(), key=lambda kv: -int(kv[1])))

    o = []
    w = o.append
    w(f"# {R('J1', title=True)}")
    w("")
    w("*Generated by `scripts/pages/openproblem_j1.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w(C("C-OQ-J1-STATUS", "**Missing: measurement** - specifically *a new metric over what is "
        "already recorded*. TEP, the quantity the hypothesis is about, is recorded in nothing "
        "held here. A metric over the optics already recorded can be written down; it cannot "
        "be formed in physical units, and if it could it could not be attributed to gel."))
    w("")
    w("## The direct quantity is absent, and this is checked rather than assumed")
    w("")
    w(C("C-OQ-J1-DISC", f"{R('J1')} says gel production rises when the N:P ratio is skewed "
        "**in either direction**, and it names its own discriminator: TEP against the ambient "
        "N:P ratio and bloom senescence stage, not against nutrient load."))
    w("")
    w(C("C-OQ-J1-CTDPARAMS", "The CTD extract `data/raw/oda/ctd.csv.gz` carries "
        f"{meta['ctd_parameters']} distinct `Parameter` values over its {ctd['rows']:,} "
        f"records: {plist}."))
    w("")
    w(C("C-OQ-J1-NOTEP", "No TEP, no polysaccharide, no Alcian blue, no gel, no microlayer - "
        "there, or among the `Parameter` values of the held water-chemistry extract "
        "`data/raw/oda/kemi.csv.gz`.") + " "
      + C("C-OQ-J1-SEARCHED", "The source register's `J1-J2-J3-GAP` records searches of "
          "PANGAEA, HELCOM's catalogue, Dryad, Zenodo and the ODA parameter lists that found no "
          "Danish TEP, sea-surface microlayer or surfactant measurement either."))
    w("")
    w(C("C-OQ-J1-NP", "The discriminator's other side is held: the water-chemistry extract "
        f"carries `Nitrit+nitrat-N` on {kemi['Nitrit+nitrat-N']:,} records, "
        f"`Ammoniak+ammonium-N` on {kemi['Ammoniak+ammonium-N']:,}, `Ortho-phosphat-P` on "
        f"{kemi['Ortho-phosphat-P']:,}, "
        f"`Nitrogen,total N` on {kemi['Nitrogen,total N']:,} and `Phosphor, total-P` on "
        f"{kemi['Phosphor, total-P']:,}, one result per record, so an ambient N:P can be "
        "formed by station, date and depth.") + " "
      + C("C-OQ-J1-UNSCOREABLE", "The hypothesis is missing its dependent variable, not its "
          f"discriminator. **Absent dimension: {R('J1')} is unscoreable, not refuted.**"))
    w("")
    w("## The new metric, stated precisely enough to be rejected")
    w("")
    w(C("C-OQ-J1-OPTICS", "The archive holds more optics than the monthly panel exposes. "
        f"`docs/data/areas/stations_series.json` carries {ss['total_station_months']:,} "
        f"station-months over {ss['n_variables']} variables, of which one is optical: `fluo`, "
        f"fluorescence in the relative unit `rel`, on {ss['variables']['fluo']['n']:,} "
        "station-months. Beside fluorescence the raw CTD file carries the three optical "
        f"channels the metric below uses: `Lysdæmpning`, light attenuation, on {L:,} records, "
        f"`Turbiditet` on {T:,}, and `FDOM`, the "
        f"fluorescence of dissolved organic matter, on {F:,}, from {fd['first_year']} to "
        f"{fd['last_year']} only."))
    w("")
    w("The metric would be, per cast carrying all four:")
    w("")
    w("> **R = Lysdæmpning − f(Fluorescens, FDOM, Turbiditet)**")
    w("")
    w("attenuation unexplained by the chlorophyll, coloured dissolved matter and particles "
      "that are supposed to explain it. "
      + C("C-OQ-J1-SHRINK", "`RESIDUAL.md` gives the test such a number must pass: **R must "
          "shrink by exactly P when a part P is measured out of it.**"))
    w("")
    w("## Why it fails")
    w("")
    w(C("C-OQ-J1-PCT", "**First, R has no physical units.** The unit column `Enhed` holds "
        f"`pct` on {unit['pct']:,} records - exactly as many as `Lysdæmpning` ({L:,}) and "
        f"`Oxygenmætning` ({O:,}) carry together - and none of its units is a coefficient per "
        "metre: the attenuation channel is a percentage transmission, not an attenuation "
        "coefficient.") + " "
      + C("C-OQ-J1-PATH", "A transmission becomes a coefficient only through the path length "
          "the light travelled, and no column of the extract records one.") + " "
      + C("C-OQ-J1-FDOMUNIT", f"`FDOM`'s {F:,} records match the {unit['ppb']:,} in `ppb`, a "
          "concentration unit, not an absorption coefficient. The total has no dimension; the "
          "parts come from one column that mixes scales."))
    w("")
    w(C("C-OQ-J1-TWOUNITS", "That the column mixes scales is visible in the same table: "
        f"`Konduktivitet`'s {K:,} records are exactly the {unit['mS/cm']:,} in `mS/cm` and the "
        f"{unit['mS/m']:,} in `mS/m`, and `Vægtfylde`'s {V:,} exactly the {unit['g/l']:,} in "
        f"`g/l` and the {unit['kg/m3']:,} in `kg/m3`: one parameter, two unit labels, told "
        "apart only by the unit field of each record."))
    w("")
    w(C("C-OQ-J1-VACUOUS", "**Second, the shrink-by-P test is vacuous, because P is fitted "
        "rather than measured.** Adding FDOM does reduce R - but FDOM's *contribution to "
        "attenuation* is the fitted coefficient of the same regression that produces R, not an "
        "independent measurement of it. The account is circular in the way `RESIDUAL.md` "
        "describes, and `R_new = R_old − P` has no independent `P`. It would become a real test "
        "only if the absorption by dissolved matter were measured, and none of the extract's "
        "channels measures an absorption."))
    w("")
    w(C("C-OQ-J1-START", "**Third, even the ship's own attenuation coefficient depends on how "
        "the cast was taken.** In this project's light analysis the growth-season casts whose "
        f"profile begins above {split:g} m give a median Kd of {sd['kd_shallow_start']} and "
        f"those beginning below it {sd['kd_deep_start']}; where a cast starts is a matter of "
        "how it was taken, not of the water.") + " "
      + C("C-OQ-J1-LYSD", "The per-depth `Lysdæmpning` channel escapes that artefact but "
          "inherits the first reason instead."))
    w("")
    w(C("C-OQ-J1-TRANSP", "**And the target's own name is the last objection.** TEP are, in "
        "the encyclopaedia's words, *otherwise transparent*: they are counted by staining them "
        "with Alcian blue.") + " "
      + C("C-OQ-J1-PROXY", "An optical proxy for them means detecting, inside a residual, a "
          "substance that is counted by staining because it is otherwise transparent. "
          "Aggregated gel does scatter - TEP form the aggregates known as marine snow - but "
          "turbidity is a measure of scattered light, and it is subtracted out before R is "
          "formed."))
    w("")
    w("## What building it anyway would and would not license")
    w("")
    w(C("C-OQ-J1-WOULD", "It **would** license a description: how much attenuation is "
        "unexplained by the three channels meant to explain it, in ranks rather than units, and "
        "whether "
        "that share has seasonal or station shape.") + " "
      + C("C-OQ-J1-NOSCRIPT", "No script in this repository computes it."))
    w("")
    w(C("C-OQ-J1-WOULDNOT", "It **would not** license calling the residual gel, TEP or "
        "fedtemøg. That is the shrinkage move in `RESIDUAL.md` - naming the leftover after one "
        "item on its list - and the list here includes the sondes' calibration, which the "
        f"extract corrects by a factor other than one on {corr['factor_other']:,} records, the "
        "unrecorded path length, dissolved matter FDOM does not see, and whatever else "
        "attenuates light that none of the three channels measures."))
    w("")
    w("## The smallest unblocking thing")
    w("")
    w(C("C-OQ-J1-SMALL", "**{param:oq_j1_samples} Alcian-blue TEP samples from the rosette on "
        "casts already running the four-sensor suite, at stations carrying FDOM.** Not a survey "
        "- a calibration: the paired points settle whether R carries any TEP information. A "
        "correlation would turn the existing four-sensor casts into a retrospective TEP series; "
        "no correlation retires the optical route. The method needs the dye and a "
        "spectrophotometer."))
    w("")
    w(C("C-OQ-J1-ASK", "Cheaper still, and prerequisite to the first reason: **ask ODA for the "
        "path length of the instrument behind `Lysdæmpning`.** Without it no attenuation "
        f"coefficient can be reconstructed from the channel's {L:,} records."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/openproblems/J1.md", page))
