#!/usr/bin/env python3
"""docs/openproblems/E7.md - what the data held here can and cannot show about E7.

Every number is read from data (live_json) or is a stated design value with its
reason; every assertion is a checked claim (LIVE_NUMBERS.md section 11), registered in
data/manual/claims.d/w3-op.json with what it rests on, and every field printed has a
declared construction. What the draft once said and could not justify is in
docs/ARCHIVE.md, not here. The page is written through scripts/pages/drafts_b_page.py.

    python3 scripts/pages/openproblem_e7.py
"""
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED, ROOT
import live

C = live.claim
R = live.ref
RAW = os.path.join(ROOT, "data", "raw")
HERBICIDES = ("Diuron", "Hydroxy-atrazin", "Hydroxysimazin")
PHENOXY = ("2-(2,6-dichlorphenoxy)propionsyre", "2-(2-Chlor-6-methylphenoxy)propionsyre")
MFS_FIELDS = {"aktivslut", "aktivstart", "da_oekol_1", "da_oekolog", "eusurfacew", "formaal",
              "link", "maaltbiota", "maaltsedim", "maaltvand", "mon_id", "mon_id_1", "monst",
              "navn", "oid_", "qecode", "qestatusor", "vandid", "xutm_euref", "yutm_euref"}
GEUS = {"seabed_sediment_dk.gpkg", "marta_sedimentproever.geojson"}
GROUNDWATER = {"grundvand_pejlinger_2021.geojson": {"id", "kilde", "kote", "navn", "x", "y"},
               "grundvand_potentialelinjer_2021.geojson": {"id", "kote", "shape_le_1",
                                                           "shape_leng"},
               "terraen_minus_gvs.geojson": {"id", "lower", "ogc_fid", "upper"}}
PEST = re.compile(r"pestic|herbic|insektic|fungic|glyphos|atrazin|simazin|diuron|lindan|DDT", re.I)


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def refuse(msg):
    raise live.Unjustified("E7: " + msg)


def single(features, key):
    vals = {str(f["properties"].get(key)) for f in features}
    if len(vals) != 1:
        refuse(f"{key} no longer takes one value across the layer")
    return vals.pop()


def text():
    dc = J("drafts_b_counts.json")
    ss, mfs = dc["stations_series"], dc["mfs"]
    hf = J("hypodraft_facts.json")
    reg, year0 = hf["stations_register"], hf["series_by_variable"]["year0"]
    en = J("enums.json")
    ctd = en["ctd"]
    par, kemi = ctd["categorical"]["Parameter"], en["kemi"]["categorical"]["Parameter"]
    meta = J("meta_facts.json")
    ox = J("oxygen.json")["hazardous"]

    # the page's statements about the files, refused if the files stop saying them
    if len(par) != meta["ctd_parameters"] or any(PEST.search(p) for p in par):
        refuse("the CTD Parameter list has changed")
    missing = [p for p in HERBICIDES + PHENOXY if p not in kemi]
    if missing:
        refuse(f"the water chemistry no longer names {missing}")
    layer = json.load(open(os.path.join(RAW, "national", "sw_mfs_tilstand.geojson"),
                           encoding="utf-8"))["features"]
    keys = set().union(*(f["properties"] for f in layer))
    if keys != MFS_FIELDS:
        refuse(f"the pollutant layer's fields have changed: {sorted(keys ^ MFS_FIELDS)}")
    if any(mfs[k] != 1 for k in ("distinct_qecode", "distinct_qestatusor",
                                 "distinct_da_oekolog", "distinct_aktivstart")):
        refuse("a field the page calls uniform now varies")
    qe, qs = single(layer, "qecode"), single(layer, "qestatusor")
    do, ak = single(layer, "da_oekolog"), single(layer, "aktivstart")
    if set(os.listdir(os.path.join(RAW, "geus"))) != GEUS:
        refuse("data/raw/geus holds other files now")
    gw = {os.path.basename(p) for p in glob.glob(os.path.join(RAW, "grundvand*"))}
    if gw | {"terraen_minus_gvs.geojson"} != set(GROUNDWATER):
        refuse("the groundwater files have changed")
    for name, props in GROUNDWATER.items():
        f0 = json.load(open(os.path.join(RAW, name), encoding="utf-8"))["features"][0]
        if set(f0["properties"]) != props:
            refuse(f"{name} carries other fields now")
    if ox["with_points"] != 0:
        refuse("a marine water body now carries a hazardous-substance point")

    herb = [kemi[p] for p in HERBICIDES]
    names = ", ".join(sorted(par, key=lambda p: -int(par[p])))

    o = []
    w = o.append
    w(f"# {R('E7', title=True)}")
    w("")
    w("*Generated by `scripts/pages/openproblem_e7.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w(C("C-OQ-E7-STATUS", "**Missing: measurement.** The quantity the hypothesis is about is "
        "held only thinly: the held marine water chemistry names a herbicide and two "
        f"degradation products of herbicides, on {min(herb):,} to {max(herb):,} records each, "
        f"and nothing held pairs them with a fauna response. {R('E7')} is **unscoreable here, "
        "not refuted**."))
    w("")
    w("## What a test would need, and which side is empty")
    w("")
    w(C("C-OQ-E7-NEEDS", f"{R('E7')} says agricultural pesticides reach the sea and act on "
        "non-target organisms, and that they are collinear with nitrogen because the same "
        "farming produces both. Discriminating it needs, at shared positions: (a) a "
        "concentration of at least one **named** active substance or degradation product in "
        "water, sediment or biota; (b) a fauna or algal response; (c) a nutrient-load covariate "
        "to hold fixed.") + " "
      + C("C-OQ-E7-SIDES", "(a) is held, thinly, in the water chemistry. (b) is in ODA "
          "`Bundfauna`, not fetched. (c) is not held as a load: the water carries nutrient "
          "concentrations, but river load lives on an ODA endpoint `fetch_oda.py` cannot "
          "reach."))
    w("")
    w("## What is actually here - counted")
    w("")
    w("- " + C("C-OQ-E7-PANEL", f"`docs/data/areas/stations_series.json` - "
               f"{ss['total_station_months']:,} station-months, {ss['n_stations']:,} stations, "
               f"{ss['months']} monthly slots from {year0}, across {ss['n_variables']} "
               "variables: fluorescence, oxygen and oxygen saturation (bed and surface), "
               "salinity and temperature (bed and surface). **No toxicant variable of any "
               f"kind.** Near-bed oxygen alone is {ss['variables']['oxy_bed']['n']:,} "
               f"station-months over {ss['variables']['oxy_bed']['stations']:,} stations: the "
               "response-side record is dense; the exposure side has no column to sit in "
               "there."))
    w("- " + C("C-OQ-E7-REG", "`data/raw/oda/stations.csv` - the ODA station register: "
               f"{reg['rows']:,} rows, {reg['stations']:,} distinct stations."))
    w("- " + C("C-OQ-E7-CTD", f"`data/raw/oda/ctd.csv.gz` - {ctd['rows']:,} records; the "
               f"`Parameter` column takes {meta['ctd_parameters']} distinct values: {names}. "
               "**Not one is a pesticide, a degradation product, or any organic "
               "contaminant.**"))
    w("- " + C("C-OQ-E7-KEMI", "`data/raw/oda/kemi.csv.gz`, the marine water chemistry with its "
               "hazardous substances, is held, and among its `Parameter` values are `Diuron` on "
               f"{kemi['Diuron']:,} records, a herbicide, and `Hydroxy-atrazin` on "
               f"{kemi['Hydroxy-atrazin']:,} and `Hydroxysimazin` on {kemi['Hydroxysimazin']:,}, "
               "the hydroxy forms of the triazine herbicides atrazine and simazine; beside them "
               f"two chlorinated phenoxypropionic acids, `{PHENOXY[0]}` on "
               f"{kemi[PHENOXY[0]]:,} and `{PHENOXY[1]}` on {kemi[PHENOXY[1]]:,}, whose use this "
               "page has not checked.") + " "
      + C("C-OQ-E7-KEMI-THIN", "The held counts are records per parameter; how many stations "
          "and years they span has not been counted, so whether they meet the test below is "
          "open."))
    w("- " + C("C-OQ-E7-GEUS", "`data/raw/geus/` holds only `seabed_sediment_dk.gpkg` and "
               "`marta_sedimentproever.geojson` - a sediment **map** and raw-material samples. "
               "There is **no Jupiter groundwater chemistry** here.") + " "
      + C("C-OQ-E7-GW", "The groundwater files in `data/raw/` - "
          "`grundvand_pejlinger_2021.geojson`, `grundvand_potentialelinjer_2021.geojson` and "
          "`terraen_minus_gvs.geojson` - hold water levels, potentiometric contours and depth to "
          "the water table, and no analyte. The groundwater route to a land-side pesticide "
          "series is not present in this archive."))
    w("- " + C("C-OQ-E7-STREAMS", "The land-side series that does exist is ODA's stream water "
               "chemistry (`ODA-VANDLOEB-MFS`), which the source register records as carrying "
               "glyphosate, AMPA, bentazon, MCPA, mechlorprop and other pesticides per sample; "
               "it is not fetched."))
    w("- " + C("C-OQ-E7-SALES", "No pesticide sales or usage series is held, and the source "
               "register records that where Denmark's national pesticide statistics are now "
               "published could not be established."))
    w("")
    w("## The national pollutant-status layer")
    w("")
    w(C("C-OQ-E7-MFS", f"`data/raw/national/sw_mfs_tilstand.geojson` - **{mfs['points']} "
        f"points, none of them marine**: {mfs['by_type']['DKLAKE']} `DKLAKE`, "
        f"{mfs['by_type']['DKRIVER']} `DKRIVER`. Matrices flagged: biota {mfs['biota']}, water "
        f"{mfs['water']}, **sediment {mfs['sediment']}**, nothing {mfs['no_matrix']}.") + " "
      + C("C-OQ-E7-MFS-ONE", f"What each point carries is `qecode = \"{qe}\"`, "
          f"`qestatusor = \"{qs}\"`, `da_oekolog = \"{do}\"` and `aktivstart = {ak}`, each the "
          f"same on all {mfs['points']}. **No analyte name, no concentration, no unit, no "
          "sampling date.**"))
    w("")
    w("- " + C("C-OQ-E7-CONFLATE", "**Schema conflation.** One quality-element code stands for "
               "every river-basin-specific pollutant, whatever the substance, in a single "
               "column. A pesticide effect cannot be separated from any other pollutant's even "
               "in principle at this resolution."))
    w("- " + C("C-OQ-E7-VERDICT", "**Model-as-datum.** The value is a status verdict, and it is "
               f"invariant across all {mfs['points']} points, so it carries no information for "
               "discriminating anything."))
    w("- " + C("C-OQ-E7-NOMARINE", "No marine water body here carries a hazardous-substance "
               f"observation: of the {ox['n_wb']} marine water bodies, {ox['with_points']} have "
               "a point of the layer, because every point belongs to a lake or a river."))
    w("")
    w("## Why *measurement* and not the other two")
    w("")
    w(C("C-OQ-E7-NOTEXP", "Not **experiment**: no intervention is required. Ordinary "
        "monitoring, of a kind already run for nutrients, would produce the series."))
    w("")
    w(C("C-OQ-E7-ARMCHAIR", "Not yet **armchair**: an armchair block means the numbers exist "
        "and joining them is merely too large.") + " "
      + C("C-OQ-E7-MFSTOPICS", "The source register records the analyte lists of the ODA marine "
          "hazardous-substance topics: sediment (`ODA-SEDKEMI-MFS`) phthalates, alkylphenols and "
          "bulk carbon, and no pesticide; mussels (`ODA-MFS-MUSLING`) organotins, metals, PAH, "
          "dioxins and PCBs; fish (`ODA-MFS-FISK`) PFAS, brominated flame retardants, PCBs, "
          "dioxins, HCH, DDT and DDE, HCB and mercury.") + " "
      + C("C-OQ-E7-LEGACY", "So pesticides do appear in the marine record - HCH, whose gamma "
          "isomer lindane has been used as an agricultural insecticide, in fish, and the "
          "herbicides above in the water - but whether any is dense enough to join against fauna "
          "is the test below, not yet run."))
    w("")
    w(C("C-OQ-E7-RECLASS", "**Reclassification test, stated in advance.** If named pesticide or "
        "degradation-product analytes are found at ≥{param:oq_e7_min_stations} marine stations "
        "with ≥{param:oq_e7_min_years} years of dated results and a non-censored fraction above "
        "{param:oq_e7_min_detect_pct}%, " + R("E7") + " moves to **armchair** and this page is "
        "wrong. Anything thinner leaves it here."))
    w("")
    w("## Smallest unblocking thing")
    w("")
    w("1. " + C("C-OQ-E7-S1", "**Count, then enumerate.** In the held water chemistry, count "
                "stations and years for each pesticide parameter - that decides the test above "
                "for the water. Then run the topic and parameter *metadata* calls "
                "`scripts/fetch_oda.py` already implements (`expand`, `option_list`) against "
                "Hav / Sedimentkemi / MFS Sporstof and Hav / MFS i biota, and record the "
                "parameter names and per-parameter station counts. Metadata only, no extract."))
    w("2. " + C("C-OQ-E7-S2", "**If that is too thin**, the smallest useful addition is one "
                "analyte panel bolted onto stations that already carry fauna: "
                "{param:oq_e7_stations} existing `Bundfauna` stations spanning an agricultural "
                "gradient, sampled before application, twice after, and in winter, sediment plus "
                "passive samplers. The requirements, each of which the national pollutant-status "
                "layer violates: **named analytes reported individually, never a \"pesticides\" "
                "sum**; **per-analyte LOD reported with every result**, chosen below the effect "
                "concentration for the conserved target rather than wherever the instrument "
                "lands; and **\"< LOD\" recorded as censoring with its threshold**, so a "
                "non-detect is reportable as a bound instead of silently becoming a zero.") + " "
      + C("C-OQ-E7-PANELCHOICE", "Pick the panel by target conservation, not market label: a "
          "photosystem-II inhibitor with its degradation product, since the algae the chlorophyll "
          "indicator counts photosynthesise, and glyphosate with AMPA, its breakdown product in "
          "soil."))
    w("")
    w("## What such data would, and would not, license")
    w("")
    w(C("C-OQ-E7-LICENSE", "Even a complete marine pesticide series would **not** license "
        f"\"pesticides did it\". {R('E7')}'s own prediction is that pesticide and nitrogen load "
        "are collinear because one agriculture produces both, so a concentration series is only "
        "discriminating where the two vary independently - same nutrient load, different "
        "pesticide exposure. Whether that contrast exists anywhere in Danish waters is a second, "
        "unanswered measurement question, and it is worth answering *before* collecting the "
        "first series rather than after.") + " "
      + C("C-OQ-E7-LICENSE2", "What the series would license immediately is narrower and still "
          "worth having: a statement of whether the exposure is present at concentrations near "
          "the effect thresholds of the conserved targets at all - which this project has not "
          "examined, for the held herbicide records or any other."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/openproblems/E7.md", page))
