#!/usr/bin/env python3
"""docs/openproblems/J1.md - generated from the hand-written draft as committed at 7c4dd30.

The prose is the draft's, moved here verbatim and then made checkable: counts of
files held in this repository read live from data/derived/drafts_b_counts.json;
counts the drafting session made from external sources or one-off runs carried as
quotations of that commit (located references, {was:COMMIT:FILE:phrase with @@}); register IDs as {ref:}; chemical species
as {chem:}. See scripts/pages/drafts_b_page.py and LIVE_NUMBERS.md.

    python3 scripts/pages/openproblem_j1.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from drafts_b_page import render

TEXT = r'''# {ref:J1|title}

*Generated by `scripts/pages/openproblem_j1.py` from the draft as committed at `7c4dd30`. Counts of files held in this repository are read live. Counts that session made from external sources or from one-off runs are quotations of that commit - what the draft reported, shown as such, not re-derived by the build.*


**Missing: measurement** — specifically the second kind, *a new metric over what is
already recorded*. The metric can be written down. It cannot be formed in physical units,
and if it could it could not be attributed. All three of those are the finding.

## The direct quantity is absent, and this is checked rather than assumed

`J1` says gel production rises when N:P is skewed **in either direction**, and it names
its own discriminator: TEP against ambient N:P and bloom senescence stage, not against
nutrient load.

Enumerating the `Parameter` column of the whole CTD extract (`data/raw/oda/ctd.csv.gz`,
one streaming pass) returns **{was:7c4dd30:docs/openproblems/J1.md:returns **@@ distinct parameters**} distinct parameters** and no more:

> Temperatur {was:7c4dd30:docs/openproblems/J1.md:more: > Temperatur @@ · Salinitet} · Salinitet {was:7c4dd30:docs/openproblems/J1.md:· Salinitet @@ · Oxygen indhold} · Oxygen indhold {was:7c4dd30:docs/openproblems/J1.md:Oxygen indhold @@ · **Fluorescens} · **Fluorescens
> {was:7c4dd30:docs/openproblems/J1.md:7,146,792 · **Fluorescens > @@** · Oxygenmætning 6,598,099}** · Oxygenmætning {was:7c4dd30:docs/openproblems/J1.md:6,783,570** · Oxygenmætning @@ · **Lysdæmpning 5,217,330**} · **Lysdæmpning {was:7c4dd30:docs/openproblems/J1.md:Oxygenmætning 6,598,099 · **Lysdæmpning @@** · Konduktivitet >}** · Konduktivitet
> {was:7c4dd30:docs/openproblems/J1.md:· Konduktivitet > @@ · Vægtfylde 4,329,607} · Vægtfylde {was:7c4dd30:docs/openproblems/J1.md:5,169,272 · Vægtfylde @@ · **Turbiditet 1,076,915**} · **Turbiditet {was:7c4dd30:docs/openproblems/J1.md:Vægtfylde 4,329,607 · **Turbiditet @@** · **FDOM 890,921**}** · **FDOM {was:7c4dd30:docs/openproblems/J1.md:**Turbiditet 1,076,915** · **FDOM @@** · > Photometer}** ·
> Photometer måling {was:7c4dd30:docs/openproblems/J1.md:Photometer måling @@ · Photometer} · Photometer reference {was:7c4dd30:docs/openproblems/J1.md:· Photometer reference @@ · pH 237,445} · pH {was:7c4dd30:docs/openproblems/J1.md:531,071 · pH @@ · > Strømhastighed} ·
> Strømhastighed {was:7c4dd30:docs/openproblems/J1.md:· > Strømhastighed @@ · Strømretning 84,572} · Strømretning {was:7c4dd30:docs/openproblems/J1.md:84,734 · Strømretning @@ · Farvestof 4,601} · Farvestof {was:7c4dd30:docs/openproblems/J1.md:84,572 · Farvestof @@ · Dihydrogensulfid 2,601} · Dihydrogensulfid {was:7c4dd30:docs/openproblems/J1.md:4,601 · Dihydrogensulfid @@ No TEP, no}

No TEP, no polysaccharide, no Alcian blue, no gel, no microlayer. This confirms
`J1-J2-J3-GAP` in `DATA_QUEUE.md` from the file rather than from the note. In-water N and
P are also absent locally — `data/raw/oda/stations.csv` is a station registry, and
`ODA-TILFOERSEL` (queued, unfetched) is *region-aggregated load*, the exact quantity `J1`
says not to use. The hypothesis is missing both its dependent variable and its
discriminator. **Absent dimension: `J1` is unscoreable, not refuted.**

## The new metric, stated precisely enough to be rejected

The archive holds more optics than the derived cube exposes.
`docs/data/areas/stations_series.json` carries {fig:dbx_ss_total} station-months over {fig:dbx_ss_nvars} variables,
of which one is optical (`fluo`, {fig:dbx_ss_fluo} station-months, unit `rel`). The raw CTD file
carries three more, and they co-occur. Distinct (station, date) casts by sensor set:

| sensors present on the cast | casts |
|---|---:|
| fluorescence + attenuation | {was:7c4dd30:docs/openproblems/J1.md:+ attenuation | @@ | | fluorescence} |
| fluorescence + attenuation + turbidity | {was:7c4dd30:docs/openproblems/J1.md:+ turbidity | @@ | | fluorescence} |
| fluorescence + attenuation + FDOM | {was:7c4dd30:docs/openproblems/J1.md:+ FDOM | @@ | | **all} |
| **all four (fluo + FDOM + attenuation + turbidity)** | **{was:7c4dd30:docs/openproblems/J1.md:+ turbidity)** | **@@** | | any}** |
| any FDOM at all | {was:7c4dd30:docs/openproblems/J1.md:at all | @@ (211 stations, **2021–2026} ({was:7c4dd30:docs/openproblems/J1.md:all | 10,589 (@@ stations, **2021–2026 only**) |} stations, **2021–2026 only**) |

FDOM — the CDOM proxy, and the one term that could be measured *out* of an optical
residual — begins in 2021. The metric would be, per cast in the {was:7c4dd30:docs/openproblems/J1.md:per cast in the @@: > **R =}:

> **R = Lysdæmpning − f(Fluorescens, FDOM, Turbiditet)**

attenuation unexplained by the chlorophyll, coloured dissolved matter and mineral
particles that are supposed to explain it. `RESIDUAL.md` gives the only test such a
number admits: **R must shrink by exactly P when a part P is measured out of it.**

## Why it fails — four reasons, computed here

**First, R has no physical units, because the inputs have none.** Enumerating
`Parameter`×`Enhed` over the same file: Lysdæmpning is recorded in **`pct`** ({was:7c4dd30:docs/openproblems/J1.md:recorded in **`pct`** (@@ rows) — a transmission}
rows) — a transmission percentage whose **beam path length is nowhere in the record**, so
it cannot be converted to m⁻¹. Fluorescens is **`Ingen`**, dimensionless, on {was:7c4dd30:docs/openproblems/J1.md:**`Ingen`**, dimensionless, on @@ of its} of
its {was:7c4dd30:docs/openproblems/J1.md:6,783,473 of its @@ rows (83 in} rows ({was:7c4dd30:docs/openproblems/J1.md:its 6,783,570 rows (@@ in µg/l, 14 "Ikke} in µg/l, {was:7c4dd30:docs/openproblems/J1.md:in µg/l, @@ "Ikke oplyst"). FDOM} "Ikke oplyst"). FDOM is `ppb`, a fluorescence-standard
unit, not an absorption coefficient. Error **class 6, absent dimension**, on the total;
**class 4, schema conflation**, on the parts. That the column really does conflate units is
visible in the same table: Konduktivitet appears as mS/cm ({was:7c4dd30:docs/openproblems/J1.md:appears as mS/cm (@@) *and* mS/m (743,747),}) *and* mS/m
({was:7c4dd30:docs/openproblems/J1.md:(4,425,525) *and* mS/m (@@), Vægtfylde as g/l}), Vægtfylde as g/l ({was:7c4dd30:docs/openproblems/J1.md:Vægtfylde as g/l (@@) *and* kg/m³ (917,384)}) *and* kg/m³ ({was:7c4dd30:docs/openproblems/J1.md:(3,412,223) *and* kg/m³ (@@) — factors of}) — factors of {was:7c4dd30:docs/openproblems/J1.md:— factors of @@ and 1000 inside} and {was:7c4dd30:docs/openproblems/J1.md:and @@ inside one}
inside one column, unflagged. {was:7c4dd30:docs/openproblems/J1.md:column, unflagged. @@ further rows} further rows are column-shifted, with the parameter
name sitting in the unit field.

**Second, the shrink-by-P test is vacuous, because P is fitted rather than measured.** Adding
FDOM does reduce R — but FDOM's *contribution to attenuation* is the fitted coefficient
of the same regression that produces R, not an independent measurement of it. The account
is circular in the way `RESIDUAL.md` describes, and `R_new = R_old − P` has no
independent `P`. It would become a real test only if CDOM absorption were measured, and
per the first reason it is not.

**Third, the candidate signal is smaller than the disagreement between two measurements of
the total.** On the {was:7c4dd30:docs/openproblems/J1.md:On the @@ same-day ship/satellite} same-day ship/satellite pairs in `data/derived/matchups.json`,
the log ratio of satellite Kd490 to ship Kd(PAR) has **sd {was:7c4dd30:docs/openproblems/J1.md:Kd(PAR) has **sd @@** (median}** (median {was:7c4dd30:docs/openproblems/J1.md:has **sd 0.352** (median @@, p10–p90 0.566–1.188). Regressing}, p10–p90
{was:7c4dd30:docs/openproblems/J1.md:(median 0.769, p10–p90 @@–1.188). Regressing log}–{was:7c4dd30:docs/openproblems/J1.md:(median 0.769, p10–p90 0.566–@@). Regressing log KD490}). Regressing log KD490 on log CHL in two single-day slices of
`data/raw/cmems/grid/{transp,plankton}__inner__2015.nc` (n = {was:7c4dd30:docs/openproblems/J1.md:(n = @@ and 15,624) leaves residuals} and {was:7c4dd30:docs/openproblems/J1.md:= 22,916 and @@) leaves residuals}) leaves
residuals of **sd {was:7c4dd30:docs/openproblems/J1.md:residuals of **sd @@ and 0.206**. The} and {was:7c4dd30:docs/openproblems/J1.md:**sd 0.172 and @@**. The satellite-only}**. The satellite-only version of this metric is dead on
arrival, by arithmetic rather than judgement.

**Fourth, even the ship total is partly a model.** `LIGHT.md` establishes that broadband Kd
falls with depth in uniform water; casts beginning above {was:7c4dd30:docs/openproblems/J1.md:beginning above @@ m give} m give median Kd {was:7c4dd30:docs/openproblems/J1.md:give median Kd @@, below}, below
{was:7c4dd30:docs/openproblems/J1.md:Kd 0.35, below @@ m 0.27 —} m {was:7c4dd30:docs/openproblems/J1.md:below 2 m @@ — a 23%} — a {was:7c4dd30:docs/openproblems/J1.md:m 0.27 — a @@% swing from an}% swing from an undocumented metadata choice. Error **class 7,
model-as-datum**. The per-depth `Lysdæmpning` channel escapes that particular artefact
but inherits the first reason instead.

**And the target's own name is the last objection.** TEP is called *transparent* because
its refractive index is close to seawater's; it requires staining to be counted at all.
An optical proxy for it means detecting, inside a residual, the substance chosen for
having the weakest optical expression in the water. Aggregated gel — marine snow — does
scatter, but turbidity already counts that and is subtracted out before R is formed.

## What building it anyway would and would not license

It **would** license a description: how much attenuation is unexplained by the three
sensors that exist, in ranks rather than units, and whether that share has seasonal or
station shape. Nobody has that figure and it is worth having.

It **would not** license calling the residual gel, TEP or fedtemøg. That is the shrinkage
move in `RESIDUAL.md` — naming the leftover after one item on its list — and the list here
demonstrably includes sonde calibration drift, unstated path length, residual CDOM beyond
what FDOM tracks, and spectral mismatch between a broadband channel and two fluorometers.

## The smallest unblocking thing

**Thirty Alcian blue TEP samples from the rosette on casts already running the
four-sensor suite, at any of the {was:7c4dd30:docs/openproblems/J1.md:of the @@ stations carrying} stations carrying FDOM since 2021.** Not a survey — a
calibration. Thirty paired points settle whether R carries any TEP information: a
correlation turns {was:7c4dd30:docs/openproblems/J1.md:correlation turns @@ existing casts} existing casts into a retrospective TEP series; no correlation
retires the optical route permanently and cheaply. The method costs a filter, a dye and a
spectrophotometer.

Cheaper still, and strictly prerequisite to the first reason: **ask ODA for the transmissometer
path length behind `Lysdæmpning`.** One field, already known to the operators, currently
unrecorded — without it no attenuation coefficient can be reconstructed from five million
readings.
'''

if __name__ == "__main__":
    sys.exit(render("docs/openproblems/J1.md", TEXT))
