#!/usr/bin/env python3
"""docs/openproblems/A7.md - what the data held here can and cannot show about A7.

Every number is read from data (live_json), from a pinned document ({read:}) or is a
stated design value with its reason; every assertion is a checked claim
(LIVE_NUMBERS.md section 11), registered in data/manual/claims.d/w3-op.json with what it
rests on, and every field printed has a declared construction. What the draft once said
and could not justify is in docs/ARCHIVE.md, not here. The page is written through
scripts/pages/drafts_b_page.py.

    python3 scripts/pages/openproblem_a7.py
"""
import os
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))
from drafts_b_page import render
from common import DERIVED, ROOT
import live

C = live.claim
R = live.ref
HE, NV, SR = "OQ-HYLEN-ESSD", "NOVANA-2327", "OQ-SR323"
P_KER = ("I 1991-1992 udgjorde frigivelsen fra sedimentet 65 % og 70 % af den samlede belastning "
         "med hhv. N og P i fjorden")
P_HY = ("The presented dataset contains 498 individual fluxes measured in situ with three types "
        "of benthic chamber landers at 59 stations over 20 years")
P_NV = ("I NOVANA 2023-27 vil der i alt blive indsamlet prøver fra 90 af de 109 vandområder; "
        "årligt overvåges 16-19 stationer")
P_NVT = "7 sedimentdybder (17-19 stn./år)"
NUTRIENT_KEYS = ("dip", "po4", "phos", "no3", "nox", "nh4", "din", "ntot", "ptot", "nut")
SEABED_FIELDS = {"fid", "Shape", "OBJECTID", "sedimentdk", "sedimenten", "scale", "kortlaegni",
                 "mapping", "kommentar", "comments", "reference", "ruleid", "override",
                 "Shape_Length", "Shape_Area"}


def J(name):
    return live.live_json(os.path.join(DERIVED, name))


def RD(sid, shown, phrase):
    """A number read out of a pinned document, located by a phrase in it."""
    return "{read:%s:%s|%s}" % (sid, shown, phrase)


def refuse(msg):
    raise live.Unjustified("A7: " + msg)


def text():
    rs = J("rescore.json")
    dip = rs["matrix"]["A7"]["fetch_supplied"]["dip"]
    bym = rs["tests"]["A7_bottom_dip_by_month"]
    lo = min(bym, key=lambda m: bym[m]["median"])
    hi = max(bym, key=lambda m: bym[m]["median"])
    if (int(lo), int(hi)) != (4, 10):
        refuse(f"the lowest and highest months of bottom phosphate are now {lo} and {hi}")
    apr, octo = bym["4"]["median"], bym["10"]["median"]

    dc = J("drafts_b_counts.json")
    ss, md, sb, portal = dc["stations_series"], dc["maaledybde"], dc["seabed"], dc["oda_portal"]
    hf = J("hypodraft_facts.json")
    year0, sbf = hf["series_by_variable"]["year0"], hf["seabed"]
    if any(k.lower().startswith(NUTRIENT_KEYS) for k in ss["variables"]):
        refuse("the monthly panel now carries a nutrient variable")
    if md["rows_x_equals_x1"] != md["rows"]:
        refuse("not every Secchi record repeats its easting column any more")
    con = sqlite3.connect(os.path.join(ROOT, "data", "raw", "geus", "seabed_sediment_dk.gpkg"))
    fields = {r[1] for r in con.execute('pragma table_info("Seabed_sedimen")')}
    con.close()
    if fields != SEABED_FIELDS:
        refuse(f"the seabed layer's fields have changed: {sorted(fields ^ SEABED_FIELDS)}")
    oda = os.listdir(os.path.join(ROOT, "data", "raw", "oda"))
    if any("sedim" in f.lower() or "sporstof" in f.lower() for f in oda):
        refuse("a sediment-chemistry extract is now held")
    if "Emne_12_19" in open(os.path.join(ROOT, "scripts", "fetch_oda.py"), encoding="utf-8").read():
        refuse("fetch_oda.py now names the sediment topic")
    vlist = " · ".join(f"`{k}` {v['n']:,}" for k, v in ss["variables"].items())
    clist = ", ".join(f"{k} {v}" for k, v in sb["by_class"].items())
    sed = portal["sedimentkemi_sporstof"]

    o = []
    w = o.append
    w(f"# {R('A7', title=True)}")
    w("")
    w("*Generated by `scripts/pages/openproblem_a7.py`: what the data held here can and "
      "cannot show about the hypothesis. Each marked statement links to what it rests on.*")
    w("")
    w(C("C-OQ-A7-STATUS", "**Missing: armchair for the weak form, measurement for the strong "
        f"form.** {R('A7')} says the bed releases stored N and P in summer. Its two "
        "discriminators fall in different categories:"))
    w("")
    w("- " + C("C-OQ-A7-WEAK", "**the DIP seasonality ratio against the sediment organic "
               "pool** - the response side is held and the pool side is in ODA, unfetched. "
               "**Armchair.** Tentative, not an obstacle."))
    w("- " + C("C-OQ-A7-STRONG", "**benthic flux chambers** - for Danish inner waters the "
               "in-situ chamber fluxes found are one cruise's, in the Skagerrak and Kattegat in "
               "2021; a seasonal internal load for four Danish fjords in 1999–2000 is tabulated "
               "from unpublished data, and the measurements behind it were not found. "
               "**Measurement.**"))
    w("")
    w(C("C-OQ-A7-DIP", "The response side: the held water-chemistry extract carries "
        f"`Ortho-phosphat-P` on {dip['n']:,} samples that `scripts/rescore.py` accepts, at "
        f"{dip['stations']:,} stations over {dip['years']}. Below its depth cut the monthly "
        f"median runs from {apr} µg/l in April, the lowest month, to {octo} µg/l in October, the "
        "highest.") + " "
      + C("C-OQ-A7-POOL", "The pool side, ODA's Sedimentkemi, is not held, so "
          f"{R('A7')} cannot yet be scored in either form."))
    w("")
    w("## Sources found")
    w("")
    w("### In-situ chamber fluxes, all of them east of the Danish straits")
    w("")
    w(C("C-OQ-A7-HYLEN", "**Hylén et al. (2025)**, *In situ-measured benthic fluxes of dissolved "
        "inorganic phosphorus in the Baltic Sea* (Earth System Science Data), publish "
        f"{RD(HE, '498', P_HY)} DIP fluxes measured in situ with benthic chamber landers at "
        f"{RD(HE, '59', P_HY)} stations between 2001 and 2021, with bottom-water oxygen, "
        "sediment organic carbon and sediment type beside them. The data are one file, "
        "`BalticSeaInSituFluxDIP_v3.xlsx`, in Zenodo record `17465937`, under the Creative "
        "Commons Attribution licence.") + " "
      + C("C-OQ-A7-HYLEN-WEST", "They do not count the Kattegat and the Belt Sea, west of the "
          "Arkona Basin, as part of the Baltic Sea, and the westernmost subbasin they group is "
          "the Arkona and Bornholm Basin, so no station of theirs lies in the Kattegat or the "
          "Belts."))
    w("")
    w(C("C-OQ-A7-HYLEN-PATH", "A chamber lander incubating a patch of bed is a different "
        "instrument, quantity and operator from the CTD sonde - the authors are at the "
        "University of Gothenburg, GEOMAR and elsewhere, not Danish monitoring - so it is a "
        "production path separate from the CTD, ocean colour and Secchi."))
    w("")
    w("### Others found")
    w("")
    w("- " + C("C-OQ-A7-FR483", "**NERI Technical Report `483`** (Fossing et al. 2004) sets up "
               "an oxygen and nutrient flux model for Aarhus Bay. Its constants were set by "
               "comparing the model's stationary state with a year's mean measurements from the "
               "HAV90 programme in Aarhus Bay, and it cites that programme's reports on the sea "
               "floor's oxygen uptake (Gundersen et al. 1995) and nitrogen cycling (Lomstein and "
               "Blackburn 1992)."))
    w("- " + C("C-OQ-A7-AL561", "**AL561** (GEOMAR, 2021): benthic landers and cores at "
               "high-accumulation sites in the Skagerrak and Kattegat; the chamber record at "
               "station `AL561_17-1` lists phosphate and ammonium among its measured nutrients, "
               "and the source register records the cruise's stations reaching from the "
               "Kattegat to the Skagerrak, several of them nearer Sweden or Norway."))
    w("- " + C("C-OQ-A7-TA14", "**NOVA teknisk anvisning `kap. 14`** (1998) specifies light and "
               "dark incubations of sediment cores for the fluxes of oxygen, ortho-phosphate, "
               "nitrate, nitrite, ammonium, urea and silicate, on type areas only."))
    w("- " + C("C-OQ-A7-SR323", "**DCE's SR323** tabulates the internal and external load of "
               "DIN and DIP for Roskilde, Odense, Horsens and Ringkøbing Fjord by three-month "
               "period from summer 1999 to spring 2000, credited to unpublished data by H. "
               "Fossing: a net annual release of phosphorus from the sediment in Roskilde, Odense "
               "and Horsens Fjord, a net uptake in Ringkøbing Fjord. It cites Kerteminde Fjord, "
               "where in 1991–1992 the sediment's release made up "
               f"{RD(SR, '65', P_KER)}% and {RD(SR, '70', P_KER)}% of the total N and P load.")
      + " " + C("C-OQ-A7-SR323-DATA", "The measurements behind the table were not found in any "
                "reachable dataset."))
    w("- " + C("C-OQ-A7-ODA", "**ODA Vandkemi** (`Emne_10_11`) is held; **Sedimentkemi** "
               "(`Emne_12_19`), with loss on ignition, total N and P and iron-adsorbed P by "
               "layer, is not. Bottle chemistry is a production path separate from the CTD "
               "sonde."))
    w("")
    w("## What is in this repository, counted")
    w("")
    w("- " + C("C-OQ-A7-PANEL", f"`docs/data/areas/stations_series.json` - "
               f"{ss['total_station_months']:,} station-months, {ss['n_stations']:,} stations, "
               f"{ss['months']} months from {year0}, {ss['n_variables']} variables ({vlist}). "
               "**No nutrient variable.**"))
    w("- " + C("C-OQ-A7-MD", f"`data/raw/oda/maaledybde.csv.gz` - {md['rows']:,} records at "
               f"{md['stations']:,} stations, {md['stations_with_bottom_depth']:,} of them "
               "carrying `BundDybde_m`. **Its northing is missing:** the second easting column "
               f"`X_UTM321` repeats `X_UTM32` in {md['rows_x_equals_x1']:,} of the "
               f"{md['rows']:,} records. Positions come from `stations_series`, not from it."))
    w("- " + C("C-OQ-A7-SEABED", "`data/raw/geus/seabed_sediment_dk.gpkg`, layer "
               f"`Seabed_sedimen` - {sb['features']} polygons in {sb['classes']} substrate "
               f"classes ({clist}), compiled from {sb['campaigns']} named survey campaigns at "
               f"map scales whose denominators run from {sbf['scale_min']:,} to "
               f"{sbf['scale_max']:,}. Usable as "
               "substrate class if the scale travels with it; **no organic-carbon value at "
               "all**, as the register's `R7-TOC-MAP-GAP` records."))
    w("- " + C("C-OQ-A7-PORTAL", "The source register records the ODA portal's station lists, "
               "taken with an explicit period in an authenticated comparison: Vandkemi "
               f"{portal['vandkemi']['with_period']:,} stations over 1970–2026 against "
               f"{portal['vandkemi']['no_period']} with no period set; Sedimentkemi/Sporstof "
               f"{sed['with_period']} over the whole record, {sed['no_period']} currently."))
    w("")
    w(C("C-OQ-A7-ASYM", "**That asymmetry is the problem.** The response side has "
        f"ortho-phosphate at {dip['stations']:,} stations in the held extract; the pool side has "
        f"{sed['with_period']} stations in the entire national record as the portal lists it."))
    w("")
    w(C("C-OQ-A7-NOVANA", "**An unresolved discrepancy, flagged not settled.** The national "
        "programme for 2023–2027 takes sediment nutrient pools - total N, total P, iron-bound "
        "phosphate, dry matter, loss on ignition and density - once a year, when the sediment "
        "is most oxidised, in January–February, from "
        f"{RD(NV, '90', P_NV)} of the {RD(NV, '109', P_NV)} water bodies over the period, at "
        f"{RD(NV, '16', P_NV)}–{RD(NV, '19', P_NV)} stations a year; its table gives "
        f"{RD(NV, '17', P_NVT)}–{RD(NV, '19', P_NVT)} stations a year.") + " "
      + C("C-OQ-A7-DISCREP", f"ODA's portal lists {sed['with_period']} Sedimentkemi/Sporstof "
          "stations ever. Either that rotation has not run long or ODA does not expose the whole "
          "record, and which is not established here. Ask before quoting either number."))
    w("")
    w("## Does this break the model-as-datum residual, or inherit it?")
    w("")
    w(C("C-OQ-A7-RESID", "Internal loading inferred as what a mass balance leaves over is "
        "model-as-datum by construction. FR483 is a local instance: a model of Aarhus Bay whose "
        "constants were fitted to a year's measured means."))
    w("")
    w("- " + C("C-OQ-A7-DIPFORM", "The **DIP-seasonality form breaks it.** It sets one directly "
               "observed quantity (summer minus winter ortho-phosphate near the bed) against "
               "another (loss on ignition and iron-adsorbed P at the same position). No budget is "
               "closed, nothing is a remainder. The price is that it is **weak**: a summer DIP "
               "rise over organic-rich bed is equally consistent with water-column regeneration "
               "co-located with it, since deposition drives both. It can *falsify* the benthic "
               f"signature - no covariance means {R('A7')} leaves no mark at station resolution "
               "- but a positive result does not isolate the bed."))
    w("- " + C("C-OQ-A7-CHAMBERFORM", "The **chamber form breaks it completely** and is the only "
               "thing that isolates the bed; the in-situ chamber fluxes found for Danish inner "
               "waters are one cruise's."))
    w("- " + C("C-OQ-A7-JANFEB", "**The January–February sampling is why the residual keeps "
               "reappearing.** The pool is measured once a year, in winter; the release is "
               "claimed for summer. With one annual observation the summer drawdown *cannot* be a "
               "difference of two measurements, so anyone wanting a number must infer it. The "
               "programme design forces model-as-datum here."))
    w("")
    w("## Smallest unblocking thing")
    w("")
    w("1. " + C("C-OQ-A7-S1", f"**One fetch.** `Emne_12_19` (Sedimentkemi): {sed['with_period']} "
                "stations ever, and it fixes how many positions the test can have. "
                "`scripts/fetch_oda.py` has no entry for it: its `TOPICS` already carry the "
                "water chemistry `Emne_10_11`, and its argument parser accepts only those keys, "
                "so it is one entry more, the node id already recorded in "
                "`data/manual/data_sources.json`. Set an explicit period - the portal's station "
                "list is filtered by the period set, and returns the current network without "
                "one."))
    w("2. " + C("C-OQ-A7-S2", "**Check the join before designing anything.** Count stations "
                "carrying *both* a sediment core and ≥{param:oq_a7_min_years} years of monthly "
                "DIP within {param:oq_a7_join_km} km. If fewer than {param:oq_a7_join_min} do, "
                + f"the armchair classification is wrong and {R('A7')} is a measurement gap in "
                "both forms. Stating this in advance is the point."))
    w("3. " + C("C-OQ-A7-S3", "**The measurement.** Sample the existing sediment stations "
                "**twice**, late February and late September, instead of once in winter. That "
                "change turns the summer release from a residual into a difference of two "
                "measured pools, at whatever station count is already funded. Then: one chamber "
                "deployment in the Kattegat, the Belts or a Danish fjord, where no chamber flux "
                "was found."))
    w("")
    w("## What a completed test would and would not license")
    w("")
    w(C("C-OQ-A7-WOULD", "**Would.** Whether near-bed phosphate seasonality covaries with bed "
        "organic content across positions, as a coefficient with its qualifiers."))
    w("")
    w(C("C-OQ-A7-WOULDNOT", "**Would not.** Any share, tonnage or \"internal loading accounts "
        "for n%\": that is a mass balance and this is not one. Nor anything about Danish inner "
        "waters from the Zenodo data, whose basins the paper defines as excluding the Kattegat "
        "and the Belt Sea - carrying them westward would be the aggregation error this project "
        "audits elsewhere."))
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    try:
        page = text()
    except live.Unjustified as e:
        print(e, file=sys.stderr)
        sys.exit(1)
    sys.exit(render("docs/openproblems/A7.md", page))
