#!/usr/bin/env python3
"""docs/PLACES.md - places, not categories.

Starts from named places where somebody says something is wrong, asks what is
measured there, and asks what would be enough to fix it. Every number is read with
its chain: near-bed oxygen by region and the hydrogen-sulphide record from
data/derived/station_places.json (written by scripts/station_places.py), the triage
classes from data/derived/triage.json, the size of the hypothesis register from
data/derived/hypotheses.json. Every assertion is a checked claim, registered with
what it rests on in data/manual/claims.d/w2-pc.json (LIVE_NUMBERS.md section 11).

    python3 scripts/pages/places.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import DERIVED, ROOT, log, write_doc
import live

OUT = os.path.join(ROOT, "docs", "PLACES.md")
SP = os.path.join(DERIVED, "station_places.json")
HY = os.path.join(DERIVED, "hypotheses.json")
TR = os.path.join(DERIVED, "triage.json")

B, E, C, R = live.claim_begin, live.CLAIM_END, live.claim, live.ref


def label(name):
    """A hovedopland name as the register writes it ("Det sydfynske øhav"), set in
    title case for the page ("Det Sydfynske Øhav")."""
    out = []
    for word in name.split(" "):
        out.append(word if word == "og" else
                   "/".join(p[:1].upper() + p[1:] for p in word.split("/")))
    return " ".join(out)


def main():
    sp = live.live_json(SP)
    ox, h2s = sp["oxy_bed"], sp["h2s"]
    regions = list(ox["regions"])
    hy = live.live_json(HY)
    nhyp = live.live(len(hy["hypotheses"]), HY, "hypotheses.[len]")
    tr = live.live_json(TR)
    ntri = tr["n_triaged"]
    unscore, expt = tr["classes"]["unscoreable"]["n"], tr["classes"]["experiment"]["n"]
    lo, hi = ox["below_low_mg_l"], ox["below_high_mg_l"]

    def row(name):
        return next(r for r in regions if r["region"] == name)
    mar, lbj, sfo = row("Mariager fjord"), row("Lillebælt/jylland"), row("Det sydfynske øhav")
    koge = row("Køge bugt")
    worst, second = regions[0], regions[1]
    times = worst["share_below_low"] / second["share_below_low"]
    top_median = max(r["median_mg_l"] for r in regions)
    also_top = [label(r["region"]) for r in regions
                if r["median_mg_l"] == top_median and r is not koge]
    top_note = ("the highest in the table" + (" alongside " + ", ".join(also_top) if also_top else "")
                if koge["median_mg_l"] == top_median else "among the highest in the table")
    few = min(regions, key=lambda r: r["stations"])
    odense, smaal = row("Odense fjord"), row("Smålandsfarvandet")
    ctd, kemi = h2s["ctd"], h2s["kemi"]
    thin = [r for r in regions if regions.index(r) < regions.index(sfo)
            and r is not mar and r is not lbj]

    o = []
    w = o.append
    w("# Places, not categories\n")
    w("*Generated by `scripts/pages/places.py`.*\n")
    w(C("C-PC-INTRO", "The rest of this project asks whether a category is real. This page does the "
        "opposite: it starts from **named places where somebody says something is wrong**, asks "
        "what is measured there, and asks what would be enough to fix it.") + "\n")
    w(C("C-PC-TRIAGE", f"Sometimes that needs a cause. Often it does not: of the {ntri} mechanisms "
        f"in the register, [the triage](hypodrafts/TRIAGE.md) counts {unscore} as unscoreable with "
        "the data that exist, and they may stay that way.") + " "
      + C("C-PC-AGNOSTIC", "**A solution that works whichever mechanism dominates does not have to "
          "wait for a triage that may never finish.**") + "\n")
    w("---\n")
    w("## What is measured, by region\n")
    w(C("C-PC-TABLE-READ", f"Near-bed oxygen, {ox['first_year']}–{ox['last_year']}, from the station "
        "record. **Read this as a locator, not as a description of a region**: the grouping is the "
        "hovedopland each station's water body belongs to, used as a label, and this project's own "
        "testing found that the official water bodies agree with the partitions the data produce no "
        "better than random connected regions of the same sizes. The table says *where low-oxygen "
        "observations are*, not what a region is like. An observation is one station's median for "
        "one month.") + "\n")
    w(f"| region | observations | stations | median mg/l | below {lo:g} | below {hi:g} |")
    w("|---|---:|---:|---:|---:|---:|")
    for r in regions:
        strong = r is mar or r is koge
        b = (lambda s: f"**{s}**") if strong else (lambda s: s)
        w(f"| {b(label(r['region']))} | {r['observations']:,} | {r['stations']:,} "
          f"| {b(format(r['median_mg_l'], '.2f'))} | {b(format(r['share_below_low'] * 100, '.1f') + '%')} "
          f"| {format(r['share_below_high'] * 100, '.1f')}% |")
    w("")
    w(C("C-PC-RATIO", f"**Mariager Fjord's share of near-bed observations below {lo:g} mg/l is "
        f"{times:.1f} times that of the next region in the table.**") + "\n")
    w("---\n")
    w("## Mariager Fjord — the worst measured\n")
    w(C("C-PC-MAR-SILL", "**What is said about it:** Mariager Fjord is a silled fjord, whose inner part "
        "forms a basin with limited water exchange, and in some summers that leads to iltsvind and "
        "fish kills (Danish Wikipedia).") + " "
      + C("C-PC-MAR-DCE", "DCE's oxygen notes name it among the hardest-hit waters at the start of "
          "October 2023, and report toxic hydrogen sulphide released from its bottom in November "
          "2025.") + "\n")
    w(C("C-PC-MAR-MEASURED", f"**Measured:** {mar['share_below_low'] * 100:.1f}% of near-bed "
        f"observations below {lo:g} mg/l, median {mar['median_mg_l']:.2f}. Of the {ctd['rows']:,} "
        f"hydrogen-sulphide rows in the CTD extract, **{ctd['top_station_rows']:,}** come from a "
        f"single station in this fjord, \"{ctd['top_station_name']}\" ({ctd['top_station_place']}). "
        f"The water-chemistry bottles spread wider: {kemi['top_station_rows']:,} of their "
        f"{kemi['rows']:,} hydrogen-sulphide rows are from the same station, the rest from "
        f"{kemi['stations'] - 1} others.") + " "
      + C("C-PC-MAR-SULPHIDE", "Sulphide from the sediment reaching the water column, where it is "
          "oxidised, is documented for Mariager Fjord among other basins (Middelburg and Levin, "
          "2009).") + "\n")
    w(C("C-PC-MAR-CAUSE", "**What is known about cause is thinner than it looks.** DCE's national "
        "runoff report says Mariager Fjord's catchment reduced its diffuse nitrogen load less than "
        "the national relation indicates, citing work this project could not read, and it gives no "
        "cause. The sill limits how often the basin's bottom water is exchanged.") + "\n")
    w(C("C-PC-MAR-TWO", "So two things are supported, each in part: a sill that limits exchange, "
        "which a nitrogen target does not address, and a catchment whose diffuse load fell less than "
        "the national relation predicts, for reasons not established here.") + "\n")
    w("**What would be sufficient**\n")
    w(C("C-PC-MAR-EXCHANGE", "*Cause-agnostic — works whichever mechanism dominates:* deep-water "
        "exchange. If bottom water is anoxic because it is not renewed, renewing it acts directly and "
        "does not require knowing why it became anoxic.") + " "
      + C("C-PC-BYFJORD", "It has been done in a fjord: for two and a half years surface water was "
          "pumped into the deepwater of Sweden's By Fjord, and the deepwater became long-term oxic "
          "(Stigebrandt and co-authors, 2015).") + " "
      + C("C-PC-BORNHOLM", "For the Baltic's Bornholm Basin the same idea has been worked through "
          "with a model, not tried.") + " "
      + C("C-PC-MAR-COST", "Cost and side effects at Mariager are not assessed here.") + "\n")
    w(C("C-PC-MAR-N", "*Cause-contingent:* nitrogen reduction in the catchment. The one readable "
        "source says this catchment's diffuse load fell less than the national relation predicts — "
        "not that it did not fall — and how the fjord's bottom water answered is not established "
        "here.") + "\n")
    w("---\n")
    w("## Lillebælt and Det Sydfynske Øhav — the second tier\n")
    w(C("C-PC-LBJ", f"**Measured:** {lbj['share_below_low'] * 100:.1f}% and "
        f"{sfo['share_below_low'] * 100:.1f}% below {lo:g} mg/l, over {lbj['observations']:,} and "
        f"{sfo['observations']:,} observations: Mariager's severity is not reached, but these are the "
        "next highest shares in the table on more than a handful of stations.") + "\n")
    if thin:
        w(C("C-PC-THIN", " and ".join(f"{label(r['region'])} ({r['stations']} stations, "
                                       f"{r['observations']:,} observations)" for r in thin)
            + " sits between them in the ranking on too few stations to rank a region on, and is "
            "read as a locator only.") + "\n")
    w(C("C-PC-LBJ-TEST", f"The register's {R('A1')} expects the nitrogen effect to be strongest where "
        "nitrogen limitation is long and flushing slow. Whether these two waters are such places is "
        "not established here; if they are, this is where a nitrogen intervention should be tested "
        "rather than assumed — a testable proposition this project has not tested.") + "\n")
    w("---\n")
    w("## Køge Bugt\n")
    w(C("C-PC-KOEGE-WORDS", "**What is said:** in the public argument this project recorded, the "
        "damage is named with four words — iltsvind, fedtemøg, fiskedød and liv i fjorden.") + "\n")
    w(C("C-PC-KOEGE-MEASURED", f"**Measured:** **{koge['share_below_low'] * 100:.1f}%** of near-bed "
        f"observations below {lo:g} mg/l, median {koge['median_mg_l']:.2f}, {top_note}.") + " "
      + C("C-PC-KOEGE-DCE", "DCE's oxygen notes record no oxygen depletion in Køge Bugt in their 2023 "
          "and 2025 periods — in 2023 in the weeks after the second-largest September extent "
          "registered.") + "\n")
    w(C("C-PC-KOEGE-NOCONFLICT", f"**These answer different questions.** DCE count iltsvind as "
        f"oxygen below {hi:g} mg/l in the bottom water. A bay that mixes readily may never meet that "
        "while its sediment is anoxic, and whether Køge Bugt's is, is not measured here. The oxygen "
        "record says the water near the bed is not short of oxygen; it says nothing about the bed or "
        "the shore.") + "\n")
    w(C("C-PC-KOEGE-THREE", "Three of the four words have no instrument behind them: fedtemøg has no "
        "shore-condition series in any source this project surveyed, fiskedød no open register, and "
        "liv i fjorden is about what lives there, which oxygen does not measure.") + "\n")
    w("**What would be sufficient**\n")
    w(C("C-PC-KOEGE-NOTOXYGEN", "*Measures sized on oxygen* have little to act on here, because "
        "near-bed oxygen is not what the record shows to be short. Whether a nitrogen reduction "
        "would change the shore is not established by anything on this page.") + "\n")
    w(C("C-PC-KOEGE-AGNOSTIC", "*Cause-agnostic and available now:* the interventions in "
        "[PROGRAMME.md](PROGRAMME.md) that act on what arrives rather than on what it causes — "
        "keeping rainwater out of the combined system, an outlet that is not the bay, and source "
        "control on what the water carries. These change the delivered load whatever the mechanism "
        "downstream, and their case does not rest on the nitrogen chain.") + "\n")
    w(C("C-PC-KOEGE-INSTRUMENT", "*And one measurement:* **there is no series for the thing people "
        "complain about.** Before a fix for *fedtemøg* is proposed, somebody has to be able to say "
        "whether it got better — which needs an instrument, not a model.") + "\n")
    w("---\n")
    w("## What this page is for\n")
    w("Three things follow from reading by place rather than by mechanism.\n")
    w(C("C-PC-FOR-1", f"1. **Ranked by near-bed oxygen, the places are far apart.** Mariager Fjord's "
        f"share below {lo:g} mg/l is {times:.1f} times the next region's; Køge Bugt's median is "
        f"{top_note}."))
    w(C("C-PC-FOR-2", f"2. **Where a nitrogen intervention should be tested is a question about "
        f"places, not the nation.** {R('A1')} says where it should work best; whether Lillebælt and "
        "Det Sydfynske Øhav are such places is not established here."))
    w(C("C-PC-FOR-3", f"3. **A cause-agnostic intervention is worth more than its evidence base "
        "suggests**, because the evidence base for *any* mechanism here is thin. Deep-water exchange "
        "does not care why the water is anoxic. Keeping sewage out of a bay does not care which of "
        f"the {nhyp} mechanisms is dominant. **Those are worth doing under uncertainty in a way that "
        "a precisely-targeted intervention is not.**") + "\n")
    w("## The meta-solution: buy the experiments\n")
    w(C("C-PC-META-ORDER", "**This is the last step of the solution scope, not a shortcut past it** — "
        "see [PLAN.md stage 8](PLAN.md) for why the entitlement is earned by the stages before it. "
        "Said first, \"just try things\" is an excuse for not knowing. Said after the field is "
        "enumerated, the data characterised, the triage done and the spatiality established, it is "
        "the correct next move.") + "\n")
    w(C("C-PC-META-FUND", "Everything above points at one instrument rather than many. **Fund trials "
        "of solution models, in named places, with pre-stated outcomes — and let the results "
        "decide.**") + "\n")
    w(C("C-PC-META-WHY", "**Why this is not a slogan.** Setting a variable, rather than observing it, "
        "identifies its effect *without enumerating the confounders*: where the setting is "
        "randomised, no backdoor path reaches it, so no adjustment set is needed and nobody has to "
        "name the environmental peculiarities that have no column.") + " "
      + C("C-PC-META-NUMBERS", f"Given that {unscore} of the {ntri} mechanisms here are unscoreable "
          f"and another {expt} need an experiment anyway, **the observational route to an answer "
          "may not exist**, and a trial does not require one.") + "\n")
    w("### Plurality is the instrument, not the fallback\n")
    w(C("C-PC-PLURAL-1", "Trying several things reads as what you do when you cannot decide. Here it "
        "is the opposite. **Difference between places is what makes any of this identifiable**, and "
        "a country that does one thing everywhere has removed the possibility of finding out whether "
        "it worked.") + "\n")
    w(C("C-PC-PLURAL-ONEARM", "A single national instrument applied everywhere at once is a design "
        "with one arm. Every catchment gets the same treatment in the same years, so whatever happens "
        "next happens to all of them together, and no estimator can recover a contrast that was never "
        "created.") + " "
      + C("C-PC-X17", "[`X17`](EXPERIMENTS.md) argues the specific case: for agricultural biocides there is "
          "nothing to compare against, because the register holds no measurement of what they do to marine "
          "decomposers and this project could not locate Danish pesticide use at any unit finer than the "
          "nation — **a comparison exists only once somebody creates one**, which `X17` proposes to do by a "
          "staggered crossover rather than a ban.") + "\n")
    w(C("C-PC-PLURAL-TRADE", "The corollary is uncomfortable for both sides of the argument. "
        "Uniformity is what a fair regulation looks like and it is also what an uninformative "
        "experiment looks like: **applying one instrument everywhere buys equity and spends "
        "information.**") + " "
      + C("C-PC-PLURAL-MET", "This project has met that trade in its own data: the official "
          "[water bodies](AREAS.md) agree with the partitions the data produce no better than random "
          "connected regions of the same sizes.") + " "
      + C("C-PC-PLURAL-POLICY", "Doing one thing nationally is aggregation applied to policy.") + "\n")
    w(C("C-PC-REFUSALS", "**Which is why the refusals count as much as the adoptions.** A municipality "
        "that declines the standard instrument and does something else is not an obstacle to the "
        "programme — *it is the control arm*, on the condition that somebody writes down what it "
        "declined, what it did instead, and from when. \"Here they refused these things and tried "
        "those; we did these, so somewhere there is the documented absence of them\" is a study "
        "design. Unrecorded, the same situation is only variation, and variation nobody dated is "
        "indistinguishable from noise.") + "\n")
    w(C("C-PC-REGISTER", "So the register is the cheap half of the meta-solution and it should exist "
        "before the first trial is funded. Four fields, and none of them needs new "
        "instrumentation:") + "\n")
    w("| | |")
    w("|---|---|")
    w("| **Who did what, where, from when** | " + C("C-PC-REG-WHO", "including who declined, and what "
      "they did instead — a refusal with a date is a control arm; a refusal without one is "
      "nothing") + " |")
    w("| **What each place expected** | " + C("C-PC-REG-EXPECT", "stated before it started, so a "
      "result can disagree with it") + " |")
    w("| **What reads it out** | " + C("C-PC-REG-READ", f"the existing series wherever possible. The "
      f"{ox['stations_total']:,}-station near-bed oxygen record is the *before* for most of them, "
      "already paid for") + " |")
    w("| **The rule that decides** | " + C("C-PC-REG-RULE", "written before the results. Plurality "
      "without a pre-stated decision rule does not produce an answer, it produces a story per place "
      "and a fight about which one counts") + " |")
    w("")
    w(C("C-PC-LOT", "And there is a sharper version available whenever more places are willing than "
        "there is money for. **Let the lot decide which willing place goes first.** That is the whole "
        "difference between a natural experiment and an experiment, it costs nothing, and it removes "
        "the objection that the places which volunteer are not like the places which do not. Where "
        "randomisation is not available — and often it will not be — the register still leaves the "
        "weaker but real design: matched places, read against their own histories.") + "\n")
    w(C("C-PC-LEVER", "**And the lever this is available on is narrower than it sounds, which is "
        "worth knowing before anyone promises it.** Product bans are harmonised at EU level, so no "
        "city and no region can close a market — that is the one instrument nobody local can start, "
        "and [the programme page says why that row sits at the wrong level](PROGRAMME.md). What is "
        "left below it is purchase, permission and use: a household not buying, a municipality "
        "refusing a compound in its own procurement or on its own ground, a utility writing a "
        "condition into a discharge permit, a state taxing a use or restricting it. Those are weaker "
        "instruments than a ban and they are the ones that make places differ — so they are the ones "
        "that generate the counterfactual, and they should be defended as an information instrument "
        "and not only as a local preference.") + "\n")
    w(C("C-PC-NOTDELAY", "None of this weakens the anti-delay conditions below. Plurality is not "
        "everybody waiting to see what the neighbours got; it is different places acting **at the "
        "same time in different ways**, on a clock that runs whether or not the results are "
        "convenient.") + "\n")
    w(C("C-PC-BEFORE", f"**Denmark has the *before* a trial needs:** "
        f"{ox['last_year'] - ox['first_year']} years of near-bed oxygen at "
        f"{ox['stations_total']:,} stations. The design that fits is Before-After-Control-Impact: "
        "intervene in one place, leave a matched place alone, and read both against their own "
        "history. **The expensive half of that design already exists and is paid for.**") + "\n")
    w(C("C-PC-PORTFOLIO", "**What the portfolio would look like**, taken from the places above "
        "rather than invented:") + "\n")
    w("| where | trial | reads out on |")
    w("|---|---|---|")
    w("| **Mariager** | deep-water exchange | bottom oxygen and sulphide, at existing stations |")
    w(f"| **Lillebælt / Sydfynske Øhav** | catchment nitrogen reduction, at intensity | where "
      f"{R('A1')} expects nitrogen to matter most, if these waters are such places |")
    w("| **Køge Bugt** | an instrument for *fedtemøg* | nothing can be judged there until the "
      "complaint is measurable |")
    w("| any | source control on what the water carries | delivered load, whichever mechanism "
      "dominates |")
    w("")
    w(C("C-PC-ECONOMICS", "**The economic case is not computed here, and the argument does not wait "
        "on it.** A national reduction applied everywhere produces no contrast to test against; a "
        "portfolio of trials produces a result per place, and a result holds whoever is in office "
        "and whatever the next model says. Value-of-information analysis would put a number on the "
        "difference; nobody here has done it.") + "\n")
    w("### The objection that would sink it, stated plainly\n")
    w(C("C-PC-OBJECTION", "**Exactly this argument is what somebody who simply wants to delay would "
        "make.** \"More research is needed\" is a familiar way to stall a regulation, and the fact "
        "that it is sometimes true is what makes it effective. There is an economic interest in delay "
        "here, and a proposal to experiment instead of act serves that interest whether or not it "
        "means to.") + "\n")
    w(C("C-PC-HONEST", "So the proposal is only honest if it is built so it **cannot** function as "
        "delay:") + "\n")
    w(C("C-PC-COND-TIME", "- **a pre-committed timetable**, with the regulation as the default if the "
        "trials do not report by it — the burden of delivery on the trials, not on the regulator;"))
    w(C("C-PC-COND-PREREG", "- **pre-registered outcomes**, chosen before the trial starts, so a null "
        "result cannot be reinterpreted afterwards;"))
    w(C("C-PC-COND-PUBLISH", "- **published protocols and data**, so a failed trial is visible "
        "rather than quietly dropped;"))
    w(C("C-PC-COND-MEASURE", "- **and no reduction in what is already measured** while it runs.")
      + "\n")
    w(C("C-PC-WITHOUT", "Without those four, this is a delaying tactic with a methodology section. "
        "With them it is an instrument that produces an answer, not only a compliance figure.") + "\n")
    w(C("C-PC-NOTCLAIM", "**And it is worth being clear about what it does not claim.** A trial that "
        "works at Mariager says nothing about Lillebælt: DCE's own runoff report says fjord "
        "catchments do not all respond alike to the national relation. **Places would have to be "
        "tried separately, which is the argument of this page.**") + "\n")
    w(C("C-PC-LIMITS", f"**Limits.** The table aggregates stations by the hovedopland of the water "
        "body they fall in, and this project's own testing found the official water bodies no better "
        "than random regions of the same sizes, so the table locates observations; it does not "
        f"characterise places. Coverage is uneven: {odense['stations']} stations at Odense against "
        f"{smaal['stations']} in Smålandsfarvandet, and {few['stations']} in "
        f"{label(few['region'])}. And the claims side is not systematic; it comes from the public "
        "record rather than a survey, so a place with a real problem and no local press does not "
        "appear here."))
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
