#!/usr/bin/env python3
"""docs/PLACES.md - places, not categories.

This page used to be written straight into the markdown, and its table was typed
in from a session that stored nothing. The prose lives here now, and every number
is read with its chain: near-bed oxygen by region, the coverage figures and the
hydrogen-sulphide record from data/derived/station_places.json (written by
scripts/station_places.py), the size of the hypothesis register from
data/derived/hypotheses.json. See LIVE_NUMBERS.md.

    python3 scripts/pages/places.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from common import DERIVED, ROOT, log, write_doc
import live

OUT = os.path.join(ROOT, "docs", "PLACES.md")
SP = os.path.join(DERIVED, "station_places.json")
HY = os.path.join(DERIVED, "hypotheses.json")
PAGE0 = "4469fc7"        # the last commit of the hand-written page


def q(text):
    """A number nothing in the repo stores yet, carried as what this page said at its
    last hand-written commit - honest, and circular as a justification."""
    return live.was(PAGE0, "docs/PLACES.md", text)   # text: a locator, @@ at the value


def label(name):
    """A hovedopland name as the register writes it ("Det sydfynske øhav"), set in
    title case for the page ("Det Sydfynske Øhav")."""
    out = []
    for word in name.split(" "):
        out.append(word if word == "og" else
                   "/".join(p[:1].upper() + p[1:] for p in word.split("/")))
    return " ".join(out)


def main():
    sp = live.live_json(SP)
    ox, h2s = sp["oxy_bed"], sp["h2s"]
    regions = list(ox["regions"])
    hy = live.live_json(HY)
    nhyp = live.live(len(hy["hypotheses"]), HY, "hypotheses.[len]")
    lo, hi = ox["below_low_mg_l"], ox["below_high_mg_l"]

    def row(name):
        return next(r for r in regions if r["region"] == name)
    mar, lbj, sfo = row("Mariager fjord"), row("Lillebælt/jylland"), row("Det sydfynske øhav")
    koge = row("Køge bugt")
    worst, second = regions[0], regions[1]
    times = worst["share_below_low"] / second["share_below_low"]
    top_median = max(r["median_mg_l"] for r in regions)
    also_top = [label(r["region"]) for r in regions
                if r["median_mg_l"] == top_median and r is not koge]
    few = min(regions, key=lambda r: r["stations"])
    odense, smaal = row("Odense fjord"), row("Smålandsfarvandet")
    ctd, kemi = h2s["ctd"], h2s["kemi"]

    o = []
    w = o.append
    w("# Places, not categories\n")
    w("*Generated by `scripts/pages/places.py`.*\n")
    w("The rest of this project asks whether a category is real. This page does the "
      "opposite: it starts from **named places where somebody says something is wrong**, "
      "asks what is measured there, and asks what would be enough to fix it.\n")
    w("Sometimes that needs a cause. Often it does not — and that matters here, because "
      f"[{q("matters here, because [@@")} of {q("@@ mechanisms are unscoreable](hypodrafts/TRIAGE.md)")} mechanisms are unscoreable](hypodrafts/TRIAGE.md), as "
      f"the triage counted them (the register now holds {nhyp}), and may stay that way. "
      "**A solution that "
      "works whichever mechanism dominates does not have to wait for a triage that may "
      "never finish.**\n")
    w("---\n")
    w("## What is measured, by region\n")
    w(f"Near-bed oxygen, {ox['first_year']}–{ox['last_year']}, from the station record. "
      "**Read this as a locator, not as a description of a region**: the grouping is the "
      "hovedopland each station's water body belongs to, used as a label, and this "
      "project's own testing found the water-body boundaries carry no signal beyond "
      "being connected regions of their size. The table says *where low-oxygen "
      "observations are*, not what a region is like. An observation is one station's "
      "median for one month.\n")
    w(f"| region | observations | stations | median mg/l | below {lo:g} | below {hi:g} |")
    w("|---|---:|---:|---:|---:|---:|")
    for r in regions:
        strong = r is mar or r is koge
        b = (lambda s: f"**{s}**") if strong else (lambda s: s)
        w(f"| {b(label(r['region']))} | {r['observations']:,} | {r['stations']:,} "
          f"| {b(format(r['median_mg_l'], '.2f'))} | {b(format(r['share_below_low'] * 100, '.1f') + '%')} "
          f"| {format(r['share_below_high'] * 100, '.1f')}% |")
    w("")
    w(f"**One place is {times:.1f} times worse than anywhere else, and it is not the one "
      "anybody argues about.**\n")
    w("---\n")
    w("## Mariager Fjord — the worst measured, and nitrogen does not reach it\n")
    w("**Claimed:** a fjord that died. It is the site of Denmark's most notorious fish "
      "kill.\n")
    w(f"**Measured:** {mar['share_below_low'] * 100:.1f}% of near-bed observations below "
      f"{lo:g} mg/l, median {mar['median_mg_l']:.2f}. {times:.1f} times the next region. "
      f"And of the {ctd['rows']:,} hydrogen-sulphide rows in the CTD extract, "
      f"**{ctd['top_station_rows']:,}** come from a single station in this fjord, "
      f"\"{ctd['top_station_name']}\" ({ctd['top_station_place']}). The water-chemistry "
      f"bottles spread wider: {kemi['top_station_rows']:,} of their {kemi['rows']:,} "
      f"hydrogen-sulphide rows are from the same station, the rest from "
      f"{kemi['stations'] - 1} others. Free sulphide in the water column is what remains "
      "after the sediment's iron buffer is spent.\n")
    w("**What is known about cause, and it is unusually definite.** Windolf et al. "
      "(2012) studied ten catchments over twenty years. Eight responded to reductions in "
      "agricultural nitrogen surplus within five years. **Mariager showed no response at "
      "all** — high diffuse loads throughout, and the highest intercept in the study. "
      "The authors attribute it to old, oxic groundwater in chalk aquifers, where nitrate "
      "survives instead of being denitrified. The fjord is also a deep silled basin, so "
      "its bottom water exchanges rarely.\n")
    w("**So the honest statement is that the two candidate explanations are both "
      "physical**: a sill that prevents exchange, and an aquifer that delays whatever the "
      "land does by decades. Neither is addressed by a nitrogen target, and the paper's "
      "own data says the nitrogen lever was pulled and nothing moved.\n")
    w("**What would be sufficient**\n")
    w("*Cause-agnostic — works whichever mechanism dominates:* deep-water exchange. If "
      "bottom water is anoxic because it does not turn over, moving it is a direct fix and "
      "does not require knowing why it became anoxic. This is engineering with "
      "precedent: forced downwelling and artificial deep-water oxygenation have been run "
      "at basin scale in Sweden's Byfjorden and trialled in the Baltic. Cost and side "
      "effects are real and are not assessed here.\n")
    w("*Cause-contingent:* nitrogen reduction in the catchment. **The evidence available "
      "says this has already been tried at scale and produced no measurable response in "
      "this fjord within twenty years.** That is not an argument against it elsewhere.\n")
    w("---\n")
    w("## Lillebælt and Det Sydfynske Øhav — the second tier, and the ones with a case\n")
    w(f"**Measured:** {lbj['share_below_low'] * 100:.1f}% and "
      f"{sfo['share_below_low'] * 100:.1f}% below {lo:g} mg/l, over "
      f"{lbj['observations']:,} and {sfo['observations']:,} observations. Not Mariager's "
      "severity, but an order of magnitude above the national pattern, and on the "
      "largest station counts in the table.\n")
    thin = [r for r in regions if regions.index(r) < regions.index(sfo)
            and r is not mar and r is not lbj]
    for r in thin:
        w(f"{label(r['region'])} sits between them in the ranking on {r['stations']} "
          f"stations and {r['observations']:,} observations — too few to rank a region "
          "on, and read as a locator only.\n")
    w("These are stratified, sheltered waters with substantial catchments — which is the "
      "combination the nutrient hypothesis actually predicts. **If the standard account "
      "is right anywhere, it is here**, and this is where a nitrogen intervention should "
      "be tested rather than assumed. That is a testable proposition and it is not "
      "tested in this project.\n")
    w("---\n")
    w("## Køge Bugt — the loudest claim, and the measurement disagrees about what is "
      "wrong\n")
    w("**Claimed:** greasy water, a shore people would rather not walk on, fish kills. "
      "The most publicly contested coastal water in Denmark, and the one nearest the "
      "largest population.\n")
    top_note = ("the highest in the table" + (" alongside " + ", ".join(also_top) if also_top else "")
                if koge["median_mg_l"] == top_median else "among the highest in the table")
    w(f"**Measured:** **{koge['share_below_low'] * 100:.1f}%** of near-bed observations "
      f"below {lo:g} mg/l. Median {koge['median_mg_l']:.2f}, {top_note}. DCE report no "
      "registered iltsvind here in 2023 or 2025 — including 2023, the worst iltsvind year "
      "in two decades.\n")
    w("**These are not in conflict.** They are answers to different questions. The bay "
      "is shallow and mixes readily, so it may never meet a criterion defined as *oxygen "
      f"below {hi:g} mg/l in stratified bottom water* while still having anoxic sediment, "
      "sulphate reduction and a fouled shoreline. **The measurement says the bay is not "
      "suffocating. It says nothing about whether it is dead.**\n")
    w("Three of the four words the public uses have no instrument behind them at all — "
      "*fedtemøg* has no measurement, *fiskedød* has no open register, and *livet i "
      "fjordene* is a claim about structure that oxygen does not address. So for this "
      "place:\n")
    w("**What would be sufficient**\n")
    w("*Nothing that targets oxygen*, because oxygen is not the measured problem here. A "
      "nitrogen reduction sized on a national residual will not change a shoreline that "
      f"is already at a median of {koge['median_mg_l']:.1f} mg/l.\n")
    w("*Cause-agnostic and available now:* the interventions in "
      "[PROGRAMME.md](PROGRAMME.md) that act on what arrives rather than on what it causes "
      "— keeping rainwater out of the combined system, an outlet that is not the bay, and "
      "source control on what the water carries. These change the delivered load "
      "whatever the mechanism downstream, and their case does not rest on the nitrogen "
      "chain.\n")
    w("*And one measurement, which costs almost nothing:* **there is no instrument for the "
      "thing people are actually complaining about.** Before proposing a fix for "
      "*fedtemøg*, somebody has to be able to say whether it got better. That is the "
      "cheapest unblocking step on this coast and it is not a modelling problem.\n")
    w("---\n")
    w("## What this page is for\n")
    w("Three things follow from reading by place rather than by mechanism.\n")
    w(f"1. **The severity ranking and the attention ranking are different.** Mariager is "
      f"{times:.1f}\n"
      "   times worse than anywhere and is not the subject of a national argument. Køge "
      "Bugt is\n"
      "   among the best-oxygenated waters in the country and is the subject of one.\n"
      "2. **The place where the standard account is most likely right is not the place it "
      "is\n"
      "   most loudly applied.** Lillebælt and the Sydfynske Øhav fit the nutrient story;\n"
      "   Mariager demonstrably does not, on twenty years of data.\n"
      "3. **A cause-agnostic intervention is worth more than its evidence base suggests**,\n"
      "   because the evidence base for *any* mechanism here is thin. Deep-water exchange "
      "does\n"
      "   not care why the water is anoxic. Keeping sewage out of a bay does not care "
      f"which of\n   the {nhyp} mechanisms is dominant. **Those are worth doing under "
      "uncertainty in a way that a\n"
      "   precisely-targeted intervention is not.**\n")
    w("## The meta-solution: buy the experiments\n")
    w("**This is the last step of the solution scope, not a shortcut past it** — see "
      "[PLAN.md stage 8](PLAN.md) for why the entitlement is earned by the seven stages "
      "before it. "
      "Said first, \"just try things\" is an excuse for not knowing. Said after the field "
      "is enumerated, the data characterised, the triage done and the spatiality "
      "established, it is the correct next move.\n")
    w("Everything above points at one instrument rather than many. **Fund trials of "
      "solution models, in named places, with pre-stated outcomes — and let the results "
      "decide.**\n")
    w("**Why this is not a slogan.** Intervention is the only thing that identifies a "
      "cause *without enumerating the confounders*. When you set a variable rather than "
      "observe it, every backdoor path is cut by construction — no adjustment set, no "
      "need to name the environmental peculiarities that have no column. Given that "
      f"{q("column. Given that @@")} of {q("@@ mechanisms here are")} mechanisms here are unscoreable and another {q("and another @@ need an")} "
      "need an experiment anyway, "
      "**the observational route to an answer may not exist**, and a trial does not "
      "require one.\n")
    w("### Plurality is the instrument, not the fallback\n")
    w("Trying several things reads as what you do when you cannot decide. Here it is the "
      "opposite. **Difference between places is the only thing that makes any of this "
      "identifiable**, and a country that does one thing everywhere has removed the "
      "possibility of finding out whether it worked.\n")
    w("A single national instrument applied everywhere at once is a design with one arm. "
      "Every catchment gets the same treatment in the same years, so whatever happens "
      "next happens to all of them together, and no estimator can recover a contrast "
      "that was never created. [`X17`](EXPERIMENTS.md) states the specific case: every "
      "Danish catchment has been sprayed for decades, so for that mechanism there is "
      "nothing to compare against — **the counterfactual does not exist at any price "
      "until somebody stops somewhere.**\n")
    w("The corollary is uncomfortable for both sides of the argument. Uniformity is what "
      "a fair regulation looks like and it is also what an uninformative experiment looks "
      "like: **applying one instrument everywhere buys equity and spends information.** "
      "This project has already met that trade three times in the data — a national "
      "relation that is tight *because* the local coefficient varies, "
      "[water bodies](AREAS.md) that carry no signal within themselves, and a national "
      "oxygen trend that tracks which stations were reporting. Aggregation is what "
      "destroyed the contrast in each case. Doing one thing nationally is aggregation "
      "applied to policy.\n")
    w("**Which is why the refusals count as much as the adoptions.** A municipality that "
      "declines the standard instrument and does something else is not an obstacle to "
      "the programme — *it is the control arm*, on the condition that somebody writes "
      "down what it declined, what it did instead, and from when. \"Here they refused "
      "these things and tried those; we did these, so somewhere there is the documented "
      "absence of them\" is a study design. Unrecorded, the same situation is only "
      "variation, and variation nobody dated is indistinguishable from noise.\n")
    w("So the register is the cheap half of the meta-solution and it should exist before "
      "the first trial is funded. Four fields, and none of them needs new "
      "instrumentation:\n")
    w("| | |")
    w("|---|---|")
    w("| **Who did what, where, from when** | including who declined, and what they did "
      "instead — a refusal with a date is a control arm; a refusal without one is "
      "nothing |")
    w("| **What each place expected** | stated before it started, so a result can "
      "disagree with it |")
    w(f"| **What reads it out** | the existing series wherever possible. The "
      f"{ox['stations_total']:,}-station near-bed oxygen record is the *before* for most "
      "of them, already paid for |")
    w("| **The rule that decides** | written before the results. Plurality without a "
      f"pre-stated decision rule does not produce an answer, it produces "
      f"{q("answer, it produces @@ and a fight")} and a fight about which one counts |")
    w("")
    w("And there is a sharper version available whenever more places are willing than "
      "there is money for. **Let the lot decide which willing place goes first.** That is "
      "the whole difference between a natural experiment and an experiment, it costs "
      "nothing, and it removes the objection that the places which volunteer are not like "
      "the places which do not. Where randomisation is not available — and often it will "
      "not be — the register still leaves the weaker but real design: matched places, "
      "read against their own histories.\n")
    w("**And the lever this is available on is narrower than it sounds, which is worth "
      "knowing before anyone promises it.** Product bans are harmonised at EU level, so no "
      "city and no region can close a market — that is the one instrument nobody local "
      "can start, and [the programme page says why that row sits at the wrong "
      "level](PROGRAMME.md). What is left below it is purchase, permission and use: a "
      "household not buying, a municipality refusing a compound in its own procurement "
      "or on its own ground, a utility writing a condition into a discharge permit, a "
      "state taxing a use or restricting it. Those are weaker instruments than a ban and "
      "they are the ones that make places differ — so they are the ones that generate the "
      "counterfactual, and they should be defended as an information instrument and not "
      "only as a local preference.\n")
    w("None of this weakens the anti-delay conditions below. Plurality is not everybody "
      "waiting to see what the neighbours got; it is different places acting **at the "
      "same time in different ways**, on a clock that runs whether or not the results "
      "are convenient.\n")
    w("**Denmark is unusually well placed to do this, and the reason is concrete.** A "
      f"trial needs a *before*. Denmark has {ox['last_year'] - ox['first_year']} years of "
      f"near-bed oxygen at {ox['stations_total']:,} stations, which is a baseline almost "
      "nowhere else has. "
      "The design that fits is Before-After-Control-Impact: intervene in one place, leave "
      "a matched place alone, and read both against their own history. **The expensive "
      "half of that design already exists and is paid for.**\n")
    w("**What the portfolio would look like**, taken from the places above rather than "
      "invented:\n")
    w("| where | trial | reads out on |")
    w("|---|---|---|")
    w(f"| **Mariager** | deep-water exchange | bottom oxygen and sulphide, existing "
      f"stations, {q("sulphide, existing stations, @@ | | **Lillebælt")} |")
    w("| **Lillebælt / Sydfynske Øhav** | catchment nitrogen reduction, at intensity | the "
      "one place the standard account predicts it should work |")
    w("| **Køge Bugt** | an instrument for *fedtemøg* | nothing can be judged there until "
      "the complaint is measurable |")
    w("| any | source control on what the water carries | delivered load, whichever "
      "mechanism dominates |")
    w("")
    w("**The economics are the argument.** A national reduction is expensive, recurring, "
      "irreversible within a year, and produces **no test**. A portfolio of trials is "
      "cheap against it, reversible, and every result is permanent — it holds whoever is "
      "in office and whatever the next model says. The value-of-information case is "
      "standard decision analysis: where the intervention cost is large and the "
      "attribution uncertain by a factor, information is worth a substantial fraction of "
      "the intervention.\n")
    w("### The objection that would sink it, stated plainly\n")
    w("**Exactly this argument is what somebody who simply wants to delay would make.** "
      "\"More research is needed\" is the oldest way to stall a regulation, and the fact "
      "that it is sometimes true is what makes it effective. There is a large economic "
      "interest in delay here, and a proposal to experiment instead of act serves that "
      "interest whether or not it means to.\n")
    w("So the proposal is only honest if it is built so it **cannot** function as delay:\n")
    w("- **a pre-committed timetable**, with the regulation as the default if the trials "
      "do not\n  report by it — the burden of delivery on the trials, not on the "
      "regulator;\n"
      "- **pre-registered outcomes**, chosen before the trial starts, so a null result "
      "cannot be\n  reinterpreted afterwards;\n"
      "- **published protocols and data**, so a failed trial is visible rather than "
      "quietly\n  dropped;\n"
      "- **and no reduction in what is already measured** while it runs.\n")
    w("Without those four, this is a delaying tactic with a methodology section. With "
      "them it is the only instrument on the table that produces an answer rather than a "
      "compliance figure.\n")
    w("**And it is worth being clear about what it does not claim.** A trial that works "
      "at Mariager says nothing about Lillebælt — the transfer coefficient between land "
      f"and estuary already varies {q("already varies @@ between bays,")} between bays, and one catchment "
      "in ten responds to nitrogen not at all. "
      "**Places would have to be tried separately, which is the whole argument of this "
      "page.**\n")
    w("**Limits.** The table aggregates stations by the hovedopland of the water body "
      "they fall in, and this project's own testing says the water bodies are not real "
      "units — it locates observations, it does not characterise places. Coverage is "
      f"uneven: {odense['stations']} stations at Odense against "
      f"{smaal['stations']} in Smålandsfarvandet, and {few['stations']} in "
      f"{label(few['region'])}. And the claims side is not "
      "systematic; it comes from the public record rather than a survey, so a place with "
      "a real problem and no local press does not appear here.")
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
