#!/usr/bin/env python3
"""docs/PLAN.md - the order of work: eight stages, each with a gate.

A status page is where stale numbers do the most harm, because it is read as
current. Every count on it is read live - the hypothesis register, the triage,
the extracts, the clock findings, the draft pages - and every assertion is a
checked claim (LIVE_NUMBERS.md section 11), in data/manual/claims.d/w2-kp.json.
What the page used to say and no longer can is in docs/ARCHIVE.md.

    python3 scripts/pages/plan.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
sys.path.insert(0, HERE)

from common import DERIVED, ROOT, log, write_doc
import live
import triage_rows

OUT = os.path.join(ROOT, "docs", "PLAN.md")
B, E, C = live.claim_begin, live.CLAIM_END, live.claim
K6 = "https://ecos.au.dk/fileadmin/ecos/Fagdatacentre/Marin/TA_NOVA_1998/Kap06.doc"
CLASS_ROWS = [("fetch", "blocked on a named fetch"), ("unscoreable", "**unscoreable**"),
              ("testable", "**testable now**"), ("experiment", "needs an experiment"),
              ("resolution", "blocked on measurement resolution"), ("unestablished", "not established")]


def J(*p):
    return live.live_json(os.path.join(*p))


def main():
    meta, en, cc, cy = (J(DERIVED, "meta_facts.json"), J(DERIVED, "enums.json"),
                        J(DERIVED, "clock_convention.json"), J(DERIVED, "cycles.json"))
    tri, ds, hf = J(DERIVED, "triage.json"), J(DERIVED, "ds_facts.json"), J(DERIVED, "hypodraft_facts.json")
    titles = {g["id"]: g.get("title") or g.get("name") for g in J(DERIVED, "hypotheses.json")["groups"]}
    ref = live.ref

    def share(part, whole):
        return live.step("K-SUBSET-SHARE", part / whole * 100)

    n = tri["n_triaged"]
    cls = {k: tri["classes"][k]["n"] for k, _ in CLASS_ROWS}
    grp, clu = tri["groups"], tri["clusters"]
    beyond = cls["unscoreable"] + cls["experiment"]
    nine = triage_rows.CLUSTERS["vandkemi"]
    zero = [g for g in grp if g != "A" and grp[g]["testable"] == 0]

    o = []

    def w(s=""):
        o.append(s)

    w("# The order of work")
    w()
    w(C("C-KP-ORDER", "Eight stages, in order, each with a gate that must be passed before the next "
        "one means anything. The order is written down so that drift from it is visible.")
      + " Generated by `scripts/pages/plan.py`.")
    w()
    w(C("C-KP-STATUS", "**Each stage's status is this project's own reading of it against its gate, "
        "set out in its section, including where it is bad.**"))
    w()
    w("| | stage | gate | status |")
    w("|---|---|---|---|")
    w("| Stage 1 | Hypothesis landscape | broad enough that no test is a two-horse race | **done, with a stated flaw** |")
    w("| Stage 2 | Data sources | provenance separated; independence counted | **done** |")
    w("| Stage 3 | The view, held open | no basket assumed; destruction stated | **partly** |")
    w(f"| Stage 4 | Testing hypotheses against data | each has an observable consequence and a null | **triage done, {meta['drafts_n']} drafts written** |")
    w("| Stage 5 | Mechanistic scoring | stability across independent measure-spaces | **not started** |")
    w("| Stage 6 | Solution in its own spatiality | the unit follows the mechanism | **premature** |")
    w("| Stage 7 | Relation to the social argument | claims in circulation, and what would move them | **partly** |")
    w("| Stage 8 | **Try things** | the stages above are *exhausted*, not skipped | **the last step, and only reachable from here** |")
    w()
    w("---")
    w()
    w("## 1. Hypothesis landscape — done, with a stated flaw")
    w()
    w(C("C-KP-LANDSCAPE", f"**{meta['hypotheses_n']} hypotheses in {meta['groups_n']} groups** "
        "([HYPOTHESES.md](HYPOTHESES.md)), each a candidate mechanism, not a finding."))
    w()
    w(B("C-KP-SATISFACTORY") + "**What \"satisfactorily\" means here.** Not exhaustive — there is no way")
    w("to know how far off that is. The requirement is weaker and achievable: *broad enough that no")
    w("test is a contest between two candidates one of which was chosen in advance.* A hypothesis")
    w("scored against \"nothing\" is scored against a strawman; it has to be scored against rivals")
    w("that could actually win." + E)
    w()
    w(B("C-KP-FLAW") + f"**The stated flaw.** The {meta['groups_n']} groups are **our own untested partition**,")
    w("the same error the rest of the project audits, committed on our own list. The grouping has")
    w("not been run through a complement test, and it should be before stage 5 uses it." + E)
    w()
    w(C("C-KP-GATE1", f"**Gate:** passed. {cls['testable']} hypotheses are testable now, spread over "
        "several groups, so stage 4 is a real contest."))
    w()
    w("---")
    w()
    w("## 2. Data sources — done")
    w()
    w("Held, with provenance separated rather than pooled:")
    w()
    ctd_m, kemi_m = en["ctd"]["rows"] / 1e6, en["kemi"]["rows"] / 1e6
    w("- " + C("C-KP-ODA", f"**ODA**: {ctd_m:.1f} M CTD measurements from {ds['ctd']['years'][0]}, and the "
               f"water-chemistry extract (`vandkemi`, {kemi_m:.1f} M rows) from {ds['kemi']['years'][0]}, plus "
               "light profiles and Secchi depths"))
    w("- " + C("C-KP-CMEMS", "**Copernicus Marine**: the source register lists four model reanalyses - "
               "physics, biogeochemistry and two wave hindcasts, which are models, not measurements - "
               "and two satellite ocean-colour retrievals held on disk"))
    w()
    w(C("C-KP-DERIVED-CHANNELS", "**Independence is the quantity that matters, not volume.** Salinity is "
        "computed from conductivity and temperature, and oxygen saturation from oxygen, temperature "
        "and salinity, so a derived channel is not an independent measurement."))
    w(C("C-KP-PATHS", "Independent production paths held today: **CTD, satellite ocean colour, Secchi disc "
        "— three.**"))
    w()
    w(C("C-KP-GATE2", "**Gate:** passed."))
    w()
    w("---")
    w()
    w("## 3. The view, held open — partly")
    w()
    w(C("C-KP-STAGE3", "The point of this stage is to make the data usable *without* committing to "
        "anyone's categories, so that stage 4 can test a hypothesis rather than inherit a model."))
    w()
    w(B("C-KP-VIEW") + "**Done.** [stations.html](stations.html) — every station-month at its own position,")
    w("nothing aggregated into a water body, nothing interpolated. Water bodies are an optional")
    w("overlay tagged as model; interpolation is a reader control, labelled as invented; outliers")
    w("are ringed, not removed." + E)
    w()
    w(B("C-KP-COLLAPSE") + "**Not done.** A measurement-level store: depth, time and *station identity*")
    w("as questions rather than columns. The station series this project analyses keep at most two depths —")
    w("surface and bed — and one value per station and month, and carry no instrument. That is a")
    w("choice made for convenience and not yet unmade." + E)
    w()
    w(C("C-KP-GATE3", "**Gate:** partly passed. Stage 4 can proceed on the collapsed view for hypotheses "
        "that do not depend on depth, sub-monthly time, or within-station position. It cannot for the "
        "others, and those must be marked rather than tested badly."))
    w()
    w("---")
    w()
    rows, filled = en["kemi"]["rows"], en["kemi"]["nonblank"]["Startklok"]
    ccl = cc["classes"]
    visits = sum(ccl[e][c] for e in ccl for c in ccl[e].keys())
    defaults = sum(ccl[e]["default"] for e in ccl if "default" in ccl[e])
    recent = cc["observed_check"]["2002-"]
    sc = cy["results"]["o2"]["sun_counts"]
    w("## 4. Testing hypotheses against the data — triage done")
    w()
    w(C("C-KP-STAGE4", f"The triage is done, and drafts testing individual hypotheses against the data "
        f"are written for {meta['drafts_n']} of them."))
    w()
    w(C("C-KP-THREE-THINGS", "Each hypothesis needs three things before it can be tested, and most "
        "fail at one:"))
    w()
    w("1. **An observable consequence.** Not \"X contributes to Y\" but \"if X, then this")
    w("   measurable quantity behaves this way and not that way.\"")
    w("2. **A source that carries it.** Named, with its error class ([the taxonomy](https://github.com/Jjokulian/statistical-methods#7b-rate-a-data-stream-by-the-errors-it-can-contain)).")
    w("3. **A null under the constraint actually imposed** — not the statistic's nominal null.")
    w()
    w("The triage classes:")
    w()
    w("- **testable now** — consequence, source and null all available")
    w("- **blocked on a named fetch**")
    w("- **blocked on measurement resolution** — waiting on stage 3's remaining half")
    w("- " + C("C-KP-MICROBIAL", f"**unscoreable** — the deciding dimension has no column. *Microbial, viral "
      f"and fungal community composition is the worked example: it decides {clu['microbial']['n']} "
      f"hypotheses in the triage, {clu['microbial']['unscoreable']} of them unscoreable, and national "
      "marine monitoring has never measured it.*"))
    w()
    w(C("C-KP-ABSENT", "An unscoreable hypothesis is marked **unscoreable**, not scored zero. An absent "
        "dimension is not evidence of absence."))
    w()
    w(B("C-KP-TIMEOFDAY") + "**Time of day belongs to a further class: the dimension is recorded, and the")
    w("sampling design seldom goes where it matters.** That is not an absent column and it is not a")
    w("testable question. It is a statement about when people are willing to be on a boat, and no")
    w("reanalysis of the archive can fix it." + E)
    w()
    w(B("C-KP-CLOCK") + f"ODA's water-chemistry extract carries a clock value on every genuine row of its")
    w(f"{rows / 1e6:.1f} million — the {rows - filled} without one are fragments of a broken note field — and the")
    w(f"technical instruction asks for the sampling time in UTC ([the nutrients chapter, Kaas & Markager")
    w(f"1998]({K6}); *\"Prøvetagningsdato og tidspunkt i UTC\"*). A clock value is not always a time,")
    w(f"though: `scripts/clockzone.py` finds filled-in defaults on {defaults:,} of {visits:,} sampling visits,")
    w("and a convention that changes by era ([DATA_SOURCES.md](DATA_SOURCES.md))." + E)
    w()
    w(B("C-KP-SAMPLING-HOURS") + f"A clock hour is not a light level: at {meta['sun_reference_lat']:.0f}°N, 09:00 on the winter")
    w(f"solstice is a sun {meta['sun_winter_0900']:.1f}° above the horizon and 09:00 on the summer solstice")
    w(f"{meta['sun_summer_0900']:.1f}°. In the record since 2002 the 5th and 95th percentiles of observed")
    w(f"sampling times are {recent['local_hour_p05']:.1f} h and {recent['local_hour_p95']:.1f} h local time; of {cy['results']['o2']['n']:,} surface")
    w(f"oxygen samples with an observed time, {sc['night']:,} were taken at night and {sc['twilight']:,} in")
    w("twilight. The pre-dawn minimum, which is the value an oxygen threshold is actually about, is")
    w("essentially never visited." + E)
    w()
    w(C("C-KP-TRIAGE", f"**The triage** — [`hypodrafts/TRIAGE.md`](hypodrafts/TRIAGE.md) — classifies all "
        f"{n} lettered hypotheses, one row each:"))
    w()
    w("| class | n | share |")
    w("|---|---:|---:|")
    for key, lab in CLASS_ROWS:
        b = "**" if key == "testable" else ""
        w(f"| {lab} | {b}{cls[key]}{b} | {b}{share(cls[key], n):.0f}%{b} |")
    w()
    w("**Four things the shape says.**")
    w()
    w(B("C-KP-VANDKEMI") + "**One extract was named as the blocker for nine.** ODA `vandkemi` (`Emne_10_11`)")
    w("is named in the blocker for " + ", ".join(ref(h) for h in nine[:-1]) + f" and {ref(nine[-1])}.")
    w(f"It is now held — {rows:,} rows and {ds['kemi']['parameters']} parameters from {ds['kemi']['years'][0]}, among")
    w("them total N, total P, ortho-P, nitrite+nitrate, ammonium, chlorophyll a, silicon, and")
    w(f"{en['kemi']['categorical']['Parameter']['Oxygen indhold']:,} oxygen measurements each carrying a depth — but the triage above")
    w("still counts the nine as blocked on a fetch. Re-scoring them against the data, rather than")
    w("against its absence, is in [OPEN_PROBLEMS.md](OPEN_PROBLEMS.md)." + E)
    w(C("C-KP-ILTKOR", "(`iltkor` is declared in `fetch_oda.py`'s topics and has never been fetched: the "
        "only one of its six topics with no file on disk.)"))
    w()
    w(B("C-KP-GROUPS") + f"**Not one hypothesis in group A is testable now.** All {grp['A']['n']} are blocked,")
    w(f"unscoreable or unestablished. Of the {cls['testable']} testable now, {grp['I']['testable']} are from group I —")
    w(f"hypotheses about the archive itself — {grp['C']['testable']} from C and {grp['Z']['testable']} from Z, the two")
    w("physical groups; none is from the groups on " + ", ".join(f"*{titles[g].lower()}*" for g in zero[:-1])
      + f" or *{titles[zero[-1]].lower()}*. **The archive can test physics and audit itself, and can")
    w("scarcely test biology or chemistry.**" + E)
    w()
    w(B("C-KP-DIMENSIONS") + "**The largest blocking dimension is not nutrients.** Microbial, viral and fungal")
    w(f"community composition alone makes {clu['microbial']['unscoreable']} hypotheses unscoreable, and toxicant")
    w(f"concentration in a marine matrix another {clu['toxicant']['unscoreable']}. **Those two are "
      f"{clu['microbial']['unscoreable'] + clu['toxicant']['unscoreable']} of the {cls['unscoreable']}.**" + E)
    w()
    w(B("C-KP-REFRAME") + f"**And {share(beyond, n):.0f}% of the field is beyond any reanalysis of existing data**")
    w("— unscoreable plus experiment. Which reframes the public argument: the nutrient hypotheses did")
    w(f"not defeat the alternatives. **{beyond} alternatives have never been in a position to compete.**" + E)
    w()
    w(B("C-KP-CAVEATS") + "Two caveats. The classification is itself an untested partition. And per")
    w("[KNOWN_AND_UNKNOWN.md](KNOWN_AND_UNKNOWN.md), every \"not measured\" here means \"not found by a")
    w("search whose sensitivity nobody has characterised\", so **the unscoreable column is an upper")
    w("bound, not a measurement.**" + E)
    w()
    w(C("C-KP-GATE4", f"**Gate:** stage 5 can proceed on the {cls['testable']} testable now."))
    w()
    w("---")
    w()
    w("## 5. Mechanistic scoring — not started")
    w()
    w(B("C-KP-MECH") + "\"Mechanistic\" is doing real work in that phrase. It does not mean *is there a")
    w("correlation*. It means: **does the mechanism's signature survive a change of measure-space?** A")
    w("mechanism is a relation that holds when other things change, so the score is invariance, not")
    w("fit." + E)
    w()
    w(C("C-KP-POSITIVE-CONTROL", "A detector with demonstrated sensitivity that returns a null is "
        "informative; one without is not. Stage 5 needs such a positive control on this data before "
        "its nulls mean anything."))
    w()
    w(C("C-KP-FIVE", "**Each hypothesis gets, and none of the five is droppable:**"))
    w()
    w("> a stability coefficient · at a stated level of organisation · against a stated null ·")
    w("> for a named functional · at a stated point in the accumulation of measure-spaces")
    w()
    w(C("C-KP-VERDICT", "Drop any one and it is a verdict, which is a different kind of object than "
        "this procedure can produce."))
    w()
    named = share(en["ctd"]["rows"] - en["ctd"]["categorical"]["SondeNr"]["999"], en["ctd"]["rows"])
    w(B("C-KP-MEASURE-SPACES") + "**And it never terminates.** Each new independently produced measure-space is")
    w("another trial, so the score carries a time index and has no final value. Three production paths")
    w(f"today; and {named:.0f}% of CTD measurements carry a named probe — {hf['enums']['probe_ids_known']} probe numbers in")
    w("all — so instruments are a further axis to compare across." + E)
    w()
    w("---")
    w()
    w("## 6. Solution in its own spatiality — premature")
    w()
    w("The requirement, and it is the reason this stage cannot be borrowed:")
    w()
    w("> " + C("C-KP-UNIT", "**The unit follows the mechanism.** Not water bodies. Not municipalities. "
               "Not Denmark."))
    w()
    w(B("C-KP-BOUNDARIES6") + "Every one of those is a model boundary, failed or untested. The official water")
    w("bodies agree with the partitions the data produce no better than random connected regions of")
    w("the same sizes ([LANDING.md](LANDING.md)). \"Denmark\" as the unit for a marine account")
    w("presupposes a closed system across which nitrogen visibly moves — the same missing")
    w("denominator, at national scale." + E)
    w()
    w(B("C-KP-GEOMETRY") + "So the geometry of the answer is whatever the surviving mechanism has: if it is")
    w("catchment-scale, the unit is the catchment; if a shoreline gradient, distance from shore; if")
    w("residence time, exchange time, and the map is not a map; if sediment memory, depositional")
    w("history, with depth as the axis." + E)
    w()
    w(C("C-KP-NO-TOTALS", "**No national totals. No per-water-body allocations. No percentage of a residual.**"))
    w()
    w(C("C-KP-PROGRAMME", "[PROGRAMME.md](PROGRAMME.md) proposes interventions ahead of stages four and five. "
        "It should be re-read against them when they exist, and the parts that assume an inherited "
        "geometry marked."))
    w()
    w("---")
    w()
    w("## 7. Relation to the social argument — partly")
    w()
    w(C("C-KP-STAGE7-WHAT", "Last, and deliberately last: what is claimed in public, what each claim "
        "rests on, and what would move it. **Not** an argument against opponents — no ghost "
        "references, no unnamed adversaries."))
    w()
    w(B("C-KP-STAGE7") + "**Done:** [GRUNDLAGET.md](GRUNDLAGET.md) audits the foundation documents;")
    w("[POLITICS.md](POLITICS.md) the social frame; [NITROGEN.md](NITROGEN.md) and")
    w("[RESIDUAL.md](RESIDUAL.md) set out that the national agricultural share is computed over an area")
    w("only part of which is measured, not measured itself." + E)
    w()
    w(C("C-KP-OUTSTANDING", "**Outstanding:** what GRUNDLAGET reports about DCE's and DHI's documents is "
        "applied only once checked against those documents, never on a subagent's word."))
    w()
    w(B("C-KP-RULE7") + "**And a standing rule this stage needs.** Finding one bad argument in one")
    w("document does not establish that a claim is unevidenced. **Before reporting that a link")
    w("fails, ask what the strongest version of the case would be and whether it was looked for.**")
    w("The sourcing a document presents is not the only evidence there is for what it claims." + E)
    w()
    w("---")
    w()
    w("## 8. Try things — and why this is the last step, not the first")
    w()
    w(B("C-KP-TRY") + "At the end of the sequence, and only at the end, something becomes legitimate that")
    w("would have been evasion at any earlier point: **stop trying to establish the cause, intervene,")
    w("and read the outcome.**" + E)
    w()
    w(C("C-KP-PLACES-LINK", "[PLACES.md](PLACES.md) sets out what that would look like. This section is "
        "about *when you are entitled to it*."))
    w()
    w(C("C-KP-ENTITLEMENT", "**The entitlement is earned by the stages above, and every one of them is "
        "doing work in the trial.** Skip them and the trial is unreadable:"))
    w()
    w("| without stage | the trial fails because |")
    w("|---|---|")
    w("| **Stage 1** hypothesis landscape | " + C("C-KP-WHY-S1", "you cannot say what else it might have been, so a success attributes itself to whatever you already believed") + " |")
    w("| **Stage 2** data sources | " + C("C-KP-WHY-S2", "you do not know whether the response variable exists — of the four public words for the damage, only one has a usable measurement behind it") + " |")
    w("| **Stage 3** the view, held open | " + C("C-KP-WHY-S3", "**you have no *before*.** A trial without a baseline reads nothing, and the baseline is the expensive half") + " |")
    w("| **Stage 4** the triage | " + C("C-KP-WHY-S4", "you do not know which mechanisms are unreachable, so you cannot tell \"the trial failed\" from \"the trial could never have shown it\"") + " |")
    w("| **Stage 5** mechanistic scoring | " + C("C-KP-WHY-S5", "you have no null, so a change of the size weather produces reads as a result") + " |")
    w("| **Stage 6** its own spatiality | " + C("C-KP-WHY-S6", "you run one trial nationally, and a response that differs from place to place averages away") + " |")
    w("| **Stage 7** the social argument | " + C("C-KP-WHY-S7", "a result lands in a discourse that has no way to receive it, and is read as whichever side funded it") + " |")
    w()
    w(B("C-KP-BOUNDARY") + "**So this is not the analysis failing.** It is the analysis returning a specific,")
    w("defensible answer: *here is the boundary of what observation can settle, and it is closer than")
    w(f"anyone assumed.* {cls['unscoreable']} of {n} mechanisms are unscoreable and {cls['experiment']} more need an")
    w(f"experiment — **{share(beyond, n):.0f}% of the field was never reachable this way**, and no amount of further")
    w("modelling moves it." + E)
    w()
    w(B("C-KP-INTERVENE") + "Past that boundary, intervening is not a retreat from method. It is the only")
    w("remaining method, and it is a good one: setting a variable cuts every backdoor path by")
    w("construction, which an observational study on an archive whose sampling seldom visits the night")
    w("cannot do." + E)
    w()
    w(B("C-KP-ORDER-ARG") + "**The order is the argument.** \"Just try things\" said first is an excuse for not")
    w("knowing. Said last, after the field has been enumerated, the data characterised, the view held")
    w("open, the triage done and the spatiality established, it is the correct next move — and the")
    w("preceding work is what makes the result legible when it arrives." + E)
    w()
    w("---")
    w()
    w("## The rule that governs all eight")
    w()
    w(B("C-KP-RULE") + "Any output of this project takes the form of a coefficient with its qualifiers, or a")
    w("count with its individuation rule stated. **Not a verdict.** The procedure has no output slot")
    w("shaped like one — the space of groupings and functionals is open, so \"the result is in\" is")
    w("not false but referentless." + E)
    w()
    w("Method, and the audit of which parts survive their own rules:")
    w("[statistical-methods](https://github.com/Jjokulian/statistical-methods).")
    try:
        write_doc(OUT, "\n".join(o).rstrip("\n") + "\n")
    except live.Unjustified as e:
        log(str(e))
        return 1
    log(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
